### PR TITLE
feat(sources): Add Envoy ALS Source

### PR DESCRIPTION
**Pull request by ADustyOldMuffin**
Adds support for [Envoy ALS](https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/service/accesslog/v3/als.proto) as a source.

closes: https://github.com/vectordotdev/vector/issues/14027

this is a re-pickup of https://github.com/vectordotdev/vector/pull/15835.

I'm new to the project and from the last comments the piece missing was log namespacing so I followed https://github.com/vectordotdev/vector/blob/master/docs/tutorials/lognamespacing.md as a rough guide and did a first pass looking for feedback.

Sorry for the ping but @neuronull 👋🏻 since you were previously reviewing the other PR and have the most context.

### CODE REVIEW

**Comment by neuronull** [comment]
Hey @ADustyOldMuffin , thanks for picking this up.

A heads up- we are experimenting with a new component qualification process to evaluate the inclusion of new service integrations such as this one.

In that spirit , a couple questions for you- 

- Are you affiliated with Envoy?
- Are you interested/be willing to be informally committed to maintaining this integration (if it were to be included in Vector), going forward? For example, if the Envoy ALS protobuf changed and edits were needed to this integration for compatibility.

Now, pending the approval of this new service integration, I just wanted to give you a preview:

- for the log namespacing, we would need the custom fields that are introduced by parsing out the Envoy protobuf messages, to be log namespaced. This is discussed a bit here (https://github.com/vectordotdev/vector/pull/15835#discussion_r1068743878) , and the `dnstap` is still a good reference point. **NOTE: best to hold off on spending time on this until post-approval.**

**Comment by ADustyOldMuffin** [comment]
- I am not affiliated with Envoy.
- Sure, I can try my best! Still new to Rust so I can't promise high quality.

I'll take a look at them once approved.

**Comment by neuronull** [comment]
This was overlooked on the initial proposal/PR, but maybe you have some thoughts here @ADustyOldMuffin -

It looks like the [Access Logging](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging) functionality, is available in a few formats (one of which being the gRPC stream that this current implementation leverages).
But there also appears to be an [export to opentelemetry via gRPC.](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto#envoy-v3-api-msg-extensions-access-loggers-open-telemetry-v3-opentelemetryaccesslogconfig) , in which case, the existing `opentelemetry` source in Vector should theoretically be able to consume that after it's been routed through Otel.
Similarly, there is a [file](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/file/v3/file.proto#envoy-v3-api-msg-extensions-access-loggers-file-v3-fileaccesslog) and [stdout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/stream/v3/stream.proto#envoy-v3-api-msg-extensions-access-loggers-stream-v3-stdoutaccesslog) variant in Envoy, which could be used with Vector's `file` and `stdin` sources respectively, using VRL to handle common logging structures within Envoy.

I know you weren't the original author of the PR but, do these sound like reasonable alternatives, or are we overlooking something?

Thanks~

**Comment by ADustyOldMuffin** [comment]
Let me take a gander at those and see if it'd work. I'm not on the original author's team so I'm not sure of their internal communication of why the wanted ALS. I believe files was a problem due to the sheer volume of logs that if the sink takes too long we'd use a lot of disk fast, but if the opentelemetry works then we can try that.

**Pull request closed without merging**
