### PR TITLE
docs: add source_type for sources that report it

### PR DESCRIPTION
**Pull request by neuronull**
Sparked by this discussion: https://github.com/vectordotdev/vector/discussions/13487

The `source_type` was added for many source outputs but was not documented.

DOES output source_type:
- aws_sqs
- docker_logs
- http
- kafka
- nats
- datadog_agent
- gcp_pubsub
- internal_logs
- kubernetes_logs
- redis
- stdin
- aws_kinesis_firehose
- demo_logs
- exec
- heroku_logs
- logstash
- socket
- syslog
- aws_s3
- file
- journald
- splunk_hec

DOES NOT output source_type:
- apache_metrics
- aws_ecs_metrics
- docker_logs
- eventstoredb_metrics
- fluent
- prometheus_scrape
- statsd
- dnstap
- host_metrics
- internal_metrics
- mongodb_metrics
- postgresql_metrics
- prometheus_remote_write

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
I spot checked a couple of these and realized that we actually aren't consistently adding `source_type` as I thought. For example: the `dnstap` and `aws_ecs_metrics` components don't seem to be annotating it, while the `file` source does. I wonder if this is something we could annotate at the topology level to ensure that all components _do_ add it rather than relying on each component to do it individually. As it stands, we should probably just add `source_type` to the `file` source (optionally audit the rest of them) and open an issue to track doing it at the topology level.

**Comment by neuronull** [comment]
> I spot checked a couple of these and realized that we actually aren't consistently adding `source_type` as I thought. For example: the `dnstap` and `aws_ecs_metrics` components don't seem to be annotating it, while the `file` source does.

Oh interesting, how are you spot checking? My method for each of the sources (I think I verified them all) , was to confirm that a `source_type()` function existed in the impl of SourceConfig ...


> I wonder if this is something we could annotate at the topology level to ensure that all components _do_ add it rather than relying on each component to do it individually. 

Makes sense yes.

**Comment by jszwedko** [comment]
> > I spot checked a couple of these and realized that we actually aren't consistently adding `source_type` as I thought. For example: the `dnstap` and `aws_ecs_metrics` components don't seem to be annotating it, while the `file` source does.
> 
> Oh interesting, how are you spot checking? My method for each of the sources (I think I verified them all) , was to confirm that a `source_type()` function existed in the impl of SourceConfig ...

That would have been sensible since it would have be reasonable to expect that to be done in a generic fashion, but actually the sources that add `source_type` do it directly. For example, `datadog_agent` source for logs:

https://github.com/vectordotdev/vector/blob/7cc3a80e5f6df3a88b636fe52b3508719b149f17/src/sources/datadog/agent/logs.rs#L148-L153

The `syslog` source:

https://github.com/vectordotdev/vector/blob/7cc3a80e5f6df3a88b636fe52b3508719b149f17/src/sources/syslog.rs#L336

I noticed the lack of those inserts for the sources I mentioned.

The `source_type` function on the config struct is used other places, for example to annotate metrics with the source type they came from. I think it could be used for this purpose of annotation too, it just isn't currently.

**Comment by neuronull** [comment]
> > > I spot checked a couple of these and realized that we actually aren't consistently adding `source_type` as I thought. For example: the `dnstap` and `aws_ecs_metrics` components don't seem to be annotating it, while the `file` source does.
> > 
> > 
> > Oh interesting, how are you spot checking? My method for each of the sources (I think I verified them all) , was to confirm that a `source_type()` function existed in the impl of SourceConfig ...
> 
> That would have been sensible since it would have be reasonable to expect that to be done in a generic fashion, but actually the sources that add `source_type` do it directly. For example, `datadog_agent` source for logs:


So this is interesting... I am going through the code checking for the actual insertion of `source_type` by the sources , and the gcp_pubsub doesn't appear to be inserting that field, but it has an assertion in the integration test that it is inserted. This makes me think there is something above calling the source_type() function and inserting that ? Unless there is a problem with that integration test 🤔 

https://cs.github.com/vectordotdev/vector/blob/17557722b20f81a11722af5ce9224644751a14da/src/sources/gcp_pubsub.rs#L994

**Comment by neuronull** [comment]
> As it stands, we should probably just add `source_type` to the `file` source (optionally audit the rest of them) 

I audited the all of them and updated the initial comment with a list of which do and do not have source_type , and in the latest commit removed the changes for those which don't have source_type.

**Review by jszwedko — APPROVED** [review]
Thanks @neuronull ! Apologies for the delayed review, I forgot about this one.

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
