### PR TITLE
fix(tests): Use one more thread for merge_and_fork test

### PR DESCRIPTION
**Pull request by jszwedko**
I'm really not sure why this works, but it appears to fix the issue we
saw with this test starting to fail on Linux after the upgrade to Tokio
1.16.1.

I'm guessing this is due to the multi-threaded scheduler changes mentioned here: https://github.com/tokio-rs/tokio/pull/4383

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
I love magic numbers!

**Comment by blt** [comment]
The comment still references "two" threads. 

On the whole I'm not really sure what this test is demonstrating and would move to strike it if no one else has a more clear idea. It's very, uh, integration test-y without being an integration test? If we're trying to show something important about the topology surely there's a less indirect way to demonstrate whatever it is this is doing and if we're testing something about tokio that's inappropriate.

I think this test is trying to establish we don't drop data during shutdown? But it's using no synchronization to ensure the test itself doesn't get ahead of the underlying topology tasks?

**Comment by jszwedko** [comment]
> The comment still references "two" threads.

Doh, I updated the comment. 258a9c0

> On the whole I'm not really sure what this test is demonstrating and would move to strike it if no one else has a more clear idea. It's very, uh, integration test-y without being an integration test? If we're trying to show something important about the topology surely there's a less indirect way to demonstrate whatever it is this is doing and if we're testing something about tokio that's inappropriate.
> 
> I think this test is trying to establish we don't drop data during shutdown? But it's using no synchronization to ensure the test itself doesn't get ahead of the underlying topology tasks?

It looks to me just like a high level integration test. I imagine the components of this are tested at various levels, but do see some value in having basic end-to-end integration tests. It looks like it was originally added very early on in Vector's lifetime though (876a09734), so it is very possible it has outlived its purpose. I'll defer to you and others that are closer to the code to decide if it (or any tests in `tests/tcp.rs`) are still useful.

**Comment by blt** [comment]
> > The comment still references "two" threads.
> 
> Doh, I updated the comment. [258a9c0](https://github.com/vectordotdev/vector/commit/258a9c03eb1b9f565aef58a425e3f83c6ee43eeb)
> 
> > On the whole I'm not really sure what this test is demonstrating and would move to strike it if no one else has a more clear idea. It's very, uh, integration test-y without being an integration test? If we're trying to show something important about the topology surely there's a less indirect way to demonstrate whatever it is this is doing and if we're testing something about tokio that's inappropriate.
> > I think this test is trying to establish we don't drop data during shutdown? But it's using no synchronization to ensure the test itself doesn't get ahead of the underlying topology tasks?
> 
> It looks to me just like a high level integration test. I imagine the components of this are tested at various levels, but do see some value in having basic end-to-end integration tests. It looks like it was originally added very early on in Vector's lifetime though ([876a097](https://github.com/vectordotdev/vector/commit/876a09734589c10afee1f93917116de569736269)), so it is very possible it has outlived its purpose. I'll defer to you and others that are closer to the code to decide if it (or any tests in `tests/tcp.rs`) are still useful.

Oh wow, ancient. For what it's worth this test strikes me as both indirect in what it's establishing and very precise in the results it is looking for, which is a bad combo. I'd strike it, me, or mark it as allow-to-fail and then setup a task to extract this into a proper integration test.

**Pull request merged**
