### PR TITLE
feat: migrate to `async_nats` client

### LINKED ISSUE #15534: Migrate to async_nats NATS client
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Vector currently uses `nats::asynk` client which is not a recommended way of using it, as newer official async api exists in a form of `async_nats` crate. `nats` crate is described as "Legacy synchronous client that supports" in it's own [repo](https://github.com/nats-io/nats.rs#nats), which also mentions that `This client will be deprecated soon`.

Furthermore `nats::asynk` lacks `async` support for `NATS JetStream` (there's a sync one, but that doesn't fit for vector's purposes), and `JetStream` seems to be a pretty good candidate for becoming another Vector source (I'll create a separate feature request for this later and will try to contribute this client myself).

So it seems that migrating to a more modern and async native `async_nats` client would be benifitial for a project as a whole.

Wanted to mention that I'm sorry if I failed to follow a proper process here. I tried my best and please feel free to point out any mistakes I've made.

### Attempted Solutions

_No response_

### Proposal

I have prepared an MR that implements such a migration. Although there're a couple of things that concern me and I would like to hear an opinion on those:
- `async_nats` doesn't support  `reconnect_buffer_size` configuration option and judging by a comment in Vector code where this options is set `Set reconnect_buffer_size on the nats client to 0 bytes so that the client doesn't buffer internally (to avoid message loss).` it appears to be quite crucial. I can create a feature request in https://github.com/nats-io/nats.rs as it seems to me it's a matter of simple addition of a setter method. 
- Due to changes in error handling approach `nats` client no longer returns `std::io::Error` as it's error type, so I was not able to retain `error_type` field in `internal_events/nats.rs`

### References

#15533

### Version

_No response_

### PR DESCRIPTION
**Pull request by makarchuk**
Implements migration from `nats::asynk` client to more modern official client `async_nats`

Closes #15534

### CODE REVIEW

**Review by StephenWakely — CHANGES_REQUESTED** [review]
Nice. Thanks for doing this.

The issue you mentioned around buffering should be fine, from what I can tell the async library isn't doing any buffering so it shouldn't be a problem. 

There are a couple of CI errors that need fixing. The integration tests have some compile errors. `nats.rs` needs to be formatted correctly, which you can do by running the file through `rustfmt`.

**Comment by StephenWakely** [comment]
Hi, I'm getting a bunch of integration test errors now, for example:

```
--- TRY 1 STDERR:        vector sinks::nats::integration_tests::nats_userpass_auth_valid ---
thread 'sinks::nats::integration_tests::nats_userpass_auth_valid' panicked at 'assertion failed: `(left == right)`
  left: `768`,
 right: `1000`', src/sinks/nats.rs:280:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Are they passing locally for you? You can run the tests by running `make test-integration-nats` from the vector project folder.

Unfortunately the integration tests weren't set to run in CI for this PR. I've just enabled it so we should now see the results on each push.

**Comment by paolobarbolini** [comment]
Since this PR hasn't received any updates I'll try continuing it in #18165

**Comment by jszwedko** [comment]
> Since this PR hasn't received any updates I'll try continuing it in #18165

That would be great, thank you!

**Pull request closed without merging**
