### PR TITLE
chore(azure service): Update revision used for the Azure SDK/chase changes as necessary

### PR DESCRIPTION
**Pull request by archoversight**
Updating the revision that the Azure SDK for Rust points at, and chasing some changes in the SDK to match the new errors.

This also updates the various `use` lines so that they pull from the new `azure_storage_blobs` crate instead of from `azure_storage`.

Closes: https://github.com/vectordotdev/vector/issues/10979

### CODE REVIEW

**Comment by archoversight** [comment]
This will need approval for CI run again, I pushed the updated `cargo fmt` for a file I missed.

**Comment by archoversight** [comment]
Fixed the failing build for the integration test. Missed an enum name chase.

**Comment by archoversight** [comment]
Alright @jszwedko and @spencergilbert. I have removed the use of my temporary fork, and have pointed it back at upstream. It is now pointing at the latest commit that I could find.

I was able to test and validate that the code compiled/tests ran locally, so now CI can also do its thing! I think this is ready to go, looking forward to having this in a new release of `vector`.

Side note, I didn't do it here, but we may be able to update the docs to point out that we can use the `SharedAccessSignature` instead of the `AccountKey` thereby allowing us to limit the blast radius, since the `AccountKey` has full privileges to the storage account, and the `SharedAccessSignature` does not, but I haven't had a chance to fully validate/test that and have yet to validate what permissions are strictly required.

**Comment by jszwedko** [comment]
The failed integration tests seem unrelated; the Azure ones pass. I'll merge this and take a look at the Datadog integration tests on master to see anything is broken. Thanks again for this contribution @archoversight !

**Comment by archoversight** [comment]
@jszwedko thanks for making it easy :-)

**Comment by archoversight** [comment]
@jszwedko @spencergilbert when will this likely be released?

**Comment by jszwedko** [comment]
@archoversight today hopefully 😄 Just tying up some loose ends. It'll be in 0.20.0.

**Pull request merged**
