### PR TITLE
feat(timestamp encoding): add unixtime formats

### PR DESCRIPTION
**Pull request by srstrickland**
* `unix_ms`: milliseconds
* `unix_us`: microseconds
* `unix_ns`: nanoseconds
* `unix_float`: seconds float

closes: https://github.com/vectordotdev/vector/issues/17323

### CODE REVIEW

**Review by aliciascott — APPROVED** [review]
No docs review required

**Comment by srstrickland** [comment]
When I run tests locally, I get 1 unrelated failure as reported [here](https://github.com/vectordotdev/vector/issues/18697)

```
thread 'sources::host_metrics::cgroups::tests::generates_cgroups_metrics' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', src/sources/host_metrics/cgroups.rs:474:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: test run failed
```

**Comment by pront** [comment]
> When I run tests locally, I get 1 unrelated failure as reported [here](https://github.com/vectordotdev/vector/issues/18697)
> 
> ```
> thread 'sources::host_metrics::cgroups::tests::generates_cgroups_metrics' panicked at 'assertion failed: `(left != right)`
>   left: `0`,
>  right: `0`', src/sources/host_metrics/cgroups.rs:474:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> error: test run failed
> ```

Hi @srstrickland and thanks for this PR!

Feels free to ignore that failure. We use `cargo vdev test` for running the test (relies on [cargo-nextest](https://nexte.st/#cargo-nextest)) and you can see it running in CI [here](https://github.com/vectordotdev/vector/actions/runs/6474123517/job/17579831975?pr=18817).

**Review by pront — APPROVED** [review]
LGTM

**Comment by srstrickland** [comment]
Sorry for the force-push; had to update the commits to have the right email associated so the CLA would clear.

**Pull request merged**
