### PR TITLE
chore(observability): Rename common counters

### PR DESCRIPTION
**Pull request by bruceg**
This is the start of work towards conforming components to the new spec (ref #8728), renaming the common counters emitted, and setting up common events which may be used by other components. This doesn't really have a defined issue to attach it to, but it is the start of the major work on #3900.

@leebenson, how do you want to handle renaming the metrics the API is looking for? Should I just do a text search-and-replace in the API code in this issue, or would you rather handle it separately?

### CODE REVIEW

**Comment by jszwedko** [comment]
Nice! I'll take a closer look next week, but I think we should aim to preserve backwards compatibility for the metrics for at least one release to let users migrate over. That is: publish the metrics under both the old and new names. I realize this would result in twice the number of internal metrics being reported though, so maybe we could have a flag to turn off the legacy metric names?

**Comment by bruceg** [comment]
Fair enough, I'll do that.

**Comment by spencergilbert** [comment]
> I realize this would result in twice the number of internal metrics being reported though, so maybe we could have a flag to turn off the legacy metric names?

Ref:
```
2021-09-10T22:33:04.620Z [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = true }` to disable them.
```

**Review by lukesteensen — APPROVED** [review]

**Comment by leebenson** [comment]
> @leebenson, how do you want to handle renaming the metrics the API is looking for? Should I just do a text search-and-replace in the API code in this issue, or would you rather handle it separately?

I think starting with a search-and-replace is fine, then a sanity check with `vector top` to ensure the metrics are reported, and the column names match.

If possible, I'd avoid making any changes to public API methods, unless @binarylogic thinks that our conventions should also extend to what's surfaced via the API. Here's the bulk of what we have currently:

image

If public API changes are warranted, then updating anything in [src/api](https://github.com/timberio/vector/tree/master/src/api) should be followed by:

```bash
make build-graphql-schema
```

... to generate the new JSON schema files which drives `top` / `tap`.

A subsequent `cargo build` should reveal if there's any drift in the public API. What it _won't_ catch in any case are internal changes (i.e. where the API is the same, but the metric we're looking at is a redundant string)-- which is why a cursory look at `vector top` should reveal any shifted ground.

We did historically have a bunch of API tests for probing expected metrics, but they were retired due to the convoluted manner I had tried to work around metrics being globally initialised. Re-implementation is being tracked in https://github.com/timberio/vector/issues/6984.

If you want me to jump in on the API, I'm happy to supplement this PR as required -- just let me know.

**Comment by bruceg** [comment]
Since this PR now only adds new metrics and does not rename anything, I will push any API changes into a separate issue.

**Pull request merged**
