### PR TITLE
chore(releasing): Remove PASS_FEATURES

### PR DESCRIPTION
**Pull request by jszwedko**
I don't see this environment variable being read anywhere.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
Never seen these before either - do they maybe do something magic for a dep we're building?

**Comment by tobz** [comment]
> Never seen these before either - do they maybe do something magic for a dep we're building?

I don't thinkkkkk so, since the only Google results for something like `PASS_FEATURES` and/or `default-cmake` is Vector.

**Review by tobz — APPROVED** [review]

**Comment by jszwedko** [comment]
> Never seen these before either - do they maybe do something magic for a dep we're building?

I can think of anything nor does anything come up when searching on Google. What is strange is I don't see where they were ever read though. Maybe it was something that was partially, but never fully, implemented.

**Review by spencergilbert — APPROVED** [review]
hehe, _Whoops_

**Pull request merged**
