### PR TITLE
chore(observability): Make check-events look at trace messages

### LINKED ISSUE #11472: Teach `check-events` to enforce required messages
The [component spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/component.md#bytesreceived) specifies a number of required texts for trace messages. We should make the `check-events` script enforce this text to prevent slippage against this spec.

### PR DESCRIPTION
**Pull request by bruceg**
Closes #11472 
Refers to [#OP-144](https://datadoghq.atlassian.net/browse/OP-144)

### CODE REVIEW

**Comment by jdrouet** [comment]
@bruceg in the following example, I'm not sure we should include the members in the `counter`
Screenshot 2022-03-01 at 08 33 01
If you don't mind, I'll update the script so that they don't get included

**Comment by jdrouet** [comment]
Rebase went wrong...

**Comment by bruceg** [comment]
Sure, go ahead and modify. Just be aware this is based on top of #11558 so it would be good to tackle that one first.

**Comment by jdrouet** [comment]
This PR is being replaced by #11747 in order to be merged to master directly.

**Comment by bruceg** [comment]
This PR will be finished in #11747

**Pull request closed without merging**
