### PR TITLE
chore(VRL decoder): add 'message' semantic meaning

### PR DESCRIPTION
**Pull request by pront**

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]

**Comment by pront** [comment]
> this PR would override semantic meanings

I realized that currently we don't allow setting semantic meanings in the VRL decoder. Those VRL functions are [not exposed](https://github.com/vectordotdev/vector/blob/master/lib/codecs/src/decoding/format/vrl.rs#L58). Still, I gave the above idea a try on a local branch and I think it's too complicated. It requires dynamically changing the schema definition between `build()` and after `build()`.

So overall I think this PR is the correct thing to do. Vector users can use a remap transform to change the meanings later.

**Review by jszwedko — COMMENTED** [review]
This still feels wrong to me to set `message` to the entire decoded event. I hear you that exposing the semantic meaning functions in the VRL codecs is complicated and so maybe we don't want to tackle that just yet, but I think the workaround for now, for users, would be to use a `remap` transform afterwards to set the required semantic meanings.

**Comment by jszwedko** [comment]
To help illustrate why I think this isn't right, consider a `vrl` decoder in a source and a `syslog` encoder in the sink. In general, I think users will be returning an object from the decoder that might have a message field, timestamp, host, etc.. The `syslog` encoder will then use that entire object as its "message" and not know where to find the host, timestamp, etc.. Instead, I think it's better to force the user to map the semantic meanings (ideally in the `vrl` decoder, but, absent that, in a follow up `remap` transform).

What problem is this actually solving? That might help me understand the intent here a bit more and maybe suggest an alternative.

**Comment by pront** [comment]
Hi @jszwedko, thank you for following up on this. 

>What problem is this actually solving?

The motivation behind this PR is having a sensible default `message` meaning for a collection of sources. 

----

Solution 1) An easy (but not ideal) solution here would be introducing a contract e.g. the `.message` event path is expected to store the `message` semantic meaning.

----

Solution 2) [My local branch](https://github.com/vectordotdev/vector/blob/pront/OPA-XXX_vrl_decoder_schema/lib/codecs/src/decoding/format/vrl.rs#L70-L78). It is easy to extend the functions to support setting semantic meanings, [see here](https://github.com/vectordotdev/vector/blob/pront/OPA-XXX_vrl_decoder_schema/lib/codecs/src/decoding/format/vrl.rs#L64). To make that branch complete,`pub fn schema_definition(...)` needs to read the semantic meaning list that was populated in build and return a modified schema definition.

What I dislike about the above: 
* changing `build(...)` interface to take in a `& mut self`. 
* `schema_definition()` returns different result based on when you call it (before or after build).

----

Interested to hear your thoughts. Happy to explore more solutions if you can think of any.

**Comment by pront** [comment]
I think the only solution worth pursuing is solution (2). Closing this PR for now. 

We will workaround by respecting the semantic meaning set by each source directly and ignore the schema definition of this decoder.

**Pull request closed without merging**
