### PR TITLE
feat(new sink): add CnosDB sink

### PR DESCRIPTION
**Pull request by Subsegment**
This pr adds [CnosDB](https://github.com/cnosdb/cnosdb) sink

### CODE REVIEW

**Comment by neuronull** [comment]
Hi @Subsegment , thanks for proposing this new sink!

Heads up- we have a formal process for accepting new components (https://docs.google.com/document/d/1ibgDdNVfub9tagRNbozwsUXn7WYGGaTwgQ9A_chx64s/edit#heading=h.ipe7eusyhxb) 

The list of questions there, are what we'll be looking at when we investigate this new integration you've proposed. So we will reach out soon probably with some questions around some of those topics. This all occurs before we review the code, in the case of the component not being accepted. As such, you can hold off on further changes to the code until we reach that decision.

Thanks

**Comment by Subsegment** [comment]
> Hi @Subsegment , thanks for proposing this new sink!
> 
> Heads up- we have a formal process for accepting new components: https://github.com/vectordotdev/vector/blob/master/CONTRIBUTING.md#new-sources-sinks-and-transforms
> 
> The list of questions there, are what we'll be looking at when we investigate this new integration you've proposed. So we will reach out soon probably with some questions around some of those topics. This all occurs before we review the code, in the case of the component not being accepted. As such, you can hold off on further changes to the code until we reach that decision.
> 
> Thanks

Hi @neuronull .I've created an issue. Without looking at the documentation before, I directly implemented it by analogy with other sinks. I am very sorry

**Comment by jszwedko** [comment]
Just a note that we are a bit backlogged at the moment, but plan to review this within the next couple of weeks. Thanks again for this contribution!

**Comment by Subsegment** [comment]
> Just a note that we are a bit backlogged at the moment, but plan to review this within the next couple of weeks. Thanks again for this contribution!

I understand. Thank you for your reply

**Comment by jszwedko** [comment]
Closing this based on the discussion in https://github.com/vectordotdev/vector/issues/18156 . Thanks for getting the ball rolling on this!

**Pull request closed without merging**
