### PR TITLE
chore(deps): Update Rust to 1.67.1

### PR DESCRIPTION
**Pull request by bruceg**
This is mostly clippy fixes of `format!("{}", x)` into `format!("{x}")`, with a few dozen `if let … else` sprinkled in, except for an issue with `track_caller` in the test utils.

### CODE REVIEW

**Comment by tobz** [comment]
@bruceg We should hold on this temporarily.

It looks like the change to [struct field grouping](https://github.com/rust-lang/rust/pull/102750/) has the potential to cause deserialization issues with `rkyv` for data that was serialized with a build based on a prior version of Rust.

I'll have to look into this a little more and see if it effects us and our particular archived structs.

**Comment by bruceg** [comment]
Possibly related: https://github.com/rust-lang/rust/issues/107440

**Comment by tobz** [comment]
For posterity, my comment above about holding can be considered resolved.

Chatting with the author of `rkyv`, we should be entirely protected from the aforementioned struct field ordering change as we use the `strict` feature flag for `rkyv`, which ensures a (more) deterministic object layout, regardless of compiler version, and so on.

**Comment by bruceg** [comment]
Replaced by #16744

**Pull request closed without merging**
