### PR TITLE
docs: Add Telegraf features to README

### LINKED ISSUE #14475: Comparing Telegraf
Hi all, I'm new at Vector and come from using Telegraf. I would love to see how Vector compares against Telegraf in the different performance tests and features table.

I opened corresponding issue on the harness repo: https://github.com/vectordotdev/vector-test-harness/issues/100

I can help by adding the Features table for Telegraf if I would know when exactly a tool gets a ✔️.

### PR DESCRIPTION
**Pull request by Hipska**
Closes #14475

### CODE REVIEW

**Comment by tobz** [comment]
@Hipska Would you mind providing link(s) to Telegraf's documentation that detail its behavior with regards to delivery guarantees?

Our definition of "delivery guarantees" is that there is support for a source (so let's say... something writing _to_ Telegraf using a request/response protocol) to be told that the event data it sent has been successfully processed by a sink (so wherever Telegraf happens to be sending the data).

Naturally, not all sources/inputs and sinks/outputs use a request/response protocol, so not all configurations will support delivery guarantees, but it wasn't clear from a cursory glance that Telegraf has any sort of delivery guarantee capabilities to begin with.

**Comment by Hipska** [comment]
Okay, that is indeed not something telegraf is providing. Telegraf can confirm the receiving of a metric to its input/source and is also aware of correct sending a metric to its output/sink, but there is no relation to the complete flow. I will remove that tick then..

As said in #14475, it is unclear when a tool gets a tick, so I'm open for comments.

**Comment by Hipska** [comment]
@tobz Maybe it should be outlined that the telegraf delivery guarantees are not end-to-end by the means of an icon or footnote?

**Review by jszwedko — APPROVED** [review]
Thanks @Hipska !

**Pull request merged**
