### PR TITLE
enhancement(api): Support tapping component inputs with vector tap

### LINKED ISSUE #7116: Tap should support inputs as well as outputs
Currently, Vector's `tap` API / CLI subcommand supports "outputs" -- events that flow _from_ a component, rather than _into_.

We should also support inputs. The use-case would be bidirectional observability into transforms (which have both inputs and outputs) and sinks (which only receive inputs.)

### PR DESCRIPTION
**Pull request by 001wwang**
Closes #7116 

This PR adds support for tapping the input of a component (either a transform or a sink) with `vector tap`. In essence, tapping a component's input is treated as a shortcut for tapping all outputs that flow into the component.

- Adds two options to the CLI command `--inputs-of` and `--outputs-of` to differentiate provided patterns. Users can still pass patterns the usual way as additional arguments, and those patterns are merged with any in `--outputs-of`. If no patterns are specified at all, we continue using `*` to match all outputs.
- Changes to `outputEventsByComponentIdPatterns` subscription
  - `patterns` argument is now `outputsPatterns` **(breaking change)**
  - `inputsPatterns` added as an additional argument

TODO
- [x] Update docs

### Example
For the following configuration:
```toml
[api]
enabled = true

[sources.test]
type = "demo_logs"
format = "shuffle"
lines = [
  "test1",
]

[sources.test2]
type = "demo_logs"
format = "shuffle"
lines = [
  "test2",
]

[transforms.remap]
type = "remap"
inputs = ["test*"]
source = '''
  .new_field = "new"
'''

[sinks.out]
type = "blackhole"
inputs = ["remap"]
```
running 
```bash
vector tap --inputs-of "remap","out"
```
will display the following:
```jsonc
{"message":"test1","source_type":"demo_logs","timestamp":"2022-02-10T01:05:06.657261335Z"} // input to remap
{"message":"test2","source_type":"demo_logs","timestamp":"2022-02-10T01:05:06.657316360Z"} // input to remap
{"message":"test1","new_field":"new","source_type":"demo_logs","timestamp":"2022-02-10T01:05:06.657261335Z"} // input to blackhole
{"message":"test2","new_field":"new","source_type":"demo_logs","timestamp":"2022-02-10T01:05:06.657316360Z"} // input to blackhole
```
Some other commands to try include:
- `vector tap --outputs-of "*" --inputs-of "*"`
- `vector tap --outputs-of "test" "test2"` (using both `--outputs-of` option and `<component_id_patterns>` argument)
- `vector tap` (should match all outputs as before)

You can also test these changes in the GraphQL API playground. For the following subscription
```graphql
subscription {
  outputEventsByComponentIdPatterns(outputsPatterns: [], inputsPatterns: ["remap"]) {
    __typename
    ... on EventNotification {
      notification
      pattern
    }
    ... on Log {
      componentId
      string(encoding: JSON)
    }
  }
}
```

You should see results like so
```jsonc
// EventNotification
{
  "__typename": "EventNotification",
  "notification": "MATCHED",
  "pattern": "remap"
}

// Log
{
  "__typename": "Log",
  "componentId": "test2",
  "string": "{\"message\":\"test2\",\"source_type\":\"demo_logs\",\"timestamp\":\"2022-02-10T01:11:45.656816489Z\"}"
}
```

### CODE REVIEW

**Review by leebenson — CHANGES_REQUESTED** [review]
Seeing some CI errors reporting mismatched types. Would you mind checking those @001wwang before I review? Thanks.

**Comment by 001wwang** [comment]
> Seeing some CI errors reporting mismatched types. Would you mind checking those @001wwang before I review? Thanks.

Sorry about that, think some things were outdated in this branch when I made the PR. It should be good to go now; I'll wait until I see CI passing to officially re-request review.

**Review by jszwedko — COMMENTED** [review]
Nice work! I played around with it locally and it looks good to me.

I can review again once the docs have been updated. We should also add a note to the upgrade guide for 0.21 about the API change.

**Review by jszwedko — APPROVED** [review]
Docs updates look good! Thank you!

**Review by leebenson — APPROVED** [review]
Great work!

I merged master and added a cfg flag to unblock the component features CI test. Will go ahead and merge this to continue reviewing your other open PRs, @001wwang.

**Pull request merged**
