### PR TITLE
chore(deps): Upgrade to Rust 1.57

### PR DESCRIPTION
**Pull request by jszwedko**
- chore(deps): Revert upgrade to Rust 1.57
- chore(deps): Upgrade to Rust 1.57

### CODE REVIEW

**Comment by jszwedko** [comment]
The k8s e2e issue ended up being that I removed an unused field, but the field was a `TempDir` that was being held onto to avoid it being dropped and the directory being deleted. I updated the struct to just implement `Drop` directly.

**Comment by jszwedko** [comment]
I think the test failures are unrelated.

**Comment by spencergilbert** [comment]
I'm not super excited about merging with failing integration tests - did they pass during other runs as you iterated here?

**Comment by jszwedko** [comment]
@spencergilbert yeah, me neither. I can rerun them. The fluent one I've seen before. The MongoDB one is new.

They did pass for the previous commit updating to Rust 1.57: https://github.com/vectordotdev/vector/runs/4437377495?check_suite_focus=true

**Review by spencergilbert — APPROVED** [review]
Probably worth issues for the flakey test/s if we don't have them already

**Comment by jszwedko** [comment]
👍 I opened one for fluent: https://github.com/vectordotdev/vector/issues/10345

I'll leave the mongodb one for now since this is the first I've seen it. I'm hoping we can integrate with Datadog's CI product at some point to get numbers on these flakes.

**Pull request merged**
