### PR TITLE
fix(ci): fix publish workflow permissions

### PR DESCRIPTION
**Pull request by bthuilot**
## Summary
Fixes workflow permission for publish

## Change Type
- [X] Non-functional (chore, refactoring, docs)

## Is this a breaking change?
- [X] No

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
I tried to test this branch, but we currently have workflows set to readonly so it ran into that. We'll have to test after re-enabling.

Screenshot 2024-11-12 at 5 25 25 PM

**Comment by bthuilot** [comment]
@jszwedko updated `custom_build.yml` because i think that will require it too

**Comment by jszwedko** [comment]
> @jszwedko updated `custom_build.yml` because i think that will require it too

Thanks! I added it to the others that call publish.yml in [2cc7bf4](https://github.com/vectordotdev/vector/pull/21773/commits/2cc7bf4f6fb259ef7fbe6a6234b98d9e4420e3da)

**Comment by jszwedko** [comment]
Testing here: https://github.com/vectordotdev/vector/actions/runs/11818786288

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
