### PR TITLE
enhancement(networking): Add support for inline TLS keys

### LINKED ISSUE #2172: Enable building TLS with in memory public/private keys
Currently `TlsSettings` are builded  with `TlsOptions` which accept paths to files with certificates. 

In the case of loading configuration on how to connect to Kubernetes cluster from `KUBECONFIG` file, we may load embeded ASCII public/private key from the file. 

This loading is done only for one test (`watch_pod`), so, before, it was solved by storing the public key in a tmp file and passed to `TlsOptions`. But this hack can't/shouldn't be done for private key, so currently `watch_pod` test is disabled for this reason.

### PR DESCRIPTION
**Pull request by bruceg**
This changes the name of the TLS options from `*_path` to `*_file`, but adds a serde alias to avoid breaking existing configs.

Closes #2172

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]

**Comment by binarylogic** [comment]
@bruce does this support both paths and inline keys?

**Comment by bruceg** [comment]
Yes, this is meant to support both paths and inline keys. The options have been renamed but a serde alias allows the old option names to continue to be used.

While reading the diffs, I notice that my search-and-replace renaming of options changed more files that it should have. I will redo this patch series without the extraneous changes and add tests to ensure both use cases.

**Comment by binarylogic** [comment]
Sounds good. I would update the docs for these options to note that inline values are also accepted.

**Comment by bruceg** [comment]
@binarylogic The documentation does describe including inline values. Did I miss a spot?

**Comment by binarylogic** [comment]
Ah! I must have misread. Looks good.

**Review by binarylogic — APPROVED** [review]

**Pull request merged**
