### PR TITLE
chore(ci): Group and tag component feature check output

### PR DESCRIPTION
**Pull request by jszwedko**
Otherwise it's difficult to figure out which check actually failed, if
one does, since the lines are interwoven.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by bruceg — COMMENTED** [review]
Hmm, my `parallel` (`parallel 20220522`) doesn't have `--output-sync`. What does this do? Would `--group` make sense?

**Comment by jszwedko** [comment]
> Hmm, my `parallel` (`parallel 20220522`) doesn't have `--output-sync`. What does this do? Would `--group` make sense?

Doh, yes 😄 I was actually pulled that flag from `make`'s `man` page by accident 😓 `--group` is what I want.

**Review by bruceg — COMMENTED** [review]
With all the output grouped together, and the test script itself outputting a header, I'm not sold on adding `--tag` to the output here. This is what it looks like in the logs:
```
aws-ec2-metadata-integration-tests	===== Feature: aws-ec2-metadata-integration-tests =====
aws-ec2-metadata-integration-tests	    Finished dev [unoptimized + debuginfo] target(s) in 56.26s
```
That's kinda redundant and stretches the output wide.

**Comment by jszwedko** [comment]
> With all the output grouped together, and the test script itself outputting a header, I'm not sold on adding `--tag` to the output here. This is what it looks like in the logs:
> 
> ```
> aws-ec2-metadata-integration-tests	===== Feature: aws-ec2-metadata-integration-tests =====
> aws-ec2-metadata-integration-tests	    Finished dev [unoptimized + debuginfo] target(s) in 56.26s
> ```
> 
> That's kinda redundant and stretches the output wide.

Yeah, good call, `--tag` isn't needed here. I wasn't sure if the header line was going to be grouped to but didn't realize that was coming from the `scripts/check-one-feature` and not `parallel` itself. I pushed another commit dropping `--tag`.

**Review by bruceg — APPROVED** [review]

**Pull request merged**
