### PR TITLE
feat(remap): Add parse_spring_boot function

### LINKED ISSUE #16190: Add function parse spring boot default log format
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

example log format:

2023-01-30 22:37:33.495  INFO 72972 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel cacheConsumer-in-0
2023-01-30 22:37:33.514  INFO 72972 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel nullChannel
2023-01-30 22:37:33.520  INFO 72972 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel reqDataConsumer-in-0
2023-01-30 22:37:33.528  INFO 72972 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler _org.springframework.integration.errorLogger

want add a parse_spring_boot function

### Attempted Solutions

_No response_

### Proposal

_No response_

### References

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by ztkmkoo**
Closes #16190 

Signed-off-by: Kebron [ztkmkoo@gmail.com](mailto:ztkmkoo@gmail.com)

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Hi @ztkmkoo ! Thanks for this! We'll get a more thorough review of the implementation soon, but would you also be able to add the docs for this new function? You can see the other function documentation here: https://github.com/vectordotdev/vector/tree/master/website/cue/reference/remap/functions . You should be able to copy/paste a similar function and modify it.

**Comment by ztkmkoo** [comment]
> Hi @ztkmkoo ! Thanks for this! We'll get a more thorough review of the implementation soon, but would you also be able to add the docs for this new function? You can see the other function documentation here: https://github.com/vectordotdev/vector/tree/master/website/cue/reference/remap/functions . You should be able to copy/paste a similar function and modify it.

Hi, I just checked this comment.
Okay, i will add new docs for this pr!

**Comment by ztkmkoo** [comment]
@jszwedko I add the docs. plz check it. thx!

**Comment by fuchsnj** [comment]
I apologize for the inconvenience, but VRL has been moved to a [separate repo](https://github.com/vectordotdev/vrl), and this PR will need to be moved over there.

**Pull request closed without merging**
