### PR TITLE
feat(reduce transform): "concat_newline" strategy merges using newline

### LINKED ISSUE #4571: Default the `reduce` transform's `concat` strategy to join with a `\n`
As a first step in making the `reduce` transform flexible enough to handle multi-line events, we want to change the behavior of the `concat` merge strategy. Currently, this simply joins strings without a delimiter, we'd like to join them with a `\n` delimiter instead.

### PR DESCRIPTION
**Pull request by JeanMertz**
closes #4571.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Is it possible to provide more context for this change? How would people use it to join multiline events? https://github.com/timberio/vector/issues/4571 is it a bit lacking.

I'd prefer letting users specify the character to concat with, but I'm not quite sure how to fit that into the current config. Maybe something like:

```toml
  merge_strategies.method = 'concat | "\n"' # similar to timestamp coercer in the coerce transform
```

or

```toml
  merge_strategies.method = "concat" # defaults to space
  merge_strategies.method.concat.separator = "\n" # overrides separator
```

?

As this PR stands, it seems like it should be labeled as a breaking change given it is changing the behavior of the "concat" strategy.

**Comment by binarylogic** [comment]
To solve the multi-line issue we must be able to join with a `\n` character, not ` `. This reconstructs the logs as they were intended. I'm open to specifying the delimiter, but I can't think of a use case where someone would not want `\n`.

**Comment by jszwedko** [comment]
@binarylogic The `reduce` transform operates at the field level though, no? Or do you mean they'd just want to concat `message` fields from multiple events with newlines? I could see it being useful to concat with spaces or other characters for non-`message` fields.

**Comment by JeanMertz** [comment]
> I'd prefer letting users specify the character to concat with

I agree with this. This was the quickest solution, and the one proposed in #4571. The second quickest (and non-breaking) solution would be to add a `concat_newline` strategy.

A somewhat more complex (but more flexible) solution would be the one you proposed, `concat | "\n"`, but I don't see a big need for that right now.

> As this PR stands, it seems like it should be labeled as a breaking

I agree, which is why I labelled it as such when I created the PR 😛

**Comment by jszwedko** [comment]
> > I'd prefer letting users specify the character to concat with
> 
> I agree with this. This was the quickest solution, and the one proposed in #4571. The second quickest (and non-breaking) solution would be to add a `concat_newline` strategy.
>
> A somewhat more complex (but more flexible) solution would be the one you proposed, `concat | "\n"`, but I don't see a big need for that right now.

Agreed, I might prefer to just add a `concat_newline` strategy for now to avoid the breaking nature of the change since there doesn't seem to be much downside aside from proliferating the strategies.
 
> > As this PR stands, it seems like it should be labeled as a breaking change
> 
> I agree, which is why I labelled it as such when I created the PR stuck_out_tongue

:smile: it doesn't seem to be labeled as such though, no? The title needs a `!`.

**Comment by binarylogic** [comment]
I say we defer this so we can focus on solving the multi-line problem, which is urgent and blocking large installations.

**Comment by JeanMertz** [comment]
@jszwedko @binarylogic updated the PR to add `concat_newline`, which is similar to `concat`, except that it only works on strings (`concat` also works on arrays), and uses `\n` (newline) instead of ` ` (space) to concatenate the fields.

**Comment by jszwedko** [comment]
Aha, I missed the Github Label, I didn't realize we had that. I think the `!` in the PR title is necessary for our semantic commit log handling. I'll update.

:+1: to adding `concat_newline`. Is there a reason we wouldn't want to support it with arrays too, though? I realize that may be used less, but the consistency would be nice.

**Comment by jszwedko** [comment]
I need to slow down :smile: This change is no longer breaking, I removed the `!`.

**Comment by JeanMertz** [comment]
@jszwedko added a test-case for the concatenation of arrays.

**Comment by jszwedko** [comment]
> Concatenating arrays results in a new array with all elements from both arrays. There isn't really any use-case for concatenating an array "using newlines".

Aha, I misunderstood, I was thinking concat'ing arrays was "joining the elements with a delimiter".

:+1:

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
