### PR TITLE
chore(buffers): new `BufferSender<T>`/`BufferReceiver<T>` + buffer topology builder

### LINKED ISSUE #9916: Buffer Improvements: create new buffer sender/receiver
_Part of the Buffer Improvements RFC ([RFC](https://github.com/vectordotdev/vector/blob/ac2b1f04fe12251b9c24af58461891100cc0ffe2/rfcs/2021-10-14-9477-buffer-improvements.md), #9476)_

We need to create the two new buffer channel types -- `BufferSender<T>` and `BufferReceiver<T>` -- that will be used in the overhauled design.

Attention will need to be paid to ensuring that they are composable, and that common misuse -- multiple channels configured but overflow mode not yet, etc -- is kept to a minimum or detected in a way that can be bubbled up during construction.

### LINKED ISSUE #9917: Buffer Improvements: create new buffer builder
_Part of the Buffer Improvements RFC ([RFC](https://github.com/vectordotdev/vector/blob/ac2b1f04fe12251b9c24af58461891100cc0ffe2/rfcs/2021-10-14-9477-buffer-improvements.md), #9476)_

We need to create a new buffer builder that works with the proposed chained design for buffers.

Our goal here is that buffer configurations can be, effectively, fed into the builder sequentially, and the builder will do the lifting of figuring out if the pieces fit together in a valid way.

We need to be able to return suitable errors that can be reported through the config parsing/builder code so that buffer-related configuration errors are actionable.

### PR DESCRIPTION
**Pull request by tobz**
This PR introduces three new primary types as part of the Buffer Improvements work: `BufferSender<T>`, `BufferReceiver<T>`, and `TopologyBuilder`.

The first two types are the proposed design for opaque sender/receiver types that will be used in the future for the reworked buffering system.  The description of their functionality, in principle, can be read about [here](https://github.com/vectordotdev/vector/blob/ac2b1f04fe12251b9c24af58461891100cc0ffe2/rfcs/2021-10-14-9477-buffer-improvements.md#implementation), although the code comments themselves should also, hopefully, be illuminating.

The third type, `TopologyBuilder`, is a new builder type for constructing cascaded buffer topologies where one buffer type feeds into another, and so on.

We've also introduced a few other items in the PR by necessity:
- we had to fix up some `tracing`-related dependencies to handle default features being turned off, and the new default behavior of Cargo (`resolver = "2"`) when unifying feature flags across crates for the same dependency
- a custom implementation of `PollSender<T>` from `tokio_util`

The custom implementation of `PollSender<T>` is due to tokio-rs/tokio#4214 not yet being merged.  I opted to simply copy the code over for now, given that I rewrote a lot of it, and feel comfortable with supporting it in the interim... and also just to avoid any potential Cargo patching shenanigans, or errors related to "are you using multiple versions of `crate-here`?".

Closes #9916.
Closes #9917.

### CODE REVIEW

**Review by blt — APPROVED** [review]
Nice work here. Micro-benchmark numbers are stable?

**Comment by tobz** [comment]
Hmm, I have not benchmarked it one bit.  This is all brand-new code, so nothing _else_ should have changed.

**Comment by blt** [comment]
> Hmm, I have not benchmarked it one bit. This is all brand-new code, so nothing _else_ should have changed.

Was curious, just in case you'd hooked it up in development.

**Comment by tobz** [comment]
I'll slap a simple end-to-end test in there just to see what it adds over a raw channel.

**Pull request merged**
