### PR TITLE
fix(remap transform): only add dropped output when enabled

### LINKED ISSUE #10129: [Topology] New reroute dropped feature creates `.dropped` stream regardless of `reroute_dropped=false` config
### Vector Version
```
vector 0.18.0 (x86_64-unknown-linux-gnu c77e085 2021-11-18)
```

### Vector Configuration File

Consider the following toy Vector pipeline configuration:
```yaml
sources:
  stdin:
    type: stdin

transforms:
  parse-syslog:
    type: remap
    inputs:
      - stdin
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = parse_syslog!(.message)
  parse-key-value:
    type: remap
    inputs:
      - parse-syslog
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = parse_key_value!(.message)

  logger:
    type: remap
    inputs:
      - '*.dropped'
    drop_on_error: true
    reroute_dropped: false
    source: |-
      host = string!(.host)
      message = string!(.message)
      component_id = string!(.metadata.dropped.component_id)
      log("component '" + component_id + "' dropped message from <" + host + ">: " + message, level: "warn")

sinks:
  console:
    type: console
    inputs:
      - parse-key-value
    encoding: json
```

### Expected Behavior

The above configuration should not have any cyclic dependency. For example, `vector graph` should show this:

image

### Actual Behavior

Vector seems instead to be creating an unexpected cyclic dependency at the `logger` component:

image

I noticed that using the following wildcard works as expected:
```yaml
    inputs:
      - 'parse-*.dropped'
```
Therefore, looks like using the wildcard at the very beginning is problematic?
The [documentation](https://vector.dev/docs/reference/configuration/#wilcards-in-component-ids) suggests that the wildcard can be used anywhere.

Furthermore, if you include the `logger` component as input for anything else, then Vector complaints about the cyclic dependency:
```yaml
sinks:
  console:
    type: console
    inputs:
      - parse-key-value
      - logger
    encoding: json
```
```
2021-11-19T22:49:39.562474Z ERROR vector::cli: Configuration error. error=Cyclic dependency detected in the chain [ logger -> logger ]
```
This is how I discovered this issue.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #10129

This is a bit of a hack, but it's small and should fix a wart that would otherwise have to wait until we do more remodeling of the transform model for branching. It takes advantage of the `impl<T> FunctionTransform for T where T: FallibleFunctionTransform` that was previously only used in tests and simply discards any error outputs. In this case we won't actually do any discarding because we know that the transform itself isn't configured to actually write anything to that output.

### CODE REVIEW

**Review by JeanMertz — APPROVED** [review]
Ah, interesting. That's a very clever (temporary) solution 👍

**Review by jszwedko — APPROVED** [review]
Nice! Makes sense. Sorry to be annoying, but could we wrap a test around this? At least `named_outputs`.

**Review by jszwedko — APPROVED** [review]
🎉

**Comment by hhromic** [comment]
So nice that you quickly managed to improve on this @lukesteensen, much appreciated!

**Pull request merged**
