### PR TITLE
enhancement(observability): add batch size histogram metric

### PR DESCRIPTION
**Pull request by lukesteensen**
There are likely more places we will want to add this for consistency,
but I'd like to get some soak numbers on the overhead of doing so.

Signed-off-by: Luke Steensen <luke.steensen@gmail.com>

### CODE REVIEW

**Comment by jszwedko** [comment]
Well, except for the performance regression maybe 😓

**Comment by lukesteensen** [comment]
I'm hoping the perf hit won't be quite as bad if this gets rebased on top of https://github.com/vectordotdev/vector/pull/11289.

**Review by blt — APPROVED** [review]

**Comment by jszwedko** [comment]
@lukesteensen just noticing that this metric wasn't documented. Do you mind adding it to the cue data?

**Comment by lukesteensen** [comment]
Just noting, this was documented in https://github.com/vectordotdev/vector/pull/12848

**Pull request merged**
