### PR TITLE
chore: Extract the ring-ish structure implicit in Fanout

### PR DESCRIPTION
**Pull request by blt**
One of the oddities of `Fanout` was the use of an `i` to index sinks. This was,
partially, preserved across polls but was not in general use when looping. It is
my understanding that `Fanout.i` was ultimately vestigial and any actual
indexing was reset each poll. I think, as a result, we would also repoll the
same sink multiple times when removals happened, which should be rare in
practice but was possible. I have extracted the vector and index munging into a
`Store` type. We should now no longer poll underlying sinks multiple times and
calling code does not have to munge indexes, although it is required to manually
advance/reset a 'cursor' because we're changing the shape of an iterator while
iterating it.

The primary difference here is the use of `swap_remove` instead of
`remove`. This saves a shift.

I expect no performance change here. I think, ultimately, this is a stepping
stone to getting the logic here very explicit so we can start to do broadcasting
in a way that is not impeded by slow receivers downstream. Or, less so.

REF #10144
REF #10912

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by lukesteensen — COMMENTED** [review]
> One of the oddities of `Fanout` was the use of an `i` to index sinks. This was, partially, preserved across polls but was not in general use when looping. It is my understanding that `Fanout.i` was ultimately vestigial and any actual indexing was reset each poll.

I think this is true everywhere except `poll_ready`. Given semantics of `poll_ready` on a channel-like sender effectively reserving a slot for a new item, it does seem like a place where we were using the `i` struct member directly for iteration and therefore avoiding double-polling any sinks that had already indicated ready. This seems like something we likely want to keep, unless the semantics of `poll_ready` mentioned are inaccurate.

**Comment by blt** [comment]
> > One of the oddities of `Fanout` was the use of an `i` to index sinks. This was, partially, preserved across polls but was not in general use when looping. It is my understanding that `Fanout.i` was ultimately vestigial and any actual indexing was reset each poll.
> 
> I think this is true everywhere except `poll_ready`. Given semantics of `poll_ready` on a channel-like sender effectively reserving a slot for a new item, it does seem like a place where we were using the `i` struct member directly for iteration and therefore avoiding double-polling any sinks that had already indicated ready. This seems like something we likely want to keep, unless the semantics of `poll_ready` mentioned are inaccurate.

I think I'm missing something subtle here potentially. I am aware of some channels reserving extra slots but I didn't realize -- and can't find documentation -- for that being a general consideration. Very possible that I've overlooked something. That said, assuming that it is a general consideration, I'm confused about why _only_ `poll_ready` would make use of `Self.i`.

**Comment by lukesteensen** [comment]
I guess it comes down to an interpretation of the `poll_ready` contract that may be overly strict. We're assuming that each call to `start_send` must be preceded by exactly one successful call to `poll_ready`. That results in `poll_ready` being the only place where we need to maintain the iteration index across polls, because we don't want to call `poll_ready` on anything that has already returned `Ready`.

It doesn't matter in `start_send` because everything there must succeed due to the previous calls to `poll_ready`, and it doesn't matter for `poll_{flush,close}` because those both can happen multiple times successfully without issue. That's why in those cases we just use a local iteration index.

Reading the `Sink` docs again, it doesn't explicitly mention that you can't `poll_ready` multiple times per `start_send`. I'd still be a little nervous about implementation-specific issues though.

**Comment by blt** [comment]
> I guess it comes down to an interpretation of the `poll_ready` contract that may be overly strict. We're assuming that each call to `start_send` must be preceded by exactly one successful call to `poll_ready`. That results in `poll_ready` being the only place where we need to maintain the iteration index across polls, because we don't want to call `poll_ready` on anything that has already returned `Ready`.
> 
> It doesn't matter in `start_send` because everything there must succeed due to the previous calls to `poll_ready`, and it doesn't matter for `poll_{flush,close}` because those both can happen multiple times successfully without issue. That's why in those cases we just use a local iteration index.

Aaah I see what you're saying now, yes. Yes I have changed the behavior here because I misunderstood what it was we were up to.

**Comment by blt** [comment]
This is a dead-end, predicated partially on a misunderstanding. Thanks for setting me straight @lukesteensen.

**Pull request closed without merging**
