### PR TITLE
chore(performance): Test use of `BTreeSet` in `EventFinalizers`

### PR DESCRIPTION
**Pull request by bruceg**

### CODE REVIEW

**Comment by bruceg** [comment]
Small sped-ups on the `http_to_http_acks` without major slowdowns on others, and it re-enables the merge test. Maybe worth it?

**Review by jszwedko — APPROVED** [review]
👍 seems like a step forward

**Review by blt — APPROVED** [review]

**Comment by blt** [comment]
> Small sped-ups on the `http_to_http_acks` without major slowdowns on others, and it re-enables the merge test. Maybe worth it?

Hmm, the most [recent](https://github.com/vectordotdev/vector/pull/10624#issuecomment-1003137017) soak shows a 20% drop in throughput. I think, considering that the test is marked erratic, there's no way to say whether this change actually has an impact. Other non-erratic soaks do show a confident drop in throughput with this patch, but below our regression threshold. 

I'd be inclined to not go forward with this.

**Comment by bruceg** [comment]
> I'd be inclined to not go forward with this.

Agreed

**Pull request closed without merging**
