### PR TITLE
fix(vrl): Fix `target_insert` for metric tags

### PR DESCRIPTION
**Pull request by fuchsnj**
closes https://github.com/vectordotdev/vector/issues/14693

Previously assigning to `.tags` of a metric would only append tags. Now it overwrites instead.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Sweet, thanks for the quick fix!

**Review by spencergilbert — APPROVED** [review]

**Comment by datsabk** [comment]
@fuchsnj - What's the usual frequency of release? When can we expect to see a new release with this fix?

**Comment by fuchsnj** [comment]
@datsabk We usually release every ~6 weeks. This PR is tagged for version `0.25` which is planned to be released October 17th

**Comment by JeanMertz** [comment]
@datsabk we do have nightly releases, in case you want to try out this fix in your set-up.

See: https://packages.timber.io/vector/nightly/latest

**Comment by datsabk** [comment]
Thanks @JeanMertz and @fuchsnj - I'll give a shot to the nightly release this week

**Pull request merged**
