### PR TITLE
enhancement(greptimedb_logs sink): provide a default value for greptimedb logs pipeline_name

### PR DESCRIPTION
**Pull request by sunng87**
## Summary

The change made `pipeline_name` for greptimedb log sink an optional configuration item. A default value is provided.

## Change Type
- [ ] Bug fix
- [ ] New feature
- [x] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## How did you test this PR?

Integration test provided

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist
- [] Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- [ ] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

### CODE REVIEW

**Review by estherk15 — APPROVED** [review]

**Review by pront — APPROVED** [review]

**Comment by pront** [comment]
Thanks @sunng87

**Comment by sunng87** [comment]
Sorry for delay of CI issue fix. Could you please trigger CI again? Thank you!

**Comment by jszwedko** [comment]
@sunng87 it looks like the integration test for GreptimDB failed here:

```
 sinks::greptimedb::logs::integration_tests::test_greptimedb_logs_sink_default_pipeline
```

You can run this locally via `make test-integration-greptimedb`.

**Comment by sunng87** [comment]
@jszwedko Thank you! I confirm integration tests pass locally

**Pull request merged**
