### PR TITLE
fix(config): allows fetching secrets from AWS secrets manager with sso profiles

### PR DESCRIPTION
**Pull request by britton-from-notion**
# Changes

- updates `aws-config` dependency to add the `sso` cargo feature

# Issue

When testing Vector configs locally that make use of the `aws_secrets_manager` secret backend and using an AWS Profile that leverages SSO, the ProfileFile provider from the aws sdk causes vector to fail. It notes the issue being a missing cargo feature, `sso`.

Given the following style of AWS config profile and secret configuration, the proceeding error will surface.

## Profile

```
[profile example]
sso_start_url=https://example.com
sso_region=us-east-1
sso_account_id=12345678
sso_role_name=example-role-name
region=us-east-1
output=json
```

## Secret Config

```yaml
secret:
  my_token:
    type: "aws_secrets_manager"
    secret_id: "staging/my-token"
```

## Output

```
vector test *.yml

Running tests
2024-08-09T21:50:16.839325Z  WARN aws_config::meta::credentials::chain: provider failed to provide credentials provider=Profile error=the credentials provider was not properly configured: ProfileFile provider could not be built: This behavior requires following cargo feature(s) enabled: sso.  (InvalidConfiguration(InvalidConfiguration { source: "ProfileFile provider could not be built: This behavior requires following cargo feature(s) enabled: sso. " }))
2024-08-09T21:50:16.846118Z ERROR vector::unit_test: Failed to execute tests:
Error while retrieving secret from backend "splunk_hec_token": dispatch failure..
```

# Solution

By following the error message's recommendations and adding the sso cargo feature, this error is fixed and vector pulls the secret successfully. After making the change and rebuilding vector, the error goes away and all the tests run successfully.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Good catch, thanks @britton-from-notion !

Do you mind adding a changelog entry describing the fix to use in the release notes for the next release? See https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md for the format.

**Comment by britton-from-notion** [comment]
Yep! Happy to!

**Comment by britton-from-notion** [comment]
@jszwedko I've added a changelog entry ✅

**Review by jszwedko — APPROVED** [review]
Perfect, thank you!

**Comment by britton-from-notion** [comment]
@jszwedko realized I mis-named the changelog file so you may have to re-enable auto merge now that I fixed that

**Comment by jszwedko** [comment]
No worries!

**Pull request merged**
