### PR TITLE
enhancement(gcp_pubsub sink, codecs)!: Integrate `encoding::Encoder` with `gcp_pubsub` sink

### PR DESCRIPTION
**Pull request by pablosichert**
Part of #9459.

This is a breaking change since the `encoding` is no longer optional.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Can we add a note to the upgrade guide since this is a breaking change?

**Comment by jszwedko** [comment]
Also, why is it no longer optional? Could we maintain the existing default?

**Comment by pablosichert** [comment]
> Also, why is it no longer optional? Could we maintain the existing default?

Largely to be consistent with all the other sinks. Previously there only existed a default here because the user had no choice at all. So I'm not sure it's worth to break consistency to remain backwards compatible here, especially since the migration path is very straight-forward.

**Review by jszwedko — COMMENTED** [review]
Thanks for adding the upgrade note. Do we need to update the docs too? Currently that option is undocumented for this sink.

**Comment by pablosichert** [comment]
@jszwedko added the `json` and `text` codecs for now until we document all new ones for the integration with #9459

**Review by jszwedko — APPROVED** [review]
Sweet, thanks!

**Review by lukesteensen — APPROVED** [review]

**Pull request merged**
