### PR TITLE
chore(sinks): fix endpoint strip for aws region

### LINKED ISSUE #3067: bug(aws_s3 sink): specified endpoint sometimes has URL mutated unexpectedly.
Confirmed on FreeBSD (ZFS):

image

Regression from 0.7.2.

Potentially complicating #2966

### PR DESCRIPTION
**Pull request by fanatid**
Closes https://github.com/timberio/vector/issues/3067

Introduced in #2489: https://github.com/timberio/vector/pull/2489/files#diff-9eda8574251e683f40cb5255b9709c13R74

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]

**Comment by binarylogic** [comment]
I'd like to get @bruceg's approval before merging this, just to make sure this doesn't regress a separate feature that we are not aware of.

**Review by lukesteensen — COMMENTED** [review]
I'd like to add a test for the case that showed us this bug.

**Review by bruceg — CHANGES_REQUESTED** [review]
I agree with @lukesteensen, this needs a test case to demonstrate the issue, preferably handling all of:
1. No trailing slash on URL,
2. With a trailing slash,
3. With trailing slash and path,
4. Maybe all of the above with a query string.
I see I tested #1, and #3 with a query, but I obviously didn't check other cases.

**Comment by fanatid** [comment]
Pushed test, but github not displayed new changes in branch..

**Review by bruceg — APPROVED** [review]

**Comment by Hoverbear** [comment]
Did... GA break?

**Pull request merged**
