### PR TITLE
fix(gcp_stackdriver_metrics): Fixes GcpSeries serialization format without breaking config.

### PR DESCRIPTION
**Pull request by jasonahills**
fix(gcp_stackdriver_metrics): Fixes `GcpSeries` serialization format without breaking config.

### CODE REVIEW

**Comment by jasonahills** [comment]
Fixes https://github.com/vectordotdev/vector/issues/14890.

Alternative approach to https://github.com/vectordotdev/vector/pull/16089 which avoids breaking vector's configuration format.

Thanks!

**Review by StephenWakely — CHANGES_REQUESTED** [review]
I'd like to have a test for this to make sure we are creating the expected json. Would it be possible to extract the creation of `gcp::GcpSeries` into a separate function that then asserts that it converts to the correct json?

**Comment by jasonahills** [comment]
@StephenWakely , I've added a test which would detect any future regressions of this sort (e.g. where we accidentally change the serialized output when making another change).  Is this what you are looking for?

**Review by StephenWakely — APPROVED** [review]
Perfect!

**Comment by StephenWakely** [comment]
CI is failing because `/home/runner/work/vector/vector/src/sinks/gcp/mod.rs` needs to be run through rustfmt. Are you able to do this?

**Comment by jasonahills** [comment]
Whoops!  Sorry I forgot that!.  I have pushed a commit which fixes the formatting.  Thanks!

**Comment by StephenWakely** [comment]
@jasonahills many thanks!

**Pull request merged**
