### PR TITLE
chore(buffers): buffer improvements RFC

### PR DESCRIPTION
**Pull request by tobz**
[Rendered](https://github.com/timberio/vector/blob/tobz/rfc9477-buffer-improvements/rfcs/2021-10-14-9477-buffer-improvements.md)

Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>

### CODE REVIEW

**Comment by jszwedko** [comment]
> EDIT: Thinking about it a little more, we might actually want to introduce some logic to `BufferReceiver` to randomize how it checks the channels, such that we always ensure that the overflow receiver is checked first at least some of the time to avoid starving it from being drained, while simultaneously avoiding the base receiver waiting for the overflow receiver to be drained, which could cause a backpressure spike that was the inverse of the overflow receiver's activity.

🤔 this makes sense though would have an impact on UX when using `drop_newest`. We'll need to clearly communicate the behavior to users. There are also some sinks, like `loki` that depend on the events being ordered which this random polling would interrupt. Maybe it could be user configurable? Like "always drain buffer first" vs. "randomly accept new events".

**Comment by binarylogic** [comment]
The ordering constraint is something I'd really like to drop, and Lokis latest release no longer requires it. I'm not aware of any other sink or use case that requires ordering.

**Comment by tobz** [comment]
> 🤔 this makes sense though would have an impact on UX when using `drop_newest`. We'll need to clearly communicate the behavior to users. There are also some sinks, like `loki` that depend on the events being ordered which this random polling would interrupt. Maybe it could be user configurable? Like "always drain buffer first" vs. "randomly accept new events".

I think ordering constraints in sinks will end up being incompatible with external buffers unless we:
1. make external buffers entirely isolated from other Vector instances with the same configuration
2. and make sure that the overflow buffer is always drained first before switching back to the base buffer

We can do number 2 trivially, in terms of code changes, although it will 100% result in extra backpressure because we'll forcibly need to stop checking the base buffer until we know we've processed all the messages we diverted to the overflow buffer.  We might actually introduce _more_ latency that way, because we need to wait for them to become available to the reader side, and services like S3 are eventually consistent.

Number 1 is _potentially_ easy to do depending on the buffer: it might be as simple as adding another component to the S3 object key to make the buffer files unique for a given Vector process, or as complex as requiring separate Kafka topics for each Vector process.

While we could do these things, they do strike me as large limitations for the benefit of Loki users running on an older version, one sink against all the others.

**Comment by lukesteensen** [comment]
> what if we simply agreed to augment the documentation -- both for the general buffering docs and for any sinks with ordering requirements -- to explain that only certain buffers provide ordering guarantees?

This makes sense to me. I don't think there are many sinks that strictly require some kind of ordering, but there are definitely situations (e.g. kafka -> kafka) where users would likely be surprised if Vector were reordering events that otherwise had ordering guarantees within the source and sink. As long as we take steps to avoid that confusion and provide guarantees around the documented type of ordering then I think we're good. Similar to end-to-end acking, we mostly want to avoid Vector being a weak link in an otherwise ordered system.

**Pull request merged**
