### PR TITLE
chore: Switch from futures channel to tokio in fanout transform

### PR DESCRIPTION
**Pull request by blt**
After running a [offwaketime](https://github.com/iovisor/bcc/blob/master/tools/offwaketime.py) profile over vector running `http_pipeline_blackhole` I found that we were
off-cpu non-trivially because of blocks sending into the futures channel. I'm
unsure if this is improved as I write this commit but I'm going to send it up to
CI for soaking. I do know that, theoretically, the tokio channel plays better
with the tokio runtime compared to futures.

REF #11006

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Comment by blt** [comment]
Since writing the initial commit I've created two offwaketime profiles:

vector-hpb-offwaketime
vector-hpb-offwaketime-tokio

The profile does look better: the main offwake in the fanout is now BTree clone. Top-of-line throughput is not changed, of course. I'll re-run the soak when #10923 goes in so we have data about variance.

**Review by tobz — APPROVED** [review]
LGTM.

I mostly skimmed over the soak test infra-related changes because I trust you at this point and I'm fairly detached from the minutiae, but the channel changes themselves make sense to me. 👍🏻

**Comment by blt** [comment]
> LGTM.
> 
> I mostly skimmed over the soak test infra-related changes because I trust you at this point and I'm fairly detached from the minutiae, but the channel changes themselves make sense to me. 👍🏻

Once #10923 is merged up the soak infra changes will disappear from here. I really wanted to capture variance data.

**Comment by lukesteensen** [comment]
Catching up here, but wanted to note that what was changed here was just the control channel, not the actual data plane that events flow through. That channel is only used on config reloads, so it makes sense that there would be essentially no change in performance here. Still, 👍  to standardizing on tokio channels.

**Pull request merged**
