### PR TITLE
docs(vrl): Add documentation for parse_proto and encode_proto

### PR DESCRIPTION
**Pull request by flavioc**
Initial VRL implementation done in https://github.com/vectordotdev/vrl/pull/739

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks @flavioc !

**Comment by rtrieu** [comment]
Created DOCS-7484 for docs editorial review.

**Comment by jszwedko** [comment]
@flavioc Apologies, I'm just realizing that `parse_proto` should probably be called `decode_proto` to be consistent with our other decode/parse functions per https://github.com/vectordotdev/vrl/blob/main/DESIGN.md. What would you think of renaming it?

**Comment by jszwedko** [comment]
Actually, never mind, I was confusing myself. `parse_proto` is consistent with the design doc since it takes a "string" and turns it into another data structure.

**Pull request merged**
