### PR TITLE
fix(codecs)!: Wrap values containing quotes in quotes

### LINKED ISSUE #12674: encode_logfmt should encapsulate values containing quotes in quotes
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The current behavior of `encode_logfmt` does not fully adhere to the [spec](https://pkg.go.dev/github.com/kr/logfmt#section-documentation).

According to the linked specification, values containing quotes must be enclosed in quotes and have quotes escaped. While this is not an official spec for `logfmt`, Vector links to it as such.

In our particular case, `logfmt`-encoded messages occasionally fail parsing in Loki which uses an [alternative go library](https://github.com/go-logfmt/logfmt) that adheres to the same spec.

This all seems to be due to [this line](https://github.com/vectordotdev/vector/blob/master/lib/vector-common/src/encode_key_value.rs#L102). However, fixing it may result in unintended changes for non-logfmt encodings.

### Configuration

_No response_

### Version

0.21.2

### Debug Output

_No response_

### Example Data

Problematic encoding:
```
message={\"time\":\"2022-05-09T23:11:10.972183439Z\",\"id\":\"\",\"remote_ip\":\"10.128.32.132\",\"host\":\"10.128.39.182:8080\",\"method\":\"GET\",\"uri\":\"/live\",\"user_agent\":\"kube-probe/1.21+\",\"status\":200,\"error\":\"\",\"latency\":20514,\"latency_human\":\"20.514µs\",\"bytes_in\":0,\"bytes_out\":17} source_type=kubernetes_logs
```

Correct encoding:
```
message="{\"level\":\"info\",\"msg\":\"HTTPRequest uri: /foo/1234/book?bar=V2, method: GET, queryString: bar=V2, remote: 10.128.22.246:39360, requestBody: , status: 200, deskId: 123,  ticker: ABC\",\"time\":\"May  9 23:07:18.756\"}" source_type=kubernetes_logs
```

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jalaziz**
Values containing quotes should be wrapped in quotes with the quotes
escaped. This allows `encode_key_value` to adhere to the logfmt spec.

Fixes #12674

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks for reporting and fixing this @jalaziz !

Can you help me understand why this is a breaking change? I mean, technically it is, but in the same way all bug fixes are "breaking changes" to those depending on the bug behavior. Unless I'm missing something?

**Comment by jszwedko** [comment]
Ah, gotcha, I missed that this was happening in `encode_key_value`. I think it's still a reasonable change, but agree that it should be noted as a breaking change for users not expecting it (perhaps doing custom parsing).

To that end, do you mind adding a note to [the upgrade guide for the next release](https://github.com/vectordotdev/vector/blob/master/website/content/en/highlights/2022-05-03-0-22-0-upgrade-guide.md) about this change? We try to call out all breaking changes in each of the upgrade guides.

**Comment by jalaziz** [comment]
@jszwedko done!

**Review by jszwedko — APPROVED** [review]
Awesome, thanks @jalaziz !

**Review by JeanMertz — APPROVED** [review]
Sweet, thanks!

**Pull request merged**
