### PR TITLE
fix(statsd sink): Handle Absolute kind for values other than Gauge.

### LINKED ISSUE #3488: Sending `internal_metrics` to `statsd` sink results in only namespace being sent
From gitter: https://gitter.im/timberio-vector/community?at=5f3b9c2478f4a801800fe861

### Vector Version

```
vector 0.11.0 (g0d0ce76 x86_64-unknown-linux-gnu 2020-08-18)
```

### Vector Configuration File

```toml
[sources.generator]
  type = "generator"
  lines = ["Line 1", "Line 2"]
  batch_interval = 1

[transforms.transform]
  type = "add_fields"
  inputs = ["generator"]
  overwrite = true
  fields.string_field = "string value"

[sources.internal_metrics]
  type = "internal_metrics"

[sinks.statsd]
  type = "statsd"
  inputs = ["internal_metrics"]
  namespace = "test"
  address = "127.0.0.1:8125"

[sinks.stdout]
  type = "console"
  inputs = ["internal_metrics", "transform"]
  target = "stdout"
  encoding = "json"
```

### Debug Output

https://gist.github.com/jszwedko/5bda09378d913d1d4eb22c9c3afc6f3e

### Expected Behavior

Metrics are sent to statsd sink.

### Actual Behavior

Only the namespace is sent to the statds sink.

### Example Data

Output of `nc -l -u -p 8125`:

```
test.test.
```

### PR DESCRIPTION
**Pull request by StephenWakely**
For the statsd sink if the Metric Kind was Absolute, it would only output values if the MetricValue was guage. The rest were ignored, code further along then prepended the namespace. This resulted in only the namespace being sent.

One possible fix could have been to make the internal metrics send Counters as an Incremental value. Theoretically perhaps this was the more correct fix? However, the Prometheus source, and possibly others would also need changing as this was also sending Absolute Counters.

The alternative is as I have done here, The statsd sink now only considers the Metric Kind if the Value is a Guage. For all other values it outputs the same regardless of the kind.

There are still same Values that the StatsD sink does not handle (AggregatedHistogram and AggregatedSummary), to avoid future confusion, I have added a warning if these types are sent to the StatsD sink.

This fixes #3488

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @FungusHumungus. I feel like there is a higher-level question here around our metrics data model and how we translate it across various protocols. It feels like there are some parallels with the discusssion [here](https://github.com/timberio/vector/pull/2913#discussion_r451173463). I could be wrong, but I've added @jamtur01 for context on this as well.

**Comment by FungusHumungus** [comment]
Yes, I think [this question](https://github.com/timberio/vector/pull/3501#issuecomment-676548570) could also be relevant. How best to handle metrics when the sink can't really cater for that type?

**Review by bruceg — APPROVED** [review]
Looks reasonable to me.

**Review by bruceg — CHANGES_REQUESTED** [review]
This is a good start on the refactor, but a little rough.

**Review by bruceg — APPROVED** [review]
Thanks for your work here!

**Review by jamtur01 — APPROVED** [review]
I think this approach makes sense. We can always examine the use of `MetricKind` in the event there's an edge case in another metrics tool, albeit I can't of any right now.

**Pull request merged**
