### PR TITLE
fix(ci): Unlink python before `brew install`

### PR DESCRIPTION
**Pull request by jszwedko**
Otherwise it fails to update Python with:

```
==> Upgrading python@3.11
  3.11.4_1 -> 3.11.5

==> Pouring python@3.11--3.11.5.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11
```

Example: https://github.com/vectordotdev/vector/actions/runs/5995416388/job/16258473755

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

### CODE REVIEW

**Review by pront — APPROVED** [review]
LGTM!

(Would be nice to link an issue as a reminder to remove this when the underlying issue is fixed.)

**Comment by jszwedko** [comment]
> LGTM!
> 
> (Would be nice to link an issue or just a TODO as a reminder to remove this when the underlying issue is fixed.)

My reading of the issue is that it isn't necessarily a bug, just a weird interaction with homebrew and the GitHub runners so it might need to be there permanently.

**Comment by jszwedko** [comment]
Kicked off another nightly build to verify since the first one failed due to a break on `master`: https://github.com/vectordotdev/vector/actions/runs/6005499047

**Comment by jszwedko** [comment]
Another try: https://github.com/vectordotdev/vector/actions/runs/6005715147. Forgot to actually merge master into this branch.

**Pull request merged**
