### PR TITLE
chore(ci): Remove unused script

### PR DESCRIPTION
**Pull request by jszwedko**
References to it removed by 79ed386aa

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by jszwedko** [comment]
Actually, I think the lack of calling this script is introducing a bug. Released versions of Vector no longer include the GIT SHA as they used to. I'll open a separate issue. Moving this to draft for now.

**Comment by jszwedko** [comment]
Verified that `scripts/ci-generate-publish-metadata.sh` is used now.

**Review by neuronull — APPROVED** [review]

**Review by neuronull — CHANGES_REQUESTED** [review]
Actually, I'm wondering if we should keep this temporarily but have a note in the script that it isn't used in automation but can be used manually when creating builds ?

**Comment by jszwedko** [comment]
> Actually, I'm wondering if we should keep this temporarily but have a note in the script that it isn't used in automation but can be used manually when creating builds ?

I'd prefer not to have a separate script that needs to be kept up-to-date with CI. Instead, I think it'd be preferable to come up with some tooling that can be used locally that is _also_ used by CI. The script is also misleading because it looks like it is run by CI but it isn't.

**Review by neuronull — APPROVED** [review]

**Pull request merged**
