### PR TITLE
fix(codecs): Handle `framing.character_delimiter.delimiter` as `char` in config serialization

### LINKED ISSUE #10814: framing.character_delimited.delimiter no longer works
#### Working:
```
vector 0.18.1 (x86_64-unknown-linux-gnu c4adb60 2021-11-30)
```

#### Not working:
```
vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)
```

### Vector Configuration File

```toml
[sources.source]
type = "stdin"
framing.method = "character_delimited"
framing.character_delimited.delimiter = "\u0000"

[sinks.sink]
type = "console"
inputs = ["source"]
encoding.codec = "json"
```

#### Working version (vector 0.18.1)

When using version `vector 0.18.1 (x86_64-unknown-linux-gnu c4adb60 2021-11-30)` vector ouputs what I expect:

```
$ printf "hey\0" | vector -c vector.stdin.toml
2022-01-12T07:18:02.500104Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
2022-01-12T07:18:02.500496Z  INFO vector::app: Loading configs. paths=["vector.stdin.toml"]
2022-01-12T07:18:02.521159Z  INFO vector::topology::running: Running healthchecks.
2022-01-12T07:18:02.521491Z  INFO vector::sources::stdin: Capturing STDIN.
2022-01-12T07:18:02.521543Z  INFO vector::topology::running: Starting source. key=source
2022-01-12T07:18:02.521591Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-01-12T07:18:02.522119Z  INFO vector::topology::running: Starting sink. key=sink
2022-01-12T07:18:02.522353Z  INFO vector: Vector has started. debug="false" version="0.18.1" arch="x86_64" build_id="c4adb60 2021-11-30"
2022-01-12T07:18:02.522456Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
2022-01-12T07:18:02.522604Z  INFO vector::shutdown: All sources have finished.
2022-01-12T07:18:02.522598Z  INFO source{component_kind="source" component_id=source component_type=stdin component_name=source}: vector::sources::stdin: Finished sending.
2022-01-12T07:18:02.522637Z  INFO vector: Vector has stopped.
{"host":"pike","message":"hey","source_type":"stdin","timestamp":"2022-01-12T07:18:02.522411555Z"}
```

#### Non-working version (vector 0.19.0)
When using version `vector 0.19.0 (x86_64-unknown-linux-gnu da60b55 2021-12-28)` I get an configuration error:

```
2022-01-12T07:21:25.761201Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-01-12T07:21:25.761416Z  INFO vector::app: Loading configs. paths=["vector.stdin.toml"]
2022-01-12T07:21:25.762699Z ERROR vector::cli: Configuration error. error=invalid type: string "\u{0}", expected u8 for key `sources.source` at line 7 column 1
```
### Additional Context

I've tried every thing I can thing of when setting `framing.character_delimited.delimiter` but it always results in the same error. Including (this is not a comprehensive list):

* `framing.character_delimited.delimiter = "\0"`
* `framing.character_delimited.delimiter = "\\0"`
* `framing.character_delimited.delimiter = '\0'`

* `framing.character_delimited.delimiter = "\u0"`

I was basically cargo culting at this stage!

### PR DESCRIPTION
**Pull request by pablosichert**
Closes #10814.

### CODE REVIEW

**Comment by blt** [comment]
Ah, hmm. It seems like the user in #10814 is expecting to be able to use a char as a delimiter, which does seem reasonable. I do buy splitting strings by non-ASCII characters. We also didn't go through a upgrade cycle to allow users to convert from a char to a byte so even if, in the future, we want to limit vector to splitting by bytes at least in this release cycle we have to support chars, no?

**Comment by pablosichert** [comment]
> We also didn't go through a upgrade cycle to allow users to convert from a char to a byte so even if, in the future, we want to limit vector to splitting by bytes at least in this release cycle we have to support chars, no

Hm, interesting question. So previously the config didn't reject `char`s that were not ASCII and instead silently truncated to one byte. One could argue that the only valid behavior (though defined by the implementation and not by a spec) at that time were ASCII characters.

The other take of course it that `char`s should work as expected without truncation.

The third option would be to allow strings as delimiters altogether, which would be compatible with both options above. And would allow for cases like `\r\n`.

**Comment by pablosichert** [comment]
Looks like we documented the behavior for variant 1: https://github.com/vectordotdev/vector/pull/10573

**Review by blt — APPROVED** [review]
Considering that we did make the documentation change to allow only byte delimiters this PR makes sense to me. It may be that we've overly constrained vector behavior if people need to split by multi-byte chars or even full strings in practice, but that seems like a separate PR, discussion.

**Review by jszwedko — APPROVED** [review]
Thanks for the quick fix here!

**Comment by jszwedko** [comment]
I forgot to call this out in my review, but we should have added this to the `known_issues` for 0.19.0. I'll open a separate PR.

**Pull request merged**
