### PR TITLE
chore: Add community note to issue templates

### PR DESCRIPTION
**Pull request by jszwedko**
Adopted this [from Terraform](https://github.com/hashicorp/terraform-provider-aws/blob/448475ec7f54b267e33d249d24acfa25904fd643/.github/ISSUE_TEMPLATE/Bug_Report.md).

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by StephenWakely — APPROVED** [review]

**Review by tobz — APPROVED** [review]

**Review by binarylogic — APPROVED** [review]
I defer to you @jszwedko if you think this is helpful. It strikes me as noise since I haven't seen problems with these things. I do agree we could communicate and use reactions better for roadmap prioritization.

**Comment by jszwedko** [comment]
> I defer to you @jszwedko if you think this is helpful. It strikes me as noise since I haven't seen problems with these things. I do agree we could communicate and use reactions better for roadmap prioritization.

My primary motivation is to encourage people to start 👍 ing issues so we can have some proxy for community demand. Historically I don't think people have been doing that. I'll often link people to an issue that is relevant to them and they don't add a 👍 .

**Comment by binarylogic** [comment]
Sure, even so, I think a Github Action might be a better approach? We can build a hook to add and maintain this. You could use it to retroactively add this to issues and update the language in the future. But this is fine for now!

**Comment by jszwedko** [comment]
> Sure, even so, I think a Github Action might be a better approach? We can build a hook to add and maintain this. You could use it to retroactively add this to issues and update the language in the future. But this is fine for now!

🤔 could you elaborate? What would the Github Action do?

**Comment by binarylogic** [comment]
The action could serve as a hook when an issue is created, adding the footer automatically. It could also be fired for existing issues to update/replace the foot as well.

**Comment by jszwedko** [comment]
Ahh, gotcha, yeah I see. That could work. Just a note that I like it better as a header so that people are less likely to miss it.

**Pull request merged**
