### PR TITLE
bug(lua transform): Emit events with the `source_id` set

### PR DESCRIPTION
**Pull request by bruceg**
By default, the `lua` transform creates output events with no source id. This is, however, the only component that does that. This change causes all output events to have a source ID:

1. All events resulting from processing an event (either the default v1 path or the v2 `process` hook) will copy the source ID from the incoming event.
2. All other events will set the source ID to the fixed string `lua`.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Review by jszwedko — CHANGES_REQUESTED** [review]
The source id should be the component id, no? Rather than a fixed string.

**Comment by jszwedko** [comment]
With this change, are there any other situations where events would be created without a `source_id`? I'm wondering if we should change it from an `Option`.

**Comment by bruceg** [comment]
> The source id should be the component id, no? Rather than a fixed string.

Ah, of course. I'm adding tests and will make sure they catch that and then fix it.

> With this change, are there any other situations where events would be created without a `source_id`? I'm wondering if we should change it from an `Option`.

Well, an event will have no `source_id` when it is initially created, and sources only set that when it exits the source (in common code), so I'm not sure how to avoid it being an `Option`. I'd love to make it non-optional, though.

**Comment by jszwedko** [comment]
> > With this change, are there any other situations where events would be created without a `source_id`? I'm wondering if we should change it from an `Option`.
> 
> Well, an event will have no `source_id` when it is initially created, and sources only set that when it exits the source (in common code), so I'm not sure how to avoid it being an `Option`. I'd love to make it non-optional, though.

Ah, yes, that makes sense. I guess the source would need to set it during construction.

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
