### PR TITLE
fix(codecs): expose VRL deserializer options

### PR DESCRIPTION
**Pull request by pront**

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Assuming the component features check passes (and doesn't flag dead code) 👍

**Comment by jszwedko** [comment]
I just want to make sure https://github.com/vectordotdev/vector/actions/runs/7877485735/job/21493748479 passes first since it isn't part of the merge queue.

**Comment by pront** [comment]
> I just want to make sure https://github.com/vectordotdev/vector/actions/runs/7877485735/job/21493748479 passes first since it isn't part of the merge queue.

Sounds good, I will keep an eye out as well.

**Comment by jszwedko** [comment]
Passed :) I readded to the merge queue.

**Review by bruceg — APPROVED** [review]

**Pull request merged**
