### PR TITLE
chore: Add markdown linting

### PR DESCRIPTION
**Pull request by binarylogic**
Adding markdown linting for consistency. It's possible I'll close this if there are too many problems.

### CODE REVIEW

**Comment by binarylogic** [comment]
I'll come back to this. It's likely we'll relax the rules to start.

**Comment by binarylogic** [comment]
This should be good to go. It caught quite a few issues, so it's obvious we need this. I also had to relax a few settings because of the way we generate docs.

**Comment by a-rodin** [comment]
I think it would be useful to be able to run this check locally. I've added corresponding target to the Makefiles.

I also updated the GitHub action to use a newer version of `markdownlint` (0.22 instead of 0.18).

**Review by ghost — APPROVED** [review]

**Comment by binarylogic** [comment]
Thanks!

**Comment by binarylogic** [comment]
@Hoverbear did you want to review this? You self-assigned yourself, so just making sure.

**Review by Hoverbear — APPROVED** [review]

**Comment by Hoverbear** [comment]
Looks good!

**Pull request merged**
