### PR TITLE
chore: re-enable GSSAPI for Kafka for all targets

### PR DESCRIPTION
**Pull request by jszwedko**
Pushing up to see what the build failures are if any, prompted by
https://github.com/vectordotdev/vector/pull/3081#issuecomment-1068151714

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
Mmm, yes, I remember this now, it fails to link correctly.

**Comment by spencergilbert** [comment]
> Mmm, yes, I remember this now, it fails to link correctly.

Add as a comment somewhere for the next time we forget? 😆

**Comment by smlgbl** [comment]
@jszwedko Does this mean there will be no SASL/SCRAM for musl builds, like alpine?

**Comment by jszwedko** [comment]
> @jszwedko Does this mean there will be no SASL/SCRAM for musl builds, like alpine?

That's correctly, only glibc builds have it (like `debian` and `distroless-libc`).

**Pull request closed without merging**
