### PR TITLE
feat(remap): add "match" remap function

### PR DESCRIPTION
**Pull request by JeanMertz**
This adds a `match` function to be used in remap-lang:

```rust
.foo = "foo"
.matches = match(.foo, /\wo{2}/)
```

```json
{
	"foo": "foo",
	"matches": true,
}
```

It's primary use-case is for usage in conditions (#4743), such as the reduce `starts_when` condition:

```toml
[transforms.ruby_exception]
    inputs = []
    type = "reduce"
    merge_strategies.message = "concat_newline"
    starts_when.type = "remap"
    starts_when.source = "match(.message, /^\\w.*/)"
```

### CODE REVIEW

**Review by StephenWakely — APPROVED** [review]
Looks straightforward enough.

**Comment by binarylogic** [comment]
I know I used this in my examples, but I wasn't aware of `contains`. How does this differ from `contains`?

**Review by jszwedko — APPROVED** [review]
Looks good! I might add some behavior tests just as a sanity check.

@binarylogic `contains` doesn't allow regexes (which I think makes sense).

**Comment by FungusHumungus** [comment]
> I know I used this in my examples, but I wasn't aware of `contains`. How does this differ from `contains`?

Good point. `contains` currently only works with strings, but I can't think of a reason why it couldn't be adapted to take regexes too which would then fill this functions purpose.

**Comment by FungusHumungus** [comment]
Although, thinking ahead to #3736 I think we may want a `matches` function which would complement this one. Rather than returning a true or false it would somehow return the actual parts of the text that the regex matched.

**Comment by jszwedko** [comment]
> Rather than returning a true or false it would somehow return the actual parts of the text that the regex matched.

I was actually thinking about that too. Go differentiates between both behaviors with `match` returning a boolean and `find` returning captures (https://golang.org/pkg/regexp/). `matches` could work too.

**Comment by JeanMertz** [comment]
> I know I used this in my examples, but I wasn't aware of `contains`. How does this differ from `contains`?

As mentioned, `contains` only takes strings. I could have updated it to support a regex, but I feel that the naming `contains` makes more sense when comparing two strings, whereas `match` fits well with what everyone expects to use when using regexes.

I also like the proposal of a `find` (or similarly named) function that allows you to return capture group values.

I'll play around with that in this PR, should be easy to add given the existing support we already have for Remap functions.

If anyone feels differently, I can merge `match` and `contains`.

**Pull request merged**
