### PR TITLE
Update to lading 0.20.1

### PR DESCRIPTION
**Pull request by blt**
This commit resolves a shutdown issue with lading and also resolve a runtime
hang introduced by recent changes to the lading capture manager.

Signed-off-by: Brian L. Troutwine <brian.troutwine@datadoghq.com>

REF SMPTNG-94

### CODE REVIEW

**Comment by jszwedko** [comment]
> /ci-run-regression

Just a heads up that we discovered recently that this uses the workflow definition from `master` rather than the PR so, in your case, it actually ran 0.19.1 still. We don't have a great way to test these upgrades before merging 😓

**Review by jszwedko — APPROVED** [review]

**Comment by jszwedko** [comment]
@blt Looks like the regression test suite failed on this one 👀

**Comment by pront** [comment]
Looking at the latest version of [regression.yml](https://github.com/vectordotdev/vector/blob/master/.github/workflows/regression.yml), the lading version is no longer exposed. If that's not the case, please let me know.

**Comment by jszwedko** [comment]
> Looking at the latest version of [regression.yml](https://github.com/vectordotdev/vector/blob/master/.github/workflows/regression.yml), the lading version is no longer exposed. If that's not the case, please let me know.

I think it is here now: https://github.com/vectordotdev/vector/blob/88d6fe7faca520bd28eba308bf08846eb1823975/regression/config.yaml#L1-L2

**Pull request closed without merging**
