### PR TITLE
enhancement(graphql api): Add `json` to `Log` type

### LINKED ISSUE #6393: Add dynamic field look-up to `LogEvent` GraphQL type
Similar to #6392, but instead of returning an array of fields, the purpose of a dynamic `field` look-up is for the user to pass an arbitrarily nested field name (nesting indicated by `.`) and get back that specific field value.

For large logs where the client requires only limited parts of it, this provides a lower bandwidth alternative vs. retrieving the full log.

Once implemented, I think GraphQL aliases can be used to retrieve multiple fields of the same underlying key, but this is something I haven't tested in async-graphql so will need to confirm.

### PR DESCRIPTION
**Pull request by leebenson**
Adds a `Log.field(name: String!): FieldValue` to the GraphQL schema, for querying arbitrarily nested log data.

Data is returned as a `FieldValue` scalar, which is an opaque type that could serialise to any JSON-encoded value -- either a scalar or object value.

Closes #6393.

## Example

Given the following config:

```toml
[api]
  enabled = true

[sources.gen1]
  type = "generator"
  lines = ["hello!"]
  format = "shuffle"
  batch_interval = 0.5

[transforms.remap]
  type = "remap"
  inputs = ["gen1"]
  source = '''
    .nested.count = 99
    encode_json(.)
  '''

[sinks.blackhole]
  type = "blackhole"
  inputs = ["gen1"]
  print_amount = 1000
```

This subscription query:

```gql
subscription {
  outputEvents(componentNames:["remap"], limit:50, interval: 10) {
    __typename
    ... on Log {
      message
      string(encoding:JSON)
      field(name:"nested.count")
    }
  	... on EventNotification {
      componentName
      notification
    }
  }
}
```

Returns:

```json
{
  "data": {
    "outputEvents": [
      {
        "__typename": "Log",
        "field": 99,
        "message": "hello!",
        "string": "{\"message\":\"hello!\",\"nested\":{\"count\":99},\"timestamp\":\"2021-03-29T13:26:38.592787Z\"}"
      }
    ]
  }
}
```

Swapping to `field(name:"nested")` returns:

```json
{
  "data": {
    "outputEvents": [
      {
        "__typename": "Log",
        "field": {
          "count": 99
        },
        "message": "hello!",
        "string": "{\"message\":\"hello!\",\"nested\":{\"count\":99},\"timestamp\":\"2021-03-29T13:27:49.593520Z\"}"
      }
    ]
  }
}
```

## Use case

Log data is dynamic, and the client may wish to inspect keys that may or may not exist, and return dynamic values.

Using a scalar defers the processing of the value type to the client.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
👍 I'm not opposed to this, but I'm having a hard time coming up with a client use-case right now. I'd be fine punting until we have a specific need.

Regarding the implementation I think we should define `FieldValue` as an actual `union` of the (boxed) scalars it can represent. I.e. `union FieldValue = BoxInt | BoxFloat ...` (the boxing needed to work around GraphQL's lack of support for scalars in unions).

**Comment by leebenson** [comment]
@jszwedko - the intended use-case is working alongside filtering in #6390, to quickly filter - and return - nested parts of a log.

I had originally thought about doing this exactly as you suggested, as a union of types. When testing async-graphql's `scalar!` macro, and our existing serialisation support, it felt that being able to select _any_ key - including an object - and get back a usable JSON payload, would be useful for a client that wants to look at an arbitrary part of the log.

A union would only allow for a specific value, which is fine too, and would have the benefit of being typed.  But it wouldn't allow for typed keys, or be ideal for situations where the client wants the whole set of objects against a matched parent key.

There's advantages to both, and this hasn't been fully specced out, so I chose the simpler path.

**Comment by jszwedko** [comment]
> I had originally thought about doing this exactly as you suggested, as a union of types. When testing async-graphql's `scalar!` macro, and our existing serialisation support, it felt that being able to select _any_ key - including an object - and get back a usable JSON payload, would be useful for a client that wants to look at an arbitrary part of the log.

Gotcha, yeah I see. What would you think of just calling the scalar `JSON` then? That would more readily convey its representation.

👍 to filtering, I'm just not sure I see the need for selecting parts of the event yet.

**Comment by leebenson** [comment]
@jszwedko, how do you feel about renaming to `json`?

e.g.

```gql
subscription {
  outputEvents(componentNames:["*"], limit:50, interval: 10) {
    __typename
    ... on Log {
      message
      nested: json(field:"nested")
    }
  }
}
```

Returning, e.g:

```json
{
  "data": {
    "outputEvents": [
      {
        "__typename": "Log",
        "message": "hello!",
        "msg": null
      },
      {
        "__typename": "Log",
        "message": "hello!",
        "msg": {
          "count": 99
        }
      }
    ]
  }
}
```

This is now:

```gql
# Raw JSON data`
scalar Json

 Log event with fields for querying log data
type Log {
  # Name of the component associated with the log event
  componentName: String!

  # Log message
  message: String

  # Log timestamp
  timestamp: DateTime

  # Log event as an encoded string format
  string(encoding: EventEncodingType!): String!

  # Get JSON field data on the log event, by field name
  json(field: String!): Json
}
```

Ultimately, the motivation is a use-case like:

```bash
vector tap --filter "nested.count > 5" --field "nested.data" <component>
```

... allowing users to return only matching logs (possibly using VRL), and grab the piece of the log they care about out of potentially too-large-to-parse payloads.

**Comment by jszwedko** [comment]
@leebenson 👍 that naming makes sense to me!

> Ultimately, the motivation is a use-case like:
> 
> ```shell
> vector tap --filter "nested.count > 5" --field "nested.data" <component>
> ```
> 
> ... allowing users to return only matching logs (possibly using VRL), and grab the piece of the log they care about out of potentially too-large-to-parse payloads.

Ah, I see 👍

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
