### PR TITLE
feat(internal_metrics source): Let scrape_interval_secs have fractional seconds

### PR DESCRIPTION
**Pull request by jszwedko**
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by binarylogic** [comment]
What's the use case for this?

**Comment by jszwedko** [comment]
> What's the use case for this?

I suggested to a user that they could identify subsecond spikes in throughput as part of diagnosing some behavior they were seeing with the `throttle` transform by setting the `internal_metrics` scrape interval to something like 100ms, but this isn't currently possible given that it is a uint.

**Review by spencergilbert — COMMENTED** [review]
Broke types elsewhere 👀 and this wouldn't make the users have to configure with a float?

**Comment by jszwedko** [comment]
> Broke types elsewhere 👀 and this wouldn't make the users have to configure with a float?

👍 I neglected this component is used by others, I rolled out the change to `host_metrics.scrape_interval_secs` and `datadog.reporting_interval_secs` in [84857ba](https://github.com/vectordotdev/vector/pull/11673/commits/84857ba7b28ebef71317b0b27c1dbc69750082cd).

I verified TOML and YAML both deserialize fine when an integer is used for a float so users can continue to easily configure whole seconds.

Eventually I'd love to see more sophisticated unit handling here so users could write things like `2s500ms`.

**Review by spencergilbert — APPROVED** [review]

**Comment by tobz** [comment]
> Eventually I'd love to see more sophisticated unit handling here so users could write things like `2s500ms`.

This is something I was thinking about during the configuration schema RFC and will likely try to provide a type/serde (de)ser helper function for as part of that work.

**Pull request merged**
