### PR TITLE
enhancement(external docs): Update S3 source example

### PR DESCRIPTION
**Pull request by maxknee**
This PR updates the example to make the regex a one-liner so users can copy-paste and doesn't cause their configs to error.

### CODE REVIEW

**Comment by lucperkins** [comment]
@maxknee You are quite right that this config won't work if copy-pasted! The issue, as you've rightly pointed out, is that this doesn't work as a multi-line string. I think the solution that we would prefer, however, is to keep this as a multi-line string for the sake of readability but fix the TOML syntax. This should do the trick:

```toml
regex = '''
  (?x)^
  (?P<type>[\\w]+)[ ]
  (?P<timestamp>[\\w:.-]+)[ ]
  (?P<elb>[^\\s]+)[ ]
  (?P<client_host>[\\d.:-]+)[ ]
  (?P<target_host>[\\d.:-]+)[ ]
  (?P<request_processing_time>[\\d.-]+)[ ]
  (?P<target_processing_time>[\\d.-]+)[ ]
  (?P<response_processing_time>[\\d.-]+)[ ]
  (?P<elb_status_code>[\\d-]+)[ ]
  (?P<target_status_code>[\\d-]+)[ ]
  (?P<received_bytes>[\\d-]+)[ ]
  (?P<sent_bytes>[\\d-]+)[ ]
  "(?P<request_method>[\\w-]+)[ ]
  (?P<request_url>[^\\s]+)[ ]
  (?P<request_protocol>[^"\\s]+)"[ ]
  "(?P<user_agent>[^"]+)"[ ]
  (?P<ssl_cipher>[^\\s]+)[ ]
  (?P<ssl_protocol>[^\\s]+)[ ]
  (?P<target_group_arn>[\\w.:/-]+)[ ]
  "(?P<trace_id>[^\\s"]+)"[ ]
  "(?P<domain_name>[^\\s"]+)"[ ]
  "(?P<chosen_cert_arn>[\\w:./-]+)"[ ]
  (?P<matched_rule_priority>[\\d-]+)[ ]
  (?P<request_creation_time>[\\w.:-]+)[ ]
  "(?P<actions_executed>[\\w,-]+)"[ ]
  "(?P<redirect_url>[^"]+)"[ ]
  "(?P<error_reason>[^"]+)"
'''
```

**Comment by maxknee** [comment]
Yep! one sec!

**Comment by maxknee** [comment]
it works!

**Review by jszwedko — APPROVED** [review]
Thanks @maxknee !

**Pull request merged**
