### PR TITLE
chore(deps): bump async-nats to v0.35

### PR DESCRIPTION
**Pull request by paolobarbolini**
Closes #20008

### CODE REVIEW

**Comment by jszwedko** [comment]
Thanks @paolobarbolini . I suspect this will need some more changes though since clippy failed on the other upgrade to v0.34. I kicked off CI to see. Locally you can run `make check-clippy`.

**Review by jszwedko — APPROVED** [review]
Looks like CI may be passing here.

**Comment by paolobarbolini** [comment]
It looks like some tests failed because of the `nkeys` 0.4.1 upgrade. https://github.com/wasmCloud/nkeys/pull/31 fixed some broken nkey verification logic which was also wrong in tests. I guess this project may have the same issue too. I'll get back to this in a few days.

**Comment by paolobarbolini** [comment]
Closing in favor of #21504

**Pull request closed without merging**
