### PR TITLE
Change ClickHouse Docker repository.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
New versions are located in `clickhouse/clickhouse-server` only.

### CODE REVIEW

**Comment by davidhuie-dd** [comment]
Actually, it looks like the tag we're trying to build here doesn't exist (`clickhouse/clickhouse-server:19`): https://github.com/vectordotdev/vector/actions/runs/4129481082/jobs/7153010391

**Comment by alexey-milovidov** [comment]
If we change the tag to 23, should it work?

**Comment by davidhuie-dd** [comment]
It looks like that tag should work. After updating the version, you should be able to test locally with the command: `cargo vdev integration test clickhouse`

**Comment by dsmith3197** [comment]
Done in https://github.com/vectordotdev/vector/pull/17723

**Pull request closed without merging**
