### PR TITLE
chore(ci): Bump the k8s versions we test against

### PR DESCRIPTION
**Pull request by jszwedko**
To include newer versions. I dropped the versions no longer supported by
GCP, AWS, and Azure as a proxy for general cloud k8s support.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
I believe we still document that we support 1.15+ do we want to formally adjust that?

And we also would probably want to do the same matrix for helm testing

**Comment by jszwedko** [comment]
> I believe we still document that we support 1.15+ do we want to formally adjust that?
> 
> And we also would probably want to do the same matrix for helm testing

Good call, I updated in 5f62e1fb3 . I'll also note it in the release notes when those are generated.

And agreed, we should update the Helm matrix too. I'll open a PR for that.

**Comment by spencergilbert** [comment]
> And agreed, we should update the Helm matrix too. I'll open a PR for that.

Note it can be a bit tricky and sometimes "close enough" patch wise, but I believe I documented it in the workflow config. I wonder if we can/should just follow kubernetes support: `The Kubernetes project maintains release branches for the most recent three minor releases`

**Review by spencergilbert — APPROVED** [review]

**Comment by jszwedko** [comment]
I believe the soak tests are due to #10803 being merged into master which showed mirrored results, in the positive direction.

> > And agreed, we should update the Helm matrix too. I'll open a PR for that.
> 
> Note it can be a bit tricky and sometimes "close enough" patch wise, but I believe I documented it in the workflow config. I wonder if we can/should just follow kubernetes support: `The Kubernetes project maintains release branches for the most recent three minor releases`

Yeah, I am wondering about that too. Sometimes I do wish we had telemetry to know what k8s versions users were running Vector with in the wild. For now, I guess I'll stick with cloud provider versions.

**Pull request merged**
