### PR TITLE
docs(logdna sink): use auto-generated config docs

### LINKED ISSUE #16171: Convert the `logdna` sink to use auto-generated docs

### PR DESCRIPTION
**Pull request by neuronull**
closes: https://github.com/vectordotdev/vector/issues/16171

epic: https://github.com/vectordotdev/vector/issues/14999

### CODE REVIEW

**Review by StephenWakely — DISMISSED** [review]
Perhaps I am jumping the gun and this isn't totally ready for review yet, but `website/cue/reference/components/sinks/logdna.cue` also needs updating..

**Review by spencergilbert — COMMENTED** [review]
Hah, yes definitely skipped over updating the old docs to use the configurable ones 😆

**Comment by neuronull** [comment]
Ah fiddle sticks. It is like the most common thing I'm forgetting.

**Review by spencergilbert — CHANGES_REQUESTED** [review]
Much better! Though, I just noticed the `proxy` config has been dropped, I suspect you'll need to get into the cue and render that conditionally.

**Comment by neuronull** [comment]
> Much better! Though, I just noticed the `proxy` config has been dropped, I suspect you'll need to get into the cue and render that conditionally.

Interesting. There has to be a place where we are handling this kind of thing. Because the batch and encoding settings are pulled in from the features. I'll take a look.

**Comment by neuronull** [comment]
> > Much better! Though, I just noticed the `proxy` config has been dropped, I suspect you'll need to get into the cue and render that conditionally.
> 
> Interesting. There has to be a place where we are handling this kind of thing. Because the batch and encoding settings are pulled in from the features. I'll take a look.

Actually, @tobz set us straight. This is handled already. We don't need to change anything because it is part of the sink context struct and the existing logic already includes it, see the deploy preview

**Comment by spencergilbert** [comment]
image

It's not rendered though?

**Comment by neuronull** [comment]
Ahhhh haha I saw healthcheck and buffer and inputs! good observation.

**Comment by neuronull** [comment]
> image
> 
> It's not rendered though?

Addressed that here https://github.com/vectordotdev/vector/pull/16200

**Review by spencergilbert — APPROVED** [review]
Worth a double check after merging to make sure things are good - but between the two PRs, LGTM

**Comment by neuronull** [comment]
> Worth a double check after merging to make sure things are good - but between the two PRs, LGTM

I see the proxy there after merging in master with the proxy PR changes.

**Comment by spencergilbert** [comment]
shipit!

**Pull request merged**
