### PR TITLE
fix(ci): Disable but do not remove soak workflows, related infra

### PR DESCRIPTION
**Pull request by blt**
This commit disables the soak tests in favor of the Regression Detector managed by Single Machine Performance. While we do intend to eventually remove the soak related code entirely from the project -- as well as the custom container build, which is no longer necessary -- we want the option to re-enable it quickly if needed. The Regression Detector has been running in parallel to the soak tests for some time now -- the last bit landing in #15376 -- but caution is the better part of valor.

Signed-off-by: Brian L. Troutwine <brian.troutwine@datadoghq.com>

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
🎉 Looks like Github is angry about the empty workflow files though. Maybe we could move them to a `.github/workflows_disabled/` directory?

**Comment by blt** [comment]
> tada Looks like Github is angry about the empty workflow files though. Maybe we could move them to a `.github/workflows_disabled/` directory?

I always forget about that.

**Comment by JeanMertz** [comment]
Just for my clarification, is https://github.com/vectordotdev/vector/tree/master/soaks still the place to modify existing, or add new soak tests?

**Comment by jszwedko** [comment]
Discussed this offline, but the `regression` directory is the new place. I opened https://github.com/vectordotdev/vector/pull/15436 to avoid confusion.

**Pull request merged**
