### PR TITLE
chore(soaks): Fix syslog soaks

### PR DESCRIPTION
**Pull request by jszwedko**
They were attempting to double parse the input as syslog.

Closes: #12847

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Ah the source is doing the parsing now, yeah?

**Comment by jszwedko** [comment]
> Ah the source is doing the parsing now, yeah?

Yeah, it always was. I'm a bit surprised that the soaks got introduced with this behavior, but then again, they don't do any validation that data is getting processed correctly.

**Review by 001wwang — APPROVED** [review]
It's been quite a while since I put these together, so I'm no longer sure if this was accidental or if I ran into an issue in the past. Thanks for updating!

**Comment by jszwedko** [comment]
Verified log messages about failing to parse no longer appear in stderr from soak artifacts.

**Pull request merged**
