### PR TITLE
fix(remap): filter out file contents from error logs

### PR DESCRIPTION
**Pull request by pront**
Error example:
```
2023-12-12T11:01:03.808753Z ERROR vector::topology::builder: Configuration error. error=Transform "my_transform_id": File contents were redacted.
error[E203]: syntax error
   ┌─ :11:7
   │
11 │                                                           
   │       ^
   │       │
   │       unexpected syntax token: "Colon"
   │       expected one of: "\n", "!=", "&&", " ", "+", ",", "-", "/", ";", "<", "<=", "=", "==", ">", ">=", "??", "|", "|", "|=", "||"
   │
   = see language documentation at https://vrl.dev
   = try your code in the VRL REPL, learn more at https://vrl.dev/examples

```

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Nice! I'd suggest adding a test, but otherwise this seems like a reasonable step that plugs this security hole without too much complexity. I might like to come up with something more sophisticated in the future to improve the UX.

**Comment by pront** [comment]
> I might like to come up with something more sophisticated in the future to improve the UX.
Agreed, it's not an ideal UX right now but this is a good compromise. A potential (non-trivial) solution is to encrypt sensitive logs so that only someone with the key can read them.

**Comment by joshcoughlan** [comment]
How do you tell vector not to redact? Like if you're running `vector test` and are actually interested in useful information.

**Comment by pront** [comment]
This needs some extra thought, since this was a quick patch for a security risk. Thoughts and contributions are always welcome.

**Pull request merged**
