### PR TITLE
fix(buffers): Require buffer sizes to be non-zero

### PR DESCRIPTION
**Pull request by jszwedko**
Providing 0 for in-memory buffers causes a panic. I'm guessing providing
0 for disk buffers will also mean you are going to have a bad time so
guarded against that here too.

Closes: #11770

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by tobz** [comment]
> I'm guessing providing 0 for disk buffers will also mean you are going to have a bad time so guarded against that here too.

For disk v1, I think so, yes. For disk v2, we round up to a multiple of the max data file size, which for production builds is 128MB so it's always at least that big, luckily.

**Review by tobz — APPROVED** [review]
Overall, this makes sense to me. 👍🏻

**Comment by jszwedko** [comment]
> > I'm guessing providing 0 for disk buffers will also mean you are going to have a bad time so guarded against that here too.
> 
> For disk v1, I think so, yes. For disk v2, we round up to a multiple of the max data file size, which for production builds is 128MB so it's always at least that big, luckily.

Ah, gotcha, that is good to know. Do we document that? Should we restrict the buffer sizes to be multiple of 128 MB?

**Comment by tobz** [comment]
We don't document it yet, no.  I had planned on it as part of the eventual
cutover, since we have no good place to document it as is and planned on
working that in somewhere.

**Pull request merged**
