### PR TITLE
feat(vrl): Add diff viewer on playground

### PR DESCRIPTION
**Pull request by jonathanpv**
Closes https://github.com/vectordotdev/vector/issues/15267

Adding this also fixes the below issue:
Closes https://github.com/vectordotdev/vector/issues/15265

### CODE REVIEW

**Comment by spencergilbert** [comment]
Drive-by suggestion, possibly make this toggle-able?

**Comment by jonathanpv** [comment]
> Drive-by suggestion, possibly make this toggle-able? Besides that, a very handy addition 🚀

I agree might be better to have this toggled, for now ill mark this as a draft

**Review by JeanMertz — APPROVED** [review]
I like it a lot! 👍 

I agree, allowing one to switch between the two would be even better.

**Comment by jonathanpv** [comment]
this pr will require more work, since adding the diff viewer as a toggle is a desired feature. Closing this now and will track in a seperate PR.

**Pull request closed without merging**
