### PR TITLE
chore(vrl): Optimize VRL byte concatenation

### PR DESCRIPTION
**Pull request by pablosichert**
I noticed this diff to improve byte concatenation in some of the initial works of @StephenWakely's VM, should be generally useful for VRL as well.

### CODE REVIEW

**Review by fuchsnj — APPROVED** [review]
I always like a PR removing a `format!`

**Review by jszwedko — APPROVED** [review]
Nice find!

**Review by bruceg — APPROVED** [review]
Nice find. I wonder how many more `format!`s there are in hot paths.

**Review by StephenWakely — APPROVED** [review]
Beautiful!

**Pull request merged**
