### PR TITLE
fix(elasticsearch sink): Gunzip Elasticsearch responses when necessary

### LINKED ISSUE #8439: Compression between vector and ElasticSearch is not working for egress traffic
### Vector Version
```
0.15.0
```

### Vector Configuration File

```toml
    [sinks.es]
      type = "elasticsearch"
      inputs = ["es_timestamp"]
      healthcheck.enabled = true

      auth.strategy = "basic"
      auth.user = "---"
      auth.password = "---"
      endpoint = "---:9200"
      mode = "data_stream"
      data_stream.auto_routing = false
      data_stream.sync_fields = false
      data_stream.type = "---"
      data_stream.dataset = "logs"
      data_stream.namespace = "ds"

      compression = "gzip"

      batch.max_bytes = 50000000
      batch.timeout_secs = 1
      buffer.max_events = 10000000
      buffer.type = "memory"
      buffer.when_full = "block"

```

### Expected Behavior
When we configure compression = "gzip" for ElasticSearch sink it is expected that compression is applied in both directions - ingress and egress.
### Actual Behavior
Compression is applied only to ingress traffic.

### Workaround

Custom headers applied on the vector side fix the situation and the return traffic is also compressed.

```toml
    [sinks.es]
      compression = "gzip"
      # response compression
      request.headers.Accept-Encoding = "gzip"

```

### Additional Context

ES version - 7.13.1
Also tested with vector - 0.12.2

Compression is clearly enabled on all ES nodes.

It might be that vector is not configuring its headers correctly when compression is enabled. 
It seems that ES is expecting to receive specific headers that will instruct it for using compression on the reply traffic (egress)
https://discuss.elastic.co/t/http-compression-enabled-but-response-not-compressed/103513/7

Ingress Traffic Rates when we apply Compression
inbound_traffic_es
Egress Traffic Rates when we apply Compression
outbound_traffic_es
Egress Traffic Rates when we apply custom Headers and Compression
outbound_traffic_es_headers

### PR DESCRIPTION
**Pull request by davidhuie-dd**
Closes #8439

This PR enables support for gzip-encoded responses from ES. To do so, gzip decompression support has been added to Vector's HttpClient. Additionally, I also fixed a bug where gzipped responses from ES previously hid potential errors, as mentioned in #8439. This is because we performed a search for the string `"\"errors\":true"` [(here)](https://github.com/vectordotdev/vector/blob/67513b7db5689011b66430fa7545ecd9f0b886e1/src/sinks/elasticsearch/service.rs#L197) in ES responses to test for issues, so that string would be scrambled in a gzipped response. 

One controversial bit is that the default `Accept-Encoding` header has been changed to `gzip` from `identity` in `HttpClient`. I figured that this should be a free bandwidth win in most applications, although there's risk in making that change because HttpClient is in widespread use. Also, there's some concern around opting people into what's a higher CPU utilization default.

### CODE REVIEW

**Review by tobz — COMMENTED** [review]
Overall, I can appreciate the issue being solved by this PR, but what feels weird to me is that we're only supporting compressed response if compression is enabled on Vector's side, which also controls if we compress requests.

Like, we should theoretically be able to support compressed response _from_ ES regardless of whether or not Vector is compressing its requests to ES. I could make a weak argument that users may not want to incur the compression cost on the request side, while still wanting the compression on the response side, due to performance / billing implications or something.

That might not actually be a valid argument, but I'd want maybe just like.. a sentence or two explaining why we should only allow compressed responses if we're compressing requests, I think, to feel better about this PR.

**Comment by davidhuie-dd** [comment]
@tobz I actually wasn't seeking feedback in that version of the branch. This newer version of the code, however, globally implements decompressing gzipped responses, which should alleviate your concerns.

**Review by neuronull — COMMENTED** [review]
Thanks for tackling this!

I'm not seeing any issues with the implementation jump out.

The defaulting to gzip is the main thing I'm not sure about whether it's a good idea or not. Will follow the discussion though.

**Comment by davidhuie-dd** [comment]
@spencergilbert I didn't know about that library, but I did a small deep dive into it after you mentioned it. 

There are a few things we would have to consider by using tower_http:
- we would be opting in to all of the different compression types that tower supports, not just gzip. Maybe this is an improvement, but this does become a change that's larger in scope. 
- our HttpClient types would change quite drastically. We currently define our `http::HttpClient`s to contain a nested `hyper::Client` (here)[https://github.com/vectordotdev/vector/blob/dh%2Fes-gzip-bug/src/http.rs#L68]. With `tower_http`, we'd have to switch to `tower_http`'s client, which wraps `hyper::Client` and enables middlewares. We don't support middlewares yet, so we've been doing a manual (wrapping deal)[https://github.com/vectordotdev/vector/blob/dh%2Fes-gzip-bug/src/sinks/util/http.rs#L395]

Any thoughts on this impact?

**Comment by davidhuie-dd** [comment]
@spencergilbert I actually had another idea: we could bring in that decompression middleware, but only apply it to the ES sink, making the change less invasive. We wouldn't gain support for gzip decompression in HTTP responses globally, however.

**Comment by spencergilbert** [comment]
> There are a few things we would have to consider by using tower_http:
> 
> * we would be opting in to all of the different compression types that tower supports, not just gzip. Maybe this is an improvement, but this does become a change that's larger in scope.

Yeah, this feels like a strict "improvement" so I wouldn't mind it generally but definitely 👎 to creeping scope unnecessarily.

> * our HttpClient types would change quite drastically. We currently define our `http::HttpClient`s to contain a nested `hyper::Client` [here](https://github.com/vectordotdev/vector/blob/dh%2Fes-gzip-bug/src/http.rs#L68). With `tower_http`, we'd have to switch to `tower_http`'s client, which wraps `hyper::Client` and enables middlewares. We don't support middlewares yet, so we've been doing a manual [wrapping deal.](https://github.com/vectordotdev/vector/blob/dh%2Fes-gzip-bug/src/sinks/util/http.rs#L395)

I _thought_ we were using more of the `tower_http`, but I guess I was misremembering...

> Any thoughts on this impact?

I'd like to leverage more of the `tower` ecosystem, but definitely feels like it's out of scope for this particular PR/issue.

**Pull request closed without merging**
