### PR TITLE
chore: add back basic per-stage pipeline metrics

### PR DESCRIPTION
**Pull request by lukesteensen**
Signed-off-by: Luke Steensen <luke.steensen@gmail.com>

### CODE REVIEW

**Comment by blt** [comment]
Super curious to see what impact this has, if anything. Will be +1 if it's neutral.

**Comment by blt** [comment]
Hmm, so, -5% with these in place on http->pipelines.

**Comment by lukesteensen** [comment]
Good to know that it doesn't nullify the gains from removing expansion, but I tend to agree that these aren't worth much vs the extra performance at this point in time. I'd say we close and revisit down the line if folks tend to agree with that.

**Comment by blt** [comment]
Agreed.

**Pull request closed without merging**
