### PR TITLE
enhancement(enrichment_tables): Changes to support GeoIP Anonymous IP database

### PR DESCRIPTION
**Pull request by publicfacingusername**
The following geoip enrichment tables are currently supported:

    GeoLite2-ASN
    GeoIP2-ISP
    GeoIP2-Connection-Type
    GeoIP2-City
    GeoLite2-City

I'd like to add support for:

    GeoIP2-Anonymous-IP

https://dev.maxmind.com/geoip/docs/databases/anonymous-ip

### CODE REVIEW

**Comment by publicfacingusername** [comment]
https://github.com/vectordotdev/vector/issues/20945

**Comment by publicfacingusername** [comment]
Please note my local test failed. Working on making the appropriate changes then will reset.

```
error[E0277]: can't compare `std::collections::BTreeMap<KeyString, vector_lib::event::Value>` with `std::collections::BTreeMap<std::string::String, vector_lib::event::Value>`
   --> src/enrichment_tables/geoip.rs:489:9
    |
489 |         assert_eq!(values, expected);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `std::collections::BTreeMap<KeyString, vector_lib::event::Value> == std::collections::BTreeMap<std::string::String, vector_lib::event::Value>`
    |
    = help: the trait `PartialEq<std::collections::BTreeMap<std::string::String, vector_lib::event::Value>>` is not implemented for `std::collections::BTreeMap<KeyString, vector_lib::event::Value>`
    = help: the following other types implement trait `PartialEq<Rhs>`:
              <std::collections::BTreeMap<K, V, A> as PartialEq>
              <std::collections::BTreeMap<K, V> as PartialEq<rkyv::collections::btree_map::ArchivedBTreeMap<AK, AV>>>
    = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0004]: non-exhaustive patterns: `DatabaseKind::AnonymousIp` not covered
   --> src/enrichment_tables/geoip.rs:129:28
    |
129 |         let result = match dbkind {
    |                            ^^^^^^ pattern `DatabaseKind::AnonymousIp` not covered
    |
note: `DatabaseKind` defined here
   --> src/enrichment_tables/geoip.rs:24:10
    |
24  | pub enum DatabaseKind {
    |          ^^^^^^^^^^^^
...
29  |     AnonymousIp,
    |     ----------- not covered
    = note: the matched value is of type `DatabaseKind`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
132 ~             DatabaseKind::City => dbreader.lookup::<City>(ip).map(|_| ()),
133 ~             DatabaseKind::AnonymousIp => todo!(),
    |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `vector` (lib) due to 1 previous error
```

**Comment by jorgehermo9** [comment]
May you add a changelog fragment too, please? https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md

**Comment by publicfacingusername** [comment]
Testing completed successfully after newly committed changes.

'''
Summary [  90.783s] 2151 tests run: 2151 passed (2 slow, 2 flaky), 11 skipped
   FLAKY 2/4 [   0.120s] vector sources::journald::tests::emits_cursor
   FLAKY 2/4 [   0.123s] vector sources::journald::tests::excludes_matches
'''

**Comment by publicfacingusername** [comment]
> May you add a changelog fragment too, please? https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md

Done!

**Review by jszwedko — APPROVED** [review]
Thanks for this @publicfacingusername !

**Review by brett0000FF — APPROVED** [review]

**Pull request merged**
