### PR TITLE
enhancement(redis sink): Support for redis stream data type

### LINKED ISSUE #10042: Redis sink: support for streams
Hello!

Since redis is already supported as a sink, I feel that supporting [streams](https://redis.io/topics/streams-intro) could be a nice low hanging fruit feature to add.

### Proposal

Suggested configuration:
```
sinks:
  my_sink_id:
    type: redis
    inputs:
      - my-source-or-transform-id
    url: redis://127.0.0.1:6379/0
    data_type: stream
    stream:
       name: 'stream-name'
       key: 'my-key'
       maxlen: 10
```

With such configuration,  each  log would be added to the stream as following:

`XADD stream-name MAXLEN 10 * my-key <logdata>`

### PR DESCRIPTION
**Pull request by NicolasFloquet**
Closes #10042

This PR adds support for Redis streams in redis sink, using following kind of configuration:

```yaml
  redis:
    type: redis
    inputs:
      - my_source_id
    url: redis://127.0.0.1:6379/0
    key: test:{{source_type}}
    data_type: stream
    stream:
      field: "message"
      maxlen:
        type: equals
        count: 10
```

Added two integration test cases: stream without maxlen parameter, and stream with maxlen parameter

### CODE REVIEW

**Comment by NicolasFloquet** [comment]
Hey @pablosichert, please notify me if you need rebase before or after review!

**Comment by svenfoo** [comment]
This looks super useful and it would be awesome to get this merged.

I see that the `entry ID` used with XADD is hardcoded to `*` in your PR. Did you consider to make this configurable so that one could choose a field that represents a timestamp? This would be useful for example when storing logs collected from `journald`.

**Review by jszwedko — COMMENTED** [review]
Hi @NicolasFloquet !

Apologies for the long delay in review on this. It fell off my radar.

In general, this looks good to me, but, rather than providing a `field` option for `stream`, what would you think of having Vector encode the entire log event as its key/values?

That is, an incoming log event like:

```json
{ "message": "hello world", "level": "DEBUG"}
```

Would be turned into:

```
xadd <key> * message "hello world" level DEBUG
```

This would require some rework of the sink as encoding currently happens _before_ the data is passed to `call()`. Let me know what you think. We can try to provide some more guidance if you want to pursue that route. The mode is different enough that we may even want to separate out the sink into a `redis_stream` sink.

**Comment by jszwedko** [comment]
Just going over open PRs. I think this behavior makes sense as an entirely new `redis_stream` sink given the differences in behavior from the current `redis` sink.

Again, apologies for the long delay in initial review. Happy to help guide this through if you (or anyone else) wants to pick it up again.

**Comment by jszwedko** [comment]
Closing this as stale, but happy to see it be picked back up!

**Comment by shomilj** [comment]
@NicolasFloquet, what did you end up doing? We are also looking into sending events from Vector into Redis streams, so this sink would be very valuable.

**Comment by NicolasFloquet** [comment]
Hello @shomilj,
The change asked by vector team (ie. create a new dedicated sink for redis stream) requires more work than what I was initially expecting, and sadly I can't really work on it right now

**Pull request closed without merging**
