### PR TITLE
fix(config): revert acquire exclusive lock to global data dir

### PR DESCRIPTION
**Pull request by jszwedko**
Reverts vectordotdev/vector#19595

Causing test failures on `master`.

### CODE REVIEW

**Comment by jszwedko** [comment]
We might be able to just roll forward too if it is easy, but staging this in case we want to roll back.

cc/ @pront you can see the failures here: https://github.com/vectordotdev/vector/actions/runs/7563041449

**Review by pront — APPROVED** [review]

**Comment by pront** [comment]
> We might be able to just roll forward too if it is easy, but staging this in case we want to roll back.
> 
> cc/ @pront you can see the failures here: https://github.com/vectordotdev/vector/actions/runs/7563041449

I will take a look tomorrow. We can wait before we merge this one but up to you.

**Comment by jszwedko** [comment]
Thanks for the approval. I'll merge now just to keep CI green, but we can re-merge the change tomorrow.

**Comment by pront** [comment]
This should fix the failures: https://github.com/vectordotdev/vector/pull/19659

**Comment by pront** [comment]
Closing in favor of https://github.com/vectordotdev/vector/pull/19659

**Pull request closed without merging**
