### PR TITLE
chore(internal_metrics source): Upgrade `metrics` crates

### LINKED ISSUE #13625: Upgrade `metrics` and `metrics-util` crates to bring in support for metric handles and a more customizable `Registry`

### PR DESCRIPTION
**Pull request by bruceg**
This does not address any potential performance issues. I want to see if anything shows up on the soak tests before targeting any performance related changes.

Closes #13625

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Awesome, happy to see us finally upgrading these crates 🎉

**Review by jszwedko — COMMENTED** [review]
@tobz's review here, too, would definitely be good.

**Comment by bruceg** [comment]
> I thought we had expected some performance hits with the upgrade? Turns out not to be the case?

We expected there _might_ be some performance hits. It's possible there are some, they just don't show up in the soak tests (ie lost in the noise).

**Comment by tobz** [comment]
Yeah, at a micro level, things are slower, but that's in all-out benchmarks in a tight loop. I guess it's mostly just lost in the noise of the real work happening in these soaks, which is great!

**Review by tobz — APPROVED** [review]

**Pull request merged**
