### PR TITLE
enhancement(file source): Add `fingerprint.lines` option

### LINKED ISSUE #5833: File source getting confused
### Vector Version

```
https://packages.timber.io/vector/0.11.X/vector-0.11.1-1-musl.x86_64.rpm
```

### Vector Configuration File

```toml
[sources.test_to_stackdriver_source]
  type         = "file"
  ignore_older = 86400
  include      = ["/var/log/test/*.log"]

[transforms.test_to_stackdriver_fix_host]
  type        = "add_fields"
  inputs      = ["test_to_stackdriver_source"]
  fields.host = "obfuscated-hostname"

[sinks.test_to_stackdriver_sink]
  type                 = "gcp_stackdriver_logs"
  inputs               = ["test_to_stackdriver_fix_host"]
  credentials_path     = "/etc/vector/conf.d/.gcp-credentials"
  tls.ca_file          = "/etc/ssl/certs/ca-bundle.crt"
  log_id               = "test"
  project_id           = "obfuscated-projectid"
  resource.type        = "gce_instance"
  resource.instance_id = "obfuscated-instance_id"
  resource.zone        = "us-east4-a"
```

### Expected Behavior

It should work

### Actual Behavior

https://packages.timber.io/vector/0.10.X/vector-x86_64.rpm was working fine. I upgraded to https://packages.timber.io/vector/0.11.X/vector-0.11.1-1-musl.x86_64.rpm

And now I just get the following logged every second or so:

```
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.546  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: Watched file has been renamed. path="/var/log/test/test1.log" old_path="/var/log/test/test3.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.546  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test0.log" old_path="/var/log/test/test1.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.546  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: Switching to watch most recently modified file. new_modified_time=SystemTime { tv_sec: 1609765456, tv_nsec: 317367352 } old_modified_time=SystemTime { tv_sec: 1609765441, tv_nsec: 787400489 }
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.547  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test7.log" old_path="/var/log/test/test0.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.547  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test6.log" old_path="/var/log/test/test0.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.547  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test5.log" old_path="/var/log/test/test0.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.548  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test4.log" old_path="/var/log/test/test0.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.548  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test2.log" old_path="/var/log/test/test0.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.549  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: More than one file has the same fingerprint. path="/var/log/test/test3.log" old_path="/var/log/test/test0.log"
Jan 04 13:04:31 obfuscated-hostname vector[28275]: Jan 04 13:04:31.549  INFO source{component_kind="source" component_name=test_to_stackdriver_source component_type=file}:file_server: file_source::file_server: Switching to watch most recently modified file. new_modified_time=SystemTime { tv_sec: 1609765466, tv_nsec: 536047331 } old_modified_time=SystemTime { tv_sec: 1609765456, tv_nsec: 317367352 }
```

There's a lot of "More than one file has the same fingerprint" in there. These log files do not contain the same content.

I downgraded to the old version, and these log entries stopped.

### PR DESCRIPTION
**Pull request by ktff**
Closes #5833

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Nice, thanks! Do you think we could / should expose this option on the `kubernetes_logs` source too?

One thing I'm wondering about is what Vector's behavior is when there is less than `lines` number of lines in the file. Does it avoid reading / checkpointing until then? It might be worth calling out in the docs that files with less lines than `lines` will not be read if that is the case.

**Comment by bruceg** [comment]
> Do you think we could / should expose this option on the `kubernetes_logs` source too?

Does this have value for Kubernetes logs? That is, do they not have a more predictable format where we already know that only the first line (or whatever) needs to be used for fingerprinting?

**Review by bruceg — APPROVED** [review]

**Comment by spencergilbert** [comment]
> > Do you think we could / should expose this option on the `kubernetes_logs` source too?
> 
> Does this have value for Kubernetes logs? That is, do they not have a more predictable format where we already know that only the first line (or whatever) needs to be used for fingerprinting?

No, it'll be application dependent there as well - we should expose it in that source as well 👍

**Comment by ktff** [comment]
> No, it'll be application dependent there as well - we should expose it in that source as well +1

I'll open a follow up PR for that.

**Review by spencergilbert — APPROVED** [review]

**Review by lukesteensen — COMMENTED** [review]
Looks reasonable to me!

**Pull request merged**
