### PR TITLE
fix(config): correctly propagate http config provider Result to caller

### PR DESCRIPTION
**Pull request by PriceHiller**
## Summary

Copied from the body of the commit:

> Problem: The HTTP config provider has been failing to parse the provided TOML from its endpoint when polled. My best guess is that including the `?` on the end of the http provider load results in the TOML parser subtly exploding due to the aliased return type (`BuildResult`).
>
> It appears that this was broken in `8ed9ec24c1eba0b2191d7c1f24ec2a7540b5bebf`.
>
> See https://github.com/vectordotdev/vector/issues/21873 for the initial issue report.
>
> Solution: Correctly propagate the `ConfigBuilder` by not using the `?` operator. This appears to allow the TOML parser to correctly pick up on the return type.
> ...

I'm not entirely certain _why_ the TOML parser is choking when we use the sugar `?`. Best I can tell, is the generated match arms aren't wrapping the `Ok` case and instead return the inner full value. What's surprising to me, is the complete lack of the compiler having a meltdown about this.

## Change Type

- [x] Bug fix
- [ ] New feature
- [ ] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?

- [ ] Yes
- [x] No

## How did you test this PR?

In two ways:

1. Building `vector` with my fix in place and testing the provided files from https://github.com/vectordotdev/vector/issues/21873:

  ```toml
  [provider]
  type = "http"
  url = "http://localhost/vector.toml"
  ```

  ```toml
# http://localhost/vector.toml
  [sources.demo]
  type = "demo_logs"
  format = "syslog"
  interval = 1

  [sinks.print]
  type = "console"
  encoding = { codec = "json", json = {pretty = true }}
  inputs = ["demo"]
  ```

2. Running relevant unit tests via: `cargo test --no-default-features --features "sinks-console,sources-demo_logs" `

## Does this PR include user facing changes?

- [x] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist

- [x] Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- [x] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
      run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

## References

- Closes: https://github.com/vectordotdev/vector/issues/21873

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks for this fix @PriceHiller ! I tested it out locally and verified that it seems to work.

**Comment by pront** [comment]
nit: @jszwedko do we want a changelog for this? or we are treating it as a non-advertised feature?

**Comment by jszwedko** [comment]
> nit: @jszwedko do we want a changelog for this? or we are treating it as a non-advertised feature?

Ah, good catch. I'd say we should add a changelog entry for this even though the feature is undocumented since there are some people relying on it. Do you mind adding a changelog entry @PriceHiller ?

**Comment by PriceHiller** [comment]
> > nit: @jszwedko do we want a changelog for this? or we are treating it as a non-advertised feature?
> 
> 
> 
> Ah, good catch. I'd say we should add a changelog entry for this even though the feature is undocumented since there are some people relying on it. Do you mind adding a changelog entry @PriceHiller ? See https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md

Sure, just a heads up I'm taking finals so I don't have access to a computer until late tonight -- I can definitely make it happen tomorrow though.

If you'd rather finish this out today, feel free to take over 🙂.

Otherwise, I'll ping when I've added a changelog entry.

**Comment by PriceHiller** [comment]
@jszwedko Amended my commit to include the changelog as requested.

**Pull request merged**
