### PR TITLE
chore: Allow CPU/memory targets to be set by user in soaks

### LINKED ISSUE #9939: Ensure soak tests numbers are per core numbers
When we think about performance benchmarks, we should think about them on a per core basis since that'll normalize the values regardless of our machine sizes. This aligns more closely with the performance metrics that we communicate with customers.

### PR DESCRIPTION
**Pull request by blt**
This commit allows the user to set CPU/memory targets for the soak environment
and the CPU limit for vector. This allows us to provide more memory than
developers are expected to have in CI and also to adjust the units of our
analysis to bytes/second/CPU.

Closes #9939
REF #9926
REF #9942

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Comment by blt** [comment]
Hmm. Curiously, two of the soaks came through without a peer.

**Comment by blt** [comment]
Confirmed by hand that the capture file was blank for the missing peers.

**Comment by blt** [comment]
Very curious. This time `datadog_agent_remap_blackhole` blanked out entirely.

**Comment by blt** [comment]
Interesting. So https://github.com/vectordotdev/vector/runs/4147311500?check_suite_focus=true shows that 111446 bytes were uploaded for the comparison soak but https://github.com/vectordotdev/vector/pull/9962#issuecomment-963765137 shows the comparison as missing for `datadog_agent_remap_blackhole`. Unfortunately I didn't nab the artifact file before re-running the job but _something_ was uploaded.

**Comment by blt** [comment]
Hmm, the last few runs have been a-okay. I've offset the capture directories and removed useless caching in https://github.com/vectordotdev/vector/pull/9962/commits/415a273effeaed83f481912ae7180c0da6ba607b to try and slim out any areas that might have been a problem. I'll re-run the action a few times to see what happens.

**Comment by blt** [comment]
Consider that I could never reproduce this locally I do wonder if this might not have been an artifact upload bug, or unexpected behavior. Looking back through the old action logs each "lost" experiment did register an upload of a non-trivial captures file.

**Comment by blt** [comment]
Assuming the next triggered run comments with no lost experiments I'm willing to say:

* there was a bug on our side and it remains mysterious but possibly resolved by offsetting 
* there was a bug on Github's side and it remains mysterious but is seemingly rare

**Review by spencergilbert — APPROVED** [review]
These seem reasonable - are we going to want to allow adjustable memory as well?

**Pull request merged**
