### PR TITLE
fix(sinks/gcp/pubsub.rs): remove pubsub log only restriction

### PR DESCRIPTION
**Pull request by genadipost**
Inspired by https://github.com/vectordotdev/vector/pull/18074

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Perfect, thanks @genadipost ! I appreciate you adding a test.

I think the only thing this is missing is a changelog entry. Could you add one per https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md ?

**Comment by genadipost** [comment]
> Perfect, thanks @genadipost ! I appreciate you adding a test.
> 
> I think the only thing this is missing is a changelog entry. Could you add one per https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md ?

Done

**Comment by jszwedko** [comment]
Perfect, thanks!

**Comment by genadipost** [comment]
@jszwedko I have fixed fmt issue. Can you enable the auto-merge again? :)

**Pull request merged**
