### PR TITLE
fix(vector): internal log rates init usage fix

### PR DESCRIPTION
**Pull request by arshiyasolei**

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Looks good! I tested it out locally this time like I should have last time 😄

**Review by spencergilbert — APPROVED** [review]
✅ on the additional seconds => true changes. Discussed with @arshiyasolei briefly about surfacing the configured rate limit, which will likely come in another PR.

**Comment by spencergilbert** [comment]
@arshiyasolei would you mind pushing an empty commit or something to trigger the k8s e2e tests? I think this change might cause them to break due to: https://github.com/vectordotdev/vector/blob/master/lib/k8s-e2e-tests/src/lib.rs#L241

**Review by spencergilbert — APPROVED** [review]
Assuming it passes CI, lgtm - one day we'll find the time to clean up that test library

**Comment by arshiyasolei** [comment]
😆

**Comment by hhromic** [comment]
@arshiyasolei thanks for this follow up PR. I can confirm now that the rate limiting works as expected!
Even for the case of unit tests, which is where we need it the most 🎉.

Just a minor suggestion for a follow up improvement.
Before, Vector used to log the actual rate limit (in secs) that was configured (`internal_log_rate_secs` tag):
```
2022-09-20T09:55:22.725289Z  WARN transform{component_kind="transform" component_id=parse-json component_type=remap component_name=parse-json}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 1" internal_log_rate_secs=30
```

After your configurable rate limit changes, it now only has a `internal_log_rate_limit=true` tag:
```
2022-09-20T09:52:23.448054Z ERROR transform{component_kind="transform" component_id=parse-json component_type=remap component_name=parse-json}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 1" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
```

I would suggest to restore the previous `internal_log_rate_secs` tag which was useful.

**Comment by spencergilbert** [comment]
Hey @hhromic,

I'm curious what your use-case on the per log limit tag was - with the existing change, all logs will be rate limited on the same window (10s or user defined at startup). This configuration will also be logged by Vector:

```rust
info!(
    message = "Internal log rate limit configured.",
    internal_log_rate_secs = root_opts.internal_log_rate_limit
);
```

We could definitely look to add the exact number back into each emitted log but I felt like this was a good compromise for this PR.

**Comment by hhromic** [comment]
@spencergilbert ah my bad, I didn't notice it was reporting it at start-up now 🙈 🤦‍♂️
Just tested setting it to `10` and indeed getting it reported properly:
```
2022-09-20T13:00:02.446335Z  INFO vector::app: Internal log rate limit configured. internal_log_rate_secs=10
```

We don't have a use-case for the tag itself on a per-line basis. I mistakenly thought that Vector was not reporting _anywhere_ the configured rate limit in secs and thus this information was missing.

So we are good with this! We don't particularly need reporting the value per line!

**Comment by spencergilbert** [comment]
Definitely open to further adjustments down the line if it comes up. During startup (and near where the log level is reported) seemed like a good place to centralize it.

Just wanted to double check we didn't break an existing use I wasn't aware of!

**Comment by arshiyasolei** [comment]
> @arshiyasolei thanks for this follow up PR. I can confirm now that the rate limiting works as expected! Even for the case of unit tests, which is where we need it the most 🎉.
> 
> Just a minor suggestion for a follow up improvement. Before, Vector used to log the actual rate limit (in secs) that was configured (`internal_log_rate_secs` tag):
> 
> ```
> 2022-09-20T09:55:22.725289Z  WARN transform{component_kind="transform" component_id=parse-json component_type=remap component_name=parse-json}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 1" internal_log_rate_secs=30
> ```
> 
> After your configurable rate limit changes, it now only has a `internal_log_rate_limit=true` tag:
> 
> ```
> 2022-09-20T09:52:23.448054Z ERROR transform{component_kind="transform" component_id=parse-json component_type=remap component_name=parse-json}: vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_json\" at (4:25): unable to parse json: expected value at line 1 column 1" error_type="conversion_failed" stage="processing" internal_log_rate_limit=true
> ```
> 
> I would suggest to restore the previous `internal_log_rate_secs` tag which was useful.
> 
> EDIT: Oh, I just realised that @spencergilbert already pointed out the above:
> 
> > ✅ on the additional seconds => true changes. Discussed with @arshiyasolei briefly about surfacing the configured rate limit, which will likely come in another PR.
> 
> All good then!

Glad things are working now!

**Pull request merged**
