### PR TITLE
docs(vrl): Document timezone configuration

### LINKED ISSUE #9455: remap transform: Incorrect docs
https://vector.dev/docs/reference/configuration/transforms/remap/

Example config shows both `file` and `source` options which is invalid, and `timezone` is not documented.

### PR DESCRIPTION
**Pull request by 001wwang**
Part of #9455 

This PR documents the remap transform `timezone` option.

### CODE REVIEW

**Comment by spencergilbert** [comment]
There's some overlap with: https://github.com/vectordotdev/vector/pull/9870

**Comment by 001wwang** [comment]
> There's some overlap with: #9870

Ah, thanks for the heads up. I'll drop the example configuration change.

**Comment by spencergilbert** [comment]
> > There's some overlap with: #9870
> 
> Ah, thanks for the heads up. I'll drop the example configuration change.

On the other hand - if just marking that not common solves it too, that might be a nicer less invasive change 🤷

**Comment by 001wwang** [comment]
> On the other hand - if just marking that not common solves it too

No worries, I think doing it Luc's way is probably for the best. I just checked the preview deploy and `file` still shows up in the `Advanced` config this way (not sure why).

**Review by jszwedko — APPROVED** [review]
Thanks!

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
