### PR TITLE
fix(mongodb_metrics source): (revert) Fix data types of metrics

### PR DESCRIPTION
**Pull request by jszwedko**
Reverts vectordotdev/vector#13729

### CODE REVIEW

**Review by tobz — APPROVED** [review]

**Comment by jszwedko** [comment]
Merging to unblock master since the integration tests passed.

cc/ @KernelErr it turns out that `max_bytes` is a float, at least in the version of MongoDB we are testing against. See failure here: https://github.com/vectordotdev/vector/runs/7616614598?check_suite_focus=true

**Comment by KernelErr** [comment]
Hi @jszwedko, I am so surprised that the data type is incorrect. Sorry for any inconvenience I caused. But in my test, it's `i64`. And I have compiled my code and run it on my server for several days.

My Docker image:

```
REPOSITORY             TAG       IMAGE ID       CREATED       SIZE
mongo                  5.0.9     c8b57c4bf7e3   7 weeks ago   701MB
```

image

**Comment by KernelErr** [comment]
`cache` section:

[cache.txt](https://github.com/vectordotdev/vector/files/9238235/cache.txt)

**Comment by tobz** [comment]
@KernelErr No worries at all. We've been meaning to make our integration tests run for all PRs precisely for this reason, because sometimes it can be easy to miss these types of issues depending on the versions being tested against, etc.

We test against 4.2.10 which I'm guessing is responsible for the mismatch here. I tried finding actual documentation for the specific format of the block manager metrics, though, and couldn't manage to find them... but ultimately, I wonder if there's a way for us to just force coercion to `f64` in `serde`, whether it's a `i64` or `f64`.

Ultimately, an `f64` can represent whole integers up to 2^53 without truncation, so that's 9 petabytes for "bytes written" without any loss in accuracy... and with counters that high, I'm not sure being off by a single byte really matters. 🤔

**Comment by KernelErr** [comment]
Use `f64` will not cause any error. I just fix it as I saw it. 😂 The actual data type caused error is the `i32` one. So we may still need to change `bytes_written`.

**Comment by KernelErr** [comment]
I will take further investigation later.

**Comment by KernelErr** [comment]
For MongoDB 4.4.15 Community, you will get:

```
"maximum bytes configured": Double(7774142464.0)
```

But in 5.0.10, it will be:

```
"maximum bytes configured": Int64(7774142464)
```

In the `WiredTiger` source code, you could find the lines:

https://github.com/wiredtiger/wiredtiger/blob/94b59d2e87c49749aad0f25ffac56709bd33176c/test/cppsuite/src/component/statistics/cache_limit.cpp#L64-L80

image

I think it's should be `i64`. But somehow, in previous MongoDB version, it became `f64`. For compatibility reason, we can use `f64`.

**Comment by KernelErr** [comment]
The other field `bytes written`. Now I am a bit confused. After upgrading my server from 5.0.9 to 5.0.10. It became `i32` rather than `i64`.

I think it's because the inner BSON build could decide the type of number according if it overflows the max/min value. For safety reason, we may need to change all `i32` to `i64`?

https://cs.github.com/mongodb/mongo/blob/4e2b9c4b8f62f81145483db734b778115a4784e1/src/mongo/bson/bsonobjbuilder_test.cpp#L90

```
/**
 * current conversion ranges in appendNumber(long long n)
 * int max/min in comments refer to max/min encodable constants
 *                       n <  int_min            -----> long long
 *            int_min <= n <= int_max            -----> int
 *            int_max <  n                       -----> long long
 */
```

Ref:

https://github.com/mongodb/mongo/blob/67187900ed20d3720a113d2a5b2f4b1e6e33c4af/src/third_party/wiredtiger/src/include/stat.h#L334

https://github.com/mongodb/mongo/blob/1c60ecd6a9bfb34b9e76ce5d1e9caee6f3264a85/src/third_party/wiredtiger/dist/stat_data.py#L214

**Comment by KernelErr** [comment]
CC @jszwedko @tobz

**Comment by KernelErr** [comment]
Anyway, I advise we could take a deeper look at the MongoDB's BSON builder. My C++ skill are poor, may have some misunderstanding.

**Comment by KernelErr** [comment]
Btw, I find that MongoDB has a new major release 6.0. Don't know if what fields have any change. 🤔

**Comment by jszwedko** [comment]
Hey @KernelErr ! Thanks for that investigation. I agree with you that it'd be best to be conservative here with the types that are used. I'd be open to seeing all of the i32s converted to i64s. It seems like we should keep max bytes written as an f64 to accommodate the fact that some versions have it as an f64 and others as an i64..

**Comment by KernelErr** [comment]
🙂 Okay, let me investigate MongoDB 6.0 later to check if there is any other things needs to change.

**Comment by KernelErr** [comment]
I checked MongoDB 6.0.1.

https://github.com/vectordotdev/vector/blob/8e2201bcfd7b7ec460d783ed8b8489cafef55902/src/sources/mongodb_metrics/types.rs#L137

Seems the `record` field is not provided. 



Should we remove it or take it as optional?

**Comment by KernelErr** [comment]
Other fields is presented. Seems current code from the master branch works for MongoDB 6. Didn't check one by one but no error occurred.

**Comment by jszwedko** [comment]
Interesting! I'd say we could make `record` optional. Thanks for digging into that @KernelErr

**Pull request merged**
