### PR TITLE
chore(website): Add a links to footer for to the /releases and /downloads pages

### PR DESCRIPTION
**Pull request by neuronull**
Closes: https://github.com/vectordotdev/vector/issues/16438

Seems to be working fine

Screenshot 2023-02-14 at 3 38 18 PM

### CODE REVIEW

**Comment by jszwedko** [comment]
Nice, thanks! Thinking about this more, I'm not sure if it rises to the level of warranting inclusion in the header given the limited amount of real estate there and the fact that I don't anticipate people clicking it super often. I'd suggest we:

* Add it to the footer
* Link it from the Downloads/ page
* Link it from the individual release page (e.g. https://vector.dev/releases/0.27.0/)

What do you think?

**Comment by neuronull** [comment]
> Nice, thanks! Thinking about this more, I'm not sure if it rises to the level of warranting inclusion in the header given the limited amount of real estate there and the fact that I don't anticipate people clicking it super often. I'd suggest we:
> 
> * Add it to the footer
> * Link it from the Downloads/ page
> * Link it from the individual release page (e.g. https://vector.dev/releases/0.27.0/)
> 
> What do you think?

From those options I think the footer or Downloads page.
Didn't seem like there was a great fit in the footer. Setup would be the closest imo.
Downloads page is fine, just not sure where, my UI sense isn't great for websites 😂 

I don't think the third option makes sense since the idea is to be able to find the releases page in general, and that would assume that they already found it.

**Comment by jszwedko** [comment]
Ah, I actually meant add it in all three places 😄  The individual release pages are linked from the downloads page, and are also usually the link we share out for each release, so I think it is feasible that users will be on this page first and may want to navigate to other releases.

**Comment by neuronull** [comment]
Ohhh that makes sense. And that is clear in your original comment, I just failed to read it carefully enough.

I'll take another look at changing it in these areas. My goal with this was a short time box so if I get lost I may just record your proposal in the original issue.

**Comment by jszwedko** [comment]
@neuronull I pushed a commit removing it from the header, adding it to the footer, and adding breadcrumbs to the release pages (which includes a link to the index). I ended up not adding it to `/downloads` since there didn't seem like a spot where it fit. Let me know what you think!

**Review by jszwedko — APPROVED** [review]

**Comment by neuronull** [comment]
> @neuronull I pushed a commit removing it from the header, adding it to the footer, and adding breadcrumbs to the release pages (which includes a link to the index). I ended up not adding it to `/downloads` since there didn't seem like a spot where it fit. Let me know what you think!

Brilliant! Looks great. Thanks for taking this over!

**Pull request merged**
