### PR TITLE
fix(metrics): normalizer doesn't handle mix of absolute and incremental metrics

### PR DESCRIPTION
**Pull request by lukesteensen**
Big thank you to @RussellRollins for writing the failing test here! That was very helpful to narrow down the issue.

This simple fix here comes with some unfortunate downsides that we're going to need to consider before merging.

The root cause here is that we didn't really expect to need to handle a mix of incremental and absolute values for the same series. Concretely, this means the metrics normalizer only maintains state when it sees an incremental metrics that it needs to convert to absolute. If it sees an absolute metric, it assumes it will always be absolute and does not bother to store any state. That is why the failing test shows that incremental values "reset" the metric and don't take into account the previous absolute value.

To handle this case, we need to maintain state for all metrics that flow through the normalizer, just in case we see an incremental version later. Depending on the workload, this could be a relatively dramatic shift in load for this part of the component. For example, previous workloads that sent only absolute values would not need to maintain any state in the normalizer at all but now will need to maintain the full state of every metric that flows through. This is especially unfortunate because the normalizer is being used as part of the prometheus exporter which already by its nature maintains the current state of every metric, deals with expiration, etc. It's far from ideal to duplicate this logic and resource use twice in the same component.

It's possible that it's fine to move forward with this fix in the short term, depending on the impact to performance and resource use, but it points pretty strongly towards the correct solution being to move this absolute/incremental handling into the state of the prom exporter itself, where we already have all the necessary state.

### CODE REVIEW

**Comment by RussellRollins** [comment]
I recognize this is easy for me to say as someone who isn't a maintainer and wouldn't be on the unpleasant end of performance complaints, but I think following the good old rule of "make it work, make it right, make it fast", getting this fix in and making statsd sources + Prometheus sinks conform to the statsd interface seems like a good thing.

**Comment by bruceg** [comment]
> The root cause here is that we didn't really expect to need to handle a mix of incremental and absolute values for the same series.

To expand on this, we did consider this early in the design of the common code for the metric normalizers, and intentionally discarded the complexity that goes with handling mixed value types for the same metric series. Much as @lukesteensen has said, the only use case envisioned was for having each series identifier represent a stream of events all of the same kind, since this is what sources _normally_ emit.

On the other hand, I wouldn't expect adding support for this to be a large performance issue in most non-degenerate cases (i.e. super high cardinality) but the ramifications are certainly something the be aware of.

**Comment by lukesteensen** [comment]
The recent commits try a different approach where we drop the normalizer as an additional concept and just inline the logic, where we can use the sink's existing state to handle this case pretty naturally. So far it looks promising.

One change of note is dropping `kind` from the exporter's definition of `MetricRef`. The reasoning there is that everything we store is absolute, so there's no need to different on that field. Let me know if that sounds reasonable.

**Review by tobz — APPROVED** [review]
Makes sense to me. 👍🏻

**Review by bruceg — APPROVED** [review]
Makes sense to me, and eliminating the parallel normalizer map looks like a win.

**Pull request merged**
