### PR TITLE
chore(core): Value unification part 1 - NotNan floats

### PR DESCRIPTION
**Pull request by fuchsnj**
This is part 1 in a series of PR's to unify the Vector and VRL `Value` types.

The VRL `Value::Float` requires all values to be `NotNan`. This PR adds that requirement to the Vector `Value` type.
The `From<f64>` was kept for testing purposes, but is only included for tests. Everywhere else now handles possible `NaN` values and converts them to `NotNan` first.

### CODE REVIEW

**Review by JeanMertz — APPROVED** [review]
sweet 👍

**Comment by jszwedko** [comment]
Nice! Does this close #11177 ?

**Comment by fuchsnj** [comment]
> Nice! Does this close #11177 ?

Unfortunately not. Most of the existing issues (silently converting to 0) are on the VRL side of things. This PR only adds NotNan to the Vector value. In addition, I'd like to explore the idea of getting rid of `NotNan` entirely, and allowing `NaN` in VRL. This would require more significant changes on the VRL side though. I'd like to keep that issue open to discuss the more long-term future of this.

**Comment by fuchsnj** [comment]
This branch originated from a commit that was now reverted. I've cherry-picked the changes to a new branch so it is mergeable: https://github.com/vectordotdev/vector/pull/11291

**Pull request closed without merging**
