### PR TITLE
chore: Clarify messages about internal logs being rate limited

### LINKED ISSUE #5223: Make it clearer that internal log rate limits refer to the log and not events
When Vector logs via internal events, it sometimes uses a rate limit to avoid flooding the output. This looks something like:

```
Nov 25 12:11:45.976 WARN transform{name=nginx_parse_json type=json_parser}: vector::internal_events::json: 19 "Event failed to parse as JSON" events were rate limited. rate_limit_secs=5
```

The wording of this is pretty confusing as it could lead users to believe that their events are being rate limited rather than the `WARN` message.

This came up in discord: https://discord.com/channels/742820443487993987/746070591097798688/781173919365201940

### PR DESCRIPTION
**Pull request by ktff**
Closes #5223

Before:
```
Field not found; dropping event. missing_field="message" rate_limit_secs=30
"Field not found; dropping event." is being rate limited. rate_limit_secs=5
3004 "Field not found; dropping event." events were rate limited. rate_limit_secs=5
```

After:
```
Field not found; dropping event. missing_field="message" internal_log_rate_secs=30
Internal log [Field not found; dropping event.] is being rate limited.
Internal log [Field not found; dropping event.] has been rate limited 3003 times.
```

### Notes
* A notable side effect is that we have to start using field `internal_log_rate_secs` instead of old `rate_limit_secs`.

### CODE REVIEW

**Comment by jamtur01** [comment]
Maybe "Internal log message"?

**Comment by ktff** [comment]
@jamtur01 
> Maybe "Internal log message"?

It sounds like we are only rate limiting the message of the internal log, when we are rating the whole log.

But what about using "Internal log with message [...]" ? That would be clearer.

**Review by jszwedko — APPROVED** [review]
This is a definite improvement, thanks @ktff ! This should lead to much less confusion.

Not a big deal, but I am wondering if we could keep the usage as `rate_limit_secs` and map it to `internal_log_rate_secs` in `lib/tracing-limit/src/lib.rs`.

**Comment by ktff** [comment]
> if we could keep the usage as rate_limit_secs and map it to internal_log_rate_secs in lib/tracing-limit/src/lib.rs.

That would be ideal, but I didn't found a way of changing it, nor a way of completely reconstructing log event with the changed field. It's a current limitation in the `tracing` api.

**Pull request merged**
