### PR TITLE
fix(config): error message with threads=0

### PR DESCRIPTION
**Pull request by zamazan4ik**
Resolves https://github.com/vectordotdev/vector/issues/11944

Just a small fix: report an error to stderr instead of built-in logging based on tracing.

Tested locally - works fine.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks @zamazan4ik

**Comment by zamazan4ik** [comment]
In this PR clippy warns about using `eprintln!` macro. Could we somehow disable this check explicitly in this case? Since I think using `eprintln!` is the only right approach here.

**Comment by jszwedko** [comment]
> In this PR clippy warns about using `eprintln!` macro. Could we somehow disable this check explicitly in this case? Since I think using `eprintln!` is the only right approach here. However, we can simply replace it with `println!` - it will work almost the same for the end-users.

Ah, yes, you are correct. You can just add an ignore for that statement. We have that clippy lint in there because some spurious debug statements via println/eprintln have been released before so now we have to add exceptions for each new intentional output.

Example: https://github.com/vectordotdev/vector/blob/84bf26d769088f1cc30673e701c30b94156e7cee/lib/vrl/cli/src/cmd.rs#L102-L105

**Comment by spencergilbert** [comment]
Why don't we just call `error!` here (and that linked place)?

**Comment by jszwedko** [comment]
> Why don't we just call `error!` here (and that linked place)?

This is output before the tracing subsystem is wired up so users would never actually see it.

**Comment by zamazan4ik** [comment]
Because `error!` macro emits some error event, which is flushed somewhere later (you could check it with a code). In this case we have an early return and `error!` simply is not printed. That is why I use `eprintln!` here.

**Comment by spencergilbert** [comment]
> This is output before the tracing subsystem is wired up so users would never actually see it.

Doh, that would do it - that's what I get for not looking closely 😄

**Pull request merged**
