### PR TITLE
chore: update Fluent Bit and Fluentd feature list

### PR DESCRIPTION
**Pull request by l2dy**
> Both Fluentd and Fluent Bit can work as Aggregators or Forwarders, they both can complement each other or use them as standalone solutions.

https://docs.fluentbit.io/manual/about/fluentd-and-fluent-bit

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @l2dy. I'm not sure I agree with this. The point of the table was to reflect the practical use of the tool. I'm sure you could deploy FluentD as an agent, but it is not practical given Fluentd's performance characteristics. As another example, you could deploy Logstash as an agent, but that is also impractical. The inverse is also true for Fluentbit.

**Comment by l2dy** [comment]
We are still using Fluentd as a log collection agent for some services, and it was used extensively in production before Fluent Bit even exists. How would you define it impractical?

**Comment by l2dy** [comment]
Performance and features are difference matrices that are both presented in the README. In my opinion, even if it's terribly bad for a certain scenario, it should get an ⚠ explaining the situation rather than nothing.

**Comment by l2dy** [comment]
Closing due to inactivity and not being able to reach consensus.

**Pull request closed without merging**
