### PR TITLE
chore(geoip transform): Deprecate `geoip` transform

### PR DESCRIPTION
**Pull request by jszwedko**
Replaced by enrichment table support

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by fuchsnj — APPROVED** [review]

**Review by spencergilbert — APPROVED** [review]
Curious if we benchmarked between the two before deprecating?

**Comment by jszwedko** [comment]
> Curious if we benchmarked between the two before deprecating?

I didn't, but given this is the direction we are moving enrichment in Vector I think we want to deprecate this either way. If it is slower, we will just have to make `remap` faster 😄

**Comment by spencergilbert** [comment]
> > Curious if we benchmarked between the two before deprecating?
> 
> I didn't, but given this is the direction we are moving enrichment in Vector I think we want to deprecate this either way. If it is slower, we will just have to make `remap` faster 😄

OFC 😄 just remembering a couple users being very attentive to the perf between "old" and VRL.

**Comment by jszwedko** [comment]
> > > Curious if we benchmarked between the two before deprecating?
> > 
> > 
> > I didn't, but given this is the direction we are moving enrichment in Vector I think we want to deprecate this either way. If it is slower, we will just have to make `remap` faster 😄
> 
> OFC 😄 just remembering a couple users being very attentive to the perf between "old" and VRL.

👍 it's a valid concern for sure. We can evaluate the performance difference before dropping it entirely, similar to `add_fields` and friends.

**Pull request merged**
