### PR TITLE
feat(reduce transform): add "starts_when" option

### LINKED ISSUE #4574: Verify that the reduce transform can handle various multi-line scenarios
This is a meta issue to ensure the upcoming `reduce` transform changes will solve a variety of multiline scenarios.

### 1. Ruby Exceptions

Log stream:

```text
Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100
foobar.rb:6:in `/': divided by 0 (ZeroDivisionError)
  from foobar.rb:6:in `bar'
  from foobar.rb:2:in `foo'
  from foobar.rb:9:in `<main>'
Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100
```

Lazy solution:

```toml
[transforms.reduce]
type = "reduce"
starts_with = '!match(.message, /^\w/)'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

Strict solution (checking both the start and end conditions)

```toml
[transforms.reduce]
type = "reduce"
starts_with = '!match(.message, /^[a-z]*\.rb/)'
ends_with = '!match(.message, /^\w/)'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### 2. Line Continuations

Log stream:

```text
First-line
Second line\
more second line\
end of second line
```

Config:

```toml
[transforms.reduce]
type = "reduce"
ends_when = '!endsWith(.message, "\")'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### 3. Line Terminations

```text
first line;
second line
more of the second line
end of second line;
third line;
```

Config:

```toml
[transforms.reduce]
type = "reduce"
ends_when = 'endsWith(.message, ";")'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### 4. Windows Event Logs

Log stream:

```text
<12> first line 
 more of the first line
<22> second line
<17> third line
```

Config:

```toml
[transforms.reduce]
type = "reduce"
starts_with = 'match(.message, /^<\d\d> /)'
merge_strategies.default = "discard"
merge_strategies.fields.message = "concat"
```

### PR DESCRIPTION
**Pull request by JeanMertz**
Similar to the existing `ends_when` option, but starts a new reduce operation when this option triggers, as opposed to ending a reduce operation when `ends_when` triggers.

Currently, if both options are provided, ~~`starts_when` takes precedence~~ a boot-time error is triggered.

I also added a bunch of behaviour tests that validate the examples provided in #4574 work as expected.

closes #4574.

### CODE REVIEW

**Review by bruceg — APPROVED** [review]
Looks good

**Review by jszwedko — APPROVED** [review]
Looks good. I appreciate all of the behavior tests testing real-world cases.

> Currently, if both options are provided, starts_when takes precedence.

Could we have it explicitly error at build time? I think that would be clearer.

**Comment by JeanMertz** [comment]
> Could we have it explicitly error at build time? I think that would be clearer.

I guess we could. I'm trying to think of an example where you want to define both. I'm sure there is one, but I can't think of one right now. I guess we can lift the restriction (and document the behavior) if we do find a situation that requires you to define both `starts_when` and `ends_when`.

**Comment by jszwedko** [comment]
:+1: Removing the restriction later, if we find such a case, would be backwards compatible.

**Comment by binarylogic** [comment]
Just noting, docs were not updated with this change. See https://github.com/timberio/vector/pull/5497.

**Pull request merged**
