### PR TITLE
fix(aws provider): Use default region provider if region unspecified

### PR DESCRIPTION
**Pull request by jszwedko**
Fixes: #12474

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by fuchsnj — APPROVED** [review]
Looks like it works this time, since you are getting test failures for missing regions!

**Comment by jszwedko** [comment]
Looking at these tests is making me realize I think we did previously allow not setting the region and falling back to `AWS_REGION` / `AWS_DEFAULT_REGION` 🤔

**Comment by jszwedko** [comment]
@fuchsnj after thinking about this more, I realized we should utilize the default AWS region provider chain to determine the region if the user doesn't explicitly set it. The default credential provider does look for the region in this way, but I think it is better to fail up front if there is no region rather than later, after Vector starts, when it tries to make a request to AWS and lazily loads the credentials. I made these changes here if you want to take another 👀

**Comment by jszwedko** [comment]
I created https://github.com/vectordotdev/vector/issues/12534 to clean this up a bit too.

**Review by spencergilbert — APPROVED** [review]

**Review by fuchsnj — APPROVED** [review]

**Pull request merged**
