### PR TITLE
feat(regex_parser transform): Add support for nested field names

### LINKED ISSUE #1812: `regex_parser` transform doesn't work with nested fields
Currently the `regex` crate which underlies our `regex_parser` implementation supports only `[_0-9a-zA-Z]+` as possible names for captures groups. Thus nested fields of form `x.y.z` cannot be captured.

For example, the following config unit test

```toml
[transforms.regex_parser_nested]
  inputs = []
  type = "regex_parser"
  regex = "^(?P<nested.timestamp>[\\w\\-:\\+]+) (?P<nested.level>\\w+) (?P<doubly.nested.message>.*)$"
[[tests]]
  name = "regex_parser_nested"
  [tests.input]
    insert_at = "regex_parser_nested"
    type = "raw"
    value = "2020-01-01T12:34:56Z INFO hello"
  [[tests.outputs]]
    extract_from = "regex_parser_nested"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "nested.timestamp.equals" = "2020-01-01T12:34:56Z"
      "nested.level.equals" = "INFO"
      "doubly.nested.message.equals" = "hello"
```

fails with the error

```
Failed to build test 'regex_parser_nested':
  failed to build transform 'regex_parser_nested': Invalid regular expression: regex parse error:
      ^(?P<nested.timestamp>[\w\-:\+]+) (?P<nested.level>\w+) (?P<doubly.nested.message>.*)$
                 ^
  error: invalid capture group character
```

I think we need to allow field names containing dots. A simplest option to do this is to fork the `regex` crate and add support for it there, send a PR to the upstream, and use the fork until the support for dots in capture groups in added to the upstream crate.

### PR DESCRIPTION
**Pull request by bruceg**
Closes #1812

### CODE REVIEW

**Comment by a-rodin** [comment]
I have two questions:

1. Would it make sense to add a test (and, if it doesn't work, also an implementation) for array indexes? For example, `array.field[0].x`.

2. Because the PR is not likely to be merged soon (because the maintainers of `regex` crate previously expressed some concerns about adding this without a careful spec) can we put the fork to the `lib` directory? I was recently thinking about doing the same with `leveldb-sys` crate which we maintain ourselves too.

**Comment by bruceg** [comment]
1. It would make sense to add such a test. However, nothing else appears to be testing this (at least not in `tests/behavior`), which makes me wonder if it shouldn't go in a separate issue.
2. I have no opinion one way or another, except that I think this would work best as a submodule rather than a full import of the regex source tree.

**Comment by binarylogic** [comment]
And just noting. I would like to standardize around a field access syntax for consistency. If we're baking this into the regex crate, as well as other parts of Vector, it makes sense to document this somewhere and/or centralize parsing this format.

**Comment by a-rodin** [comment]
This format is already centrally supported by the Vector's core (reading and writing fields in this format automatically operate on internal nested structures). However, I agree that we need to have a dedicated place for it in the documentation (#1975 represents it).

**Comment by binarylogic** [comment]
From planning: embedding the regex repo was a light suggestion, we decided not to do this.

**Comment by binarylogic** [comment]
From planning: given the caveats of maintaining a fork of the regex crate we've decided to add an option to place fields into a namespace, similar to the [`target` option in the `geoip` transform](https://vector.dev/docs/reference/transforms/geoip/#target). Use can then subsequently move fields around with the `rename_fields` transform. Concrete changes are:

- [ ] Add a `target` option that functions like the one referenced above.
- [ ] Add docs on pairing this with the `rename_fields` transform to achieve more customized naming.

**Comment by bruceg** [comment]
Closing this due to [discussion on the main issue](https://github.com/timberio/vector/issues/1812#issuecomment-596759785)

**Pull request closed without merging**
