### PR TITLE
enhancement(sinks): Add `logfmt` encoding

### LINKED ISSUE #8060: Support `logfmt` encoding on sinks
A user requested support for the `logfmt` encoding on the `loki` sink.

A current workaround is to use `encode_logfmt` in VRL and then `encoding.codec = "text"` for sinks that support it.

We should pull out the encoding code from `encode_logfmt` to share it to ensure the implementation is the same.

### PR DESCRIPTION
**Pull request by ktff**
Closes #8060

Existence of two representations for `Value`, one VRL other Vector, complicates things. For now it seems simplest to transform Vector `Value` to VRL `Value` since even with this conversion it will be faster than going through remap. 

An alternative would be to abstract over both values via trait or enum. But the resulting abstraction would be quite specific and probably won't be useful anywhere else at the moment. `Serialize` could be used instead but some 300 lines extra would be needed to bridge the gap which seems kinda much for this. 

This is a draft at the moment so to gather comments on the direction. What remains is to extend this to other sinks.

cc. @bruceg @jszwedko

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Thanks @ktff !

I'm actually curious to get @JeanMertz 's thoughts on the choice here to marshal to a VRL value.

**Comment by JeanMertz** [comment]
> I'm actually curious to get @JeanMertz 's thoughts on the choice here to marshal to a VRL value.

I don't mind it, but I think I'd vote to create a layer of separation: move all encoding logic into the existing `shared` crate (not `vrl-shared`), have it return a `T` which implements `From<Bytes> + From<i64> + ...` similar to the existing [conversion logic](https://github.com/timberio/vector/blob/5b5f457108345be94a9617a7291b433f3902cd04/lib/shared/src/conversion.rs#L114-L118).

Since both `vector::Value` and `vrl::Value` implement those traits, both sides can leverage the shared logic.

This way, we don't need to use `vrl::Value` inside sinks that have no other relation to VRL, and there's no cross-dependency `Value` requirement between Vector and VRL.

All of this is without knowing the impact on performance, I'd expect it to be negligible, but it might be worth profiling. Also, there might be other aspects of this that I missed, that make my proposal impossible.

**Comment by ktff** [comment]
@JeanMertz

> create a layer of separation: move all encoding logic into the existing shared crate (not vrl-shared), 

That's preferable, but 

> `From<Bytes> + From<i64> + ...`

aren't enough here. The encoding logic can flatten booleans so it needs to know when it's dealing with a boolean, so something like `ToString` isn't enough. Additionally with generic trait which would transform itself to `String`, all implementations would need to be done and maintained in a way to produce the same result, which is fragile. What fits all of these requirements is the alternative from [opening comment](https://github.com/timberio/vector/pull/8826#issue-717293143), specifically `Serialiize`  which requires reimplementing encoder as a `Serializer`.

**Comment by ktff** [comment]
> all implementations would need to be done and maintained in a way to produce the same result,

Escaping `\`, `"` and so on is especially fragile here.

**Comment by ktff** [comment]
Sounds good.

**Pull request closed without merging**
