### PR TITLE
fix(core): Fix panic when reloading config under load

### LINKED ISSUE #13814: Vector panic on reload
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello, when I try to reload this conf below (see the vector.address that changed), I get the following logs:

```
Aug 03 11:44:29 host systemd[1]: Stopped Vector.
Aug 03 11:44:29 host systemd[1]: vector.service: Failed with result 'timeout'.
Aug 03 11:44:29 host systemd[1]: vector.service: Main process exited, code=killed, status=9/KILL
Aug 03 11:44:29 host systemd[1]: vector.service: Killing process 26826 (vector) with signal SIGKILL.
Aug 03 11:44:29 host systemd[1]: vector.service: State 'stop-sigterm' timed out. Killing.
Aug 03 11:43:53 host vector[26826]: 2022-08-03T11:43:53.521100Z  WARN sink{component_kind="sink" component_id=vector_out component_type=vector component_name=vector_out}:request{request_id=0}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
Aug 03 11:42:58 host systemd[1]: Stopping Vector...
Aug 03 11:42:41 host vector[26826]: 2022-08-03T11:42:41.021153Z ERROR source{component_kind="source" component_id=journald_in component_type=journald component_name=journald_in}: vector::sources::journald: Could not send journald log. error=Sender is closed.
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.871743Z ERROR source{component_kind="source" component_id=syslog_in component_type=syslog component_name=syslog_in}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.738450Z ERROR source{component_kind="source" component_id=syslog_in component_type=syslog component_name=syslog_in}: vector::sources::syslog: Error sending line. error=Sender is closed.
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.738342Z ERROR source{component_kind="source" component_id=journald_in component_type=journald component_name=journald_in}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.738285Z ERROR source{component_kind="source" component_id=syslog_in component_type=syslog component_name=syslog_in}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: thread 'vector-worker' panicked at 'join error: JoinError::Panic(Id(66), ...)', src/topology/builder.rs:212:30
Aug 03 11:42:40 host vector[26826]: thread 'vector-worker' panicked at 'join error: JoinError::Panic(Id(69), ...)', src/topology/builder.rs:212:30
Aug 03 11:42:40 host vector[26826]: thread 'vector-worker' panicked at 'unit error: ()', lib/vector-core/src/fanout.rs:369:42
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.737937Z ERROR transform{component_kind="transform" component_id=journald_filter component_type=filter component_name=journald_filter}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.737900Z ERROR transform{component_kind="transform" component_id=syslog_filter component_type=filter component_name=syslog_filter}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: :369:42
Aug 03 11:42:40 host vector[26826]: thread 'vector-worker' panicked at 'unit error: ()', thread 'lib/vector-core/src/fanout.rsvector-worker:' panicked at '369unit error: ():', 42lib/vector-core/src/fanout.rs
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.737464Z ERROR transform{component_kind="transform" component_id=journald_parser component_type=remap component_name=journald_parser}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.737412Z ERROR transform{component_kind="transform" component_id=syslog_parser component_type=remap component_name=syslog_parser}: vector::topology: An error occurred that Vector couldn't handle.
Aug 03 11:42:40 host vector[26826]: ' panicked at 'Pausing non-existent sink is not valid: vector_out', lib/vector-core/src/fanout.rs:315:17
Aug 03 11:42:40 host vector[26826]: vector-workernote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aug 03 11:42:40 host vector[26826]: thread 'vector-worker' panicked at 'Pausing non-existent sink is not valid: vector_out', lib/vector-core/src/fanout.rs:315:thread '17
Aug 03 11:42:40 host vector[26826]: 2022-08-03T11:42:40.736299Z  INFO vector::topology::running: Reloading running topology with new configuration.
Aug 03 11:42:40 host systemd[1]: Reloaded Vector.
Aug 03 11:42:40 host vector[28838]:                            Validated
Aug 03 11:42:40 host vector[28838]: ------------------------------------
Aug 03 11:42:40 host vector[28838]: √ Health check "metrics_out"
Aug 03 11:42:40 host vector[28838]: √ Health check "vector_out"
Aug 03 11:42:40 host vector[28838]: √ Component configuration
Aug 03 11:42:40 host vector[28838]: √ Loaded ["/etc/vector/vector.toml"]
Aug 03 11:42:40 host systemd[1]: Reloading Vector.
Aug 03 11:41:24 host vector[26826]: 2022-08-03T11:41:24.509124Z  WARN sink{component_kind="sink" component_id=vector_out component_type=vector component_name=vector_out}:request{request_id=0}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
Aug 03 11:39:29 host vector[26826]: 2022-08-03T11:39:29.503232Z  WARN sink{component_kind="sink" component_id=vector_out component_type=vector component_name=vector_out}:request{request_id=0}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.
Aug 03 11:37:55 host vector[26826]: 2022-08-03T11:37:55.496935Z  WARN sink{component_kind="sink" component_id=vector_out component_type=vector component_name=vector_out}:request{request_id=0}: vector::sinks::util::retries: Request timed out. If this happens often while the events are actually reaching their destination, try decreasing `batch.max_bytes` and/or using `compression` if applicable. Alternatively `request.timeout_secs` can be increased.

```

I think it's linked to the fact that thevector_out sinks is having timeouts

cc @jszwedko I think it's the same I encountered in #13731 

### Configuration

```text
[api]
enabled = true
address = "127.0.0.1:8686"

[sources.syslog_in]
type = "syslog"
address = "127.0.0.1:8699"
max_length = 102_400
mode = "udp"
# Keep only haproxy logs from syslog
[transforms.syslog_filter]
type = "filter"
inputs = [ "syslog_in" ]
condition = ".appname == \"haproxy\""
# Parse haproxy logs
[transforms.syslog_parser]
inputs = [ "syslog_filter" ]
type   = "remap"
source = '''
.log.ident = del(.appname)
.log.pid = to_string(del(.procid)) ?? ""
.log.pri = del(.severity)
.log.@timestamp = del(.timestamp)
.log.message = del(.message)
.log.host = del(.host)

. = .log
'''
# Read from journald
[sources.journald_in]
type = "journald"
since_now = true
[transforms.journald_filter]
type = "filter"
inputs = [ "journald_in" ]
condition = 'true && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && .SYSLOG_IDENTIFIER != "..." && (!contains(.SYSLOG_IDENTIFIER, "...") ?? true) && (!contains(.SYSLOG_IDENTIFIER, "...") ?? true) && (!contains(.SYSLOG_IDENTIFIER, "...") ?? true)'
# Parse journald logs
[transforms.journald_parser]
inputs = [ "journald_filter" ]
type   = "remap"
source = '''
.log.ident = del(.SYSLOG_IDENTIFIER)
.log.pid = to_string(del(._PID)) ?? ""
.log.pri = to_syslog_level(to_int(del(.PRIORITY)) ?? 0) ?? ""
.log.@timestamp = del(.timestamp)
.log.message = del(.message)
.log.host = del(.host)

. = .log
'''

# Send all logs to vector server
[sinks.vector_out]
type = "vector"
inputs = [ "journald_parser", "syslog_parser"]
address = "x.x.x.x:8700" # <- this is what I changed/reloaded
version = "2"
compression = true
# Scrap internal metrics
[sources.metrics_in]
type = "internal_metrics"
scrape_interval_secs = 20
# Expose prometheus metrics
[sinks.metrics_out]
type = "prometheus"
inputs = [ "metrics_in" ]
address = "x.x.x.x:8800"
default_namespace = "service"
```

### Version

0.23.0

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by Zettroke**
Fixes #13814

Fix panic when reloading config under load.
Panic was caused by incorrect `pause` implementation in `SendGroup`, which tries to remove senders without handling case when send is in-flight

It appears to me that handling control signals *during* events sending is useless. Because in `Fanout::send` before each send we consume and process all control signals. 
Also `add`, `replace` and `pause` handlers in `SendGroup` is equivalent to handlers in `Fanout` (they didn't affect in-flight sends). Only `remove` is handled differently, and I am not sure if this special handling is required.

Also removing control signals handling during send simplifies code a bit.

### CODE REVIEW

**Comment by tobz** [comment]
@Zettroke I appreciate you taking the time to try and come up with a fix for the linked issue.

> Fix panic when reloading config under load. Panic was caused by incorrect `pause` implementation in `SendGroup`, which tries to remove senders without handling case when send is in-flight

Can you elaborate more on what the broken logic is?

The main reason that we handle control messages during an in-flight send in `Fanout` is precisely for the configuration reloading case, in order to avoid a deadlocked component (a component that we're blocked on sending to) from preventing us from reconfiguring `Fanout` to match the new configured topology. Imagine reconfiguring Vector to get rid of a component that was pointed at a non-existent network endpoint, which was causing the sink to stall and block Vector from making progress... and you now you can't remove it without fully restarting Vector because `Fanout` has an in-flight send to that component which it's blocked on completing before it responds to control messages to remove that component.

I see your change gets rid of the handling of control messages during an in-flight send, and simply blocks waiting for the send to fully complete... which would certainly avoid issues of handling changes to `Fanout` during an in-flight send, but as mentioned above, this basically makes `Fanout` unfit for the intended purpose.

> It appears to me that handling control signals _during_ events sending is useless. Because in `Fanout::send` before each send we consume and process all control signals. Also `add`, `replace` and `pause` handlers in `SendGroup` is equivalent to handlers in `Fanout` (they didn't affect in-flight sends). Only `remove` is handled differently, and I am not sure if this special handling is required.

This is partially addressed but what I've mentioned above, but the reason for the symmetry -- having `SendGroup` handle not only `remove` but also `add`/`replace`/`pause` -- is because we need to keep control messages in order, and there's no way to receive a control message, see if it's a `remove` message, and then push it back onto the front of the control message channel if it's not. So if we want to handle any control messages at all in `SendGroup`, we have to be able to handle all of them in `SendGroup`.

**Comment by Zettroke** [comment]
@tobz Seems I rushed with fix without completely understanding reload logic. Thanks for explanation.
I've replaced fix in this pull request. Now I am replicating `remove` logic in pause, by detaching in progress sends

>Can you elaborate more on what the broken logic is?

`pause` tries to remove sender from `SendGroup.senders`, but if it happens while send is in-flight, assertion fails resulting in panic. And commenting out assertion wont help, because when send completes it will put sender back.

**Comment by tobz** [comment]
> `pause` tries to remove sender from `SendGroup.senders`, but if it happens while send is in-flight, assertion will fails resulting in panic. And removing assertion wont help, because when send completes it will put sender back.

I'll preface this with saying that I realize I touched this code most recently, and so I'm still refreshing myself on all the reasons I wrote it the way that I did, so apologies for asking questions that theoretically I should know the answer to. 😂 

I'm still unclear on why this bug is occurring. The assert in `pause` is there to make sure we're not trying to double pause a sender, because that would imply that the topology had lost track of what components should be in what state. Specifically, the panic itself isn't that the send future encounters an error because we moved it out of the `SendGroup`, but that we tried to `pause` a sender that had already been previously paused.

This change is still papering over that fact by simply not asserting that we actually got back the sender value when we `pause` it... which, yes, solves the panic but doesn't answer the question of why the topology is trying to double pause that specific sender.

**Comment by Zettroke** [comment]
Topology doesn't send pause twice.
When pause arrives, send is in progress and sender is not in place. So assert is failing.

Also fun fact: problem occurs in release mode, not debug

There is debug logs which may help with my lousy explanations)
I have simple topology `sources.input -> transforms.kappa -> sinks.out`
and changing ` transforms.kappa`

image
image

**Comment by tobz** [comment]
> Topology doesn't send pause twice.
When pause arrives, send is in progress and sender is not in place. So assert is failing.

Ah, right! Sorry, I think I'm finally caught up. Right, so we take the `Sender` out of `Option<Sender>` when we actually build the send future and the send is in progress... so of course it won't be there while the send is in progress because the future still owns it.

Thinking it through, I believe your new approach is the correct one. The main constraint we need to uphold is that the sender slot -- `Option<Sender>` -- is `None` after a `pause` command is processed, which this provides. Since the sender slot is already `None` during a send (as we took ownership of the `Sender`), and we only give it back when _we_ poll the send future to completion and get the `Sender` as a result... a detached send has no way to add itself back to the sender slot.

I'd still like to keep the assertion that we aren't double pausing, though. One way we could do that is to have `try_detach_send` return a `bool`, where we return `true` if we actually found a send for the given component and detached it, and `false` otherwise. With that, we would simply assert that we actually detached the send, since we should never be in a send group unless we created a send future for all senders before awaiting `SendGroup::send`.

I'm thinking we may also want to do the same type of assert for `SendGroup::remove`, too, since `pause`/`replace` and `remove` should be mutually exclusive operations, so we wouldn't be removing a paused component, only ever replacing it... but I'll think about that a little more.

**Review by tobz — APPROVED** [review]
This change makes sense to me, and thinking it through, it also seems good to me. Going to get another review on it, though, as now I myself have added/changed code.

**Review by bruceg — APPROVED** [review]

**Pull request merged**
