### PR TITLE
The start of supporting freebsd as a target

### PR DESCRIPTION
**Pull request by jszwedko**
This is a WIP.

Currently requires these changes to the cross build image:

* https://github.com/rust-embedded/cross/pull/620
* https://github.com/rust-embedded/cross/pull/613

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by onedr0p** [comment]
@jszwedko looks like those changed were merged in

**Comment by jszwedko** [comment]
> @jszwedko looks like those changed were merged in

👍 it does, but it doesn't look like they've released the changes as a new image yet.

**Comment by onedr0p** [comment]
Their image is 7 months old, I wonder if they will ever release it 😆

**Comment by jszwedko** [comment]
> Good point, their image is 7 months old, I wonder if they will ever release it 😆
> 
> [cross-rs/cross#542](https://github.com/cross-rs/cross/issues/542)

😄 true, though there has been movement on the repository in recent months so we could see a new image soon 🤞

**Comment by jszwedko** [comment]
Got further with the new cross images, now it is failing due to:

```
  = note: /usr/local/lib/gcc/x86_64-unknown-freebsd12/6.4.0/../../../../x86_64-unknown-freebsd12/bin/ld: warning: libcxxrt.so.1, needed by /usr/local/lib/gcc/x86_64-unknown-freebsd12/6.4.0/../../../../x86_64-unknown-freebsd12/lib/libc++.so, not found (try using -rpath or -rpath-link)
```

**Comment by kellytk** [comment]
I'm beginning the process of building out OpenTelemetry-based observability for a new service written with Rust and running on FreeBSD.

Although I presently lack the bandwidth to contribute code, I'm available for testing and couching usage questions. Can provide quick responses for tight iteration, here or OOB. (kellytk(.)sw-e.org)

I also intend to include tracing in the o11y so bringing FreeBSD support current would add another tester and prospective production user to [that initiative](https://github.com/vectordotdev/vector/issues/1444).

Getting started...

# Environment

* FreeBSD 13.1
* Rust 1.62.1 installed via `rustup` (quarterly pkg is out-of-date for Vector's MSRV)
* `git clone https://github.com/vectordotdev/vector.git` (f64bceffe)

# Building

From Vector's directory, `RUST_BACKTRACE=1 cargo build` errors at:

error: failed to run custom build command for `tikv-jemalloc-sys v0.5.0+5.3.0`

Further details available upon request; summarizing until I know I can be of help and not add noise to the discussion.

**Comment by kellytk** [comment]
May I ask if there's a schedule for undertaking this?  Could an offer to cooperate on the associated (code, dog-fooding) work move that forward?

**Comment by kellytk** [comment]
@jszwedko As heim-rs is the [current blocker](https://github.com/heim-rs/heim/issues/362) and the project appears dormant, would Vector be willing to fork it so I could add support for FreeBSD and continue? (https://github.com/heim-rs/heim/issues/364#issuecomment-1220272475)

**Comment by kellytk** [comment]
@jszwedko May I ask what it means to Vector to support a PR?  If I'm blocked from getting to that point, and Vector could grease the skids with the above request, is that not included?  Due to the unresponsiveness, I'm dangerously close to having to find an alternative Otel solution for FreeBSD.

**Comment by onedr0p** [comment]
Vector can be built without hiem-rs, do you actually need the features it provides?

**Comment by kellytk** [comment]
Not sure.  However, I'm dubious of the value of an incomplete port.

**Comment by onedr0p** [comment]
Personally I use Prometheus and node-exporter for insights into host metrics. I only use Vector for shipping logs, not host/container metrics.

**Comment by jszwedko** [comment]
👍 building without heim could be a good start to at least getting something on FreeBSD.

**Comment by abh** [comment]
@jszwedko  Yeah, it's sad that the "bonus features" are blocking shipping the core competencies of Vector on FreeBSD. :-)

**Pull request closed without merging**
