### PR TITLE
chore: Faster macOS dev builds

### PR DESCRIPTION
**Pull request by leebenson**
Minor PR to improve incremental debug compilation speeds on macOS.

Motivated by https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/

Signed-off-by: Lee Benson <lee@leebenson.com>

### CODE REVIEW

**Review by JeanMertz — APPROVED** [review]
🎉

**Comment by JeanMertz** [comment]
Do we know how/if this impacts non macOS builds?

**Review by jszwedko — APPROVED** [review]
Nice! I have the same question as Jean, but this looks good otherwise.

**Comment by leebenson** [comment]
I couldn't find a lot of material to support consequences on non-macOS platforms, and it's mentioned without warning in the Rust 1.51 [release notes](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information).

I was able to compile a debug build of Vector on Ubuntu 18.04 with Rust 1.51 without errors or obvious differences.

@blt, any footguns here I'm not considering?

**Comment by blt** [comment]
> I couldn't find a lot of material to support consequences on non-macOS platforms, and it's mentioned without warning in the Rust 1.51 [release notes](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information).
> 
> I was able to compile a debug build of Vector on Ubuntu 18.04 with Rust 1.51 without errors or obvious differences.
> 
> @blt, any footguns here I'm not considering?

My understanding is that this is a no-op on any platform other than MacOS, which is fine by me. To my knowledge we also don't need to support migrating `target/` between machines.

**Review by blt — APPROVED** [review]

**Pull request merged**
