### PR TITLE
fix(aws_sqs source): add proxy support to aws_sqs source

### PR DESCRIPTION
**Pull request by fuchsnj**
closes https://github.com/vectordotdev/vector/issues/11020

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Nice! This makes sense to me.

It did prompt me to realize that we aren't using our custom `HttpClient` here (from `src/http.rs`). That client has some additional functionality like logging and emitting metrics. Do you think we could incorporate that client here? I think users might expect to see the same HTTP metrics emitted as they see for other HTTP-based components. Looking at `aws_s3` source using `rusoto` it does appear to use our custom HTTP client so there is some precedent for that even with the AWS SDKs.

**Comment by fuchsnj** [comment]
@jszwedko 
I played around with using our custom `HttpClient`, but it's not really supported. It requires implementing `SmithyConnector` for our `HttpClient`, which specifically states it "should never be implemented". I still went ahead to see what it would look like, and it would require copying parts of the SDK which aren't public, as well as pulling in a few more crates we don't need today. I don't think this is a great idea just for the logging/metrics we are doing today. However, if we really want something like this I think it's out of scope for this PR.

**Review by jszwedko — APPROVED** [review]
👍 thanks for taking a look. I agree, it is out of scope for this PR so we can leave it for later. I was just hoping it might be easy.

Otherwise, looks good! There is one clippy warning.

**Comment by hhromic** [comment]
Just tested this change using the Vector nightly Docker image.
Can confirm the proxy support is working like a charm :)

Thank you very much for the quick implementation, really appreciated.

**Pull request merged**
