### PR TITLE
chore: Improve soak aesthetics

### PR DESCRIPTION
**Pull request by blt**
This commit improves the aesthetics of our soak comments, resolving #10184. The primary change is the conversion of the analysis step away from shell script and into python, allowing the use of pandas, scipy et al to to the statistical analysis the soak tests require. I had intended to do the work in Rust but the ecosystem there is too immature; please forgive my poor python. 

The analysis step has two major changes in its operation. First, we now hide detailed tables below a fold in the posted comment, relying instead on a summary table above the fold to notify about changes in throughput. Second, we use Welch's t-test to measure whether the changes between baseline and comparison are statistically distinct, within a 95% confidence. Above the fold we only show throughput differences for soaks that pass this confidence threshold. 

This commit sets us up for future work. We could, for instance, add outlier detection to our soak tests in the same manner as criterion -- do point fall outside +/- IQR*1.5, Tukey's method -- or improve the confidence of our statistical test further by adding in more replicas of each experiment on different machines. We can also, critically, now consider what adding the soaks as a CI blocker would look like.

### CODE REVIEW

**Review by LEDlastchance — APPROVED** [review]
Ok

**Comment by blt** [comment]
> Ok

Hi @LEDlastchance, thanks for the review but this commit isn't ready to be reviewed. I'm going to cycle your approval out to avoid any confusion.

**Comment by blt** [comment]
TODO:

* must adjust throughput down by core count
* diff table looks weird, why so many 0 bytes?

**Comment by LEDlastchance** [comment]
Yes sir thank you I'm sorry I just want to stop and this to be over so I can move on with my life they start messing with me I'm sure the same people that made this happen and it's very upsetting and unnecessary. Please help me however you can and please hold the person accountable of what's right and wrong isn't no different in America or Japan I mean what kind of world are we building for our children. Thank you

**Comment by bruceg** [comment]
This is a much improved presentation, both the tabular data and the hidden by expandable fine details. Please also add percentages to the deltas, to help understand the significance of the absolute differences. Also consider sorting the differences by the percentage difference, to make visualizing the biggest improvements and regressions faster.

**Review by tobz — APPROVED** [review]
Works for me as-is, but Bruce's suggestions should either be tacked on here or tacked on with an immediate follow-up PR because, yeah, if we're trying to optimize the format, we should optimize the actual "did anything meaningfully change?" aspect, too.

**Comment by blt** [comment]
@bruceg @tobz excellent suggestions.

**Review by JeanMertz — APPROVED** [review]
Sweet!

Does this already include a feature that makes the message as minimal as possible when there are no significant changes, or do we want to tackle that in a follow-up PR?

Either way, I'm happy to see this merged.

**Comment by binarylogic** [comment]
Super small thing. If you remove the space between the numbers and the units (i.e., `554.48KiB`), you won't have double-line rows.

**Comment by 001wwang** [comment]
This looks great to me. The significant change table and collapsible sections improve the readability a ton.

**Comment by blt** [comment]
> Sweet!
> 
> Does this already include a feature that makes the message as minimal as possible when there are no significant changes, or do we want to tackle that in a follow-up PR?
> 
> Either way, I'm happy to see this merged.

It does! If the change is below the 9th percentile the table won't be shown and there will be a small message saying that no regressions were detected.

**Pull request merged**
