### PR TITLE
fix(socket source): Ignore "not connected" after connecting

### LINKED ISSUE #2731: TCP source: "Socket not connected"
When using the socket source with type TCP and creating short-lived connections, vector quickly crashes with the following error: 

```
source{name=in type=socket}: vector::sources::util::tcp: failed to accept socket error=Could not get peer address: Socket not connected (os error 107)
```

I narrowed the configuration down to the following: 
```toml
[sources.in]
  address = "0.0.0.0:5514"
  mode = "tcp"
  type = "socket"

[sinks.blackhole]
  type = "blackhole"
  inputs = ["in"]
  print_amount = 1000
```

I run it as a docker image like so:
`docker run -it --network host -v $(pwd):/etc/vector/config  timberio/vector:nightly-alpine --config /etc/vector/config/config.toml`

And then I send something via netcat, directly closing the connection afterwards. Sometimes it takes a couple attempts, but it does consistently crash at some point. You should definitely be able to reproduce it with something like:
`while true; do echo "hi" | nc -c -v localhost 5514; done`

When I connect to it without the `-c` flag (i.e. keeping the connection open), everything is fine. The error appears to only happen when the connection is closed directly after sending.

Log level trace doesn't reveal any more information, btw.

### PR DESCRIPTION
**Pull request by bruceg**
There is a small window for a client to race the connection handling
code and trigger a spurious error of "Socket not connected". Since
there's not much to realistically do here, just ignore this condition.

Signed-off-by: Bruce Guenter <bruce@timber.io>

Closes #2731

### CODE REVIEW

**Review by lukesteensen — COMMENTED** [review]
It looks to me like the only difference here is that we won't log that type of error. Is that the intent or do we need to ignore the error where it's being propagated?

**Comment by bruceg** [comment]
The intent is to simply drop the error, however the more I think about it, the less I'm convinced this is a bug. The scenario is that the remote connected and then disconnected before this end could get the peer address or otherwise make useful progress on the connection. This would tend to indicate either abuse (ie denial of service type attack) or potentially lost events. In either case silencing the error is the wrong path.

**Comment by binarylogic** [comment]
@bruceg, is there anything left here? Just wondering if we should merge this or close it.

**Comment by bruceg** [comment]
I think this should be closed. It doesn't resolve the original bug, nor does it fix an issue that is actually causing any problems.

**Pull request closed without merging**
