### PR TITLE
feat(sinks elasticsearch): Add compatibility between elasticsearch cl…

### PR DESCRIPTION
**Pull request by gmicouin**
Add compatibility between the elasticsearch client and elasticsearch server in 8.x and after 7.12 (tested from 7.12)

### CODE REVIEW

**Comment by tobz** [comment]
@gmicouin Do you mind providing references to the documentation used to show why this should be valid?

**Comment by gmicouin** [comment]
Hi @tobz !
You can find [here](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/migration.html) an example for the python client to enable the compatibility with elastic v8.

And [here](https://github.com/elastic/elasticsearch-py/blob/2f5e8e25e039db3da9547814d88846f4bcdaabaa/elasticsearch/client/utils.py#L145) the code of official python client which replaces the Content-Type and Accept header by _"application/vnd.elasticsearch+json;compatible-with=7"_

I'm newbie in Rust, perhaps a better way exists to do that ;)

**Comment by tobz** [comment]
@gmicouin No worries, your change is totally valid.

My main question would be: it sounds like, from the PR description, you tested this against Elasticsearch 7.12, but did you also test it against 8.x? Did it not work with 8.x without this change?

From reading the [REST API compatibility](https://www.elastic.co/guide/en/elasticsearch/reference/master/rest-api-compatibility.html#request-rest-api-compatibility) documentation, it appears that there also needs to be an `Accept` header on requests, in addition to `Content-Type` if there's a post body... but we don't send an `Accept` header. I'm trying to understand if the documentation is wrong, or if we're setting ourselves up for some incompatibility down the road.

**Comment by gmicouin** [comment]
@tobz Yes I test this code with Elastic 8.x, and without this change the Elastic server 8.0 does not accept the request.

Yes you're right, I have forgotten the Accept header, because during my tests it was possible to configure it with requests.header.

Do you think it would be possible to configure the Content-Type in the vector.toml ? It would be more generic, what do you think ?

**Comment by tobz** [comment]
> Yes I test this code with Elastic 8.x, and without this change the Elastic server 8.0 does not accept the request.
> 
> Yes you're right, I have forgotten the Accept header, because during my tests it was possible to configure it with requests.header.

@gmicouin OK, great. I'd say that this PR should also be setting the `Accept` header then, as well.

> Do you think it would be possible to configure the Content-Type in the vector.toml ? It would be more generic, what do you think ?

It's technically possible, but it's not a change we would make. Elasticsearch only supports a given set of encodings, and we need to ensure the codec we use to generate bulk requests matches what we send in `Content-Type`, so exposing the ability to override `Content-Type` just makes it easy to misconfigure the sink.

I think what we'd want to do, if anything, is expose a configuration setting that allows setting the version value that gets used in compatibility mode i.e. `compatible_version = 7`, which would then get interpolated in the `Accept`/`Content-Type` headers.

But like I said above, let's do the change to also update the `Accept` header. I still need to figure out what our actual ES compatibility guarantees are, to think about whether this current PR is acceptable as-is or if we need to expose something to allow configuring the compatibility headers (the idea about `compatible_version`).

**Comment by gmicouin** [comment]
Hi @tobz !
It's a good idea this `compatible_version`. I have seen how could I do this implementation about the `Accept`, but I have no knowledge in Rust :s
I think we could do something like this
```
for (header, value) in &self.http_request_config.headers {
  let new_value = &value
  if "Accept".eq(header){
    new_value = &value +"," + "application/vnd.elasticsearch+json;compatible-with=7"
  } else {
    new_value = "application/vnd.elasticsearch+json;compatible-with=7"
  }
  builder = builder.header(&header[..], &new_value);
}
```

But I know this code doesn't compile, and I don't know how do that :s

**Comment by spencergilbert** [comment]
If we're considering adding a `compatibile_version` option, we should consider folding [suppress_type_name](https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#suppress_type_name) into that as well as it's used for compatibility reasons as well.

Going even _further_ we should be able to query the cluster on startup and identify the version from that request and self-configure the sink at runtime, rather than having the user configure ahead of time. I haven't fully thought through the implications of this, and it's certainly a larger change.

**Comment by gmicouin** [comment]
Hi @spencergilbert,
Query the cluster to identify the version is a good idea, but I think this can be have limitations. For security reason, the version api is not authorized for all users. (See [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html).

**Comment by StephenWakely** [comment]
We are closing this for now in favour of coming up with a better way to handling behaviour appropriately according to a specified or detected version of ElasticSearch.

Ref #10342

**Pull request closed without merging**
