### PR TITLE
chore: Convert buffer model check to proptest

### PR DESCRIPTION
**Pull request by blt**
This commit removes our quickcheck implementation from buffer in favor of
proptest, as per #9131. The main change here, other than slimming out code, is
the adjustment to use a tokio runtime in the model test. This was technically
necessary before but we didn't drive into that branch properly to cause
crashes.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Comment by blt** [comment]
Oh neat, test failures with `variant = Disk { max_size: 1, when_full: Block, data_dir: "/tmp/0.Ng26q7qHysng", id: "0" }, actions = [Send(Message { id: 0 }), Recv]`. I _think_ it might be a timing issue but I will follow-up tomorrow.

**Review by spencergilbert — APPROVED** [review]
Neat!

**Review by jszwedko — APPROVED** [review]

**Review by 001wwang — APPROVED** [review]
Cool to see property-based testing outside the classroom.

**Comment by blt** [comment]
I'm going to close this out. There's a bug in disk buffers but we'll need to do more focused work to flush it out and it only impacts shutdowns in the specific circumstance that the property tests discover, which are extreme and unusual.

**Pull request closed without merging**
