### PR TITLE
chore(vrl): revert `parse_grok` delegation to `parse_groks`

### PR DESCRIPTION
**Pull request by fuchsnj**
closes https://github.com/vectordotdev/vector/issues/14060

reverts https://github.com/vectordotdev/vector/pull/13635
reverts https://github.com/vectordotdev/vector/pull/14098

The change to [delegate `parse_grok` to `parse_groks`](https://github.com/vectordotdev/vector/pull/13635) had an unintended regression. It is being reverted since the fix is more involved and we don't want to introduce a breaking change to then break it again.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]

**Review by pablosichert — COMMENTED** [review]
Are we fine with breaking #13534 again?

**Comment by jszwedko** [comment]
@pablosichert good call, we should be careful not to break https://github.com/vectordotdev/vector/issues/13534 again. I thought that was fixed by a separate PR: https://github.com/vectordotdev/vector/pull/13721. I'll test it out locally though.

**Comment by jszwedko** [comment]
The remove empty behavior still looks good on this branch:

```
$ parse_grok!("2020-10-02T23:22:12.223222Z", "(%{TIMESTAMP_ISO8601:timestamp}|%{LOGLEVEL:level})")
{ "timestamp": "2020-10-02T23:22:12.223222Z" }

$ parse_groks!("2020-10-02T23:22:12.223222Z", ["(%{TIMESTAMP_ISO8601:timestamp}|%{LOGLEVEL:level})"])
{ "timestamp": "2020-10-02T23:22:12.223222Z" }
```

**Comment by pablosichert** [comment]
@jszwedko oh neat, forgot that we split it out specifically for that reason!

**Review by pablosichert — APPROVED** [review]

**Pull request merged**
