### PR TITLE
Transmute between vrl value and vector value

### PR DESCRIPTION
**Pull request by StephenWakely**
Experimental branch to see if we can just do a quick transmute betweer Vector Value and Vrl Value.

The main issue is that Vrl Value contains an extra `Regex` variant, which cannot be converted to Vector value. Currently, we convert this to a `Bytes`.

This will cause a segfault when converting a Vrl Array or Object containing a Regex to a Vector Value. 

It is a rare occurrence that someone would set a field in Vrl to a Regex. I am just pushing this to see what it does to the soak numbers, and we can perhaps consider ways to handle Regexes if the numbers seem promising enough.

Signed-off-by: Stephen Wakely <fungus.humungus@gmail.com>

### CODE REVIEW

**Comment by JeanMertz** [comment]
Awesome to see this up here 👍 

> It is a rare occurrence that someone would set a field in Vrl to a Regex. I am just pushing this to see what it does to the soak numbers, and we can perhaps consider ways to handle Regexes if the numbers seem promising enough.

Right, this is the reason why I mentioned we'll want to transmute the wrapped values individually, instead of the `Value` enum wholesome. This way, we can do whatever we want in safe rust without the risk of a segfault.

In this case, my assumption is we can access the values within a container type mutably, and transmute the memory if it's safe (e.g. no regex), but do a safe (but costly) conversion if it's a regex. The latter should almost never happen as you mention, so the cost of that conversion is insignificant, but obviously superiour over a potential segfault.

**Comment by tobz** [comment]
I'm not familiar with the etymology of the different `Value` types here, but is there no way we could actually unify them?

I'm skeptical of a `transmute`-based because now we're talking about potential issues with struct/enum layout that may change between compiler versions, field changes, etc.

**Comment by StephenWakely** [comment]
> I'm not familiar with the etymology of the different `Value` types here, but is there no way we could actually unify them?

It is one option.

The issue is that Vrl has the concept of a Regex type and Vector does not. We could add this Regex to Vector and then just hope Vector doesn't use it anywhere. Vrl can just use that.

**Comment by jszwedko** [comment]
Yeah, as Stephen mentioned, we did discuss that option. We decided to explore this one first since it requires less of a change and we figured we could do it fairly safely with sufficient test coverage.

**Comment by blt** [comment]
I think the posted throughput increases here are a positive step, so I would vote to develop this a little more. I do share in the reservations about transmuting and I am not totally convinced that the memory layout is actually safe to transmute what with padding and all in repr rust. If we do move forward with transmutation I'd like to see us fuzz this aggressively.

**Comment by binarylogic** [comment]
> It is a rare occurrence that someone would set a field in Vrl to a Regex.

Then let's remove support for it. This way we can properly align the value types. Why are we prioritizing support for a feature that is rarely used over this, which is arguably more important?

I'm also not a fan of the safety concerns that others are raising here. And the work to raise confidence (i.e., @blt's fuzzing recommendation) seem like more work than actually doing this work correctly.

**Comment by binarylogic** [comment]
And to clarify, since context is lost here, I'm very happy with this direction as an experiment, which seems to have proved worthwhile. But I would prefer to do the work properly now that we proved it out.

**Comment by jszwedko** [comment]
> > It is a rare occurrence that someone would set a field in Vrl to a Regex.
> 
> Then let's remove support for it. This way we can properly align the value types. Why are we prioritizing support for a feature that is rarely used over this, which is arguably more important?
> 
> I'm also not a fan of the safety concerns that others are raising here. And the work to raise confidence (i.e., @blt's fuzzing recommendation) seem like more work than actually doing this work correctly.

We aren't prioritizing support for setting regexes to event fields as a feature, we would just need to do the work to separate out regexes so that they can still be used as `Value`s elsewhere in VRL like arguments to `parse_regex` and as variables, but not as event fields. I would be curious to explore that a bit more though. cc/ @StephenWakely @JeanMertz rather than unifying the value could we use a different type to represent function parameters, variables, etc. that would be enum of `vector_core::Value` _or_ `Regex`?

I think fuzzing this would be relatively straight-forward so I don't anticipate that being a ton of work if we do pursue this route.

**Comment by StephenWakely** [comment]
> Then let's remove support for it. This way we can properly align the value types. Why are we prioritizing support for a feature that is rarely used over this, which is arguably more important?

This would be a more complicated change. It's fairly simple to avoid the following:

```
.regex = r'.*'
```

But harder to avoid this:

```
.regex = { "regex": r'.*' }
```

Or, since it should be possible to assign regexes to variables:

```
variable = { "regex": r'.*' }
.regex = variable
```

Certainly not impossible, and it may be a good idea to add that restriction.

However, this doesn't get over the possibility that a regex could sneak in to a path due to a bug, and since the cost of not handling it is a segfault, just to be safe we should handle it as this PR does anyway.

**Comment by JeanMertz** [comment]
To give a bit more context:

I already did a few experiments with allowing VRL to keep using regexes, but not allow then in Vector, without having to do unsafe operations. The gist of it is that it just isn't possible to do so without incurring allocation costs when converting from one `Value` type to another _or_ without introducing a type-hole in Vector by having to `panic` when pattern-matching over a new `Value` type that would include a `Regex` variant.

This is because the Value type in VRL is used for _both_ internal variables _and_ field values (or, put another way, `Value` is _the_ main type when it comes to types in VRL).

Assigning a regex to a variable is definitely something we want to support, take for example this (pseudo) use-case when it comes to iteration:

```coffee
my_regexes = [r'aaa', r'bbb']

for_each(my_regexes) -> { |regex| parse_regex(.foo, regex) }
```

These are use-cases customers have asked for, and are using currently (without iteration, since that hasn't landed yet).

We can reject assigning regexes to event fields (it's useless anyway, since we convert them to a string), and in fact we rejected that back in the day, we just never ported that logic over to the new parser/compiler. But that doesn't solve the problem this PR (or any future PR based on further discussion) wants to solve, which is to avoid allocation costs when converting between the two `Value` types.

> rather than unifying the value could we use a different type to represent function parameters, variables, etc. that would be enum of `vector_core::Value` _or_ `Regex`? We would want to do this in a way that still feels "ergonomic" in VRL.

Perhaps, but it would be quite a big undertaking that we'd (1) have to plan for, and (2) probably want to have an RFC for, given the impact this change will have on the code, and I don't have a full picture right now to say with confidence that this isn't going to cause issues in some places.

The solution of having an enum of `core::Value` and `Regex` isn't going to work (it's one of the experiments I did) because as demonstrated above, you still need to be able to store a regex in a collection.

---

As I said yesterday in the check-in before I had to sign off, I think this PR proved that there is performance gains to be made here, but the next step takes more than a few hours to complete (whether it's making this PR production-worthy, or going with an alternative solution entirely). I considered the 1-day experiment a success, and suggest we now shift our focus to something we already agreed on, the VM work, while also planning work to create an RFC and have a discussion there on how we can unify/solve the value-conversion cost we're currently paying.

**Comment by JeanMertz** [comment]
One more addition:

The transmute solution I originally proposed was to do the transmutation on a _variant level_, that is, instead of:

```rust
impl From<Value> for vrl_core::Value {
    fn from(v: Value) -> Self {
        unsafe { std::mem::transmute(v) }
    }
}
```

We'd do:

```rust
impl From<Value> for vrl_core::Value {
    fn from(v: Value) -> Self {
		match v {
			Value::Integer(v) => vrl_core::Value::Integer(v),
			Value::Object(v) => {
				/* do some sanity checks here */
				
				for v in v.values_mut() {
					// do transmutation here
				}
			}
			// ...
    }
}
```

The example isn't complete, but the idea is to only transmute when needed, for Rust's stdlib types. There's more work to do here, and I'm not entirely sure my suggestion is even possible, but the goal would be to wrap `unsafe` over the smallest types possible.

All of this still needs loads of (fuzz) tests and scrutiny, so I'd also heavily favor a non-unsafe solution, but as mentioned before, this was the quickest solution we could think of to validate how much conversion cost we're paying in actual use-cases (and this PR shows that it's quite a heavy cost, so it's worth coming up with a/any solution).

**Comment by JeanMertz** [comment]
Also, to put a finer point on what we're actually trying to solve, it's these two conversions right here that are causing the allocations we'd like to get rid of, all other conversions are allocation-free:

https://github.com/vectordotdev/vector/blob/caebaf3fe790a2e7093324437782f05b90d3b9e4/lib/vector-core/src/event/value.rs#L306-L307

**Comment by binarylogic** [comment]
> Assigning a regex to a variable is definitely something we want to support

I'm not sure I agree. Your example can be accomplished without iteration:

```
parse_regex(.foo, r'aaa') ?? parse_regex(.foo, r'bbb')
```

And I believe the above syntax is easier to read and manage. But it doesn't really matter. This is a contrived example and we need to hear it from customers first. I don't understand why we are prioritizing contrived regex examples over the problem this PR is addressing, which is much more important.

> but it would be quite a big undertaking that we'd (1) have to plan for, and (2) probably want to have an RFC for

Then that's what we should do.

> I considered the 1-day experiment a success, and suggest we now shift our focus to something we already agreed on, the VM work, while also planning work to create an RFC and have a discussion there on how we can unify/solve the value-conversion cost we're currently paying.

Agree

**Comment by jszwedko** [comment]
I'll note we have seen users want to assign regexes to variables just to name them, but I'd be ok considering whether we want to drop this support, temporarily, in the name of performance until we can find a better modeling of VRL values that doesn't impact performance. This could be discussed in an RFC of the "right approach" here.

Regarding whether to push this work forward now, or do an RFC for the right approach, I feel we should consider pushing the work forward as-is. It has a significant performance impact, as we can see. I think fuzzing this to improve confidence should be a relatively straight-forward process. If this is something we think we could finish by the end of the week, I'd opt to push it forward, reap the performance benefits, and then follow up later on a better approach that doesn't require transmutation.

**Comment by blt** [comment]
> I think fuzzing this to improve confidence should be a relatively straight-forward process. 

What I'd want from a fuzzing setup may or may not be straight-forward, before I'd sign off on a transmute that I'm not confident in. We need:

* fuzzing targets with representative coverage of the transmutation 
* seeds to drive initial bootstrap
* integration with oss-fuzz / clusterfuzz / clusterfuzzlite to get ongoing CI integrated fuzzing
* support ARM ideally 

My concerns here are to do with layout padding that might change without notice, differ between architectures and compiler versions. Fuzzing one time won't be enough and we'll need a fair bit of CPU time per change -- merge to master? -- to get enough coverage to make me confident in the result.

**Comment by blt** [comment]
FWIW, I agree with Jean. The 1-day experiment is a success and if someone with slack time has an interest in keeping this moving forward that I'm okay with, but we should start in on the VM work.

**Comment by JeanMertz** [comment]
> This is a contrived example and we need to hear it from customers first. I don't understand why we are prioritizing contrived regex examples over the problem this PR is addressing, which is much more important.

I'm not prioritizing anything, I'm stating that we _have_ heard from customers who do this (or want to do iteration). I just don't have those examples at hand (one downside of having a chat support channel is that the information you see passing through is fleeting and hard to find again).

One more point I want to make, which I haven't made because I don't think it's as heavy as a counter-point, is that I can see other observability-related types being introduced down the line, for example a "duration" type. That one too might not have a Vector counter-type, so the solution of not allowing regex to be assigned to a variable — aside from it just being weird that a language has these constraints because of external factors — would not scale well, as it might mean we're going to have to put constraints on other types as well.

As far as I'm concerned, I think we're mostly aligned here; this work is important, the experiment has proven that out, but to get it production-ready is more effort than I'd favour doing without proper planning/RFCing, and we already have another piece of work agreed on that has an even bigger impact, so it makes sense to me to start that work first, and circle back to this later (where "later" can be in three weeks time, if we deem it important enough for someone else to work on it while Stephen continues pushing the VM work forward).

**Pull request closed without merging**
