### PR TITLE
enhancement(performance): Try out snmalloc

### PR DESCRIPTION
**Pull request by jszwedko**
Pushing it up to compare with jemalloc and mimalloc.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by mjp41** [comment]
> I added libatomic1, to try to fix:
> 
> ```
> libatomic.so.1: cannot open shared object file: No such file or directory
> ```
> 
> I can build locally, but seeing an issue with `ALLOC` still referencing jemalloc.
> 
> Couldn't fix an obvious ref to it within source. Could it be a cache thing?

It's because it is merging with #10459, which adds the jemalloc reference, and running CI on the merge. 

I would be super interested to see how the performance for snmalloc is for your scenario.

**Comment by leebenson** [comment]
> It's because it is merging with #10459, which adds the jemalloc reference, and running CI on the merge.

💡 That makes sense! - thanks @mjp41. 

I'm surprised we didn't see it when introducing an explicit allocator previously, but I assume the distinction there is that we were adding it against the backdrop of the default, rather than overlaying snmalloc -> jemalloc.

@blt, @jszwedko - is there a quick path for fixing this, or is that part of #10455?

**Comment by jszwedko** [comment]
I rebased to resolve the conflict. I'm curious to see what it looks like 🤞

**Comment by blt** [comment]
Interesting results from the soaks. All improvements over jemalloc save for `splunk_transforms_splunk3`. The relevant vector config is [here](https://github.com/vectordotdev/vector/blob/190d453d8997af10e384af6a82139b834de0b5ae/soaks/tests/splunk_transforms_splunk3/terraform/vector.toml). The `splunk_hec_route_s3` also saw a serious drop and does similar routing, though it doesn't show in the change table for as it just _barely_ squeaks in under the allowable drift. 

I would be willing to hazard a guess that snmalloc interacts poorly with routing.

**Comment by mjp41** [comment]
> I would be willing to hazard a guess that snmalloc interacts poorly with routing.

Could you expand a bit by what this means?   What kind of allocation patterns are in that example?

**Comment by binarylogic** [comment]
> though it doesn't show in the change table for as it just barely squeaks in under the allowable drift

It might be worth adjusting this threshold if we think it warrants being raised in this PR.

**Comment by blt** [comment]
> > I would be willing to hazard a guess that snmalloc interacts poorly with routing.
> 
> Could you expand a bit by what this means? What kind of allocation patterns are in that example?

Ah yes, of course. So when I say routing I'm referring to the [route](https://vector.dev/docs/reference/configuration/transforms/route/) transform, source code [here](https://github.com/vectordotdev/vector/blob/21e252598300e0777ca412f0ae72e36b3dd3b1fb/src/transforms/route.rs). What differs between the vector configurations that show an improvement and those that don't is the presence of the route transform. It's not obvious, from just reading the source, how the allocation pattern is materially different. 

Our process for reproducing these results is documented [here](https://github.com/vectordotdev/vector/tree/master/soaks) if you'd like to give it a shot on your system. The relevant command would be something like:

```
> ./soaks/soak.sh --local-image --soak splunk_transforms_splunk3 --baseline a32c7fd09978f76a3f1bd360c3a8d07a49538b70 --comparison be8ceafbf994d06f505bdd9fb392b00e0ba661f2
```

from project root. This runs vector in an isolated environment on your host; a similar setup can be run directly on your host, but vector needs to be built and the configuration referenced above will need to have port numbers and what not adjusted. 

Also, @lukesteensen, I think you might be the most expert on the route transform these days? I wonder if anything stands out to you.

**Comment by blt** [comment]
> > though it doesn't show in the change table for as it just barely squeaks in under the allowable drift
> 
> It might be worth adjusting this threshold if we think it warrants being raised in this PR.

Right now the threshold is the default, just over 8%. The lower we go the more potentially noisy the regression detection will be, so it's a tradeoff between noise and slow, barely perceptible regression. REF https://github.com/vectordotdev/vector/issues/10493

**Comment by lukesteensen** [comment]
The main thing of note about the way route is currently implemented is that it involves more copies and more channel hops than would be ideal. 

For example, this bit of config: 

```toml
[transforms.container_type]
type = "route"
inputs = ["timestamp_field"]
[transforms.container_type.route]
service = '.attrs.c2cContainerType == "service"'
ingress = '.attrs.c2cContainerType == "ingress"'
other_sidecar = '.attrs.c2cContainerType != "service" && .attrs.c2cContainerType != "ingress"'
```

expands to three `filter` transforms, each running one of those conditions. So that means we're copying every event to fan out to each of those nodes, then running the filters and forwarding to their individual outputs.

So I'm not sure that `route` has any terribly unique allocation patterns, but it is likely to allocate a bit more heavily than other configurations.

**Comment by blt** [comment]
Once https://github.com/vectordotdev/vector/pull/10730 is merged we should rebase this PR and try again. It's possible that the one down measurement is a noise problem.

**Comment by blt** [comment]
Interesting. So per [this table](https://github.com/vectordotdev/vector/pull/10451#issuecomment-1010355850) the use of snmalloc isn't uniformly positive. Artifact plot: 

splunk_hec_route_s3

**Comment by blt** [comment]
@lukesteensen I'll be very interested to see what happens with this if you're able to remove some excess copying from the route transform.

**Comment by lukesteensen** [comment]
> I'll be very interested to see what happens with this if you're able to remove some excess copying from the route transform.

This is in master as of 3ce45b409f649da484e219303bda3da6df4cca6e, so we should be able to rebase and see how it looks.

**Comment by blt** [comment]
> > I'll be very interested to see what happens with this if you're able to remove some excess copying from the route transform.
> 
> This is in master as of [3ce45b4](https://github.com/vectordotdev/vector/commit/3ce45b409f649da484e219303bda3da6df4cca6e), so we should be able to rebase and see how it looks.

Neat. I'll get this rebased and we'll see.

**Comment by blt** [comment]
Hmm, still not a uniformly positive result and bad yet for `splunk_hec_route_s3`.

**Comment by binarylogic** [comment]
That's a shame, because the improvements are nice. Do you have any sense for why? Or changes we can make/are making that would eliminate those regressions?

**Comment by blt** [comment]
> If someone can send me a `perf` trace of one of the regressing examples, I can look at what snmalloc bits are being hit.

@mjp41 I'll get these prepared for you. Thanks!

**Comment by blt** [comment]
I've prepared a run of release vector at 9cad381 with debug symbols left in, using [these configs](https://gist.github.com/blt/93498dddc7b0f0a3ca76c0c82652074c). The `http_gen` and `http_blackhole` are from [this project](https://github.com/blt/lading), at 1224888ad643ad7525aac8816391ad79c21ef544. 

Each of the programs necessary to reproduce these results were run like so:

```
> firejail --noprofile --cpu=1 ./target/release/http_gen --config-path ~/consider-snmalloc/http_gen.yaml

> firejail --noprofile --cpu=0 ./target/release/http_blackhole --config-path ~/consider-snmalloc/http_blackhole.yaml

> perf record --compression-level=22 --call-graph=dwarf ./target/release/vector --config ~/consider-snmalloc/vector.toml
```

Unfortunately the `perf.data` is 50MB and too large to attach here. I'd be happy to email it to you if you'd like. The capture was done for a 10 minute period, flamegraph:

vector-flamegraph

**Comment by binarylogic** [comment]
Hmm, getting closer. Those improvements are enticing.

**Comment by mjp41** [comment]
That looks less good than before.  Different baseline?

**Comment by blt** [comment]
> That looks less good than before. Different baseline?

Hmm, that is pretty rough. Yes, different baseline. The regression detector compares the tip of master branch with the tip of each PR, so the comparisons in this run are between:

* https://github.com/vectordotdev/vector/commit/290fbd4f0849e1b9b8496dd1afd050a6ba7dc4d6 
* https://github.com/vectordotdev/vector/commit/efedd3da517930cbac1f33a9680d1f08857e9255

**Comment by mjp41** [comment]
FYI, I have just bumped the snmalloc-rs package to the latest snmalloc, there are some perf improvements in there, so might be worth revisiting this.

**Comment by mjp41** [comment]
Sorry, I see I broke the `build_cc` feature, I have a PR to fix https://github.com/SchrodingerZhu/snmalloc-rs/pull/168.

**Comment by jszwedko** [comment]
Thanks for looking and the quick fix @mjp41 ! I'll try out that fix when it is released.

**Comment by mjp41** [comment]
> Thanks for looking and the quick fix @mjp41 ! I'll try out that fix when it is released.

FYI, the new release 0.3.1 contains this fix.

**Comment by jszwedko** [comment]
Thanks @mjp41 ! I bumped it. I'm curious to see any differences.

**Comment by jszwedko** [comment]
Hmm, looks like we hit some new compilation issues:

```
  error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "snmalloc/src/snmalloc" "-Wall" "-Wextra" "-O3" "-mcx16" "-fno-exceptions" "-fno-rtti" "-g" "-fomit-frame-pointer" "-fpermissive" "-ftls-model=initial-exec" "-o" "/home/runner/actions-runner/_work/vector/vector/target/debug/build/snmalloc-sys-d4d86f840e77d646/out/snmalloc/src/snmalloc/override/rust.o" "-c" "snmalloc/src/snmalloc/override/rust.cc" with args "c++" did not execute successfully (status code exit status: 1).
```

https://github.com/vectordotdev/vector/runs/6801746251?check_suite_focus=true

**Comment by mjp41** [comment]
Could you try forcing it to C++17?  It looks like the compiler might not support C++20?  This can be done by setting:
  `usecxx17`

I will try to update the `build_cc` feature logic to detect that in a PR, but I won't be able to try that for a few days.

**Comment by jszwedko** [comment]
Thanks @mjp41 ! That did the trick. Got some numbers this time which do appear better than last time, but still worse than jemalloc for our allocation patterns, seemingly 🤔

**Comment by mjp41** [comment]
> Thanks @mjp41 ! That did the trick. Got some numbers this time which do appear better than last time, but still worse than jemalloc for our allocation patterns, seemingly 🤔 

Interesting. Thanks for trying

**Comment by jszwedko** [comment]
Closing this since we can always open a new PR if we want to recheck snmalloc against jemalloc for our workloads.

**Pull request closed without merging**
