### PR TITLE
fix(aws_s3 sink): ship final batches when shutting down

### PR DESCRIPTION
**Pull request by tobz**
This PR fixes the behavior of the S3 sink by ensuring that the main task does not shut down until the I/O task shuts down, and that the I/O task only shuts down when it has processed all requests.

Prior to this, exiting the process (via something like Ctrl-C) would lead to in-flight batches never being fully sent, because while the batcher would recognize that it needed to emit them, the I/O task never had a chance to send them.

Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Just confirming, will this timeout after a period of time? For example, the `vector` source has a [`shutdown_timeout_secs` option](https://vector.dev/docs/reference/configuration/sources/vector/#shutdown_timeout_secs) that defaults to `30`.

**Comment by tobz** [comment]
@binarylogic Normal graceful shutdown behavior should still apply i.e. if the sink will still waiting to send all of its batches, and Vector had reached the 60 second mark trying to shut down, it would just do so forcefully.

**Review by blt — APPROVED** [review]
Makes good sense to me. Would you be willing to add the same fix to the datadog logs sink please?

**Comment by tobz** [comment]
Can do.

**Comment by lukesteensen** [comment]
Agree this looks good, just want to note for context that we do have our own [shutdown system](https://github.com/vectordotdev/vector/blob/5c702182e39e351406e420a4b7bcb6692f77ae97/src/shutdown.rs) that's currently focused around sources. Whether or not it makes sense to evolve/improve that to cover sinks as well is something we can consider as we work through these redesigns.

**Comment by tobz** [comment]
Nah, the system we have is fine.  This problem was purely about coordination between two intertwined tasks, not a deficiency in our approach to shutdown sources and let their closure cascade to downstream components.

**Pull request merged**
