### PR TITLE
docs(splunk_hec source): add info about endpoints

### PR DESCRIPTION
**Pull request by davidhuie-dd**
Confusion around this source came up in Discord. A user incorrectly thought that the root HTTP path should be used for sending events. Reading the docs, that's a valid interpretation given that we don't mention the specific endpoints to use. This change mentions all three endpoints in the the description 😄

### CODE REVIEW

**Comment by neuronull** [comment]
I don't know much about this source but, if I'm understanding correctly that these endpoints would be specified in a vector config file, should we check for a match with one of them and flag a warning or stop the source, if the endpoint is mis configured ? Or am I misunderstanding it?

**Review by spencergilbert — APPROVED** [review]

**Comment by spencergilbert** [comment]
> I don't know much about this source but, if I'm understanding correctly that these endpoints would be specified in a vector config file, should we check for a match with one of them and flag a warning or stop the source, if the endpoint is mis configured ? Or am I misunderstanding it?

Ah, pretty sure it's the equivalent of the `datadog_agent` endpoints we expose. It's not configured by the user, but they may need to know the path to send to it properly.

**Comment by neuronull** [comment]
> Ah, pretty sure it's the equivalent of the `datadog_agent` endpoints we expose. It's not configured by the user, but they may need to know the path to send to it properly.

Ohhh that makes a lot more sense 😄 

I wonder if we could borrow some of the wording from

https://vector.dev/docs/reference/configuration/sources/datadog_agent/#multiple_outputs

, to make it more clear that these endpoints being exposed, should be used as the inputs to other components.

**Comment by spencergilbert** [comment]
🤔 it still has a single `output`, it's more akin to [these URLs](https://vector.dev/docs/reference/configuration/sources/datadog_agent/#configuring-the-datadog-agent)

**Comment by neuronull** [comment]
Oh I see. TIL some things about splunk hec 😆 
I suppose if users have an understanding of splunk hec already, they will understand what to do.

**Review by neuronull — APPROVED** [review]

**Comment by davidhuie-dd** [comment]
> Ah, pretty sure it's the equivalent of the datadog_agent endpoints we expose. It's not configured by the user, but they may need to know the path to send to it properly.

Yeah, exactly. If you're configuring an endpoint for Splunk HEC, like in the Vector Splunk HEC *sink*, you need to specify the the exact path.

**Review by StephenWakely — APPROVED** [review]

**Pull request merged**
