### PR TITLE
enhancement(datadog_metrics sink): Add acknowledgements support

### LINKED ISSUE #7520: Add acknowledgement support to `datadog_metrics` sink
Other metrics sinks may fall out easily from this work.

This depends on #6045 due to issues in the metrics buffer.

Ref #7337

### PR DESCRIPTION
**Pull request by bruceg**
As there are no integration tests for this sink, this is untested.

After trying a couple of more incremental approaches, I gave up on doing something smart with the metadata, as it would require a lot of work up front for this one metric sink. It'll have to wait for #6045

Closes #7520

Signed-off-by: Bruce Guenter <bruce.guenter@datadoghq.com>

### CODE REVIEW

**Review by tobz — APPROVED** [review]
Looks reasonable to me.

**Comment by binarylogic** [comment]
Could you open an issue for this?

> After trying a couple of more incremental approaches, I gave up on doing something smart with the metadata, as it would require a lot of work up front for this one metric sink. It'll have to wait for #6045

And then we can block it on #6045

**Review by blt — APPROVED** [review]

**Comment by jszwedko** [comment]
I was expecting docs changes here to indicate this sink now supports acknowledgements. Is that something that is tracked elsewhere?

**Comment by bruceg** [comment]
> I was expecting docs changes here to indicate this sink now supports acknowledgements.

Since the main docs for that haven't landed yet, I will make the appropriate changes there. #7412

**Comment by jszwedko** [comment]
> > I was expecting docs changes here to indicate this sink now supports acknowledgements.
> 
> Since the main docs for that haven't landed yet, I will make the appropriate changes there. #7412

Aha 👍 I missed that issue.

**Pull request merged**
