### PR TITLE
docs(vrl): add documentation for punycode encoding functions

### PR DESCRIPTION
**Pull request by esensar**
Related: https://github.com/vectordotdev/vrl/pull/672

### CODE REVIEW

**Review by hestonhoffman — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Thanks @esensar ! I realized this one and #19795 won't pass until we update VRL. I'll approve for now and we can merge once VRL is updated.

**Comment by jszwedko** [comment]
@esensar apologies, do you mind merging master into this and your other PR? I tried to but it doesn't look like I have [access to push to this branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by esensar** [comment]
I have just realized that I have messed up the history of this branch yesterday. Do you want me to force push, or make another PR, or is this fine? I guess you are squashing, so it is probably okay to leave it as is, but let me know if you need me to make some changes.

**Comment by jszwedko** [comment]
@esensar no worries! We do squash PRs when merging so the branch history doesn't matter too much.

**Pull request merged**
