### PR TITLE
fix(kubernetes platform): Fix binfmt exclusion in Helm chart

### LINKED ISSUE #6842: function "statvfs" call failed: Too many levels of symbolic links
### Vector Version

```
version="0.12.1" git_version="v0.12.1" released="Fri, 12 Mar 2021 21:27:28 +0000" arch="x86_64"
```

### Vector Configuration File

install vector-agent by helm with default config in k8s.

[the helm values.yaml](https://github.com/timberio/vector/blob/master/distribution/helm/vector-agent/values.yaml)

### Debug Output

main error

```
vector::sources::host_metrics: Failed to load partition usage data. mount_point="/host/proc/sys/fs/binfmt_misc"
error=FFI function "statvfs" call failed: Too many levels of symbolic links (os error 40) internal_log_rate_secs=60
```

while enter this pod:

```
# kubectl exec -it vector-agent-5b45m -- bash                                                                                                  
root@vector-agent-5b45m:/# ls /host/proc/sys/fs/binfmt_misc
ls: cannot open directory '/host/proc/sys/fs/binfmt_misc': Too many levels of symbolic links
```

details:

https://gist.github.com/zzswang/d9956a3934cea1703b4c35b3603f0b30

### Additional Context

k8s was setup on PVE's kvm, not sure if it is related to this error.

### PR DESCRIPTION
**Pull request by bruceg**
Signed-off-by: Bruce Guenter <bruce.guenter@datadoghq.com>

Closes #6842

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks!

**Comment by jszwedko** [comment]
@bruceg is this good to go? Or did you want another review?

**Review by StephenWakely — APPROVED** [review]
Looks good to me.

Just noting this is documented on the [website](https://vector.dev/docs/reference/configuration/sources/host_metrics/). I wonder if we should amend that to note that this workaround is now included by default in the helm chart?

**Comment by spencergilbert** [comment]
> Just noting this is documented on the [website](https://vector.dev/docs/reference/configuration/sources/host_metrics/). I wonder if we should amend that to note that this workaround is now included by default in the helm chart?

I'd say that makes sense - it's certainly possible that people aren't using our chart/resources so it may be nice to still document it, or it may apply in other environments like running under Nomad

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
