### PR TITLE
chore(deps): remove some unused deps

### PR DESCRIPTION
**Pull request by pront**
## Summary

Guided by `cargo machete`

## Change Type
- [ ] Bug fix
- [ ] New feature
- [x] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## How did you test this PR?

Ran all features workflow.

## Does this PR include user facing changes?

- [ ] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [ ] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist
- [ ] Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- [ ] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

### CODE REVIEW

**Review by pront — COMMENTED** [review]
/ci-run-component-features

**Review by pront — COMMENTED** [review]
/ci-run-component-features

**Review by jszwedko — COMMENTED** [review]
If CI, and in particular `check-component-features` passes 👍 

@neuronull previously tried this in https://github.com/vectordotdev/vector/pull/19327 and ran into a wall though.

**Comment by pront** [comment]
> If CI, and in particular `/ci-run-component-features` passes 👍

It passed. There were some problems with deps used in macros so I left those in.

**Review by pront — COMMENTED** [review]
/ci-run-component-features

**Comment by pront** [comment]
https://github.com/vectordotdev/vector/actions/runs/12298944271

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
