### PR TITLE
enhancement(unit tests): Add testing for component specification features

### LINKED ISSUE #9227: Set up a mechanism for unit testing component spec compliance
With the demise of #9110 we should develop a mechanism for unit testing component spec compliance. This will encompass the following parts:

1. Enhance the `emit!` macro when in test mode to record the actual internal events emitted in a common format (ie JSON) in a buffer that can be per-test segmented buffer. This may require that all internal events also implement `Serialize`.
2. Devise a mechanism for segmenting emitted logs and metrics into individual tests. Some ideas are a thread-local receiver or attaching an ID unique to the test run to each record that can later be extracted.
3. Set up tests to run compliance check functions after each unit test to ensure the right events are emitted.

### PR DESCRIPTION
**Pull request by bruceg**
This is an early-look at this component test framework. I would appreciate feedback on what I'm doing with the `thread_local` stuff in `lib/vector-core/src/metrics/mod.rs`. It's pretty horrible, but I all the other things I tried died painful deaths in lifetime rule violations. I hope to try something similar for internal logs (a thread-local recorder), so if there's a better way of doing it, I'd like to know it.

Closes #9227

### CODE REVIEW

**Comment by bruceg** [comment]
Thanks @tobz for steering me towards a simpler (and much less ugly) implementation, that has the added bonus of actually being at least closer to correct. The magic now lives in `VectorRecorder`, which is stored globally much the same as before (smaller diff from the master branch).

**Comment by tobz** [comment]
Agreed, this looks a lot more succinct now.  Good work. 👍🏻

**Comment by bruceg** [comment]
This should be complete for a first pass implementation, and ready for final review and use in other components. A second effort could do the same thread local switch magic to the internal logs recorder to ensure output logs match the spec, but the event parser will also catch that, so it's likely not worth it.

**Review by tobz — APPROVED** [review]
This seems good enough to start wiring up.  👍🏻

**Comment by JeanMertz** [comment]
Note that a user on Discord thought this was a user-facing change to our Vector unit tests, given the `enhancement` commit type. I suppose we should have marked this as `chore` instead, since it's about Vector internals.

**Comment by jszwedko** [comment]
Ah, yeah, the `unit tests` scope is about Vector's unit test feature. You can use the `tests` scope for internal Vector tests.

**Pull request merged**
