### PR TITLE
chore(ci): Use free OSS 4 vCPU runners

### PR DESCRIPTION
**Pull request by jszwedko**
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/ announced
larger default runners for OSS projects. This should avoid our need to use the paid 4 vCPU runners
(previously they were 2 vCPU).

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

### CODE REVIEW

**Review by neuronull — APPROVED** [review]

**Comment by kapilsinha** [comment]
Noticed that most builds (certainly all nightly, and even custom builds e.g. https://github.com/vectordotdev/vector/actions/runs/7833275067/job/21374004966) take over an hour to complete. Curious, how sizable a speed-up would there be by increasing CPUs?
Also noticed that there is no caching step, so the initial setup seems to take the lion's share of the time. Is caching something the team has tried before?

**Comment by jszwedko** [comment]
> Noticed that most builds (certainly all nightly, and even custom builds e.g. https://github.com/vectordotdev/vector/actions/runs/7833275067/job/21374004966) take over an hour to complete. Curious, how sizable a speed-up would there be by increasing CPUs? Also noticed that there is no caching step, so the initial setup seems to take the lion's share of the time. Is caching something the team has tried before?

Thanks for the thoughts @kapilsinha ! We have looked into caching before using sccache but removed it because it was causing issues. We'd also like to look into building "build images" with cached build dependencies since we spend a good amount of time running `apt update` and friends.

Also, we aren't as sensitive to the build times of the nightly and custom build workflows because those run infrequently ("nightly" for the nightly build and on-demand for custom builds) rather than as part of CI on pull requests. The bulk of the time of those builds, though I haven't looked closely recently, is in the linking stage so increasing CPU count wouldn't help with that

**Comment by kapilsinha** [comment]
@jszwedko +1 on the build images, that makes a lot of sense 
If linking eats up a lot of time, does using a faster linker (I know the mold linker is now MIT licensed and works well on Linux) help?

Frustrated with local build times (especially with proc macro heavy crates like async-graphql), I have modified the compiler itself and built some light tooling around it to speed up local incremental builds. 12% speed-up for vector.dev ‘cargo check’ out of the box:
image

I understand this may not be the right channel — so I had made a discussion post — but please free to redirect me elsewhere!

**Review by jszwedko — COMMENTED** [review]
/ci-run-all

**Review by jszwedko — COMMENTED** [review]
/ci-run-all

**Review by jszwedko — COMMENTED** [review]
/ci-run-all

**Review by jszwedko — COMMENTED** [review]
/ci-run-all

**Review by pront — APPROVED** [review]

**Pull request merged**
