### PR TITLE
fix(http source): Ensure http server will accept non-utf8 data

### PR DESCRIPTION
**Pull request by fpytloun**
This is same behavior as http_client, non-utf8 data are being replaced. Otherwise http server returns Bad Request when there are non-utf8 characters in data.

Related: https://github.com/vectordotdev/vector/issues/11577, https://github.com/vectordotdev/vector/issues/10571

### CODE REVIEW

**Comment by neuronull** [comment]
Thanks  for the contribution! And for linking that audit issue.

As that audit issue suggests, we have done this in the past.

Here is a relatively recent example: https://github.com/vectordotdev/vector/issues/11577

I think this is a good addition to the `http_server` source.

In the long run, we should ideally handle this in the JSON codec and then wouldn't need to have to handle it explicitly in each component.

@fpytloun , would you mind adding a test similar to https://github.com/vectordotdev/vector/pull/10858/commits/b133f7f8fba15ee95cc3bcefbc7fcdcadb9e29fd

, to  validate the desired behavior?

**Comment by fpytloun** [comment]
@neuronull I tried to add the test as best as my poor Rust skill allows, can you please verify eventually help to fix?

**Comment by neuronull** [comment]
Apologies for not asking for this earlier @fpytloun , but would you be able to provide some more details about the Bad Request rejection you are seeing that prompted this change? What input is being provided, to receive that error, and what does the error look like exactly?

The change to use the lossy function call should just be altering the content of the byte stream we decode, but without the lossy function, non utf-8 data should still be being accepted into the byte array by the extend from slice function.

**Comment by neuronull** [comment]
Thanks for that extra context @fpytloun.

We're discussing internally the ideal way to handle this.

As it is, there could be users passing through non utf8 , and generally speaking we want to make the lossy approach configurable.
Will get back to you soon with the consensus.

But as a preview, we'd be requesting that this PR be altered to take a more holistic approach to how we handle non utf8 vs utf8 , throughout the project, and to that effect would translate to a larger set of changes.

**Comment by fpytloun** [comment]
@neuronull I think that ideally this should be an option for decoder or two separate decoders (json vs json_lossy), then it would work for all sources I suppose 🤔

**Comment by neuronull** [comment]
> @neuronull I agree that it's not good that there's no unified approach. In this case I think ideally this should be an option for decoder or two separate decoders (json vs json_lossy) so user can choose proper behavior. Also then it would work for all sources I suppose 🤔

Yep, codecs is the idea!

**Comment by jszwedko** [comment]
Hi @fpytloun !

After some more discussion we think we've settled on adding a new option for lossy decoding for the JSON codec:

```
codec.decoding.json.lossy = true|false
```

This will allow us to avoid breaking existing use cases and step us closer to the UX around byte handling that we want to have in Vector per https://github.com/vectordotdev/vector/issues/11577.

I think this option is better than a new `json_lossy` codec since it'll let us add more JSON-specific codec options in the future (like `max_depth`).

Does that make sense to you? Thanks for getting this conversation started!

**Comment by fpytloun** [comment]
@jszwedko Great, this option should be fine 👍 
Would be also nice to add `lossy` option to `parse_json` VRL function :-)

**Comment by jszwedko** [comment]
@fpytloun just to confirm, is updating this PR to add the new option something you'd be able to take on?

**Comment by fpytloun** [comment]
> @fpytloun just to confirm, is updating this PR to add the new option something you'd be able to take on?

I am afraid this is beyond my Rust skills 😞

**Comment by jszwedko** [comment]
No worries 😄 I just wasn't sure. Given that we don't want to proceed with the approach here, I'll close out this PR. I created an issue to track the enhancement here: https://github.com/vectordotdev/vector/issues/16406 . Thanks for suggesting this!

**Pull request closed without merging**
