### PR TITLE
chore(deps): make prost* crates workspace dependencies

### PR DESCRIPTION
**Pull request by pront**

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Nice!

**Comment by pront** [comment]
Apologies for the force-push, I rebased on latest master to resolve a conflict for `lib/loki-logproto/Cargo.toml`. I did a pass on the changes after the rebase and they look good now.

**Review by pront — COMMENTED** [review]
/ci-run-component-features

**Comment by pront** [comment]
This looks better now. Would you like to take another look @jszwedko before I enqueue this one?

**Review by jszwedko — APPROVED** [review]
Nice, this looks good, thank you!

**Pull request merged**
