### PR TITLE
chore(datadog_archives sink): Remove this component

### PR DESCRIPTION
**Pull request by bruceg**
The `datadog_archives` sink is an unfinished component that was never included in docs or announced. The initiative on this has shifted and the component is being dropped.

### CODE REVIEW

**Review by neuronull — APPROVED** [review]
I think we'll also want to remove the reference to it in 

```
.github/semantic.yml
.github/workflows/changes.yml
```

**Comment by spencergilbert** [comment]
> I think we'll also want to remove the reference to it in
> 
> ```
> .github/semantic.yml
> .github/workflows/changes.yml
> ```

Technically the one in semantic comes from the resources repo.

**Comment by spencergilbert** [comment]
> Also I guess mention in the upgrade guide?

I'm not sure we need to/should? I don't believe it was ever announced or documented - so I'm not sure that would be the best way to message the removal?

**Comment by jszwedko** [comment]
> > Also I guess mention in the upgrade guide?
> 
> I'm not sure we need to/should? I don't believe it was ever announced or documented - so I'm not sure that would be the best way to message the removal?

Agreed, this was never a released feature so I don't think it needs to be noted in the upgrade guide.

**Comment by bruceg** [comment]
> Agreed, this was never a released feature so I don't think it needs to be noted in the upgrade guide.

Given this, does it need to be marked as a breaking change (`!`)?

**Comment by bruceg** [comment]
> I think we'll also want to remove the reference to it in
> 
> ```
> .github/semantic.yml
> .github/workflows/changes.yml
> ```

I don't see any references to it in `changes.yml`. What am I missing?

**Comment by jszwedko** [comment]
I'm also not seeing it in `changes.yaml` since there are no integration tests for this sink.

**Comment by jszwedko** [comment]
> > Agreed, this was never a released feature so I don't think it needs to be noted in the upgrade guide.
> 
> Given this, does it need to be marked as a breaking change (`!`)?

Nope!

**Comment by psemeniuk** [comment]
Hi, @bruceg can you elaborate on "The initiative on this has shifted" part?

Unfortunately we're extensively utilising this sink, and it works very well for us, but now we're locked on the older version.

**Comment by jszwedko** [comment]
Hi @psemeniuk !

Apologies for any inconvenience this caused. The component was never finished/released. As a result, we can't commit to supporting it, which is why it was removed. We may revisit it in the future if there is sufficient demand. If you are using this component, I'd encourage you to reach out to your Datadog CSM to explore options.

**Comment by piotr1212** [comment]
We were using it as well, it was working great. Now we have to ship the logs to Datadog before we can archive it, this results in large bills due to Datadog charging for "log ingest".

**Pull request merged**
