### PR TITLE
docs: Build rust docs in netlify

### PR DESCRIPTION
**Pull request by StephenWakely**
This will place the rust docs under https://vector.dev/rustdocs/vector/

You can preview [here](https://deploy-preview-16276--vector-project.netlify.app/rustdocs/vector/).

Signed-off-by: Stephen Wakely <fungus.humungus@gmail.com>

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Awesome, great work on this! I'd personally still like to see these hosted at a subdomain rather than a path on https://vector.dev since it has a fairly different look and feel. I can help with that if needed. To start, you can look at the Netlify build for the VRL playground which also ends up as a different subdomain.

I'm thinking something like `rust-doc.vector.dev`.

**Comment by tobz** [comment]
> I'm thinking something like `rust-doc.vector.dev`.

@jszwedko We might want to consider how we'll do version support. Like, I know that docs.rs has version in the _path_, but I'm not sure if they're doing a bunch of manipulating of generated output, etc, to keep that all around... and what we might have to do to emulate that.

That, in my mind, was the thing that made nesting the docs as a path under `vector.dev` seem right... because I was assuming we'd get the versioning for free like we do for the normal configuration documentation.

**Comment by StephenWakely** [comment]
> We might want to consider how we'll do version support.

I imagine we only need to support master. I can't think of any scenario where anyone is going to want to be developing against older versions of Vector.

**Comment by jszwedko** [comment]
Yeah, my thinking was the same as Stephen's: that people developing against Vector will only ever really need `master`. If it is something we could get for free, easily, sure, but I don't think we need to invest too much time making it happen.

**Comment by jszwedko** [comment]
I'm noticing that this build is a little expensive compared to vector.dev. vector.dev takes ~2 minutes to build. The addition of the rustdocs here bumps that to ~12 minutes. Given that I don't think these need to be as fresh as vector.dev I'd suggest we only build these docs on updates to `master` and not deploy previews. We could even go so far as only building them nightly.

**Comment by StephenWakely** [comment]
Closing in favour of #16386.

**Pull request closed without merging**
