### PR TITLE
fix: allow empty message_key value in config

### PR DESCRIPTION
**Pull request by pront**
fixes: https://github.com/vectordotdev/vector/issues/17935

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
This _seems_ correct, but I'd be curious to see if we're relying on the "message" being present for sinks/transforms and this could introduce panics.

I thought @StephenWakely had made a similar comment or asked if allowing this was strictly necessary.

**Comment by pront** [comment]
A couple of options:
* Do not treat `message_key` as special. This means we should never panic if it doesn't exist.
* Treat it as a special case and give an error on startup.

Any preference here @spencergilbert and @StephenWakely?

**Comment by spencergilbert** [comment]
I'd prefer fewer "special" keys, but I'd be worried about whack-a-mole with chasing down issues.

If we're not concerned about tracking down what may be affected by a missing "message" that's my preference.

**Comment by pront** [comment]
> I'd prefer fewer "special" keys, but I'd be worried about whack-a-mole with chasing down issues.
> 
> If we're not concerned about tracking down what may be affected by a missing "message" that's my preference.

I would also like to avoid "special" cases. Currently users will see a panic on startup so they probably do not rely on `message_key = ""`. I think we should get this change in and if it exposes issues down the line, we can tackle them as separate issues.

**Review by StephenWakely — APPROVED** [review]
Yeah. I can't think of any scenario where users would want to turn off the message field, but if we do allow it we should do so without panicking.

This isn't the only place where it panics without a message field though. For example, the InfluxDB sink would panic without a message field. We should leave the issue open until all the places are addressed.

**Pull request merged**
