### PR TITLE
chore(ci): move datadog-agent to new integration tests

### PR DESCRIPTION
**Pull request by jdrouet**
Following #10466, this PR moves the datadog-agent tests to use docker-compose on the CI.

Signed-off-by: Jérémie Drouet <jeremie.drouet@datadoghq.com>

### CODE REVIEW

**Comment by jdrouet** [comment]
Triggered the integration tests here: https://github.com/vectordotdev/vector/actions/runs/1630647314

**Review by spencergilbert — APPROVED** [review]

**Review by jszwedko — COMMENTED** [review]
Generally looks good!

I am wondering if we need to split out the CI job though. Could we keep the `make` target as it was before where it runs the tests and cleans up (maintaining the `AUTODESPAWN` behavior)? That would let us just keep the original CI job and migrate over the targets. I think you mentioned one draw back is that it doesn't automatically stop the services if the tests fail, but that we could improve that with a strategy similar to the one mentioned in https://stackoverflow.com/questions/28597794/how-can-i-clean-up-after-an-error-in-a-makefile . If you wanted, you could still keep the clean-up as a separate make traget that can be run independently but is still run as part of `test-integration-*`.

**Comment by jdrouet** [comment]
> Could we keep the make target as it was before where it runs the tests and cleans up (maintaining the AUTODESPAWN behavior)?

We could but, in my opinion, we shouldn't.
First, this makes the `Makefile` harder to read and therefore, harder to contribute as a newcomer that doesn't have a PHD in bash or make.
Second, using this environment variable is not really explicit. Having an explicit way to stop the containers when you're done working on it locally is a plus.

Now, let's look at the CI script:

```yaml
      # old version
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-${{ matrix.test }}
      # new version
      - run: make test-integration-${{ matrix.test }}
      - run: make test-integration-${{ matrix.test }}-cleanup
        if: ${{ always() }}
```

To me, the first version is not explicit of what it does, has a big boilerplate when the second is clear about the fact that it does a cleanup after, in any case.

> That would let us just keep the original CI job and migrate over the targets.

If we do that, we'd keep running the `bootstrap-ubuntu-20.04.sh` (and `prepare.sh`, etc) just for the sake of not having 2 different jobs and therefore we'd loose the advantage of reducing the build time.

**Comment by jszwedko** [comment]
> First, this makes the `Makefile` harder to read and therefore, harder to contribute as a newcomer that doesn't have a PHD in bash or make.

I'm sympathetic to this, but I think the UX here has suffered due to needing to manually run the clean-up task after you run the tests (see below). It'd be nice to maintain that behavior if we can.

> Second, using this environment variable is not really explicit. Having an explicit way to stop the containers when you're done working on it locally is a plus.

I was thinking we'd maintain the `AUTODESPAWN` behavior for the targets that run the tests (like`make test-integration-datadog-agent`) but you could still have a separate make target that runs the clean up to run directly if desired.

I think the nice part of this is that there is just one task you run that runs the tests and the cleanup without requiring you to remember to run the clean-up task afterwards when running locally.

Put another way, it feels a bit weird that `make test-integration-datadog-agent` starts the dependencies, but doesn't stop them.

> > That would let us just keep the original CI job and migrate over the targets.
> 
> If we do that, we'd keep running the `bootstrap-ubuntu-20.04.sh` (and `prepare.sh`, etc) just for the sake of not having 2 different jobs and therefore we'd loose the advantage of reducing the build time.

Yeah, that's fine, I feel less strongly about this aspect. Until we migrate over all of them, I don't think we'll really reap the benefits of the shorter build times in terms of CI feedback, but it would reduce CI contention.

**Comment by jdrouet** [comment]
> Put another way, it feels a bit weird that make test-integration-datadog-agent starts the dependencies, but doesn't stop them.

It makes sense when you run it locally while debugging something: your run the test it fails, you don't want to wait 30s that the agent starts, it's faster to not kill the services automatically. When you're done, cleanup...
Putting that on the CI is just one more explicit line and less complexity in the Makefile.

I personally don't like leveraging those environment variables for magic features like this because it's not explicit and there's no autocomplete about it (make commands do). But I'll add it to make this PR move on 😉

**Comment by jszwedko** [comment]
👍 that's fair. I personally like the ability to just run `make test-integration-X` and have it start-up, run the tests, and clean-up, but I can see your argument about making it easier to iterate by splitting it up. To me, the `AUTODESPAWN` that we already have in the Makefile suits this purpose. I'm definitely on-board with swapping in `docker-compose`, just less so about the other refactoring happening here.

**Comment by spencergilbert** [comment]
> 👍 that's fair. I personally like the ability to just run `make test-integration-X` and have it start-up, run the tests, and clean-up, but I can see your argument about making it easier to iterate by splitting it up. To me, the `AUTODESPAWN` that we already have in the Makefile suits this purpose. I'm definitely on-board with swapping in `docker-compose`, just less so about the other refactoring happening here.

I'd _prefer_ it to be split for local use, but do think it makes sense to separate that change into a different PR

**Comment by jszwedko** [comment]
👍 I'm happy to consider that refactoring in another PR.

**Comment by jdrouet** [comment]
It's a bit unclear to me what I've to do now 😅
But I guess it's adding the `AUTODESPAWN` in another PR.

**Pull request merged**
