### PR TITLE
enhancement(host_metrics source): Add number of logical & physical CPUs metrics

### LINKED ISSUE #13738: Publish metric for number of CPUs in `host_metrics`
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

In order to interpret the load metrics that `host_metrics` reports, it is useful to know the number of available CPUs. 

### Attempted Solutions

_No response_

### Proposal

We should publish two new metrics:

* `logical_cpus` the number of logical cpus
* `physical_cpus` the number of physical cpus

### References

_No response_

### Version

vector 0.23.0

### PR DESCRIPTION
**Pull request by neuronull**
Closes #13738.

The number of CPUs reported appears to be unaffected by vector running within a cgroup:

```
$ ./target/debug/vector -c /home/ubuntu/vector_configs/host_metrics.toml
2022-08-08T20:22:36.819479Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-08-08T20:22:36.819937Z  INFO vector::app: Loading configs. paths=["/home/ubuntu/vector_configs/host_metrics.toml"]
2022-08-08T20:22:36.835317Z  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
2022-08-08T20:22:36.835447Z  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
2022-08-08T20:22:36.836261Z  INFO vector::topology::running: Running healthchecks.
2022-08-08T20:22:36.837001Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-08-08T20:22:36.837588Z  INFO vector: Vector has started. debug="true" version="0.24.0" arch="x86_64" build_id="none"
2022-08-08T20:22:36.837811Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.

2022-08-08T20:23:06.838633228Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="logical_cpus"} = 32
2022-08-08T20:23:06.838633228Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="physical_cpus"} = 10
...

2022-08-08T20:23:36.838654750Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="logical_cpus"} = 32
2022-08-08T20:23:36.838654750Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="physical_cpus"} = 10



$  sudo cgget -g cpuset:baz
baz:
cpuset.cpus.partition: member
cpuset.cpus.effective: 2
cpuset.mems:
cpuset.mems.effective: 0
cpuset.cpus: 2

$ ps ax | grep vector
  79940 pts/2    Sl+    0:00 ./target/debug/vector -c /home/ubuntu/vector_configs/host_metrics.toml

$ sudo cgclassify -g cpuset,cpu:baz 79940

$ cat /proc/79940/cgroup
0::/baz
```

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
Seems straightforward code wise - definitely curious what the behavior appears to be when interacting with `cgroups`. We _should_ be able to integration test that as well, if we felt so inclined.

**Comment by neuronull** [comment]
> Seems straightforward code wise - definitely curious what the behavior appears to be when interacting with `cgroups`. 

Is there anything specific that you're curious about?
Or is it just a question of if the number of cpus reported is somehow impacted by having cgroups enabled? So far I haven't been able to run a scenario that yields anything interesting, but maybe I'm not looking at the right place.

**Comment by spencergilbert** [comment]
> Or is it just a question of if the number of cpus reported is somehow impacted by having cgroups enabled?

Yeah mostly curious if the metric changes depending on if Vector is running inside a `cgroup` that limits the CPU it can have. I think we mostly want to ensure the metric we're reporting is the _actual_ count and not just want Vector may have access to.

**Comment by neuronull** [comment]
> > Or is it just a question of if the number of cpus reported is somehow impacted by having cgroups enabled?
> 
> Yeah mostly curious if the metric changes depending on if Vector is running inside a `cgroup` that limits the CPU it can have. I think we mostly want to ensure the metric we're reporting is the _actual_ count and not just want Vector may have access to.

I believe it is un-impacted:

```
$ ./target/debug/vector -c /home/ubuntu/vector_configs/host_metrics.toml
2022-08-08T20:22:36.819479Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info,kube=info"
2022-08-08T20:22:36.819937Z  INFO vector::app: Loading configs. paths=["/home/ubuntu/vector_configs/host_metrics.toml"]
2022-08-08T20:22:36.835317Z  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
2022-08-08T20:22:36.835447Z  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
2022-08-08T20:22:36.836261Z  INFO vector::topology::running: Running healthchecks.
2022-08-08T20:22:36.837001Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-08-08T20:22:36.837588Z  INFO vector: Vector has started. debug="true" version="0.24.0" arch="x86_64" build_id="none"
2022-08-08T20:22:36.837811Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.

2022-08-08T20:23:06.838633228Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="logical_cpus"} = 32
2022-08-08T20:23:06.838633228Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="physical_cpus"} = 10
...

2022-08-08T20:23:36.838654750Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="logical_cpus"} = 32
2022-08-08T20:23:36.838654750Z host_cpu_seconds_total{collector="cpu",host="ip-172-31-39-253",mode="physical_cpus"} = 10



$  sudo cgget -g cpuset:baz
baz:
cpuset.cpus.partition: member
cpuset.cpus.effective: 2
cpuset.mems:
cpuset.mems.effective: 0
cpuset.cpus: 2

$ ps ax | grep vector
  79940 pts/2    Sl+    0:00 ./target/debug/vector -c /home/ubuntu/vector_configs/host_metrics.toml

$ sudo cgclassify -g cpuset,cpu:baz 79940

$ cat /proc/79940/cgroup
0::/baz
```

**Review by spencergilbert — APPROVED** [review]

**Review by bruceg — COMMENTED** [review]
Looks okay except for the type of the metrics, noted below.

**Review by jszwedko — COMMENTED** [review]
👍 Agree with Bruce that these should be gauges, otherwise this looks good to me. There appear to be some tests that just assert collection that you could add these too, below.

**Review by jszwedko — APPROVED** [review]

**Review by bruceg — APPROVED** [review]

**Pull request merged**
