### PR TITLE
chore(route transform): Use multiple outputs for route

### PR DESCRIPTION
**Pull request by 001wwang**
This PR refactors `route` to use the new system of multiple outputs rather than macro expansion.

Based off #10640

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]
Nice! This looks great. I'd just wait to merge until the two underlying PRs land.

**Comment by lukesteensen** [comment]
This failure looks relevant as well:
```
---- route stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<0
>1

', tests/config.rs:845:5
```

**Comment by 001wwang** [comment]
> This failure looks relevant as well:
> 
> ```
> ---- route stdout ----
> thread 'main' panicked at 'assertion failed: `(left == right)`
> 
> Diff < left / right > :
> <0
> >1
> 
> ', tests/config.rs:845:5
> ```

Ah interesting. This fails because `config::validation::warnings()` now outputs a warning that the route transform has no consumers. The validation assumes that the transform's base `ComponentKey` must appear in downstream component `inputs` which is no longer the case for transforms/sources with no default output, like `route`.  

We could instead take into account `outputs()` and check that every output is used. I see there's already a `TODO` about whether or not to warn about no consumers for named outputs. I think it makes sense to do so, especially given components can have no default output. Does that sound alright?

@lukesteensen

**Comment by lukesteensen** [comment]
Oh good catch! Yeah I think it makes sense to start with a default of warning when any output is left unconnected. Later we can make that part of the `Output` specification so transforms can annotate whether or not a specific output being left unused should give a warning.

**Comment by 001wwang** [comment]
Note, force pushed to resolve some issues from the base branch changing.

**Comment by jszwedko** [comment]
Nice work! It seems like this should enable https://github.com/vectordotdev/vector/issues/4644

**Comment by jszwedko** [comment]
@001wwang Actually, I'm realizing the metrics for this transform might be different now? Previously, due to transform expansion, we'd see each "route" be a separate transform with its own input/output event, bytes, and discarded metrics. With the change I believe:

* that the discarded metric will not be as useful since it is incremented for each non-matching route when ideally it'd be tagged with the route it didn't match
* The events and bytes input metrics for each route won't be emitted; instead it'll just emit for the whole transform. I think this is actually better, but is worth a "breaking change" note in the release guide for 0.20.0.
* Users will likely want to still see the event and bytes output per route. Do you know if that is already happening as a part of the named outputs work?

**Comment by 001wwang** [comment]
> @001wwang Actually, I'm realizing the metrics for this transform might be different now? Previously, due to transform expansion, we'd see each "route" be a separate transform with its own input/output event, bytes, and discarded metrics. With the change I believe:
> 
> * that the discarded metric will not be as useful since it is incremented for each non-matching route when ideally it'd be tagged with the route it didn't match
> * The events and bytes input metrics for each route won't be emitted; instead it'll just emit for the whole transform. I think this is actually better, but is worth a "breaking change" note in the release guide for 0.20.0.
> * Users will likely want to still see the event and bytes output per route. Do you know if that is already happening as a part of the named outputs work?

Ah, great points @jszwedko, I'll make changes in a follow up.
- 👍 Will add a tag with the route name. Is this slightly different metrics UX worth a note in the 0.20.0 release guide?
- 👍 Will add a note
- There is a [TODO](https://github.com/vectordotdev/vector/blob/master/src/topology/builder.rs#L549) in the relevant code, but I'm not sure if it's actively being worked on. Since #10687 is merged, I think it's worth getting started if not. cc: @lukesteensen for any more context

**Comment by lukesteensen** [comment]
> * There is a [TODO](https://github.com/vectordotdev/vector/blob/master/src/topology/builder.rs#L549) in the relevant code, but I'm not sure if it's actively being worked on. Since [docs(internal docs): Update component spec for multiple outputs #10687](https://github.com/vectordotdev/vector/pull/10687) is merged, I think it's worth getting started if not. cc: @lukesteensen for any more context

This is accurate, it's not being worked on but the spec update should mean we're unblocked.

**Comment by 001wwang** [comment]
> > * There is a [TODO](https://github.com/vectordotdev/vector/blob/master/src/topology/builder.rs#L549) in the relevant code, but I'm not sure if it's actively being worked on. Since [docs(internal docs): Update component spec for multiple outputs #10687](https://github.com/vectordotdev/vector/pull/10687) is merged, I think it's worth getting started if not. cc: @lukesteensen for any more context
> 
> 👍 agreed, I think we should fix that before 0.20.0. Do you mind opening issues to track this work and linking them up with #9514 ?

Yep, opened #10832 and added to #9514.

**Pull request merged**
