### PR TITLE
docs(http_server source): use auto-generated config docs

### LINKED ISSUE #16037: Convert the `http_server` source to use auto-generated docs

### PR DESCRIPTION
**Pull request by neuronull**
closes: https://github.com/vectordotdev/vector/issues/16037
epic: https://github.com/vectordotdev/vector/issues/14998

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Y'all have been testing me by putting the `auto_generated` field at the bottom instead of the top of the section 😭

**Comment by neuronull** [comment]
> Y'all have been testing me by putting the `auto_generated` field at the bottom instead of the top of the section 😭

Oh, if there is a convention to follow I'm happy to adapt. I have been doing it this way just because the hardwired approach to adding new stuff "at the end".

**Comment by spencergilbert** [comment]
> Oh, if there is a convention to follow I'm happy to adapt. I have been doing it this way just because the hardwired approach to adding new stuff "at the end".

Hahaha, I'd been doing it from the top because alphabetical - I'm 99% sure the generated cue is alphabetized (at least per object) which could just be incidental.

**Comment by neuronull** [comment]
> Hahaha, I'd been doing it from the top because alphabetical - I'm 99% sure the generated cue is alphabetized (at least per object) which could just be incidental.

Mmm I had forgotten about that.

**Pull request merged**
