### PR TITLE
feat(splunk_hec_logs splunk_hec_metrics humio sink) Allow host and timestamp key fields to be namespaceable

### PR DESCRIPTION
**Pull request by sbalmos**
Allows the `host_key` and `timestamp_key` configuration fields to reference namespaced fields outside of the main event namespace (e.g. a timestamp key using the new `%vector.ingest_timestamp` field, host key using other custom namespaced fields, etc). This is linked to the discussion in #18867.

### CODE REVIEW

**Comment by sbalmos** [comment]
Done. And yeah, I know better. Switched dev environment setups here, and I forgot to recreate my on-build run-these-action rules. :/ Not sure how the tests were passing previously when they needed all kinds of code changes also.

**Comment by StephenWakely** [comment]
There are still a bunch of errors in the `splunk` integration test and in the unit tests.

You should be able to run these with `cargo vdev test` and `cargo vdev int test splunk`.

**Comment by sbalmos** [comment]
I'll need a bit of help here on which way to solve this. I have no experience on the metrics side of things, and this could have 3 answers. The root issue for all these tests is getting the `host` tag value in `splunk_hec/metrics/sink.rs:173`. After all is said and done, `key.to_string()` for an `OwnedValuePath`, as it was pre-PR, produces `"host"` for looking up the tag name. For an `OwnedTargetPath`, it produces `".host"` (note the leading period), since there's potentially a namespace involved.

I just don't know whether actual real-life metrics have namespace support, and thus tags would have namespaces, or if it was just the log side of Vector that was supposed to have namespaces. That could potentially lead me to reverting the code on the metrics side, while leaving in the namespace support on the log side.

This could also be a case of "fix the test", as the sample metric `host` value we're testing against is built in `get_counter()` at `splunk_hec/metrics/tests.rs:42`. Note it's named `host` and not `.host`.

Any advice here?

**Comment by StephenWakely** [comment]
> Any advice here?

Ah, yes of course, I should have thought of that. Metrics don't have namespaces, since they are a very fixed schema. So all it is doing here is looking up the tag name, which is a simple string. To fix, just revert all the changes to the metrics sink.

**Comment by sbalmos** [comment]
Wow, this was more painful to partially revert than I thought. The tests all pass now (save for a cgroups-related one that fails even on the `master` branch, so I'm ignoring that one).

I'm a little suspect on the Humio metrics-to-log config wrapping for the `host_key` and `timestamp_key` fields, since metrics `host_key` and `timestamp_key` are back to being `OptionalValuePath`s while log `host_key` and `timestamp_key` are `OptionalTargetPath`s.

This actually makes me think if there's a larger app-wide config gap here - wouldn't metrics sinks overall break if someone set their global `log_schema.host_key` and/or `log_schema.timestamp_key` fields to non-event namespaced fields? Maybe there should be a global `metrics_schema` config now in addition to the global `log_schema` config?

Completely separately, `CONTRIBUTING.md` should be updated to note that you need to install `vdev`, referencing `vdev/README.md`, before you can run the `cargo vdev test` and similar commands. And `vdev/README.md` should be updated to note that you need to run `cargo install cargo-nextest` before `cargo vdev test` will work. I have yet to get `cargo vdev int` to run tests, with either Podman or Docker. With Docker, `cargo vdev int test splunk` returns "no container tool could be detected", even though `docker` is on my path. With Podman, it returns "Starting service environment. Error: No such file or directory (os error 2)". Tihs is under Debian 11 in WSL 2.

**Comment by StephenWakely** [comment]
One final change.. you need to run `make generate-component-docs` to update the docs.

**Comment by sbalmos** [comment]
Regen'd docs pushed. I'll probably start a separate thread later on dev env setup docs updating, no need to pollute the PR comments here.

**Review by estherk15 — COMMENTED** [review]
No docs review needed

**Review by StephenWakely — APPROVED** [review]
Awesome! Thanks.

**Pull request merged**
