### PR TITLE
chore(tests): migration clickhouse integration tests to docker-compose

### PR DESCRIPTION
**Pull request by jdrouet**
Following #10466, this PR moves the clickhouse tests to use docker-compose on the CI.

### CODE REVIEW

**Review by tobz — DISMISSED** [review]
Looks like you forgot to update the CI workflow to use the Docker-based test?

**Review by spencergilbert — APPROVED** [review]

**Comment by spencergilbert** [comment]
I noticed the following at the end of the integration test run:

```
docker-compose -f scripts/integration/docker-compose.clickhouse.yml rm --force --stop --volumes
Removes stopped service containers.

By default, anonymous volumes attached to containers will not be removed. You
can override this with `-v`. To list all volumes, use `docker volume ls`.

Any data which is not in a volume will be lost.

Usage: rm [options] [--] [SERVICE...]

Options:
    -f, --force   Don't ask to confirm removal
    -s, --stop    Stop the containers, if required, before removing
    -v            Remove any anonymous volumes attached to containers
    -a, --all     Deprecated - no effect.
```

Maybe missing an option to make it quieter/remove moar things?

**Comment by spencergilbert** [comment]
> @spencergilbert it's weard, it seems to work well on the CI... What version of the docker engine are you using?

That's from CI actually! https://github.com/vectordotdev/vector/runs/4728919447?check_suite_focus=true#step:4:16

**Comment by jdrouet** [comment]
> That's from CI actually! https://github.com/vectordotdev/vector/runs/4728919447?check_suite_focus=true#step:4:16

Ok, that's really weird that the job doesn't fail... I'll fix that in that PR and merge it right away 😉

**Comment by jdrouet** [comment]
To be fair, on my machine:
```bash
❯ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

❯ docker-compose -f scripts/integration/docker-compose.aws.yml rm --help

Usage:  docker compose rm [SERVICE...]

Removes stopped service containers

By default, anonymous volumes attached to containers will not be removed. You
can override this with -v. To list all volumes, use "docker volume ls".

Any data which is not in a volume will be lost.

Options:
  -f, --force     Don't ask to confirm removal
  -s, --stop      Stop the containers, if required, before removing
  -v, --volumes   Remove any anonymous volumes attached to containers
```

**Comment by jdrouet** [comment]
I'm really curious what version of Docker we're using on the CI...

**Pull request merged**
