### PR TITLE
chore(ci): Swap out mockwatchlogs for localstack

### PR DESCRIPTION
**Pull request by balonik**
Now that localstack supports CloudWatch Logs as a service.

### CODE REVIEW

**Comment by balonik** [comment]
FYI @jszwedko (sorry for spam)

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-aws

**Comment by jszwedko** [comment]
Thanks @balonik ! I appreciate you taking a look at it. I kicked off the AWS integration tests to see if they pass now 🙏

**Comment by jszwedko** [comment]
Or, hmm, that didn't work for some reason. Let me just pick your commit over to my PR to try it there.

**Pull request closed without merging**
