### PR TITLE
enhancement(sinks): Enable acknowledgements by default on archiving sinks

### LINKED ISSUE #10273: Enable end-to-end acknowledgements by default

### PR DESCRIPTION
**Pull request by bruceg**
Closes #10273

### CODE REVIEW

**Review by binarylogic — APPROVED** [review]
Very nice. It looks like you got all of the object stores.

**Comment by jszwedko** [comment]
We discussed this offline, but noting for posterity that we've decided to hold off on this because users should also configure a disk buffer on these sinks or they'll have a bad time with end-to-end acknowledgements. Instead, we plan to just document and release end-to-end acknowledgements in 0.21.0, gather user feedback, and circle back to this later.

**Comment by binarylogic** [comment]
Sounds good. The rest of the documentation changes are good. If we can default to `false` for all sinks then we should be able to merge this, right?

**Comment by bruceg** [comment]
> The rest of the documentation changes are good. If we can default to `false` for all sinks then we should be able to merge this, right?

This does not change any behavior or documentation for anything other than the four archiving sinks, so the rest of the changes are effectively no-ops.

**Pull request closed without merging**
