### PR TITLE
docs(internal docs): Fix basic sink tutorial issues

### PR DESCRIPTION
**Pull request by tombruijn**
Fix typo in the link in the word "sinks".

### CODE REVIEW

**Review by StephenWakely — APPROVED** [review]
Well spotted. Thankyou!

**Comment by tombruijn** [comment]
@StephenWakely as I continue following this guide I come across some more issues, like:

- The `use crate::prelude::*;` doesn't resolve
- references to types that don't exist (anymore) `RequestCountByteSize`
- a missing `BasicRequestBuilder` struct definition
- differences in expected return types for the Encoder trait

Is this guide still the best way to go to build/rewrite a sink? I am looking to update the AppSignal sink.

**Comment by tombruijn** [comment]
I have some more changes in this branch that makes the basic sink compile, but not work (as it has no encoder): https://github.com/vectordotdev/vector/compare/master...appsignal:vector:basic-sink

And working on the actual rewritten AppSignal sink I think we found some more things that could be useful changes for the basic sink tutorial as well, but that's still a work in progress here: https://github.com/vectordotdev/vector/compare/master...appsignal:vector:new-appsignal-sink

I'll try and submit a PR for the docs when we have a working rewritten sink.

**Comment by StephenWakely** [comment]
> Is this guide still the best way to go to build/rewrite a sink?

Yeah. Some recent changes may mean this tutorial needs updating. I'll look into it right away.

**Comment by StephenWakely** [comment]
> I have some more changes in this branch that makes the basic sink compile, but not work (as it has no encoder): [master...appsignal:vector:basic-sink](https://github.com/vectordotdev/vector/compare/master...appsignal:vector:basic-sink)
> 
> And working on the actual rewritten AppSignal sink I think we found some more things that could be useful changes for the basic sink tutorial as well, but that's still a work in progress here: [master...appsignal:vector:new-appsignal-sink](https://github.com/vectordotdev/vector/compare/master...appsignal:vector:new-appsignal-sink)
> 
> I'll try and submit a PR for the docs when we have a working rewritten sink.

I have updated the docs in a PR [here](https://github.com/vectordotdev/vector/pull/18148). Feel free to take a look and any feedback would be appreciated.

**Pull request merged**
