### PR TITLE
performance(route transform): run concurrently

### LINKED ISSUE #12481: Run `route` condition checks concurrently
A user reported a regression to the performance of their large `route` configuration with 0.20.0 in https://github.com/vectordotdev/vector/issues/11997

This is very likely to be due to https://github.com/vectordotdev/vector/pull/10738 which now runs the condition checks sequentially rather than expanding into one separate transform task per route.

Even with removing the transform expansion, I think we can still execute the condition checks concurrently to improve the performance of `route` transforms with a large number of routes.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #12481

Signed-off-by: Luke Steensen <luke.steensen@gmail.com>

### CODE REVIEW

**Comment by jszwedko** [comment]
> Makes sense to me. Should not all function and synchronous transforms be able to run concurrently?

I was just about to ask the same question. I also have a vague sense of deja vu that I asked this question before.

**Review by jszwedko — APPROVED** [review]

**Comment by jszwedko** [comment]
Hmm, actually, this seems worse for large numbers of routes 🤔 

Using the config from https://github.com/vectordotdev/vector/issues/11997#issuecomment-1082959988 with `count = 10000` for `demo_logs`, running with `hyperfine`:

This PR:  658.2 ms ±   3.9 ms
Previous commit:  519.6 ms ±  18.1 ms

**Comment by jszwedko** [comment]
Literal config: https://gist.github.com/jszwedko/260ef603510e1fcb98ee0c7781543a68

**Comment by lukesteensen** [comment]
@jszwedko I do see that locally as well, but that config also seems to run much faster on 0.21.1 than it does on 0.19.3, so I'm not quite sure what to make of it. It seems like the original issue was about configs that run more slowly on versions  after 0.19? Really we should try to make it faster always, but I'm just trying to narrow it down for now.

**Comment by jszwedko** [comment]
> @jszwedko I do see that locally as well, but that config also seems to run much faster on 0.21.1 than it does on 0.19.3, so I'm not quite sure what to make of it. It seems like the original issue was about configs that run more slowly on versions after 0.19? Really we should try to make it faster always, but I'm just trying to narrow it down for now.

Yeah, I'm fine with this going in as-is since I think it is more correct. It just surprised me a bit that it was slower.

I'm still wondering about Bruce's question above though. Is there a reason not all sync transforms are marked as runnable in parallel ?

**Comment by lukesteensen** [comment]
> Is there a reason not all sync transforms are marked as runnable in parallel?

Simply being synchronous doesn't mean that something can be run in parallel while maintaining correctness. This is a little bit of an academic concern, since I don't think we have any real stateful synchronous transforms, but it felt wrong to automatically enable something that's very much not guaranteed to be safe given the current APIs. But I definitely agree it's a bit of a wart and it'd be good to make these kinds of mistakes less likely.

**Comment by lukesteensen** [comment]
> It just surprised me a bit that it was slower.

I think I maybe found the issue here. The `demo_logs` source only ever emits individual events, so we never end up getting any batching through the rest of the topology (i.e. all of the event arrays hold a single event). I used demo logs to fill up a file, and then ran the same test using stdin instead of demo logs and the difference was dramatic.

**Comment by lukesteensen** [comment]
0.19.3:
```
$ hyperfine 'vector --config routes.yaml < input.log'
Benchmark 1: vector --config routes.yaml < input.log
  Time (mean ± σ):     14.666 s ±  0.075 s    [User: 156.887 s, System: 7.636 s]
  Range (min … max):   14.520 s … 14.746 s    10 runs
```

0.21.1:
```
$ hyperfine 'vector --config routes.yaml < input.log'
Benchmark 1: vector --config routes.yaml < input.log
  Time (mean ± σ):      8.248 s ±  0.090 s    [User: 9.384 s, System: 0.085 s]
  Range (min … max):    8.118 s …  8.363 s    10 runs
```

HEAD of this branch:
```
$ hyperfine './target/release/vector --config routes.yaml < input.log'
Benchmark 1: ./target/release/vector --config routes.yaml < input.log
  Time (mean ± σ):     842.1 ms ±  24.2 ms    [User: 8094.0 ms, System: 85.7 ms]
  Range (min … max):   794.4 ms … 881.6 ms    10 runs
```

**Comment by jszwedko** [comment]
Hah! Wow. Batching makes a big difference.

@hhromic something else to note when doing benchmarks.

**Pull request merged**
