### PR TITLE
chore: Analyze all captures at once

### PR DESCRIPTION
**Pull request by blt**
Building from #9873 we now perform analysis in one step over all soaks. This has
the added benefit of allowing us to compute a markdown blob for output, which
should set us up nicely for #9622.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by jszwedko** [comment]
Just waiting for CI to finish on this to see the output, but the implementation looks good!

**Review by jszwedko — COMMENTED** [review]
It looks like the analysis is currently failing due to an unbound variable: https://github.com/vectordotdev/vector/runs/4097509002?check_suite_focus=true

**Comment by blt** [comment]
Ah shoot. Easy to fix but it’ll have to wait until later tonight. Please feel free to push changes if you’d like.

**Comment by jszwedko** [comment]
Nice! The output looks great. Excited to see this end up as Github comments.

**Pull request merged**
