### PR TITLE
enhancement(gcp provider): Add support for instance accounts

### LINKED ISSUE #2243: Use GCP instance service account for sinks
Most GCP related sinks (gcp_cloud_storage, gcp_pubsub, gcp_stackdriver_logs, etc) have credentials_path config where we can give the path to the service account private key json file. This means we have to download the SA private key which is insecure and hard for rotations.

Can we add support for retrieving that from the GCE instance metadata?
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

In case of GKE, we can also use the workload identity:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

### PR DESCRIPTION
**Pull request by bruceg**
Closes #2243

### CODE REVIEW

**Review by binarylogic — APPROVED** [review]
Docs look great. I'm about to submit a PR for `0.9.0` and would love to include this.

**Review by lukesteensen — APPROVED** [review]

**Review by binarylogic — APPROVED** [review]

**Comment by bruceg** [comment]
Unfortunately, while you both approved it, it is broken. If no credentials are configured on a system that is not within GCP's network, it produces an obscure error about "Name or service not known". It needs to do a DNS lookup on the `metadata.google.internal` name and only switch on the instance account behavior when it's found, but all of my attempts to do that from within the context of `SinkConfig::build` are turning into a huge mess.

Furthermore, none of this process (neither before nor after this change) is using our custom DNS resolution, which means its not obeying configured DNS resolvers. However, that's not in scope for this PR.

**Comment by binarylogic** [comment]
Is there tech-debt related work that would unblock that? If so, we could open issues for them and address them separately.

**Comment by bruceg** [comment]
So the situation as it stands now is that it works for "normal" use cases except that:
1. The error message when no credentials are available is obtuse. This is not a bug per se, and resolving beyond fudging the self test it will likely take some tech debt work.
2. The token fetch process does not obey custom DNS resolution. This is not a new issue, and I'd class it as a bug more than tech debt.

If we are satisfied with the following error message when no credentials are available, I will work around it in the test and merge it.

```Apr 17 10:11:36.413 ERROR vector::topology: Configuration error: Sink "pubsub": Failed to get implicit GCP token```

**Comment by binarylogic** [comment]
> The token fetch process does not obey custom DNS resolution. This is not a new issue, and I'd class it as a bug more than tech debt.

Can you open an issue for this?

> If we are satisfied with the following error message when no credentials are available, I will work around it in the test and merge it.

I am happy with that error message for now. Can you open an issue to improve it?

**Comment by bruceg** [comment]
I just added a fix for the failing test, and will open follow-up issues for the identified problems and merge this once the CI tests pass.

**Comment by bruceg** [comment]
Oh, this is fun. The `test-stable` is failing because apparently Circle is running on GCP, and so our tests _are_ able to fetch from the internal address, but cannot get a token because it's not enabled for their hosts. This makes it a different error than we would get anywhere else and will break our builds until moving off of Circle. Any objection to me just adding an ignore for this test for now?

**Comment by binarylogic** [comment]
I'll defer to @lukesteensen on that.

**Comment by lukesteensen** [comment]
I think it's fine to ignore it for now. We could actually fix that with a custom resolver once those are integrated (i.e. always use a normal public resolver for that test so it doesn't resolve no matter where the test is running).

**Pull request merged**
