### PR TITLE
feat(prometheus): add more compression algorithms to Prometheus Remote Write

### PR DESCRIPTION
**Pull request by zamazan4ik**
Resolves https://github.com/vectordotdev/vector/issues/17199

- add Zstd and Gzip support to Prometheus Remote Write
- add a new compression option in the config (Snappy is the default)
- update the documentation

Tested:
- Local build

### CODE REVIEW

**Comment by StephenWakely** [comment]
According to the [prometheus remote write spec](https://prometheus.io/docs/concepts/remote_write_spec/):

> The remote write request in the body of the HTTP POST MUST be compressed with [Google’s Snappy](https://github.com/google/snappy).

Are these changes just being made for Victoria metrics? Are they straying from the spec?

**Comment by spencergilbert** [comment]
> I left Snappy as a default that conforms to Prometheus spec. If a user's Prometheus Remote Write supports other compression algorithms - it could be enabled via this new option. I didn't create a new remote write plugin (like Victoria Remote Write sink) since it will be an overhead (IMHO).

Agreed on not needing a new sink for just compression support.

> IMO, supporting additional compression algorithms, even if they violate the formal specification, is ok in this case.

I think opting in to non-spec choices isn't unreasonable, perhaps we should be documenting it more clearly for the end user? I'm not entirely sure. On one hand, I expect if someone is tweaking the default compression algorithm they _probably_ know what they're doing - on the other noting we're straying from the spec for reasons XYZ is good clarity.

**Comment by StephenWakely** [comment]
Yeah definitely this needs documenting, with a link to the Victoria Metrics page you linked above to explain why we are doing it. 

I'm not seeing `gzip` mentioned anywhere? Unless it's needed anywhere I would prefer to not include it.

**Comment by zamazan4ik** [comment]
Regarding the comment in "How it works". I suggest clarify the actual text right now for avoiding another couple of review :)

**Comment by StephenWakely** [comment]
I would add the following to `how_it_works` section of `prometheus_remote_write.cue`:

```
		compression_schemes: {
			title: "Compression schemes"
			body: """
				Officially according to the [Prometheus Remote-Write specification]
				(\(urls.prometheus_remote_write_spec)), the only supported
				compression scheme is [snappy](\(urls.snappy)). However,
				there are a number of other implementations that do support other schemes. Thus
				Vector also supports using Gzip and Zstd.
			"""
		}
```

Add these to `urls.cue`:

```
	prometheus_remote_write_spec:               "https://prometheus.io/docs/concepts/remote_write_spec/#protocol"
	snappy:                                     "https://github.com/google/snappy"
```

**Comment by zamazan4ik** [comment]
@StephenWakely applied the proposed changes. The only difference is "snappy" link since `snappy` already existed in the `urls.cue` file I decided not changing the actual link value.

**Comment by zamazan4ik** [comment]
As far as I see, CI fails not from my changes but from smth else.

**Comment by neuronull** [comment]
> As far as I see, CI fails not from my changes but from smth else.

That does look like it shouldn't be related. I just triggered a re-run 🤞

**Review by StephenWakely — APPROVED** [review]
Nice one. Thank you very much!

**Pull request merged**
