### PR TITLE
chore(greptimedb_metrics sink): fix greptimedb examples

### PR DESCRIPTION
**Pull request by sunng87**
## Summary

This patch updates examples of `greptimedb_metrics`

- corrected example value of `gzip_compression`
- add example of `new_naming`
- removed redundant example of `endpoint`

## Change Type
- [ ] Bug fix
- [ ] New feature
- [x] Non-functional (chore, refactoring, docs)
- [ ] Performance

## Is this a breaking change?
- [ ] Yes
- [x] No

## How did you test this PR?

N/A

## Does this PR include user facing changes?

- [ ] Yes. Please add a changelog fragment based on our [guidelines](https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md).
- [x] No. A maintainer will apply the "no-changelog" label to this PR.

## Checklist
- [x] Please read our [Vector contributor resources](https://github.com/vectordotdev/vector/tree/master/docs#getting-started).
- [x] If this PR introduces changes Vector dependencies (modifies `Cargo.lock`), please
  run `dd-rust-license-tool write` to regenerate the [license inventory](https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv) and commit the changes (if any). More details [here](https://crates.io/crates/dd-rust-license-tool).

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks @sunng87 !

**Comment by sunng87** [comment]
@jszwedko Thank you for fast response! I have a question. My idea is to change default value of this `new_naming` to `true` eventually. But this change will affect existing users, if done wrong, it will break users' data, because this option control how we name timestamp column in GreptimeDB.

My idea is to:

1. Add a breaking change to `greptimedb_metrics` sink, to make this option a required one and change default value from `false` to `true`. So users will get notified when upgrading from older versions and set correct value of this field.
2. After several months and a few minor releases of vector, change this option back to optional so new users won't need to know this option.

Do you think this will work? Do you have similar practice at Vector before?

**Comment by jszwedko** [comment]
> @jszwedko Thank you for fast response! I have a question. My idea is to change default value of this `new_naming` to `true` eventually. But this change will affect existing users, if done wrong, it will break users' data, because this option control how we name timestamp column in GreptimeDB.
> 
> My idea is to:
> 
> 1. Add a breaking change to `greptimedb_metrics` sink, to make this option a required one and change default value from `false` to `true`. So users will get notified when upgrading from older versions and set correct value of this field.
> 2. After several months and a few minor releases of vector, change this option back to optional so new users won't need to know this option.
> 
> Do you think this will work? Do you have similar practice at Vector before?

Hey! Yes, something like that would work. It matches the deprecation process [we have documented](https://github.com/vectordotdev/vector/blob/master/docs/DEPRECATION.md#lifecycle-of-a-deprecation). See [the deprecation process documentation](https://github.com/vectordotdev/vector/blob/master/docs/DEPRECATION.md#lifecycle-of-a-deprecation) for more details on the process.

**Review by rtrieu — APPROVED** [review]

**Comment by pront** [comment]
For https://github.com/vectordotdev/vector/actions/runs/12247198112/job/34178224846?pr=21984:
```
./website/scripts/cue.sh fmt
CI=true make check-docs
```

**Comment by sunng87** [comment]
@pront Thank you! It seems example is not allowed for bool fields

**Pull request merged**
