### PR TITLE
fix(aws_s3 sink): Fix incorrect _IA storage class names

### LINKED ISSUE #5244: Invalid validation of "STANDARD_IA" or "ONEZONE_IA" storage_class parameter in aws_s3 sink
### Vector Version

```
# vector --version
vector 0.10.0 (g0f0311a x86_64-unknown-linux-musl 2020-07-22)
```

### Vector Configuration File

```toml
[sources.in]
  type = "kafka" # required
  bootstrap_servers = "..." # required
  group_id = "tools" # required
  topics = ["..."] # required

...

[sinks.s3_archives]
  # General
  type = "aws_s3" # required
  inputs = ["in"] # required
  bucket = "some-bucket-name" # required
  compression = "gzip" # optional, default
  healthcheck = true # optional, default
  region = "some-aws-region" # required, required when endpoint = ""

  # Batch
  batch.max_bytes = 1000000 # optional, default, bytes
  batch.max_events = 1000 # optional, no default, events
  batch.timeout_secs = 300 # optional, default, seconds

  # Buffer
  buffer.max_events = 500 # optional, default, events, relevant when type = "memory"
  buffer.type = "memory" # optional, default

  # Encoding
  encoding.codec = "ndjson" # optional, default
  encoding.only_fields = ["timestamp", "message"] # optional, no default

  # Naming
  key_prefix = "date=%F/"

  # Storage
  storage_class = "STANDARD_IA" # optional, no default
```

#### with storage_class="STANDARD_IA"

```sh
# RUST_BACKTRACE=full vector validate /etc/vector/vector.toml  
Nov 26 14:25:50.487  INFO vector: Log level "warn" is enabled.
Failed to parse "/etc/vector/vector.toml"
--------------------------------------
x unknown variant `STANDARD_IA`, expected one of `STANDARD`, `REDUCED_REDUNDANCY`, `INTELLIGENT_TIERING`, `STANDARD_I_A`, `ONEZONE_I_A`, `GLACIER`, `DEEP_ARCHIVE` for key `sinks.s3_archives`
```
### Expected Behavior

- Application should start
- Configuration file with storage_class="STANDARD_IA" or storage_class="ONEZONE_IA" in aws_s3 sink should be validated successfully
- Configuration file with storage_class="STANDARD_I_A" or storage_class="ONEZONE_I_A" in aws_s3 sink should show configuration error
- Validation should show valid list of possible values: 'STANDARD | REDUCED_REDUNDANCY | STANDARD_IA | ONEZONE_IA | INTELLIGENT_TIERING | GLACIER | DEEP_ARCHIVE | OUTPOSTS'

### Actual Behavior

- Application fails to start with valid parameter value 'STANDARD_IA'
- Application starts with invalid parameter value 'STANDARD_I_A' and fails on PutObject S3 API request:
- Application shows invalid list of possible values: 'STANDARD | REDUCED_REDUNDANCY | INTELLIGENT_TIERING | **STANDARD_I_A** | **ONEZONE_I_A** | GLACIER | DEEP_ARCHIVE' 

### Example Data

```xml
Nov 26 12:54:40.546 ERROR sink{name=s3_archives type=aws_s3}:request{request_id=2}: vector::sinks::util::retries2: encountered non-retriable error. error=Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidStorageClass</Code><Message>The storage class you specified is not valid</Message><StorageClassRequested>STANDARD_I_A</StorageClassRequested><RequestId>...</RequestId><HostId>...</HostId></Error>
```
### Additional Context

Vector app is running on EC2 instance in docker image: timberio/vector:0.10.0-alpine
### References

Documentation:
[Vector Documentation](https://vector.dev/docs/reference/sinks/aws_s3/#storage_class)
[rusoto_s3 Documentation](https://rusoto.github.io/rusoto/rusoto_s3/struct.PutObjectRequest.html#structfield.storage_class)
[AWS PutObject Documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax)

### PR DESCRIPTION
**Pull request by bruceg**
Closes #5244 

Signed-off-by: Bruce Guenter <bruce@timber.io>

### CODE REVIEW

**Review by jamtur01 — APPROVED** [review]
LGTM

**Review by jszwedko — APPROVED** [review]
Looks good!

I am wondering if we even need to have an enum for this since we seem to just pass it directly to rusoto. That would save us from having to define new ones as they are added.

**Comment by bruceg** [comment]
> I am wondering if we even need to have an enum for this since we seem to just pass it directly to rusoto. That would save us from having to define new ones as they are added.

Could you create a new issue for that question? I will merge this one as-is as it fixes the immediate issue.

**Comment by jszwedko** [comment]
:+1: https://github.com/timberio/vector/issues/5248

**Pull request merged**
