### PR TITLE
enhancement(route transform): Accept metrics

### LINKED ISSUE #6727: Let `route` route metrics
Just noticing that the `route` transform doesn't accept metrics. I don't see any real reason it couldn't given that `remap` supports it. The deprecated `check_fields` condition type may not though.

### PR DESCRIPTION
**Pull request by ktff**
Closes #6727 

All of the conditions support metrics in an adequate way so this was a straightforward change.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Thanks @ktff !

Could we add:

* an example to the docs here of routing metrics
* tests to both `src/conditions/remap.rs` and `src/conditions/check_fields.rs` testing conditions against metrics events

?

Otherwise, I think this looks good.

**Comment by ktff** [comment]
@jszwedko 

> an example to the docs here of routing metrics

Yea, that will be nice.

> tests to both src/conditions/remap.rs and src/conditions/check_fields.rs testing conditions against metrics events

`remap` is already covered by tests for metric in src/conditions/remap.rs, but check_field isn't so I'll add those.

**Comment by ktff** [comment]
@jszwedko on second thought, regarding tests for src/conditions/check_fields.rs, since it's deprecated for route, does it need to support metrics? It's fine if it does but we don't need to guarantee it.

**Comment by jszwedko** [comment]
> `remap` is already covered by tests for metric in src/conditions/remap.rs, but check_field isn't so I'll add those.

Ah you are right, I see it now.

`check_fields` does seem to support metrics already too. I don't see a test for it though. It'd be nice to have one, but that shouldn't block this PR.

**Review by jszwedko — APPROVED** [review]

**Review by JeanMertz — APPROVED** [review]

**Pull request merged**
