### PR TITLE
enhancement(datadog sinks): extract common config struct attributes to shared struct

### PR DESCRIPTION
**Pull request by neuronull**
Mini refactor of the DD sinks to get rid of a bunch of duplicate code.
Noticed while working auto gen docs from config schemas.

### CODE REVIEW

**Review by bruceg — APPROVED** [review]
I'm not a big fan of the `dd_common` field name, but I'm not sure either `datadog` or `common` really works either. Otherwise, this is a nice cleanup.

**Review by spencergilbert — APPROVED** [review]
Similarly not crazy about the name, but don't have better suggestions

**Comment by neuronull** [comment]
Ima merge with the name as is.
`datadog_shared_cfg` / `DatadogSharedConfig` could be options.
Super easy to change later.

**Review by bruceg — APPROVED** [review]

**Comment by neuronull** [comment]
was not easy to track down (in CI), but this PR introduces a regression .
The alias to `api_key` in the shared struct is not applied, due to this outstanding serde issue:

https://github.com/serde-rs/serde/issues/1504

I'll have to circle back and extract that field from the shared struct 😢

**Review by spencergilbert — APPROVED** [review]
LGTM

**Pull request merged**
