### PR TITLE
docs(unit tests): Document the use of hyphens in key names in input data

### PR DESCRIPTION
**Pull request by dannystaple**
Document how hyphens can be used in unit test input data with an example.

### CODE REVIEW

**Review by tobz — COMMENTED** [review]
What errors do you see when you _don't_ use the double quotes?

**Comment by tobz** [comment]
Yeah, the reason I was asking is to understand if there's any potential for creating a better error message that actually provides the fix itself, rather than having to relegate it to the documentation.

**Comment by spencergilbert** [comment]
> Yeah, the reason I was asking is to understand if there's any potential for creating a better error message that actually provides the fix itself, rather than having to relegate it to the documentation.

👍 I expect the test code isn't using any of the newest lookup functions that return more helpful errors, but @fuchsnj would probably know best. I think adding to the docs isn't bad, saves having to jump over to the VRL docs.

**Comment by tobz** [comment]
Yeah, true, we can improve the documentation now and the error later.

**Review by tobz — APPROVED** [review]

**Comment by tobz** [comment]
Just going to force merge because now it needs `master` merged in to pick up a fix for a markdown issue, and I'm pretty sure you ... can't do that through a web-based PR.

If it somehow still has a bug in the changes related to this PR, and it breaks `master`, I'll make sure it gets fixed.

**Pull request merged**
