### PR TITLE
feat(error code when shutdown fails): set exit flag to non-zero when shutdown times out

### PR DESCRIPTION
**Pull request by DominicBurkart**
Issue: [Exit non-zero when Vector fails to gracefully shutdown](https://github.com/vectordotdev/vector/issues/13731)

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Aside from the missing scope, looks straight forward enough.

**Comment by DominicBurkart** [comment]
Ok, the windows story was a bit more complicated than I thought 😅

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
