### PR TITLE
fix(file source): Fix checksum calculation

### PR DESCRIPTION
**Pull request by Ilmarii**
The checksum is now calculated only from the bytes read, and not from the entire buffer.
Also added an auto-update procedure from the previous version.

Resolves: #15700

### CODE REVIEW

**Comment by spencergilbert** [comment]
Thanks for the contribution @Ilmarii - it struck us that this could also be a good opportunity to switch to `crc32fast` to improve performance here as well (while we're doing the migration of what we're checksumming).

Is that something you're interested in tackling, and if not do you mind if I/we push some commits to this PR to introduce that as well?

**Comment by Ilmarii** [comment]
Hi! Yes, I think I can integrate `crc32fast` here.

**Comment by spencergilbert** [comment]
> Hi! Yes, I think I can integrate `crc32fast` here.

Awesome, thanks so much! Please let us know if you need a hand or need to hand over the PR for us to finish.

**Comment by Ilmarii** [comment]
Hi! I looked at the crate and found that it only supports CRC32, i.e. the result is 32-bit.
Since CRC64 is currently used, which has a 64-bit result, this replacement will increase the number of collisions.
@spencergilbert  Please tell me if you are aware and it's ok

**Comment by tobz** [comment]
@Ilmarii Thinking about it a little more, given what you brought up.... I think we can leave things as-is for now. Looking closer at all of this code, I realized we _only_ use the checksum/fingerprint for identifying a file... instead of identifying it by path + fingerprint.

If we also included the filepath, I think using CRC32 would be totally fine, but without it... it definitely doesn't feel great to make the change.

I appreciate you pointing out that fact. We'll review the code as-is.

**Comment by spencergilbert** [comment]
👍 thanks y'all - I'll give this a review before the end of day today.

**Review by spencergilbert — APPROVED** [review]
This seems good to me, @lukesteensen did you want to take a look before we merge this?

**Review by lukesteensen — APPROVED** [review]
Makes sense to me, thanks @Ilmarii!

**Pull request merged**
