### PR TITLE
chore: Add component_ prefix to metric naming

### PR DESCRIPTION
**Pull request by 001wwang**
As per [the discussion here](https://github.com/vectordotdev/vector/pull/9165#discussion_r711134056), we'd like to introduce prefixes to better organize metrics as instrumentation expands in scope. This PR adds `component_` prefix to existing component metrics.

[rendered view](https://github.com/vectordotdev/vector/blob/2fa827629a2d388be281458cd7b0c717aeee8db3/docs/specs/component.md)

Signed-off-by: 001wwang <will.wang@datadoghq.com>

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]

**Review by spencergilbert — APPROVED** [review]
Is there an issue to implement this change?

**Review by bruceg — COMMENTED** [review]
Should this also rename the events in the documentation and source?

**Comment by jszwedko** [comment]
Yeah, I think it was unclear if we should just update the spec, and then have a separate issue to update the implementation, or do it all in one go. For this particular update, since it is just a find/replace, I think we could do it all in one go if you are open to it @001wwang

**Comment by spencergilbert** [comment]
> Yeah, I think it was unclear if we should just update the spec, and then have a separate issue to update the implementation, or do it all in one go. For this particular update, since it is just a find/replace, I think we could do it all in one go if you are open to it @001wwang

Though that would be a breaking change? We'd need to duplicate metrics with the old and new names?

**Comment by jszwedko** [comment]
> > Yeah, I think it was unclear if we should just update the spec, and then have a separate issue to update the implementation, or do it all in one go. For this particular update, since it is just a find/replace, I think we could do it all in one go if you are open to it @001wwang
> 
> Though that would be a breaking change? We'd need to duplicate metrics with the old and new names?

It would be, but thankfully we haven't released the current new metric names 😄

**Comment by 001wwang** [comment]
Sounds good, I will make those additional updates in this PR.

**Review by bruceg — APPROVED** [review]
LGTM

**Review by spencergilbert — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
