### PR TITLE
enhancement(external docs): Use defaults more extensively in CUE

### PR DESCRIPTION
**Pull request by lucperkins**
This PR is a broad-based effort to improve contributor ergonomics in the CUE sources. At the moment, I feel pretty strongly that we require too much boilerplate in places where default values could reduce that substantially. For example, I found almost 500 instances of `warnings: []` in the docs. Some changes I've made thus far:

* Make `"literal"` the default for `syntax`
* Make an empty array the default for `warnings` in configuration parameters
* Made `unit: null` the default for the `uint` type
* Removed all `default: null` instances for configuration params

I do acknowledge that there's an implicit wager at work here that a more default-heavy approach in CUE will yield better outcomes than a more explicit approach in the longer term. I could be wrong on this and I'm open to feedback and discussion. The core issue, though, is that CUE's error messages continue to be pretty inscrutable in many cases. I just killed over two hours trying to figure out what to do with an `empty disjunction` error that provided no further information. My wager is that anything we can do to cut down on the _possibility_ of such issues coming about is an ergonomic improvement.

I do have some other ideas about how to improve things but I decided that it'd be better to get some feedback before proceeding further.

### CODE REVIEW

**Review by binarylogic — CHANGES_REQUESTED** [review]
I'm a no. The point of not using defaults is to pose the question, otherwise we'll unknowingly use the defaults. The goal of documentation is to  be accurate and create a good experience for the user, and that should be put over our own internal QOL.

**Review by binarylogic — APPROVED** [review]
I've been convinced. I'll leave it to others to decide if this is helpful.

**Comment by lucperkins** [comment]
@binarylogic I actually gave it some thought and I convinced _myself_ that removing `unit: null` for integers goes too far :smile: There is surely a happy medium here. Curious what others think.

**Review by jszwedko — COMMENTED** [review]
Nice, I like this idea @lucperkins .

However, I do think that defaulting the `required.default` arg will lead us to frequently forget to document that one in the case that there should be a default. What do you think about leaving that one as undefaulted? I'm 👍 on the rest of the defaults here.

**Comment by lucperkins** [comment]
@jszwedko Okay, I've reinstated the `default: null`s

**Pull request merged**
