### PR TITLE
perf: add fast path and caching api to event insert

### PR DESCRIPTION
**Pull request by lukesteensen**
There are two separate changes here:

1. Adding a fast path to the `path_iter` parser. We check for "simple" inputs (i.e. no array indexes or escaping) and skip the whole parser in those cases.

2. Providing a second `insert_path` API that lets components cache parsed paths and use them directly. The `grok_parser` transform was updated to use this.

Together, these add about ~27% more throughput to an example grok-based pipeline.

### CODE REVIEW

**Comment by binarylogic** [comment]
Whoa. Nice job! Can't wait to run these through the test harness.

**Comment by binarylogic** [comment]
This is nice to see. After looking at this more I have a few questions:

1. How can we remove the human aspect of optimizing this going forward? Ex: remembering to use `insert_path` instead of `insert`? I'd say we could drop `insert` entirely, but I'm sure that's abrasive and annoying for things like tests. Some off-the-cuff suggestions:
  1. Rename `insert` to `insert_slow` to make it more obvious there is a performance penalty.
  2. Drop `insert` (as stated above).
  3. Do nothing and assume the developer will take performance into account like they would any other code. Ex: not defining regexes in the hot path, etc.
2. Do you have any idea how much each optimization contributes to the overall ~27% improvement? I know `1` depends on the paths provided, but I have to assume users are very rarely accessing arrays and/or escaping. Assuming this is true, what kind of performance increase could a user expect without `2`?

**Review by Hoverbear — APPROVED** [review]

**Comment by Hoverbear** [comment]
Looks good please fix CI and add benches showing no decrease in speed before merging.

**Comment by Hoverbear** [comment]
@binarylogic I think we can do some general UX improvements to `Event`.

Some possibilities:

* There is no `Event::new()` or `Event::default()` type (due to LogEvent and Metric existing)
* `LogEvent` and `Metric` are basically disjoint, we should consider how to better do that split.
* An `Event` and `LogEvent` don't `impl Into` or `From` for a `JsonValue`
* Cleanly distinguish "I want to insert a Toml string dotpath" or "I want to insert an actual real string" through "insert" and "path"(?)

**Comment by lukesteensen** [comment]
@binarylogic 

> How can we remove the human aspect of optimizing this going forward?

There are two optimizations here. The first is based on the input data, so there's not really a human factor there other than encouraging people to use simple keys. The second has to do with the API we present, and that we can change to force the faster pattern (i.e. migrate and remove the slow one).

> Implement a global cache

This was actually slower, at least with a naive mutex-based implementation.

> Do you have any idea how much each optimization contributes to the overall ~27% improvement?

They actually don't overlap much for the use case I'm benchmarking. The first optimization makes parsing faster, and the second avoids doing it repeatedly. Right now the second only applies to the grok parser, but the first should improve everything (at least for simple paths).

For non-grok stuff, I tested a similar pipeline with `tokenizer` (so only the first optimization in play) and it was ~23% faster.

**Comment by lukesteensen** [comment]
Here are the existing `event` benchmark results `critcmp`'d:

```
group                              after                                  before
-----                              -----                                  ------
create and insert array            1.09  1393.4±18.97ns        ? B/sec    1.00  1273.5±40.80ns        ? B/sec
create and insert nested-keys      1.00  1216.0±21.19ns        ? B/sec    1.66      2.0±0.02µs        ? B/sec
create and insert single-level     1.00   577.9±11.59ns        ? B/sec    1.35   781.4±13.21ns        ? B/sec
iterate all fields array           1.00   641.3±10.38ns        ? B/sec    1.34    861.6±7.96ns        ? B/sec
iterate all fields nested-keys     1.00   667.2±11.45ns        ? B/sec    1.36    907.0±8.44ns        ? B/sec
iterate all fields single-level    1.00    277.0±9.10ns        ? B/sec    1.22   336.6±11.23ns        ? B/sec
```

Slightly slower for arrays (likely opting out of the fast path?), but nothing terribly meaningful imo.

**Comment by a-rodin** [comment]
> 1. Adding a fast path to the `path_iter` parser. We check for "simple" inputs (i.e. no array indexes or escaping) and skip the whole parser in those cases.

In my opinion, if paths are going to be cached in the transform, what can be done for `tokenizer`, then each path is parsed just once, then it might make sense to not complexify the parser by having both "fast" and "full" implemetations. My concern is that having two alternative implementations of parser requires more effort to ensure correctness for both of them, as ideally, there should be separate unit tests for each of the parsers.

However, I like the idea of caching paths in the components. I think that it might sense to even introduce a dedicated type `OwnedPath` instead of just `Vec<PathComponent>` in order to make it possible to alter the implementation later.

**Comment by binarylogic** [comment]
I tend to agree but given the current time constraints this was a good change. It delivered a 23% performance bump without having to make changes across all of Vector. I would like to open issues representing the optimal approach so that we can get to work on it.

**Comment by lukesteensen** [comment]
> In my opinion, if paths are going to be cached in the transform, what can be done for `tokenizer`, then each path is parsed just once, then it might make sense to not complexify the parser by having both "fast" and "full" implemetations.

I agree! I'd be happy to consider this fast path temporary until we finish converting everything to use cached paths.

> I think that it might sense to even introduce a dedicated type `OwnedPath` instead of just `Vec<PathComponent>` in order to make it possible to alter the implementation later.

I agree with this too! I'm also curious if we could use borrowed or at least ref-counted path representations on certain paths, so it's worth thinking about how we present that API.

**Pull request merged**
