### PR TITLE
feat(transforms): Introduce aggregate configuration

### PR DESCRIPTION
**Pull request by tomers**
If aggregate=true reduce transformation behaves like aggregator that
aggregates records and flushes them periodically

type=feat

Closes issue #8747

### CODE REVIEW

**Review by kvitali — APPROVED** [review]

**Comment by spencergilbert** [comment]
Thanks for the PR! It's a little unclear to me what behavior we're trying to introduce here - it seems to me like the `expire_after` and `flush_period` options would provide similar today?

**Comment by kvitali** [comment]
Using the original reduce transform in case similar events are keep coming and coming, the state are not being flushed because `stale_since` member is being updated after each event. For example:
1. We send keep-alive event each 5 seconds for period of 5 minutes
2. We want to have flush period of 60 seconds
3. This means that with original reduce transform only 1 event will passthru after 6 mins

We want a behavior that during those 5 minutes we will passthru 1 event each 60 seconds, 5 event during the period of 5 minutes. This is the reason we altered the reduce transform code.

I saw that you have new `aggregate` transform, but it is for metrics only, is it possible that the aggregate transform will support logs also?

**Review by lukesteensen — COMMENTED** [review]
If I'm understanding correctly, this is essentially changing the meaning of `expire_after_ms`. Currently it's keyed off of the last event collected, and this PR adds an option that when true makes it keyed off of the first event collected. In other words, it's changing it from an idle timeout to more of a maximum total collection period.

In general I can see why this would be helpful, my concern is getting the UI right so that it's easy to understand what it does and how it works. While `flush_periodically` describes what ends up happening, I'm not sure it's quite descriptive enough for unfamiliar users to really understand the mechanism here. One option would be to split `expire_after_ms` into two different timeout values with descriptive-enough names. Another could be to make it an explicit `expire_mode` or similar. I'm curious if others have thoughts on this.

/cc @jszwedko

**Comment by tomers** [comment]
I think the proper solution for issue #8747 is https://github.com/vectordotdev/vector/pull/16146. Closing this for now.

**Pull request closed without merging**
