### PR TITLE
chore(observability): Check for and remove unused internal events

### PR DESCRIPTION
**Pull request by bruceg**
This updates the `check-events` script to scan for uses of internal
events and report an error for any that have none, along with a cleanup
of all such unused internal events.

### CODE REVIEW

**Review by tobz — APPROVED** [review]
Assuming it passes CI, looks good to me. 👍🏻

**Review by blt — APPROVED** [review]
Nice find.

**Comment by blt** [comment]
Sorry to disable auto-merge @bruceg. Looks like http->pipelines dropped some, although I imagine it's behind master a touch:

```
http_pipelines_blackhole | -734.25KiB | -33.47
```

**Comment by blt** [comment]
> Sorry to disable auto-merge @bruceg. Looks like http->pipelines dropped some, although I imagine it's behind master a touch:
> 
> ```
> http_pipelines_blackhole | -734.25KiB | -33.47
> ```
> 
> I will rebase with master branch.

Confirmed that this PR was just slightly behind master branch.

**Pull request merged**
