### PR TITLE
feat(datadog_logs sink): use v2 endpoint for logs

### LINKED ISSUE #9179: Use V2 Datadog Logs API
Companion issue to #9144. The Datadog Agent recently switched to sending to a new API endpoint by default, `/api/v2/logs`. We should have Vector switch to this new API too.

It sounds like the payload is the same, so it may just be a matter of switching the route we are sending to.

### PR DESCRIPTION
**Pull request by jdrouet**
fixes #9179

Signed-off-by: Jérémie Drouet <jeremie.drouet@datadoghq.com>

### CODE REVIEW

**Review by prognant — APPROVED** [review]
LGTM 👍 
It seems new headers may also be added by the Agent in some conditions (As per DataDog/datadog-agent#8896 & DataDog/datadog-agent#8555: DD-EVP-ORIGIN-VERSION, DD-EVP-ORIGIN & DD-PROTOCOL) I don't exactly know their purpose, but it looks like they are optional.

**Review by blt — CHANGES_REQUESTED** [review]
There are some problems with this, considering that the v2 endpoint is undocumented. We reference https://docs.datadoghq.com/api/latest/logs/#send-logs in the module documentation. Is this documentation still valid? Do the constraints in this module regarding payload size, number of members in the payload etc still hold in the v2 endpoint? If not, can we adjust those so vector isn't sending invalid payloads? 

If the above docs are not valid we need to remove reference to them and note that we're supporting an undocumented endpoint, then list out its constraints as we know them.

**Comment by jdrouet** [comment]
@blt I've asked internally if there's a plan to update the doc.

**Review by blt — APPROVED** [review]

**Comment by blt** [comment]
> @blt I've asked internally if there's a plan to update the doc.

Excellent. If the docs location changes we'll need to adjust our docs, but this looks good to me.

**Review by jszwedko — APPROVED** [review]

**Review by vladimir-dd — APPROVED** [review]

**Comment by vladimir-dd** [comment]
> LGTM 👍
> It seems new headers may also be added by the Agent in some conditions (As per [DataDog/datadog-agent#8896](https://github.com/DataDog/datadog-agent/pull/8896) & [DataDog/datadog-agent#8555](https://github.com/DataDog/datadog-agent/pull/8555): DD-EVP-ORIGIN-VERSION, DD-EVP-ORIGIN & DD-PROTOCOL) I don't exactly know their purpose, but it looks like they are optional.

I'd like to set headers(DD-EVP-ORIGIN-VERSION, DD-EVP-ORIGIN) in #9298. DD-PROTOCOL should be set if it is some custom protocol, which is not the case here.

**Pull request merged**
