### PR TITLE
chore(ci): Regenerate certificates used for nats integration tests

### PR DESCRIPTION
**Pull request by jszwedko**
They had expired.

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

### CODE REVIEW

**Comment by jszwedko** [comment]
Ideally these would be part of the certificate hierarchy at `tests/data/ca`, but just unblocking `master` for now.

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-nats

**Review by neuronull — APPROVED** [review]

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-nats

**Comment by jszwedko** [comment]
Force merging to unblock master since the nats tests passed.

**Pull request merged**
