### PR TITLE
chore(dev): Add script to run vector with minimal features

### PR DESCRIPTION
**Pull request by bruceg**

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
🎉 

I personally wouldn't mind seeing this just return the features so I could compose it like `cargo build --no-default-features --features $(./scripts/features vector.toml) vector.toml` but this covers most of my usage.

**Review by lukesteensen — APPROVED** [review]
Very cool! I agree it'd be nice not to be tied to `cargo run`, so maybe it could just pass through a subcommand? Something like `./min-features check` or similar.

**Comment by bruceg** [comment]
> I personally wouldn't mind seeing this just return the features

Makes sense, done in 3daae71ec

**Review by jszwedko — APPROVED** [review]
Awesome, thanks for breaking it up.

**Pull request merged**
