### PR TITLE
chore(dev): Set up vdev to allow `cargo vdev`

### PR DESCRIPTION
**Pull request by bruceg**
via `cargo run --package vdev`

### CODE REVIEW

**Comment by lukesteensen** [comment]
If we do this, can we get rid of all the build/distribution/install bits from the initial PR?

**Comment by bruceg** [comment]
> If we do this, can we get rid of all the build/distribution/install bits from the initial PR?

I think so, yes, at least a lot of it.

**Comment by spencergilbert** [comment]
I know we originally had some discussion between `cargo xtask` and a standalone binary, and ended up going with the latter.

This seems more akin to `xtask`, are we intentionally reversing that decision or am I not clear on the changes happening here?

**Comment by bruceg** [comment]
> I know we originally had some discussion between `cargo xtask` and a standalone binary, and ended up going with the latter.
> 
> This seems more akin to `xtask`, are we intentionally reversing that decision or am I not clear on the changes happening here?

This approach allows for both approaches. That is, it doesn't preclude installing a standalone binary, as `cd vdev && cargo build` still builds just the `vdev` executable (albeit in a different location). It just allows us to run `cargo vdev` from anywhere in the source tree and get the same tool without external installation, pathing, etc.

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
