### PR TITLE
fix(internal_logs source): ensure all early buffered events are captured

### PR DESCRIPTION
**Pull request by tobz**
# Context

While investigating a fix for #12251, I discovered that the "early buffering" feature used for the `internal_logs` source did not appear to reliably capture early events.

Early events, in this case, are log events that occurred between when `tracing` is initialized and when we disable early buffering, which logically occurs after the topology runner tells us that the topology is now running. There's a few reasons here why the collection of early events as-is is unsatisfactory:

- the topology can report back as running, even though a component has not yet reached a point of waiting for the next/first input event
- the `internal_logs` source, as such, created its trace subscription (used to collect these internal log events) when it was run, not when it was built via the topology builder
- the logic for acquiring a subscription to the event stream is itself the point where the buffered-so-far events are drained out and handed over to the subscription
- this means that a single subscription will change the early buffer leading to a guaranteed inconsistency if multiple subscribers are ever used (practically, people will only have a single `internal_logs` source)
- this also means that events can be missed if the subscription happens before early buffering is disabled and other log events are still occurring

# Solution

This PR fixes the aforementioned issue by reworking how early buffering functions on the subscription side.

While early buffering is mostly the same -- mutex-protected buffer of events -- we've changed to a waiter-based approach where subscriptions don't greedily consume the current early buffer, but instead get a receiver that represents a promise to get a vector of all log events that were buffered up until the point that early buffering was stopped.

Now, the stopping of early buffering itself triggers the logic that consumes the buffer, sends a copy of it to every waiting subscriber, and switches over the broadcast layer to continue sending new events to the broadcast stream itself instead of buffering them.

We've tweaked `TraceSubscription` somewhat, where there's now a method to await the buffered events -- which returns immediately if the subscription was acquired after early buffered was disabled -- and a separate one to convert the subscription object to the broadcast stream.  That part has become somewhat more succinct but it's not perfect, and I'm open to thoughts on making that part an opaque impl detail.

## Notes

I've removed `crate::trace::current_span` as it was kind of a loner function with no real keystroke savings or apparent value, which ended up touching quite a few files.

### CODE REVIEW

**Comment by tobz** [comment]
I really don't understand these soak test results... does the syslog source and/or splunk sink really log _so_ much that they're hitting these codepaths and somehow slowing down?

Like, the previous code path was:

- load early buffer via `OnceCell` (atomic load to check if value initialized yet)
- try to lock buffer (std mutex, `pthread`-based, not particularly fast)
- if `Option<Vec<...>>` in the lock is `Some`, write it to that
- also always try and write it to the broadcast channel

Now the code path is:

- load `SHOULD_BUFFER` (single atomic load)
- if true, do first three steps of previous code path
- if false, return event immediately
- if event returned, send to broadcast channel

Arguably, we're doing _much_ less work -- a single atomic load vs single atomic load + mutex lock -- so it strains belief that this could actually be slower... and I'm pretty sure I have `master` fully merged and up-to-date... 🤔

**Comment by jszwedko** [comment]
Yeah, those numbers are odd. I merged in `master` again to see if they are consistent.

**Review by bruceg — APPROVED** [review]
This looks reasonable to me, albeit a little more complicated. The added documentation is great.

**Comment by tobz** [comment]
I plan on trying to run the soak locally to do some profiling to understand what the heck is going on.  I can totally believe that _something_ is happening... it's just hard to grok _how_.

**Pull request merged**
