### PR TITLE
feat(kubernetes_logs source): add pod annotations

### LINKED ISSUE #8338: Expose pod annotations in kubernetes_logs
### Current Vector Version

```
vector 0.14.0 (x86_64-apple-darwin 5f3a319 2021-06-03)
```

### Use-cases

For some workloads being managed by an operator, it is not possible to add pod labels, so you have to fall back to annotations (e.g. `istio-operator`).

Since pod annotations are not exposed, I cannot handle the logs properly.

### Attempted Solutions

none

### Proposal

Expose pod annotations, maybe optionally, being disabled by default.

### PR DESCRIPTION
**Pull request by aquarhead**
Close #8338

The issue should have enough context, let me know if you need more information. Also, should we make this behind a flag?

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Thanks! I do wonder if we need to consider exposing some controls so that users can decide what/how many labels and annotations to add - we could definitely bloat some events depending on all this metadata

**Review by spencergilbert — CHANGES_REQUESTED** [review]
Oh - actually @aquarhead would you mind updating the component documentation to reflect this feature as well?

**Comment by aquarhead** [comment]
Absolutely, sorry I forgot about that.

**Comment by aquarhead** [comment]
> Thanks! I do wonder if we need to consider exposing some controls so that users can decide what/how many labels and annotations to add - we could definitely bloat some events depending on all this metadata

Didn't notice this comment since I was on phone, I'll give it a try to add some filters, is there existing benchmark suite I can use to compare the effect?

**Comment by MOZGIII** [comment]
I'd advocate for testing this thoroughly - it will definitely increase the average amount of metadata on the average cluster tenfold without providing useful info. This should be opt-in imo, or enabled dynamically on a per-annotation-field basis.

**Comment by aquarhead** [comment]
> For instance, think about `kubectl apply` - it adds an annotation with _the whole resource_ as in the source of apply. It can easily be KBs of data per pod - per event.

That should be on the "controller" resource, such as `Deployment` or `StatefulSet`? Each pod would not have that annotation attached, I believe? (not with access to a kube cluster atm, will check later) I guess it would apply for `Pod` resources directly, but I don't think that necessarily translates to "increase the average amount of metadata on the average cluster tenfold without providing useful info".

**Comment by spencergilbert** [comment]
> I'd advocate for testing this thoroughly - it will definitely increase the average amount of metadata on the average cluster tenfold without providing useful info. This should be opt-in imo, or enabled dynamically on a per-annotation-field basis.
> 
> For instance, think about `kubectl apply` - it adds an annotation with _the whole resource_ as in the source of apply. It can easily be KBs of data per pod - per event.

@MOZGIII as far as I can tell, @aquarhead is correct. If you `kubectl apply` on a singular pod it may include the "last applied config" annotation. I think opt-in is probably appropriate for all of these "extensions" but I'm curious what @jszwedko thinks as well

**Comment by jszwedko** [comment]
Discussed a bit offline with @spencergilbert . As long as we don't expect this to bloat the event payload significantly more than any of the other metadata, which it seems like we don't, I think it's fine to include by default. Users can disable it by setting `pod_annotations = ""` in the config.

**Comment by spencergilbert** [comment]
@aquarhead when you get around to the docs could you also run `make signoff` to resolve the DCO error?

**Comment by aquarhead** [comment]
Will do, did I miss a contributing guide somewhere?

**Comment by jszwedko** [comment]
@aquarhead the DCO bits are mentioned over here: https://github.com/vectordotdev/vector/blob/master/docs/CONTRIBUTING.md#dco

**Comment by aquarhead** [comment]
@jszwedko Thanks! I totally missed that, I thought `docs` are for Vector's documentation... It might help future contributors if it's in the root directory, or at least have a link in the root README.

I added docs now and signed off, also run a `make check-docs` locally which was all good, I don't know if there's a way for me to see the rendered website? Though I mostly followed the format of `pod_labels` so it should be fine.

**Comment by spencergilbert** [comment]
> @jszwedko Thanks! I totally missed that, I thought `docs` are for Vector's documentation... It might help future contributors if it's in the root directory, or at least have a link in the root README.
> 
> I added docs now and signed off, also run a `make check-docs` locally which was all good, I don't know if there's a way for me to see the rendered website? Though I mostly followed the format of `pod_labels` so it should be fine.

Thanks! I remember a good amount of back and forth on where those needed to live, "developer" docs ended up in `docs/` (IIRC) and everything website in `website/`.

For the rendered site 👀 : https://deploy-preview-9180--vector-project.netlify.app/docs/reference/configuration/sources/kubernetes_logs/?utm_source=github&utm_campaign=bot_dp#pod_annotation_fields.pod_annotations

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
