### PR TITLE
enhancement(influxdb_metrics sink): add TLS settings to influxdb_logs and influxdb_metrics sinks

### PR DESCRIPTION
**Pull request by oktal**
TLS settings were available for ElasticSearch sink.

Add TLS settings for `influxdb_logs` and `influxdb_metrics` sinks.

It might be a good idea to provide tls settings for every sink based on `HttpClient`.

The TLS options need to be documented as well

### CODE REVIEW

**Review by ktff — APPROVED** [review]
As mentioned, the documentation needs to be updated.

> It might be a good idea to provide tls settings for every sink based on HttpClient

Yep, for a rather small amount of change we would gain nice features. Sounds like this should be an issue with the list of components to update.

**Comment by ktff** [comment]
It seams the `infulxdb` test should be updated.

**Review by bruceg — CHANGES_REQUESTED** [review]
As @ktff indicated, this needs docs and test cases, but the code looks correct. Thanks.

I'll also give a :+1: on setting this up for every `HttpClient` sink. That should be done separately though.

**Comment by oktal** [comment]
Hi @bruceg what test cases would you add ? integration tests through https ?

**Comment by bruceg** [comment]
Having a test where it attempts to use HTTPS explicitly would be good, to ensure the functionality is available.

**Comment by oktal** [comment]
Hi @bruceg I just added an integration test that pushes metrics through https

**Comment by jamtur01** [comment]
@oktal Neat. All this needs is the docs update, if you don't have a chance to do it @ktff can you please pick it up? Thanks!

**Review by bruceg — APPROVED** [review]
Looks good except for missing docs as noted.

**Comment by binarylogic** [comment]
@oktal thanks for this! Would you mind resolving the conflicts and then updating [the `tls` feature](https://github.com/timberio/vector/blob/9b1eada50e8679bfe4f4e97660ef8cf6e2090dae/docs/reference/components/sinks/influxdb_logs.cue#L36) to:

https://github.com/timberio/vector/blob/9b1eada50e8679bfe4f4e97660ef8cf6e2090dae/docs/reference/components/sinks/azure_monitor_logs.cue#L28-L33

**Comment by binarylogic** [comment]
@oktal @ktff is this enabled by default? It should be given that data is passing over the internet.

**Comment by binarylogic** [comment]
@oktal @ktff should this be enabled by default? It is assume data will be traveling over the internet?

**Comment by ktff** [comment]
@binarylogic yes, and it is enabled by default, for the reason you mentioned.

**Comment by binarylogic** [comment]
Thanks @oktal

**Pull request merged**
