### PR TITLE
fix(observability): Lower log level for HTTP errors

### PR DESCRIPTION
**Pull request by jszwedko**
This lowers the log level for errors seen at the HTTP client level to
debug. If the error is fatal and won't be retried, it will be logged at
a higher level by the component using the HTTP client. As it stands, it
is confusing to users that they see an error log for a request failure
that will automatically be retried.

It's possible we shouldn't be emitting the metrics at this level either,
but I'll leave that as a follow-up as part of implementing
https://github.com/vectordotdev/vector/pull/12822.

Closes: #12850

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
I'd also think the metrics are worth reconsidering

**Comment by jszwedko** [comment]
> I agree with lowering this from `error!` but am a little concerned about dropping it below `info!`, which will completely hide the individual errors which given an indication why the request would be delayed. Also, if these error metrics are also being output by the component, then they don't belong here, in which case is this really an internal event?

Dropped it to `warn` for now. I still think the way we are logging errors at this level as well as in sinks isn't quite right, but I'll leave that as a followup.

**Comment by kellytk** [comment]
@jszwedko 

> I still think the way we are logging errors at this level as well as in sinks isn't quite right, but I'll leave that as a followup.

Is there an associated issue for that?

**Comment by jszwedko** [comment]
> @jszwedko
> 
> > I still think the way we are logging errors at this level as well as in sinks isn't quite right, but I'll leave that as a followup.
> 
> Is there an associated issue for that?

It's intended to be covered by https://github.com/vectordotdev/vector/issues/12921

**Comment by hgiasac** [comment]
@jszwedko we also see many `connection closed before message completed` errors in the Honeycomb. Does this PR fix that error too?

**Comment by jszwedko** [comment]
> @jszwedko we also see many `connection closed before message completed` errors in the Honeycomb. Does this PR fix that error too?

Hi @hgiasac ! It should just make log them warnings instead of errors.

**Comment by hgiasac** [comment]
Got it. Thanks for the clarification!

**Pull request merged**
