### PR TITLE
enhancement(vrl): Allow parse regex fns to accept expressions for their patterns

### PR DESCRIPTION
**Pull request by moogeric**
enhancement(vrl): Allow parse regex fns to accept expressions for their patterns

Signed-off-by: Eric Schirtzinger <eric.schirtzinger@moogsoft.com>

### CODE REVIEW

**Comment by moogeric** [comment]
Taking expressions amongst other utility allows saving off a pattern to a variable to then pass in as an argument. Core feature wise this seems to be working, though I noticed there are some newer vrl tests that are failing. I wasn't sure if that is a sign this is no longer adhering to vrl grammar, or if simply the tests need to be update to reflect the changes. Maybe it isn't quite feature complete, I'm not entirely clear on all the subtleties of vrl. I'm sure there is some additional doc work needed as well.

**Comment by JeanMertz** [comment]
I haven't done a deep-dive into the technical implementation, but on a high-level, I don't expect we're willing to accept the change as it stands currently.

The reason for this, is that we want to avoid people compiling a regex at runtime as much as possible. Regex compilation is an expensive operation, and people should avoid doing so at runtime, as that'll result in the regex being re-compiled for each individual events, which will tank throughput.

If you really *must* compile a regex at runtime, we have a separate [`to_regex`](https://vector.dev/docs/reference/vrl/functions/#to_regex) function, which comes with the warning I noted above in the documentation.

Now, the part that I *do* agree with, is that these two examples should be treated equally:

```coffee
parse_regex!("foobar", r'(foo)(.*)', true)
```

```coffee
re = r'(foo)(.*)'
parse_regex!("foobar", re, true)
```

While currently, the first succeeds, but the second fails:

```
error[E610]: function compilation error: error[E400] unexpected expression type
  ┌─ :1:7
  │
1 │ foo = parse_regex!("foobar", re, true)
  │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │       │
  │       unexpected expression for argument "pattern"
  │       expected: regex
  │       received: variable call
  │
  = learn more about error code 400 at https://errors.vrl.dev/400
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

However, this should be fixed at the compiler level, specifically in the type checker, such that passing a variable call of type `regex` should be no different from passing in an actual regex value into the function.

So, I'd be happy to take a PR that fixes this shortcoming. Note that this specific shortcoming is tracked in https://github.com/vectordotdev/vector/issues/7428.

**Comment by Anonymodesu** [comment]
To help with readability, would it be possible to define regex across multiple lines like for [Multiline strings](https://vector.dev/docs/reference/vrl/expressions/#multiline-strings)?```toml

Something like:
```toml
source = '''
  complex_regex = r'foo \
                    bar \
                    baz'
'''
```

**Comment by fuchsnj** [comment]
I apologize for the inconvenience, but VRL has been moved to a [separate repo](https://github.com/vectordotdev/vrl), and this PR will need to be moved over there.

**Pull request closed without merging**
