### PR TITLE
enhancement(topology): Remove `ComponentId.value`

### PR DESCRIPTION
**Pull request by leebenson**
Small adjustment per https://github.com/timberio/vector/pull/8706#discussion_r692487121 to remove the `ComponentId.value` field.

### CODE REVIEW

**Comment by jdrouet** [comment]
Although, I'm going to put it back right away 🤔

**Comment by leebenson** [comment]
@jdrouet, if you have an imminent PR that reverts this, feel free to close.

**Comment by jdrouet** [comment]
I'll have one today I think

**Comment by jdrouet** [comment]
like this one https://github.com/timberio/vector/pull/8810

**Review by jszwedko — APPROVED** [review]
Thanks @leebenson !

**Comment by jszwedko** [comment]
I ended up updating this PR to also switch displaying the ids in logs to using `Display` as they were otherwise showing up as:

```
Aug 24 10:46:02.359  INFO vector::topology::running: Starting source. id=ComponentId { value: "source0", id: "source0" }
```

I'll merge once CI passes.

**Pull request merged**
