### PR TITLE
chore(ci): Swap out mockwatchlogs for localstack

### PR DESCRIPTION
**Pull request by jszwedko**
Now that localstack supports CloudWatch Logs as a service.

Signed-off-by: Jesse Szwedko <jesse.szwedko@datadoghq.com>

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-aws

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-aws

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-aws

**Comment by balonik** [comment]
@jszwedko it looks like the problem is just in different order of elements in the arrays.

```
Differences (-left|+right):
 [
-    "JSZZsjJTGPDQ10QtksYVmLDjjnDuryk3UeWr9sZs7CgC3pql52NyCMt2ktQHww4uqLNBbQgpTr55MrHaE7no7310pzSdORsiX1eo",
-    "6KGbduMeX2hdfuShWjoMmZYQ9M5XJAQCYzYZPEKRR6Q4HJraEzKfdLfpZtdMLYNZHRZPSOsCFKwmR7zTa2RrvsH5eoot4lAhF1xB",
     "u9yYAzLpFzMAIZbPFBXk0J6P0SY7lQDVdnKBkTnOd5Mn5tGhzzYam3I7uGKDzf2CdJ2suPW3aZRFLLdePkasYngwmb83eFx63uaz",
     "oL4OWJsWYjWZMdkqsOmIlgwqyzVNYsIbbgc3v9ypHJB4cC5fTmhr32qSnNGzAyHvILk1qUscHj2osu7thTXalFpAKPAchhqcSvgM",
     "HzoAUMymQEe8ts6LWr7S4IsqKEq62gBoXdbboNqsusKwBFnUHo5K4ikHdzmR3tjn2AbptscGndikfIPAomdI0YpPfK8j7LVjjZcL",
+    "6KGbduMeX2hdfuShWjoMmZYQ9M5XJAQCYzYZPEKRR6Q4HJraEzKfdLfpZtdMLYNZHRZPSOsCFKwmR7zTa2RrvsH5eoot4lAhF1xB",
+    "JSZZsjJTGPDQ10QtksYVmLDjjnDuryk3UeWr9sZs7CgC3pql52NyCMt2ktQHww4uqLNBbQgpTr55MrHaE7no7310pzSdORsiX1eo",
 ]
 ```

sorting the arrays might just do the trick, like:
` assert_eq!(output_lines, input_lines); -> assert_eq!(output_lines.sort(), input_lines.sort());`

**Comment by balonik** [comment]
Trying it in https://github.com/vectordotdev/vector/pull/21140

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-aws

**Comment by balonik** [comment]
@jszwedko almost there. those arrays are not defined as mutable 😩

```
error[E0596]: cannot borrow `output_lines` as mutable, as it is not declared as mutable
```

**Comment by jszwedko** [comment]
> @jszwedko almost there. those arrays are not defined as mutable 😩
> 
> ```
> error[E0596]: cannot borrow `output_lines` as mutable, as it is not declared as mutable
> ```

I just saw that too :) I'll fix it up.

**Review by jszwedko — COMMENTED** [review]
/ci-run-integration-aws

**Comment by jszwedko** [comment]
This looks to be working now. Thanks for the suggestion and the assist @balonik !

**Review by lukesteensen — APPROVED** [review]

**Pull request merged**
