### PR TITLE
enhancement(websocket sink): Allow setting HTTP authorization header

### PR DESCRIPTION
**Pull request by wez470**
Fixes: https://github.com/vectordotdev/vector/issues/13386

Allows setting the HTTP authorization header during upgrade requests for the websocket sink. ~I was a bit unsure for the testing portion. I believe the websocket lib being used in the tests currently doesn't give an easy way to test the header was sent. I did however change one test to set the auth so that the code path would be run and verified functionally that it sends the header. I'm curious for thoughts on if this is good enough or ideas how to best go about testing it. Thanks!~

### CODE REVIEW

**Comment by tobz** [comment]
@wez470 I think what you'd want to do is make the `send_events_and_assert` and `create_count_receiver` functions take an `Option<Auth>`, and if it was populated, `create_count_receiver` would use [`accept_hdr_async`](https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/fn.accept_hdr_async.html) instead of `accept_async`, and it could get the headers during the initial WebSocket handshake request, similar to how it's shown being done here: https://github.com/snapview/tokio-tungstenite/issues/98

**Review by tobz — APPROVED** [review]
Woo, this looks good to me. Appreciate you getting the unit tests sorted out. 👍🏻

**Comment by tobz** [comment]
@wez470 Actually, sorry, one more small change required: we need to document these new configuration fields.

You'll need to edit `website/cue/reference/components/sinks/websocket.cue` and add the new `auth` section. Luckily, you can crib this from exactly how we do it for the `http` sink by looking for the `configuration: { auth: { ... } }` bit in `website/cue/reference/components/sinks/http.cue`, and copy pasting that `auth` block into the `configuration` section for `websocket.cue`.

**Review by tobz — APPROVED** [review]

**Comment by wez470** [comment]
Thanks for the review and detailed help!

**Pull request merged**
