### PR TITLE
chore: Use cargo-nextest for integration tests too

### PR DESCRIPTION
**Pull request by jszwedko**
Expanding usage from unit tests.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
The AWS test is failing because it is failing on master (it also shows the retries are working though!) so this is ready for review.

**Review by spencergilbert — APPROVED** [review]
kinda annoying this is duplicated across so many files

**Comment by jszwedko** [comment]
> kinda annoying this is duplicated across so many files

Yeah, true, maybe we could DRY it up a bit by using an `entrypoint.sh` that is shared by all of them.

**Comment by spencergilbert** [comment]
> > kinda annoying this is duplicated across so many files
> 
> Yeah, true, maybe we could DRY it up a bit by using an `entrypoint.sh` that is shared by all of them.

_or we could use gitlab ci and jsonnet to dynamically create the ci config at runtime!!!_ 😆

**Comment by blt** [comment]
> > > kinda annoying this is duplicated across so many files
> > 
> > 
> > Yeah, true, maybe we could DRY it up a bit by using an `entrypoint.sh` that is shared by all of them.
> 
> _or we could use gitlab ci and jsonnet to dynamically create the ci config at runtime!!!_ laughing

Spencer no.

**Pull request merged**
