### PR TITLE
feat(new transform): Initial `logfmt_parser` transform impl

### LINKED ISSUE #1482: New `logfmt_parser` transform
A simple transform that parses [logfmt](https://brandur.org/logfmt).

There's a lot to be said about this format 😄, such as nested key support, implicit typing, and so on. To start we should:

- [ ] Produce flat structures only. Ex: keys with `.` characters will not result in nested structures. We can consider adding this as an option later.
- [ ] Make a best effort to coerce numbers.
- [ ] Support the `types` sub-table that is available in other parsers (`regex_parser`).

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #1482 

Adds a pretty conservative logfmt parser. It will basically scan and extract any logfmt-style `foo=bar` pairs in the given field (handling quoting and such), and add them as fields on the event. If there are no such pairs, nothing is added and the message is passed through normally.

### CODE REVIEW

**Review by binarylogic — APPROVED** [review]
Docs look good 👍

**Comment by binarylogic** [comment]
Can we rename this to `logfmt_parser` for consistency?

**Review by bruceg — APPROVED** [review]
LGTM

**Comment by binarylogic** [comment]
Can we add a test that accounts for `#` in the key name? Heroku uses this for their [log runtime metrics](https://devcenter.heroku.com/articles/log-runtime-metrics):

```
source=web.1 dyno=heroku.2808254.d97d0ea7-cf3d-411b-b453-d2943a50b456 sample#memory_total=21.00MB sample#memory_rss=21.22MB sample#memory_cache=0.00MB sample#memory_swap=0.00MB sample#memory_pgpgin=348836pages sample#memory_pgpgout=343403pages
```

**Pull request merged**
