### PR TITLE
feat(config): support loading secrets from files and directories

### LINKED ISSUE #20747: Support reading auth token from file
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I am deploying vector in k8s and I am trying to scrape metrics from cadvisor. For that vector would need to be configured to using the content in mounted serviceaccount token file `/var/run/secrets/kubernetes.io/serviceaccount/token`

equivalent curl command:
`curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc/api/v1/nodes/ns1/proxy/metrics/cadvisor`

Vector only supports specifying the token value under auth.token

### Attempted Solutions

_No response_

### Proposal

Proposing vector to add an option to read auth.token from a file.

### References

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by tie**
This change adds a secrets backend that retrieves secrets from files and directories. For example, this is useful for loading secrets from [systemd credentials directory](https://systemd.io/CREDENTIALS) and similar mechanisms.
E.g.
```toml
[secret.systemd_credentials]
type = "directory"
path = "$CREDENTIALS_DIRECTORY"
remove_trailing_whitespace = true
```
`SECRET[systemd_credentials.password.txt]` → `$CREDENTIALS_DIRECTORY/password.txt`

Closes #20747

References:
- #21270
- https://github.com/vectordotdev/vector/pull/20138#pullrequestreview-1968616241

### CODE REVIEW

**Review by estherk15 — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Apologies @tie ! This one fell off my radar. I found it again skimming open PRs. This looks like a great addition. I appreciate you adding the behavior tests.

**Comment by jszwedko** [comment]
Could you add a changelog fragment here? I attempted to, but I'm not able to push to this branch. You can apply this diff:

```diff
ffbf204849 - (HEAD -> tie/master) add changelog entry (32 seconds ago) <Jesse Szwedko>
diff --git a/changelog.d/add-file-secrets.enhancement.md b/changelog.d/add-file-secrets.enhancement.md
new file mode 100644
index 0000000000..6c80fe8540
--- /dev/null
+++ b/changelog.d/add-file-secrets.enhancement.md
@@ -0,0 +1,4 @@
+Vector now supports two additional back-ends for loading secrets: `file`, for leading a set of
+secrets from a JSON file, and `directory`, for loading secrets from a list of files.
+
+authors: tie
```

**Review by jszwedko — APPROVED** [review]
Thank you!

**Comment by pront** [comment]
Can you please run:
```
./website/scripts/cue.sh fmt
CI=true make check-docs
```
and commit the result? I tried to do it but cannot push to the fork directly.

**Comment by tie** [comment]
@pront, done. Note that running `./website/scripts/cue.sh fmt` changed many other unrelated files so I’ve only pushed the changes to `website/cue/reference/configuration.cue`.

**Comment by tie** [comment]
`make test-behavior` failed because it tries to run `vector test` against all files in `tests/behavior/config` directory, including test data. I’ve moved these files to `tests/data/secret-backends`.

**Comment by jszwedko** [comment]
Aha, thanks @tie

**Pull request merged**
