### PR TITLE
chore(website): bump openssl version used for links in docs

### PR DESCRIPTION
**Pull request by hhromic**
This simple PR bumps the major/minor openssl version in the website variables so the generated links to external OpenSSL documentation are consistent with the vendored version of openssl used in Vector.

For reference, openssl was upgraded from 3.1.x to 3.2.x in #19364.

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]

**Review by jszwedko — APPROVED** [review]
Thanks for catching that! I forgot we had a link to the OpenSSL docs.

**Comment by hhromic** [comment]
> Thanks for catching that! I forgot we had a link to the OpenSSL docs.

Happy to help!
I am investigating how to automate this (you know, software at the service of humans and not the other way around).
So far I have two major ideas: (1) make Hugo read `../Cargo.lock` to automatically get any version number required from the current set of dependencies or (2) make `build.rs` generate a `website/depversions.toml` file with Hugo params that Hugo then can use to directly read this information.

Do you have any preference for these ideas? or a better idea?
Also, I noticed that you moved the generation from Netlify to Amplify, and the specs used are no longer avaiable in the repository. This means I cannot confirm which version of Hugo is now being used to generate the website :(.

**Comment by jszwedko** [comment]
> > Thanks for catching that! I forgot we had a link to the OpenSSL docs.
> 
> Happy to help! I am investigating how to automate this (you know, software at the service of humans and not the other way around). So far I have two major ideas: (1) make Hugo read `../Cargo.lock` to automatically get any version number required from the current set of dependencies or (2) make `build.rs` generate a `website/depversions.toml` file with Hugo params that Hugo then can use to directly read this information.

If we can manage the former, that seems better to me to have it be part of the website build process since otherwise we'd need to commit changes to a `website/depversions.toml` file since the website build doesn't build Vector. Certainly doable, but I think we'd then also want a CI check to make sure it isn't out of date. I think fetching the version from the Cargo.lock file could be a prereq task in `websites/Makefile`.
 
> Do you have any preference for these ideas? or a better idea? Also, I noticed that you moved the generation from Netlify to Amplify, and the specs used are no longer avaiable in the repository. This means I cannot confirm which version of Hugo is now being used to generate the website :(.

That is an unfortunate side-effect. There's another team that owns the website infrastructure now so the deploy bits were moved over to them. Currently the Hugo version is 0.84.0 though.

**Comment by hhromic** [comment]
> If we can manage the former, that seems better to me to have it be part of the website build process since otherwise we'd need to commit changes to a `website/depversions.toml` file since the website build doesn't build Vector. Certainly doable, but I think we'd then also want a CI check to make sure it isn't out of date. I think fetching the version from the Cargo.lock file could be a prereq task in `websites/Makefile`.


Yes was thinking the same about tooling in the Makefile. I'll take a look and let you know!

**Pull request merged**
