### PR TITLE
fix(docker_logs source): Fix panic after bump bollard

### LINKED ISSUE #13861: panic with sources `docker_logs`
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

panic when starting with docker_logs source configurated

### Configuration

```text
[sources.docker]
type = "docker_logs"

[sinks.console]
type = "console"
inputs = [ "docker" ]
encoding.codec = "json"
```

### Version

vector 0.24.0 (x86_64-unknown-linux-gnu debug=full)

### Debug Output

```text
2022-08-05T16:29:04.763770Z  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,vrl=trace,file_source=trace,tower_limit=trace,rdkafka=trace,buffers=trace,kube=trace"
2022-08-05T16:29:04.764039Z  INFO vector::app: Loading configs. paths=["config/vector.toml.tmp"]
2022-08-05T16:29:04.768411Z DEBUG vector::config::loading: No secret placeholder found, skipping secret resolution.
2022-08-05T16:29:04.770886Z DEBUG vector::topology::builder: Building new source. component=docker
2022-08-05T16:29:04.772750Z  INFO vector::sources::docker_logs: Capturing logs from now on. now=2022-08-05T16:29:04.772510822+00:00
2022-08-05T16:29:04.773250Z  INFO vector::sources::docker_logs: Listening to docker log events.
2022-08-05T16:29:04.773591Z DEBUG vector::topology::builder: Building new sink component=console
2022-08-05T16:29:04.774201Z  INFO vector::topology::running: Running healthchecks.
2022-08-05T16:29:04.774358Z DEBUG vector::topology::running: Connecting changed/added component(s).
2022-08-05T16:29:04.774556Z  INFO vector::topology::builder: Healthcheck: Passed.
2022-08-05T16:29:04.774579Z DEBUG vector::topology::running: Configuring outputs for source. component=docker
2022-08-05T16:29:04.774726Z DEBUG vector::topology::running: Configuring output for component. component=docker output_id=None
2022-08-05T16:29:04.774855Z DEBUG vector::topology::running: Connecting inputs for sink. component=console
2022-08-05T16:29:04.775142Z DEBUG vector::topology::running: Adding component input to fanout. component=console fanout_id=docker
2022-08-05T16:29:04.775415Z DEBUG vector::topology::running: Spawning new source. key=docker
2022-08-05T16:29:04.775800Z TRACE vector::topology::running: Spawning new sink. key=console
2022-08-05T16:29:04.776076Z DEBUG source{component_kind="source" component_id=docker component_type=docker_logs component_name=docker}: vector::topology::builder: Source pump starting.
2022-08-05T16:29:04.776492Z  INFO vector: Vector has started. debug="true" version="0.24.0" arch="x86_64" build_id="none"
2022-08-05T16:29:04.777238Z DEBUG sink{component_kind="sink" component_id=console component_type=console component_name=console}: vector::utilization: utilization=0.10581087667989697
2022-08-05T16:29:04.779203Z TRACE vector: Beep.
2022-08-05T16:29:04.782360Z ERROR source{component_kind="source" component_id=docker component_type=docker_logs component_name=docker}: vector::internal_events::docker_logs: Error in communication with Docker daemon. error=DockerResponseServerError { status_code: 500, message: "strconv.ParseInt: parsing \"2022-08-05 16:29:04\": invalid syntax" } error_type="connection_failed" stage="receiving" container_id=None internal_log_rate_secs=10
2022-08-05T16:29:04.782854Z  INFO vector_common::shutdown: All sources have finished.
2022-08-05T16:29:04.782873Z DEBUG source{component_kind="source" component_id=docker component_type=docker_logs component_name=docker}: vector::topology::builder: Finished.
2022-08-05T16:29:04.782998Z  INFO vector: Vector has stopped.
2022-08-05T16:29:04.783122Z DEBUG source{component_kind="source" component_id=docker component_type=docker_logs component_name=docker}: vector::topology::builder: Source pump finished.
2022-08-05T16:29:04.783855Z DEBUG sink{component_kind="sink" component_id=console component_type=console component_name=console}: vector::topology::builder: Finished.
```

### Example Data

_No response_

### Additional Context

_No response_

### References

the bug is introduced from #13255

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>

fix #13861

### CODE REVIEW

**Comment by zhongzc** [comment]
PTAL @jszwedko

**Comment by zhongzc** [comment]
PTAL @neuronull

**Comment by tobz** [comment]
Merged this without two of the checks passing as they were known failures (DD integration tests on a contributor PR, and the Prometheus unit test issue on macOS).

**Comment by tobz** [comment]
@zhongzc Thanks for your contribution. 👍🏻

**Pull request merged**
