### PR TITLE
chore: Refactor pipelines soaks to use `datadog_agent` as input

### PR DESCRIPTION
**Pull request by jszwedko**
This more closely matches expected usage of the `pipelines` config provided where the input is expected to be from the Datadog Agent.

This is just renaming along with slight config tweaks. I kept the lading
source as `http` to use the pregenerated logs which match pipeline
conditions, but added the other keys that Vector would expect to see on
logs coming into `datadog_agent`.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by blt — APPROVED** [review]

**Comment by blt** [comment]
`datadog_agent_pipelines_blackhole` has a mean of 14MiB/s/core. That... hmm. When it was `http` at the source we were down at 1.3MiB/s/core-ish. 

@jszwedko I'm not reading that table wrong, right? Lol did we just stumble onto what's been up with `http->pipelines->blackhole` and the answer was _the http source itself_?

**Comment by jszwedko** [comment]
@blt I pushed up some more changes that _almost_ bring it in line with the existing `http` soaks. The one missing piece is that the `datadog_agent` source expects that the incoming JSON logs are encapsulated in a JSON array `[]` which the `static` `http_gen` lading variant does not currently support this (it sends them as newline delimited).

I did test, with the input file, using `curl` that if it is sent as a JSON array, it does get processed by the pipelines config and I get the 179 events out that match the cardinality of the 179 in.

**Comment by jszwedko** [comment]
A couple of observations that came out of this:

* The [prior soak run report](https://github.com/vectordotdev/vector/pull/12597#issuecomment-1118112413) was the throughput we see if Vector just returns a 404 to all incoming requests. I was a bit surprised that we only hit 20 Mbps / core in that case.
* Having more validation that soaks are running correctly is likely to be useful. Maybe some assertion on the output throughput? This is related to monitoring `component_errors_total` mentioned in https://github.com/vectordotdev/vector/issues/12186

**Comment by jszwedko** [comment]
@blt just curious to get your thoughts here. Would it make more sense to have `static` variant to have a flag for sending the payloads as JSON arrays (with wrapping `[]`) or to have the `datadog` variant accept a `static` argument?

**Comment by jszwedko** [comment]
Closing this since pipelines have been deprioritized for the time being.

**Pull request closed without merging**
