### PR TITLE
fix(kinesis): add again missing partition key

### PR DESCRIPTION
**Pull request by zamazan4ik**
Resolves https://github.com/vectordotdev/vector/issues/16263

- return missing partition key

Tested:
- No

@neuronull I think you could review this one.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
This looks correct to me - @neuronull quick double check if you don't mind?

**Comment by neuronull** [comment]
🤦 
Thanks for root causing and fixing it @zamazan4ik !

**Review by neuronull — APPROVED** [review]

**Comment by jszwedko** [comment]
Do we need a test for this?

**Comment by jszwedko** [comment]
@zamazan4ik do you mind adding an integration test for this? https://github.com/vectordotdev/vector/blob/88b4c941af03c4218ab540ff968fbd6a43db288c/src/sinks/aws_kinesis/streams/integration_tests.rs#L26-L74 should be a good reference. We should assert the partition key of the results we fetch from AWS.

**Comment by spencergilbert** [comment]
@jszwedko I can't remember what we discussed in the meeting, were you wanting tests for both the `None` and `Some` cases?

**Comment by jszwedko** [comment]
> @jszwedko I can't remember what we discussed in the meeting, were you wanting tests for both the `None` and `Some` cases?

Yeah, I think testing both would be prudent. We have a test with that is specifying `None` already so I think it would be adding one testing the `Some` case including asserting the partition key on the fetched records.

**Review by spencergilbert — APPROVED** [review]
🚀 thanks a ton!

**Pull request merged**
