### PR TITLE
fix(vrl): Add ipv6 support to parse_aws_alb_log.rs

### PR DESCRIPTION
**Pull request by unixninja92**
Adds parsing for ipv6 address to parse_aws_alb_log.rs

### CODE REVIEW

**Review by JeanMertz — CHANGES_REQUESTED** [review]
Sweet. Thanks, @unixninja92. Would you mind adding a test as well? You can copy one of the existing tests in the same file.

**Comment by unixninja92** [comment]
Sure, just added a test.

**Review by JeanMertz — APPROVED** [review]
👌

**Comment by jszwedko** [comment]
Thanks for this contribution @unixninja92 !

**Pull request merged**
