### PR TITLE
enhancement(graphql api): File source metrics

### PR DESCRIPTION
**Pull request by leebenson**
Follow-up to #5319. Adds a `Source.metrics` field for breaking out component-specific metrics, starting with the file source.

## Example query

**Config:**

```toml
[api]
  enabled = true

[sources.gen1]
  type = "generator"
  lines = ["{\"count\": 1}"]
  batch_interval = 0.01
  format = "shuffle"

[sources.wifi]
  type = "file"
  data_dir = "checkpoints"
  include = ["/var/log/wifi*.log"]

[transforms.json]
  type = "json_parser"
  inputs = ["gen1"]

[transforms.double_value]
  type = "remap"
  inputs = ["json"]
  source = """
    .count = .count * 2
  """

[sinks.blackhole2]
  type = "blackhole"
  inputs = ["double_value", "wifi"]
  print_amount = 1000
```

**Query:**

```gql
{
  sources {
    name
    processedEventsTotal {
      processedEventsTotal
    }
    metrics {
      __typename
      ...on FileSourceMetrics {
        files {
          name
          processedEventsTotal {
            processedEventsTotal
          }
          processedBytesTotal {
            processedBytesTotal
          }
        }
      }
    }
    processedBytesTotal {
      processedBytesTotal
    }
    processedEventsTotal {
      processedEventsTotal
    }
  }
}
```

**Result:**

```json
{
  "data": {
    "sources": [
      {
        "metrics": {
          "__typename": "FileSourceMetrics",
          "files": [
            {
              "name": "/var/log/wifi-12-19-2020__16:40:45.758.log",
              "processedBytesTotal": {
                "processedBytesTotal": 4157211
              },
              "processedEventsTotal": {
                "processedEventsTotal": 37093
              }
            },
            {
              "name": "/var/log/wifi-12-19-2020__16:40:47.237.log",
              "processedBytesTotal": {
                "processedBytesTotal": 4157227
              },
              "processedEventsTotal": {
                "processedEventsTotal": 37077
              }
            },
            {
              "name": "/var/log/wifi-12-19-2020__21:51:56.619.log",
              "processedBytesTotal": {
                "processedBytesTotal": 4157245
              },
              "processedEventsTotal": {
                "processedEventsTotal": 37059
              }
            },
            {
              "name": "/var/log/wifi.log",
              "processedBytesTotal": {
                "processedBytesTotal": 200350
              },
              "processedEventsTotal": {
                "processedEventsTotal": 1474
              }
            }
          ]
        },
        "name": "wifi",
        "processedBytesTotal": {
          "processedBytesTotal": 12672033
        },
        "processedEventsTotal": {
          "processedEventsTotal": 112703
        }
      },
      {
        "metrics": null,
        "name": "gen1",
        "processedBytesTotal": null,
        "processedEventsTotal": {
          "processedEventsTotal": 2001
        }
      }
    ]
  }
}
```

## Notes on interface

To avoid breaking changes, `processedEventsTotal` (and bytes) is still implemented against the `Component` interface.

`Source.metrics` is defined as:

```gql
union SourceMetrics = FileSourceMetrics
```

The intention is to expand this schema to accommodate all metrics that offer component-specific meta.

An alternative would be to remove `Component.processedEventsTotal` (and bytes), and turn `SourceMetrics` into an interface re-implementing those fields. That would possibly be cleaner, it that all metrics would be hosted under `Component.metrics` and not hoisted to the parent.

We could then implement a `GenericMetric` type that provides the base implementation where we don't currently offer any additional meta. `FileSourceMetrics` etc would expand this.

I didn't do that because it's a breaking change and wanted to solicit feedback first.

## Aggregating metrics

This PR also bundles a fix for aggregating file metrics, started (but not entirely resolved) in #5319.

The `Metric.add()` method contains a guard that prevents absolute values from being mutated:

```rust
if other.kind.is_absolute() {
    return;
}
```

This prevented aggregation, since _all_ metrics being counted are of `MetricKind.Absolute`.

To workaround that, I moved the body of the function to `Metric.update_value`, and called that from within `Metric.add()`, retaining the guard. Elsewhere where we want to aggregate regardless, `update_value` can be called directly.

I'm not super happy with this - it feels a bit redundant. It feels cleaner to implement `std::ops::Add` on `MetricValue` directly, to enable `m1.value + m2.value`, and just mutate in place where relevant.

I started down that road, but it felt like a potential hot path where immutability could be an unnecessary expense, so I just did the quick refactor option.

@lukesteensen, let me know if you have any preferences/suggestions here and I'll update accordingly.

### CODE REVIEW

**Comment by leebenson** [comment]
## Reviews

- @binarylogic - This PR starts down the path #5402, commencing with the file source. The idea being to expand `SourceMetrics` to ultimately accommodate all source metrics, and the same with `TransformMetrics` and `SinkMetrics` eventualy. This enables querying for the kind of data shown [here](https://share.getcloudapp.com/L1uOpKQ4). Does this match your expectations?

- @lukesteensen - Mostly validation around aggregating metrics. This PR should fix #5319.

- @jszwedko - Would be interested in your thoughts on the graph, especially the union vs. interface approach for `SourceMetrics` and hoisting of events/bytes metrics.

- @sghall - General test, and thoughts around consuming this in the UI.

Thanks all.

**Comment by binarylogic** [comment]
@leebenson it does, assuming we can query metrics both with a component ID and component type. Each type could have specific metrics that are not shared by others.

**Comment by leebenson** [comment]
> @leebenson it does, assuming we can query metrics both with a component ID and component type. Each type could have specific metrics that are not shared by others.

This PR doesn't directly enable finding by component ID (name) or type. What it does is add `Source.metrics`, which is the schema support needed to get at source-specific fields.

I'll add a follow-up issue to add `componentByName(name: String!)` and `componentsByType(type: SourceType!)` fields, which would enable pulling back a specific component and components by type, respectively.

**Review by jszwedko — APPROVED** [review]
Nice! I like the way you've modeled the schema to make the dimensions (here "file") first-class citizens of the API, which I think is consistent with GraphQL's best-practices. I could see us adding a generic field in the future if we find a need from the client.

I am wondering about cardinality here. We've had some users use the `file` source with very large directories (a million files in one case) which seems like it could result in heavy queries. We may want to think about pagination sometime.

**Comment by jszwedko** [comment]
I meant to ask if it was possible to add a test for this behavior.

**Comment by leebenson** [comment]
> Nice! I like the way you've modeled the schema to make the dimensions (here "file") first-class citizens of the API, which I think is consistent with GraphQL's best-practices. I could see us adding a generic field in the future if we find a need from the client.

👍 Thanks! Did you have any thoughts on making `SourceMetrics` an interface, and moving `processedEventsTotal` (and bytes) into it?

@jamtur01 had mentioned being okay with breaking backwards compatibility (not a big deal, I think, given we're probably the only - or at least one of very few - current clients of the API). I think that's my preference too, but I wondered if you felt strongly either way?

> I am wondering about cardinality here. We've had some users use the file source with very large directories (a million files in one case) which seems like it could result in heavy queries. We may want to think about pagination sometime.

Yeah, that's a very good point. Async-graphql has [support for Relay's cursor spec](https://async-graphql.github.io/async-graphql/en/cursor_connections.html). Might be worth getting that in fairly quickly.

**Comment by leebenson** [comment]
> I meant to ask if it was possible to add a test for this behavior.

👍 Will do. Looks like this PR has dislodged component ordering and a test is failing because of it, too. If we move `processedEventsTotal` to the _metrics_ field, that'll also require some shuffling.

I'll tackle tests in one go.

**Comment by jszwedko** [comment]
> +1 Thanks! Did you have any thoughts on making `SourceMetrics` an interface, and moving `processedEventsTotal` (and bytes) into it?

Hmm, I don't think I have a strong opinion there. It seems like the only advantage would be namespacing the shared source component metrics under `metrics`. I think the separation is OK as it is: with the shared source component metrics directly on `Source` and then a full list of metrics under `.metrics`. I'm also fine if you want to change it though :smile: I agree that compatibility isn't a huge concern yet.

**Review by sghall — APPROVED** [review]
Tried this out today @leebenson.  Looking great 👍   The UI would definitely benefit from querying by component name (as Ben suggested).  The idea is to click of a topology node into the internal metrics for that component.   As Jesse touched on, for making that UI work we would probably need to be able to filter and sort as well,  something like a top x by bytes or events.   Nice to get a total file count as well.  I like the idea of moving the existing metrics even if it's a breaking change.   I think it would make sense to have everything under that same metrics key.

**Comment by leebenson** [comment]
This has now been updated to move metrics to an interface. This is implemented separately for `SourceMetrics`, `TransformMetrics` and `SinkMetrics`. 

I've fixed tests, and added a new one for the file source.

`top` has been updated to consume the latest. @sghall - noting the breaking change in the UI.

Issues #5650 and #5674 tackle `componentByName(name: String!)` and Relay connections for paging, respectively.

**Pull request merged**
