### PR TITLE
added option to insert to random shard

### PR DESCRIPTION
**Pull request by rguleryuz**
adds support for "insert_distributed_one_random_shard" mentioned here by me #20335

source : https://clickhouse.com/docs/en/engines/table-engines/special/distributed#distributed-parameters

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Thanks @rguleryuz ! I think this PR just needs a couple of things:

- A changelog entry (see https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md)
- `make generate-component-docs` ran to regenerate the documentation

**Comment by rguleryuz** [comment]
> Thanks @rguleryuz ! I think this PR just needs a couple of things:
> 
>     * A changelog entry (see https://github.com/vectordotdev/vector/blob/master/changelog.d/README.md)
> 
>     * `make generate-component-docs` ran to regenerate the documentation

done!

**Review by jszwedko — COMMENTED** [review]
One comment, otherwise 👍

**Review by jszwedko — APPROVED** [review]
Thanks @rguleryuz !

**Comment by rguleryuz** [comment]
I guess I need to add some stuff for testing as well. Can I get some help with that :(

**Pull request merged**
