### PR TITLE
enhancement(external docs): Add multiple favicons

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by jszwedko** [comment]
Should I be seeing the favicons in the deploy preview? They don't seem to be showing. I checked the dev console and it doesn't seem to be making the request for it.

**Comment by lucperkins** [comment]
@jszwedko Yeah, I'm still kind of trying to figure this method out

**Comment by jszwedko** [comment]
Ah, cool, no worries.

**Comment by lucperkins** [comment]
@jszwedko Okay, I've pushed a change that *should* work AFAIK. If not, then I'll revisit.

**Comment by jszwedko** [comment]
🤔 I'm still not seeing it on the deploy site at least. Do you?

**Comment by lucperkins** [comment]
@jszwedko I came back to revisit this and somehow the favicon seems to be working 🤷🏼‍♂️  Same for you?

**Review by jszwedko — APPROVED** [review]
Hah, how about that, yeah it looks good now.

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
