### PR TITLE
docs: add encoding configuration examples

### PR DESCRIPTION
**Pull request by cuichenli**
Signed-off-by: Cuichen Li <cuichli@cisco.com>

This PR tries to show the encoding configurations examples in the examples block.

I am new to the vector project and was trying the `aws_s3` sink, I followed the example configurations and then got error says `encoding` was not specified. So I raised this PR. Honestly I am not sure if the change is in the right way and if it will break anywhere else. Feel free to reject the PR. Thanks!

### CODE REVIEW

**Comment by spencergilbert** [comment]
Hi @cuichenli thanks for the PR! One issue that jumps out to me is that the configuration would be rendered for every sink, including the ones that _don't_ accept that option. We'd need to be able to conditionally render it depending on the sink.

**Comment by cuichenli** [comment]
> Hi @cuichenli thanks for the PR! One issue that jumps out to me is that the configuration would be rendered for every sink, including the ones that _don't_ accept that option. We'd need to be able to conditionally render it depending on the sink.

I may miss something here, so please correct me if I am wrong 🙇 .

If my understanding is correct, the example is only rendered when `encoding` feature is enabled
https://github.com/vectordotdev/vector/pull/11645/files#diff-8ba5ce8aa2017c766d9af3dba68d0858c04e9766883c1ce3d170c2f6b94ce82cL170. 

Take `aws_cloudwatch_metrics` as an example, it is not showing the `encoding` part configuration in the preview-app. 
https://deploy-preview-11645--vector-project.netlify.app/docs/reference/configuration/sinks/aws_cloudwatch_metrics/

**Comment by spencergilbert** [comment]
> > Hi @cuichenli thanks for the PR! One issue that jumps out to me is that the configuration would be rendered for every sink, including the ones that _don't_ accept that option. We'd need to be able to conditionally render it depending on the sink.
> 
> I may miss something here, so please correct me if I am wrong 🙇 .
> 
> If my understanding is correct, the example is only rendered when `encoding` feature is enabled https://github.com/vectordotdev/vector/pull/11645/files#diff-8ba5ce8aa2017c766d9af3dba68d0858c04e9766883c1ce3d170c2f6b94ce82cL170.
> 
> Take `aws_cloudwatch_metrics` as an example, it is not showing the `encoding` part configuration in the preview-app. https://deploy-preview-11645--vector-project.netlify.app/docs/reference/configuration/sinks/aws_cloudwatch_metrics/

🤔 no you're right - this doesn't appear to be happening everywhere, maybe just on the one sink I checked 😆 - https://deploy-preview-11645--vector-project.netlify.app/docs/reference/configuration/sinks/datadog_logs/ 

That sink doesn't take a codec as we always use json there, so that might be a bug in the cue for that component specifically - I'll take a more thorough look and see if I can see why, and if there are any other sinks that look to be rendering this inaccurately.

As a side note, I think we should default it to `json` instead of `text` - the fact that `text` only outputs the `.message` field of the event makes it regularly confusing for users.

**Comment by spencergilbert** [comment]
Ah yes, that would be it @cuichenli - I do think that should resolve it anywhere else we may have that configured as such. `encoding` is possible as to allow for the `only|except_fields` options for example, but the `codec` is preset.

If you want to make that change I'd be happy to merge this in - I really appreciate you digging into this!

**Comment by cuichenli** [comment]
@spencergilbert i have updated accordingly, please have a look. thanks

**Review by spencergilbert — APPROVED** [review]
Great! Thanks again for the PR!

**Pull request merged**
