### PR TITLE
chore(performance): Use multiple of CHUNK_SIZE for SOURCE_SENDER_BUFFER_SIZE

### PR DESCRIPTION
**Pull request by 001wwang**
With `CHUNK_SIZE == SOURCE_SENDER_BUFFER_SIZE` and sufficient load, an unintended serialization point can arise in `send_batch`/`send_event_stream` since the internal SourceSender channel can only hold `SOURCE_SENDER_BUFFER_SIZE` items at a time and `CHUNK_SIZE` items are sent a time -- in essence, large enough event payloads make progress one by one.

`8 * CHUNK_SIZE` was arbitrarily chosen to see some initial soak results.

### CODE REVIEW

**Comment by blt** [comment]
REF #11731

**Comment by jszwedko** [comment]
Yeah, agreed, `TRANSFORM_CONCURRENCY_LIMIT` seems like it could be a better fit here than the static constant.

**Comment by 001wwang** [comment]
> Yeah, agreed, `TRANSFORM_CONCURRENCY_LIMIT` seems like it could be a better fit here than the static constant.

Will give that a shot.

**Comment by jszwedko** [comment]
(merged master since the baseline had some recent perf changes)

**Review by lukesteensen — APPROVED** [review]
Nice find! This makes sense to me.

Looking a bit more, I'm also curious about https://github.com/vectordotdev/vector/pull/11587/commits/3818bd551bf2fdbd0239681876c7cd8607a3e488, where we break up batches larger than `CHUNK_SIZE`. The commit claims to be testing it out, but it remained in the final PR and it's not obvious to me what impact it made on the soaks. Maybe @bruceg has some context there.

I'm also not so sure about 1000 as a chunk size in the first place. It'd be interesting to try bumping that to 2048 or 4096.

**Comment by 001wwang** [comment]
> I'm also not so sure about 1000 as a chunk size in the first place. It'd be interesting to try bumping that to 2048 or 4096.

Mmm, gotcha @lukesteensen. Why might those values be better for chunk size? Is it because we expect large event payloads and want to avoid breaking them up into overly small chunks? Any reason in particular for 2048/4096?

**Comment by 001wwang** [comment]
Hm, so I fixed a merge conflict with master and the most recent soak results show a regression. The fine details tab does show minor improvements across more soaks, just not at the `>5% mean` threshold. Results have been pretty varied with each run at this point potentially due to larger changes from master, so I'm re-running to see how consistent this is.

**Comment by lukesteensen** [comment]
@001wwang 

> Why might those values be better for chunk size? Is it because we expect large event payloads and want to avoid breaking them up into overly small chunks? Any reason in particular for 2048/4096?

Yeah, mostly to avoid breaking up larger batches for no good reason. Those are just the next larger powers of two, which are nice to stick with. I don't actually know whether it'd make much of a difference, just something I'm curious about.

**Comment by 001wwang** [comment]
Note, this was tabled since #11772 was affecting soak results, and thus the results of this change were unclear. Since #11772 is likely resolved now, I'll bring this up to speed and we can take another look.

**Pull request merged**
