### PR TITLE
feat(kubernetes_logs source): Use resource_version of 0 to use cache

### LINKED ISSUE #7943: Vector making inefficient api GETs in large K8s clusters
### Vector Version

```
vector version: `Vector/0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03`
```

### Context

While investigating some API latency regressions in our production Kubernetes clusters, which are >2k nodes with 10s of thousands of pods, we found vector making the following watch/list calls, that dont seem to be setting resourceVersion in them. 

Most kube clients, that get deployed across the cluster set their resourceVersion to 0 when they can tolerate weak consistency, asking the API server to return the list results from the cache, there by not needing an ETCD range request, which is strongly consistent and significantly costly. This is also now programmed into client-go for all golang clients in the informer factory that implements the golang reflector like what you have here for rust: https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L286-L299

### Expected Behavior

We expect all LIST/GET/WATCH calls from vector to be hitting the apiserver cache and not etcd directly thereby reducing load on etcd.

### Actual Behavior

Some WATCH calls missing apiserver cache and hitting etcd 

### Kubernetes API Server logs

```
I0619 21:39:44.679278       1 wrap.go:47] GET /api/v1/pods?&allowWatchBookmarks=true&fieldSelector=spec.nodeName%3Dhello-world-node&labelSelector=vector.dev%2Fexclude%21%3Dtrue&timeoutSeconds=290&watch=true: (4m50.000539436s) 200 [Vector/0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03) hello-world-node:37716]
I0619 21:39:45.682526       1 get.go:250] Starting watch for /api/v1/pods, rv=1725125265 labels=vector.dev/exclude!=true fields=spec.nodeName=hello-world-node timeout=4m50s
I0619 21:39:45.682685       1 wrap.go:47] GET /api/v1/pods?&allowWatchBookmarks=true&fieldSelector=spec.nodeName%3Dhello-world-node&labelSelector=vector.dev%2Fexclude%21%3Dtrue&resourceVersion=1725125265&timeoutSeconds=290&watch=true: (691.548µs) 200 [Vector/0.14.0 (x86_64-unknown-linux-gnu 5f3a319 2021-06-03) hello-world-node:37716]
I0619 21:39:46.684515       1 get.go:250] Starting watch for /api/v1/pods, rv= labels=vector.dev/exclude!=true fields=spec.nodeName=hello-world-node timeout=4m50s
```

I have never been a contributor to a rust project and dont think I will be the best one to make this change, but I think changing the default `resource_version` from `None` to `0` for the first call above would help by a large extent here: https://github.com/timberio/vector/blob/ab697bae210151ac3eb0be1de3e435f34dec6407/src/kubernetes/reflector.rs#L163

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>

Closes #7943

I had to remove the const to set it like this, if there's a better alternative let me know. Setting this to 0 rather than None should allow us to use cached values from the apiserver rather than getting the freshest results from etcd directly.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Makes sense. For the `kubernetes_logs` source we only consume logs for local pods so I imagine that the local node will have any relevant data available. Are you aware of any risks here?

**Comment by spencergilbert** [comment]
> Makes sense. For the `kubernetes_logs` source we only consume logs for local pods so I imagine that the local node will have any relevant data available. Are you aware of any risks here?

We actually don't communicate with the "local" node. We today, and after this, make calls to the control plane for pod/namespace information. This changes our requirements around the freshness of the resource and whether we get it from what the kube-apiserver has cached (part of the control plane) or ends up querying etcd directly (also sorta part of the control plane, but more in a storage manner).

Communicating with "node local" api's is what Datadog suggested after a short review, but would be a pretty full rewrite.

**Comment by jszwedko** [comment]
Ah, gotcha, thanks for clearing that up.

Is the risk then that we might get stale metadata for k8s resources like the pods or namespaces and use that to annotate the logs?

**Comment by spencergilbert** [comment]
> Ah, gotcha, thanks for clearing that up.
> 
> Is the risk then that we might get stale metadata for k8s resources like the pods or namespaces and use that to annotate the logs?

Yeah - it does introduce that possibility, but I'd consider the stability improvements are worth it. As is (especially with every vector instance making calls) we can DDoS etcd pretty easily :|

**Comment by jszwedko** [comment]
Yeah, I agree, I just wanted to make sure I understood the trade-offs.

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
