### PR TITLE
chore(splunk_hec source): Fix handling of non UTF8 payloads

### LINKED ISSUE #10778: Handle non UTF-8 payloads for the splunk_hec source
As a user highlighted, the `splunk_hec` source errors when a request to `/services/collector/event` includes a JSON event with non UTF-8 characters. For example, `{"event": "\xe4"}` results in 
```
ERROR source{component_kind="source" component_id=in component_type=splunk_hec component_name=in}: vector::internal_events::splunk_hec::source: Invalid request body. error=Custom { kind: InvalidData, error: Error("invalid unicode code point", line: 1, column: 37) } error_type="parse_failed" stage="processing" internal_log_rate_secs=10
```
This is because the `splunk_hec` source parses the request body into JSON with `serde_json::Deserializer::<serde_json::Value>` where `Value::String` involves a Rust `String` that must be `UTF-8`. 

On the other hand, an actual Splunk HEC instance (tested using `v8.2.4`) does accept such payloads, replacing invalid characters with a replacement char �. 

We should consider performing some sort of lossy conversion and/or redirecting the invalid input to a separate output of the source to handle this scenario.

### PR DESCRIPTION
**Pull request by 001wwang**
Closes #10778 

This PR handles non UTF8 payloads in incoming requests using `String::from_utf8_lossy`. This matches Splunk HEC's behavior of accepting such payloads and replacing invalid bytes with the replacement character (tested against `v8.2.4`).

As mentioned in the ticket, potential follow up work could include configuring this behavior and sending to a separate output for invalid payloads. Let me know if this change should be included in the `v0.20.0` upgrade guide.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Nice! I am a bit wary that now the entire request body needs to be read into memory and decompressed before we extract events from it. I believe previously it was incrementally decoding them. Albeit, I'm guessing that reading it all at once is probably contributing to the performance gain here.

I'm curious if @binarylogic or @blt have any thoughts about what we should be preferring for sources. Incremental reading and streaming of events to keep memory consumption down at, probably, the risk of worse performance? Or reading in entire batches at once and decoding which will use more memory but, probably, perform faster?

**Comment by 001wwang** [comment]
> Nice! I am a bit wary that now the entire request body needs to be read into memory and decompressed before we extract events from it. I believe previously it was incrementally decoding them. Albeit, I'm guessing that reading it all at once is probably contributing to the performance gain here.
> 
> I'm curious if @binarylogic or @blt have any thoughts about what we should be preferring for sources. Incremental reading and streaming of events to keep memory consumption down at, probably, the risk of worse performance? Or reading in entire batches at once and decoding which will use more memory but, probably, perform faster?

Indeed, the overall performance increase here is interesting. @blt and I had discussed adding some micro-benchmarks around this code to get a better sense of whether this logic is faster or if it's creating some impact elsewhere. It would also be a good opportunity for me to learn `criterion` and such. Happy to dig into this more after wrapping up other tasks.

**Comment by binarylogic** [comment]
To add context, throughput is king. So using more memory (within reason) for higher performance is preferable. Ideally users could opt out of this behavior, but that would be an advanced setting to reduce the batch sizes.

**Comment by blt** [comment]
The implementation of `from_utf8_lossy` is [here](https://doc.rust-lang.org/stable/src/alloc/string.rs.html#558). I can conceive of implementing something like this in terms of an iterator, but I'm not sure it's motivated.  You're right, @jszwedko, that this patch potentially uses more memory, but as I read it not terribly more theoretically than previous? The previous implementation would read the payload piecemeal and deserialize into a `JsonValue`, so we'd have to fit whatever the chunk size of the reader was in plus the `JsonValue` we built up. Now we fit the whole payload plus the `JsonValue`, yes? So maybe 2X whatever the eventual size of `JsonValue` is at peak usage versus the previous 1.xX usage?

Personally I'd vote we merge this as-is and if we can construct a payload that causes a serious memory blow-up then we address by making an iterator consuming `from_utf8_lossy` variant.

**Review by blt — APPROVED** [review]

**Comment by blt** [comment]
> > Nice! I am a bit wary that now the entire request body needs to be read into memory and decompressed before we extract events from it. I believe previously it was incrementally decoding them. Albeit, I'm guessing that reading it all at once is probably contributing to the performance gain here.
> > I'm curious if @binarylogic or @blt have any thoughts about what we should be preferring for sources. Incremental reading and streaming of events to keep memory consumption down at, probably, the risk of worse performance? Or reading in entire batches at once and decoding which will use more memory but, probably, perform faster?
> 
> Indeed, the overall performance increase here is interesting. @blt and I had discussed adding some micro-benchmarks around this code to get a better sense of whether this change is faster than before or if it's creating some impact elsewhere. It would also be a good opportunity for me to learn `criterion` and such. Happy to dig into this more after wrapping up other tasks.

I look forward to this.

**Comment by jszwedko** [comment]
> To add context, throughput is king. So using more memory (within reason) for higher performance is preferable. Ideally users could opt out of this behavior, but that would be an advanced setting to reduce the batch sizes.

👍 this is a good overall rule-of-thumb.

**Review by jszwedko — APPROVED** [review]

**Comment by 001wwang** [comment]
(Kudos to @blt for walking me through this!)
### Summary
At face value, the change introduced in this PR looks like it would cause a performance regression. Instead of simply lazily iterating through and deserializing the request body into `Event`s, we're now reading the entire request body upfront, replacing any invalid UTF-8 bytes, and then proceeding as before. 

Yet, the soak results show a (sizeable) performance _increase_ for `splunk_hec` related soaks. What?! Surely then, the new implementation is actually faster than before, and that's why performance increased? You might even begin to hypothesize some seriously convincing reasons why that could be.

Unfortunately, no. The new implementation is, like you initially suspected, slower than the original (see Details section). This PR is just a great example of how slowing down one piece of a complex system can result in an overall speed up (for reasons that are hard to pin down).

### Details
To prove that this new change is indeed slower than the original implementation, we can extract the core logic, create some microbenchmarks, and compare the two implementations. [Here is a branch including the simple new benchmarks](https://github.com/vectordotdev/vector/compare/splunk-lossy-decoding-change-benchmark).

The core logic we're comparing is as follows:
```rust
// new implementation
let mut data = Vec::new();
let body = if payload.gzip {
    MultiGzDecoder::new(payload.body.reader())
        .read_to_end(&mut data)
        .unwrap();
    String::from_utf8_lossy(data.as_slice())
} else {
    String::from_utf8_lossy(payload.body.as_ref())
};

Deserializer::from_str(&body).into_iter::<Value>();
```
```rust
// old implementation
let reader: Box<dyn Read + Send> = if payload.gzip {
    Box::new(MultiGzDecoder::new(payload.body.reader()))
} else {
    Box::new(payload.body.reader())
};

Deserializer::from_reader(reader).into_iter::<Value>();
```
The JSON body used for input is simply
```
"{ "message": "hello world" }"
```

Running them, we get the following results (output simplified for legibility). `new` is the implementation introduced in this PR and `old` is the original. To explore both branches of the core logic, `-gzip` indicates whether the payload is gzipped.
```shell
vector::sources::splunk_hec/new                                                                             
                        time:   [24.407 ns 24.482 ns 24.555 ns]
vector::sources::splunk_hec/new-gzip                                                                             
                        time:   [4.8594 us 4.8820 us 4.9057 us]
vector::sources::splunk_hec/old                                                                             
                        time:   [18.194 ns 18.235 ns 18.272 ns]
vector::sources::splunk_hec/old-gzip                                                                            
                        time:   [1.6066 us 1.6433 us 1.6816 us]
```
As you can see, even in this simple scenario, the new implementation is indeed slower.

**Comment by jszwedko** [comment]
Nice write-up! That is very interesting.

I noted in the benchmarks that the closures weren't returning their value which would allow a clever Rust compiler to optimize the code in the closures away to just return `()`. I re-ran them using `criterion::black_box` just to see if it had an effect and I did actually see somewhat different results, but still showing that the new implementation was seemingly slower; in particular for gzip:

```
     Running unittests (target/release/deps/splunk-c7d05f05ddf8c280)
Gnuplot not found, using plotters backend
vector::sources::splunk_hec/new
                        time:   [38.912 ns 38.976 ns 39.036 ns]
                        thrpt:  [26.232 Gelem/s 26.272 Gelem/s 26.316 Gelem/s]
                 change:
                        time:   [-1.2545% -0.6844% -0.2294%] (p = 0.00 < 0.05)
                        thrpt:  [+0.2299% +0.6892% +1.2704%]
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe
vector::sources::splunk_hec/new-gzip
                        time:   [6.2626 us 6.2884 us 6.3156 us]
                        thrpt:  [162.14 Melem/s 162.84 Melem/s 163.51 Melem/s]
                 change:
                        time:   [+1.1500% +2.3718% +3.4677%] (p = 0.00 < 0.05)
                        thrpt:  [-3.3515% -2.3168% -1.1369%]
                        Performance has regressed.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe
vector::sources::splunk_hec/old
                        time:   [38.447 ns 38.718 ns 39.110 ns]
                        thrpt:  [26.183 Gelem/s 26.448 Gelem/s 26.634 Gelem/s]
                 change:
                        time:   [-0.9939% +0.6989% +2.2279%] (p = 0.42 > 0.05)
                        thrpt:  [-2.1794% -0.6941% +1.0039%]
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe
vector::sources::splunk_hec/old-gzip
                        time:   [2.2449 us 2.2717 us 2.2979 us]
                        thrpt:  [445.63 Melem/s 450.76 Melem/s 456.15 Melem/s]
                 change:
                        time:   [+2.1543% +5.7133% +9.1655%] (p = 0.00 < 0.05)
                        thrpt:  [-8.3960% -5.4045% -2.1089%]
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild
```

(I also used the default criterion parameters to avoid the two minute long collection time for each benchmark; criterion estimated it only needed 5s to get the necessary number of samples to be statistically confident)

A few other notes / questions:

* Is the payload used for the micro-benchmark representative of what lading sends for the end-to-end benchmark? Naively, I'd expect the implementations to differ more in performance with larger payloads. There isn't likely to be much difference doing incremental reads if the input is relatively small to begin with, as it here.
* I'm curious if the criterion parameters chosen were intentional or just copied from somewhere. I'd naively assume we'd want to stick with the default criterion parameters (in particular for the warm up time and sample collection) unless we have a good reason to differ them.

**Comment by jszwedko** [comment]
Answered my own questions:

> * Is the payload used for the micro-benchmark representative of what lading sends for the end-to-end benchmark? Naively, I'd expect the implementations to differ more in performance with larger payloads. There isn't likely to be much difference doing incremental reads if the input is relatively small to begin with, as it here.

It wasn't, but that is just what we were starting the micro benchmarks with within the timebox to keep things simple. I did manage to snag and example ~500 kb payload from lading, which is used for the soak tests that show the improvement above, but these show an even more drastic advantage to the old implementation so seemingly there is something else going on here:

```
vector::sources::splunk_hec/new
                        time:   [333.35 us 333.81 us 334.29 us]
                        thrpt:  [3.0632 Melem/s 3.0676 Melem/s 3.0718 Melem/s]
                 change:
                        time:   [-7.0795% -3.5906% -0.7073%] (p = 0.02 < 0.05)
                        thrpt:  [+0.7123% +3.7243% +7.6188%]
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) low mild
  1 (1.00%) high mild
  1 (1.00%) high severe
vector::sources::splunk_hec/new-gzip
                        time:   [616.67 us 617.81 us 619.09 us]
                        thrpt:  [1.6540 Melem/s 1.6575 Melem/s 1.6605 Melem/s]
                 change:
                        time:   [+3.7615% +4.0164% +4.2886%] (p = 0.00 < 0.05)
                        thrpt:  [-4.1122% -3.8613% -3.6251%]
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe
vector::sources::splunk_hec/old
                        time:   [36.930 ns 36.984 ns 37.045 ns]
                        thrpt:  [27.642 Gelem/s 27.687 Gelem/s 27.728 Gelem/s]
                 change:
                        time:   [-0.1399% +0.1805% +0.4556%] (p = 0.25 > 0.05)
                        thrpt:  [-0.4536% -0.1802% +0.1401%]
                        No change in performance detected.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
Benchmarking vector::sources::splunk_hec/old-gzip: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 9.1s, enable flat sampling, or reduce sample count to 50.
vector::sources::splunk_hec/old-gzip
                        time:   [4.3773 us 4.4223 us 4.4623 us]
                        thrpt:  [229.48 Melem/s 231.55 Melem/s 233.93 Melem/s]
                 change:
                        time:   [+9.9781% +12.579% +15.400%] (p = 0.00 < 0.05)
                        thrpt:  [-13.345% -11.173% -9.0728%]
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe
```

Diff: https://github.com/vectordotdev/vector/compare/splunk-lossy-decoding-change-benchmark...splunk-lossy-decoding-change-benchmark-jesse?expand=1

> * I'm curious if the criterion parameters chosen were intentional or just copied from somewhere. I'd naively assume we'd want to stick with the default criterion parameters (in particular for the warm up time and sample collection) unless we have a good reason to differ them.

@blt mentioned these were determined by experimentation to increase statistical confidence and reduce outliers for this specific benchmark. We talked about getting this guidance added to https://github.com/vectordotdev/vector/blob/master/docs/DEVELOPING.md#benchmarking

**Pull request merged**
