### PR TITLE
fix(config): Continue polling http config after error

### LINKED ISSUE #12579: Http configuration poll stops after error
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using `"http"` provider type, [the poll loop will exit when an error is found](https://github.com/vectordotdev/vector/blob/v0.21.1/src/providers/http.rs#L154), preventing fetching further config changes.

### Configuration

```text
[provider]
type = "http"
url = "https://raw.githubusercontent.com/vectordotdev/vector/master/config/examples/stdio.toml"
poll_interval_secs = 5
```

### Version

0.21.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jorgebay**
Fixes #12579.

Small fix to continue the polling loop after encountering an error fetching the http config.

### CODE REVIEW

**Comment by jszwedko** [comment]
Thanks for reporting, and for this quick fix @jorgebay ! I tagged @leebenson to review it.

**Comment by binarylogic** [comment]
@jorgebay I'm curious what your use case is for this feature? I ask because we've considered removing it since configuration delivery seems better handled by purpose built software, like `confd` or other platform-specific systems. This would help us keep Vector focused. Does that make sense? Thoughts?

**Comment by jorgebay** [comment]
I would like to pick up configuration for various instances from a central location, like S3. I have distributed vector topologies that might change over time. Having "hot" reload of topologies without the need to bounce the pod is a killer vector feature.

Having confd or other way to replicate a central config locally is just another moving part.

**Comment by leebenson** [comment]
I'll go ahead and merge this, since it does address the immediate issue.

FWIW, I think there is a general question mark over long-term maintenance of this feature. I would encourage exploring other ways to retrieve and persist a config to disk outside of Vector, in case this is something we drop in the future.

I appreciate hearing your use-case though, that's certainly feedback we'll bear in mind.

**Pull request merged**
