### PR TITLE
fix: reorder service layers to prevent unbounded retries

### PR DESCRIPTION
**Pull request by KH-Moogsoft**
This change is intended to handle the issues noted in  https://github.com/timberio/vector/issues/8647 and https://github.com/timberio/vector/issues/8211, where concurrency limits were not being respected for http-based sinks when bad network conditions arose.

In changing this code, I noticed that the test `sinks::util::adaptive_concurrency::tests::all_tests` fails, due to the test sink achieving values well outside the maximums specified in the test file. I'm not sure if this is a case where the maximums were simply wrong before, or the layer swap has introduced improper behavior. I didn't want to commit to changing all of the concurrency test files until I had a better idea of which direction to take, so I would appreciate input there.

### CODE REVIEW

**Review by blt — APPROVED** [review]

**Comment by jszwedko** [comment]
Thanks @KH-Moogsoft ! I'll let @bruceg comment about `sinks::util::adaptive_concurrency::tests::all_tests` since he is the most familiar with those tests.

**Comment by KH-Moogsoft** [comment]
I've added the test file values that would allow the concurrency layer tests to pass. They seem like fairly large changes in the values, but I'm not familiar with the code enough to be certain if that's acceptable. I'll defer to @bruceg  on this.

**Review by bruceg — APPROVED** [review]
Yes, these test data changes look alarming, but I think they can all be explained by the fact that the underlying layer is now handling retries. I am still concerned this is going to lead to excessive backoffs in the algorithm, but I guess we'll see how it pans out.

**Comment by jszwedko** [comment]
I ran the concurrency suite and it seems to be performing roughly the same (see below). Thanks for this contribution @KH-Moogsoft !

# before

before

# after

after

**Pull request merged**
