### PR TITLE
chore(log_to_metric transform): Add Cargo feature for the transform

### PR DESCRIPTION
**Pull request by hhromic**
The `log_to_metric` transform was missing a corresponding Cargo feature. Therefore, when compiling Vector with a reduced set of features, this transform was always included even if not requested.

This is the only transform that was still missing a Cargo feature.

The [previous attempt](https://github.com/vectordotdev/vector/pull/18308
) incorrectly tried to feature-gate the `parser` module in `internal_events`. Instead, this PR allows for the `parser` module imports to be left unused when not required. I think doing this is safer and keeps the parser module an integral part of the internal events module regardless of the features enabled.

The test configuration in the `api` module was also missing a dependency on `transforms-log_to_metric`.

I checked all the errors reported in <https://github.com/vectordotdev/vector/actions/runs/5908210923/attempts/1> and I manually verified that the affected sources/sinks/api now compile correctly. This time it should be good.

Can the Vector team trigger a CI component-feature check on this PR to validate? :)

### CODE REVIEW

**Comment by jszwedko** [comment]
Thanks @hhromic ! I triggered the component features check.

**Comment by hhromic** [comment]
@jszwedko looks like the component feature check failed during Git fetch?
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/readd-log-to-metric-feat*:refs/remotes/origin/readd-log-to-metric-feat* +refs/tags/readd-log-to-metric-feat*:refs/tags/readd-log-to-metric-feat*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 11 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/readd-log-to-metric-feat*:refs/remotes/origin/readd-log-to-metric-feat* +refs/tags/readd-log-to-metric-feat*:refs/tags/readd-log-to-metric-feat*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/readd-log-to-metric-feat*:refs/remotes/origin/readd-log-to-metric-feat* +refs/tags/readd-log-to-metric-feat*:refs/tags/readd-log-to-metric-feat*
  Error: The process '/usr/bin/git' failed with exit code 1
```

Let me know if I need to do something in the branch for it to work.

**Comment by jszwedko** [comment]
Hmm, yeah, it seems like the workflow failed to run; maybe because it is a fork (cc/ @neuronull you might be interested in this). I was, however, able to run it locally successfully.

**Comment by hhromic** [comment]
@jszwedko glad to hear it passed now 🎉
Hope the CI check can be improved to run on forks (if that is the problem).

**Comment by neuronull** [comment]
> Hmm, yeah, it seems like the workflow failed to run; maybe because it is a fork (cc/ @neuronull you might be interested in this). I was, however, able to run it locally successfully.

I agree with your assessment.
It appears to be a limitation of https://github.com/xt0rted/pull-request-comment-branch , which is checking out the base vector repo, and looking for the branch from the PR, but it doesn't find it because that is on the fork.

I've opened https://github.com/vectordotdev/vector/issues/18437 to track this. / cc @jszwedko

**Pull request merged**
