### PR TITLE
chore: Adjust Datadog Logs sink timeout to 5 seconds

### PR DESCRIPTION
**Pull request by blt**
Inspired by the conversation on #9185 this PR adjusts the timeout down from 60
seconds to 5.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Review by binarylogic — APPROVED** [review]
Thanks.

**Review by jszwedko — APPROVED** [review]
Indeed, thanks for making this adjustment!

**Comment by spencergilbert** [comment]
Commenting here as well, given this is currently hardcoded for the agent should set enforce an upper bound on the user override?

**Comment by jszwedko** [comment]
> Commenting here as well, given this is currently hardcoded for the agent should set enforce an upper bound on the user override?

I think the issue with this is that the data may be coming from somewhere other than `datadog_agent`. Maybe it is coming from some other source that has an even lower request timeout.

This would be more sophisticated than other validation we currently do, but we could consider validating that the timeout is not greater than, say, `5` whenever the `datadog_logs` sink is connected to a `datadog_agent` source.

**Comment by spencergilbert** [comment]
Oh duh, yes ignore me. 😂

**Comment by blt** [comment]
> > Commenting here as well, given this is currently hardcoded for the agent should set enforce an upper bound on the user override?
> 
> I think the issue with this is that the data may be coming from somewhere other than `datadog_agent`. Maybe it is coming from some other source that has an even lower request timeout.
> 
> This would be more sophisticated than other validation we currently do, but we could consider validating that the timeout is not greater than, say, `5` whenever the `datadog_logs` sink is connected to a `datadog_agent` source.

I think that could end up being a natural consequence of the work @lukesteensen is doing with the topology, adding constraints to the metadata of a component. We've talked some about needing to 'taint' a sub-graph with knowledge of whether loki is downstream and events can't be processed out-of-order.

**Pull request merged**
