### PR TITLE
fix: make instrumentation only on trace

### PR DESCRIPTION
**Pull request by Hoverbear**
Makes our logevent tracing only create spans at the trace level.

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]

**Comment by Hoverbear** [comment]
https://github.com/tokio-rs/tracing/issues/1070

**Comment by binarylogic** [comment]
Is it worth some kind of simple CI check that'll prevent this going forward? Doesn't need to be in the PR, we can open an issue to represent the work.

**Comment by Hoverbear** [comment]
@binarylogic I'd love to spend some time refining our internal observability guidelines with this info

**Comment by binarylogic** [comment]
Yep, if you wouldn't mind opening issues then we can slot the work.

**Pull request merged**
