### PR TITLE
feat(vrl): add encode_zstd and decode_zstd functions

### PR DESCRIPTION
**Pull request by zamazan4ik**
Adds `encode_zstd` and `decode_zstd` functions as discussed here: https://github.com/vectordotdev/vector/issues/15978#issuecomment-1387170572

I think this should be merged after https://github.com/vectordotdev/vector/pull/16039

### CODE REVIEW

**Comment by zamazan4ik** [comment]
Not sure about the current errors, but it seems like `encode/decode_zstd` could not be used in WASM due to dependency on `zstd-sys` which requires Clang installed. Do we need to tweak somehow the build or just remove the functions from Web Playground?

**Comment by jszwedko** [comment]
> Not sure about the current errors, but it seems like `encode/decode_zstd` could not be used in WASM due to dependency on `zstd-sys` which requires Clang installed. Do we need to tweak somehow the build or just remove the functions from Web Playground?

I think you can enable the `wasm` feature for the `zstd` crate.

**Comment by zamazan4ik** [comment]
@jszwedko after the enabling `wasm` feature in the `zstd` crate it still does not work in Web due to a missing `clang` crate somewhere in the build pipeline.

I see here two options:
* Install `clang` in the build pipeline. I do not know how to do it since I am not familiar at all with your CI
* Disable `encode/decode_zstd` functions on VRL playground

What do you think>

**Comment by jszwedko** [comment]
> @bruceg after the enabling `wasm` feature in the `zstd` crate it still does not work in Web due to a missing `clang` crate somewhere in the build pipeline.
> 
> I see here two options:
> 
> * Install `clang` in the build pipeline. I do not know how to do it since I am not familiar at all with your CI
> * Disable `encode/decode_zstd` functions on VRL playground
> 
> What do you think?

Ah, yeah, I see it. I think what we need to do here is add clang to the build pipeline for the vrl-web-playground. You can see the entrypoint for this here as the build happens completely on Netlify: https://github.com/vectordotdev/vector/blob/master/lib/vrl/web-playground/netlify.toml . In this case I'd probably reuse `ensure-wasm-pack-installed.sh` to install all needed vrl-web-playground build dependencies (and rename it to something like `bootstrap-vrl-web-playground.sh`). Does that make sense?

**Comment by zamazan4ik** [comment]
@jszwedko I have added `clang` to the build. Right now `wasm-opt` is segfaulting in the build pipeline. I found possibly the related issue in the upstream (spoiler: no viable solution is available right now): https://github.com/WebAssembly/binaryen/issues/4630

What do we need to do next with it? I suggest just disable `encode/decode_zstd` on VRL playground with a note, why we did it (with a link to the `wasm-opt` issue).

**Comment by zamazan4ik** [comment]
> I have added clang to the build. Right now wasm-opt is segfaulting in the build pipeline. I found possibly the related issue in the upstream (spoiler: no viable solution is available right now): https://github.com/WebAssembly/binaryen/issues/4630
> 
> What do we need to do next with it? I suggest just disabling encode/decode_zstd on the VRL playground with a note, of why we did it (with a link to the wasm-opt issue).

@bruceg hopefully you could help here.

**Comment by jszwedko** [comment]
Hmm, I'm actually getting SIGSEVs when trying to build the playground with these changes. Netlify seems to be hitting that as well, but this seems different from issue you found: https://github.com/WebAssembly/binaryen/issues/4630. Are you seeing a different error when trying to build locally?

In any event, it actually looks like using a newer version of `wasm-pack` resolves the issue. I was able to install https://github.com/rustwasm/wasm-pack.git at [e3582b7](https://github.com/rustwasm/wasm-pack/commit/e3582b700217746ddb864909a20ef2f571a75326) and it built ok. Would you want to update `scripts/ensure-wasm-pack-installed.sh` to do that? We should tag to a specific revision until the next versioned release.

**Comment by zamazan4ik** [comment]
Is there a way to drop the already existing cache to test?

**Comment by jszwedko** [comment]
I dropped the cache and it looks good! Thanks for this contribution @zamazan4ik !

**Comment by jszwedko** [comment]
Merging since failed check was Netlify, but the subsequent build worked even though it didn't notify GHA of success.

**Pull request merged**
