### PR TITLE
enhancement(aws_cloudwatch_logs sink): add support for custom log retention period

### PR DESCRIPTION
**Pull request by chaychoong**
## Description
This PR adds a new configuration option to set the log retention period (in days) for new cloudwatch log groups created by vector.

~The default value is 0, which sets it to `never expire`.~

### CODE REVIEW

**Comment by chaychoong** [comment]
Hi @ktff or @LucioFranco, I'm new to this repo, and I'm wondering if I can get some guidance here on how to solve the issues that's being flagged

**Comment by spencergilbert** [comment]
We can definitely lend a hand:

- The check failure should be fixable with a `make fmt`
- DCO check needs a `--signoff` with git commits, and `make signoff` can make it easy to sign old commits
- Semantic I should be just renaming the PR: `enhancement(aws_cloudwatch_logs sink): ....`

These are the _basic_ fixes I noticed, but I'll take a deeper look at the other failures today.

**Review by pablosichert — COMMENTED** [review]
Hey @chaychoong, thanks for the contribution!

I applied some small adjustments to make your proposed changes work. Notably, I introduced the `PutRetention` state, renamed the config option that is exposed to users to `retention_days` (to be consistent with our naming scheme) and removed the default value. Instead, it will not issue a `PutRetentionPolicyRequest` if no value is provided.

**Comment by pablosichert** [comment]
Regarding the failing DCO and netlify/cue checks, you can run the `make signoff` command to rebase with master and sign off your commits, as @spencergilbert suggested.

If you can't run these commands locally and want me to go through it, please let me know if you are OK with me signing off your commit with your email.

**Comment by chaychoong** [comment]
@spencergilbert @pablosichert thank you both so much for your help! I've signed off the commit successfully

@pablosichert if I'm understanding this right, what I was missing that prevented it from working is 
- the logic to actually run the `put_retention_policy` function, as well as the 
- state machine transitions

is that accurate?

**Comment by pablosichert** [comment]
@chaychoong yes, that sounds about right!

I assume you must have gotten a cryptic error message regarding `async` and `Pin` which made it difficult to see where the error came from: `State::CreateGroup` expects a `ClientResult<(), CreateLogGroupError>`, but you provided a `ClientResult<(), PutRetentionPolicyError>` from the `put_retention_policy ` return value

**Comment by pablosichert** [comment]
For reference: I added an integration test, but it is still failing for me locally.

Unfortunately, it did not run on CI yet.

I'd like a passing run before we land this PR. Otherwise, looks good to me!

**Comment by jszwedko** [comment]
Closing this as stale, but feel free to reopen if you pick this work back up!

**Pull request closed without merging**
