### PR TITLE
fix(datadog_metrics sink): fix datadog api key pass-through for metrics

### LINKED ISSUE #13357: Datadog API key pass-through doesn't work for metrics
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Passing `datadog_agent` to `datadog_metrics` does not result in the API key making it through. This appears to be because the metrics endpoints pass the API key as a query parameter `?api_key=....` rather than an HTTP header like Vector expects:

https://github.com/vectordotdev/vector/blob/55228f6da30c22c72321b6680b5de96a99f6c0d0/src/sources/datadog/agent/metrics.rs#L107

We should check for the API key in the query parameters as well.

We should also double check the logic for log and trace ingestion to make sure it correctly looks for both the header and query parameter.

### Configuration

```text
[sources.source0]
type = "datadog_agent"
address = "0.0.0.0:8282"
multiple_outputs = true
store_api_key = true

[sinks.sink0]
inputs = ["source0"]
default_api_key = ""
type = "datadog_metrics"
```

### Version

vector 0.22.0

### Debug Output

```text
2022-06-27T20:58:15.284738Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=1}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://0-21-2-vector.agent.datadoghq.com/api/v1/series method=POST version=HTTP/1.1 heade
rs={"dd-api-key": "", "dd-agent-payload": "4.87.0", "content-type": "application/json", "content-encoding": "deflate", "user-agent": "Vector/0.21.2 (aarch64-apple-darwin)", "accept-encoding": "identity"} body=[2673 bytes]                                                                                              2022-06-27T20:58:15.373714Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=1}:http: vector::internal_events::http_client: HTTP response. status=403 Forbidden version=HTTP/1.1 headers={"date": "Mon, 27 Jun 2022 20:58:15 GMT", "content-type
": "application/json", "content-length": "170", "connection": "keep-alive", "cache-control": "no-cache", "via": "haproxy"} body=[170 bytes]                                                                                                                                                                                2022-06-27T20:58:15.373935Z ERROR sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=1}: vector::sinks::util::retries: Not retriable; dropping the request. reason="response status: 403 Forbidden"
```

### Example Data

_No response_

### Additional Context

Tested with Datadog Agent version 7.35.1 with config:

```yaml
vector:
  metrics:
    enabled: true
    url: "http://localhost:8282"
```

### References

_No response_

### PR DESCRIPTION
**Pull request by neuronull**
Closes #13357.

The issue was that the datadog_metrics sink was not using the dd api_key which was being sent over in the event metadata.

Tested with the following configuration:

```toml
[sources.source0]
type = "datadog_agent"
address = "0.0.0.0:8181"
multiple_outputs = true
store_api_key = true

[sinks.sink0]
inputs = [ "source0.metrics" ]
type = "datadog_metrics"
default_api_key=""
```

Log snippet showing successful request:

```
2022-07-01T01:15:15.788926Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}: vector_core::stream::driver: Submitting service request. in_flight_requests=0 request_id=0
2022-07-01T01:15:15.789679Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=0}:http: vector::internal_events::http_client: Sending HTTP request. uri=https://0-23-0-vector.agent.datadoghq.com/api/v1/series method=POST version=HTTP/1.1 headers={"dd-api-key": "<redacted>", "dd-agent-payload": "4.87.0", "content-type": "application/json", "content-encoding": "deflate", "user-agent": "Vector/0.23.0 (x86_64-unknown-linux-gnu debug=full)", "accept-encoding": "identity"} body=[1741 bytes]
2022-07-01T01:15:16.068489Z DEBUG sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=0}:http: vector::internal_events::http_client: HTTP response. status=202 Accepted version=HTTP/1.1 headers={"date": "Fri, 01 Jul 2022 01:15:16 GMT", "content-type": "text/json", "content-length": "16", "connection": "keep-alive", "x-content-type-options": "nosniff", "strict-transport-security": "max-age=15724800;"} body=[16 bytes]
2022-07-01T01:15:16.069058Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=0}: vector_core::stream::driver: Service call succeeded. request_id=0
2022-07-01T01:15:16.069252Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=0}: vector_common::internal_event::bytes_sent: Bytes sent. byte_size=30751 protocol=https
2022-07-01T01:15:16.069497Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}:request{request_id=0}: vector_common::internal_event::events_sent: Events sent. count=157 byte_size=1741
2022-07-01T01:15:16.069823Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}: vector_core::stream::driver: Acknowledging service request. request_id=0 ack_size=157
2022-07-01T01:15:16.070007Z TRACE sink{component_kind="sink" component_id=sink0 component_type=datadog_metrics component_name=sink0}: vector_core::stream::driver: Acking events. ack_size=157
```

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
I need to take a closer look and compare to the logs sink, but I think we should also update the config to match the log sink (`default_api_key`) along with the documentation

**Review by jszwedko — APPROVED** [review]
Nice find, thanks!

I know we still need integration tests for this sink too (https://github.com/vectordotdev/vector/issues/13363)

**Comment by neuronull** [comment]
> I need to take a closer look and compare to the logs sink, but I think we should also update the config to match the log sink (`default_api_key`) along with the documentation

I'm wondering if that applies here because in the datadog metrics sink we are getting the api key from the event? Genuinely curious, as I did see that the datadog logs sink has a default api key , but I intentionally didn't add it here because it wasn't needed for the fix and wasn't sure if it should be added.

**Comment by neuronull** [comment]
> Nice find, thanks!
> 
> I know we still need integration tests for this sink too (#13363)

BTW, I did verify that the datadog logs and traces sinks do have the api key pass through set up already.

**Comment by spencergilbert** [comment]
> I'm wondering if that applies here because in the datadog metrics sink we are getting the api key from the event? Genuinely curious, as I did see that the datadog logs sink has a default api key , but I intentionally didn't add it here because it wasn't needed for the fix and wasn't sure if it should be added.

I also may be confused here. We have a plain [`api_key`](https://vector.dev/docs/reference/configuration/sinks/datadog_metrics/#api_key) option, I would assume the behavior of the logs and metrics sink to be identical in terms of "if the event didn't get passed through with a key use the one configured in the sink" but I'm also not very familiar with these sinks.

**Comment by neuronull** [comment]
> I also may be confused here. We have a plain [api_key](https://vector.dev/docs/reference/configuration/sinks/datadog_metrics/#api_key) option, I would assume the behavior of the logs and metrics sink to be identical in terms of "if the event didn't get passed through with a key use the one configured in the sink" but I'm also not very familiar with these sinks.

I did see in the docs somewhere that `api_key` was being deprecated in lieu of `default_api_key` so perhaps they serve the same purpose and its just a naming inconsistency ?

**Comment by jszwedko** [comment]
Hmm, yeah, seems like the docs weren't updated. All of the Datadog sinks deprecated `api_key` in-lieu of `default_api_key` to make it clearer that the API key from the metadata would be used, if it exists.

**Comment by jszwedko** [comment]
Opened https://github.com/vectordotdev/vector/pull/13416 to fix the docs.

**Review by spencergilbert — APPROVED** [review]

**Pull request merged**
