### PR TITLE
chore: Update OpenTelemetry Protobuf Definitions to v1.0.0

### PR DESCRIPTION
**Pull request by hdost**
This will also make sure that all the necessary files exist for the rest of the signals.

Relates #1444
Signed-off-by: Harold Dost <h.dost@criteo.com>

Not expected to be a breaking change to https://github.com/open-telemetry/opentelemetry-proto/pull/414

### CODE REVIEW

**Review by StephenWakely — APPROVED** [review]
Awesome. Thanks!

**Comment by StephenWakely** [comment]
@hdost We have some very trivial checks that have failed. Would you be able to amend these:

```
cargo vdev check fmt
File "lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/logs/v1/logs_service_http.yaml" doesn't end with a newline
File "lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/collector/metrics/v1/metrics_service_http.yaml" doesn't end with a newline
File "lib/opentelemetry-proto/src/proto/opentelemetry-proto/opentelemetry/proto/common/v1/common.proto" contains trailing spaces in some of the lines
```

**Comment by hdost** [comment]
Yup I should be able tomorrow morning.

**Comment by hdost** [comment]
@StephenWakely should be set

**Pull request merged**
