### PR TITLE
chore(javascript website): Pixel tracking setup

### PR DESCRIPTION
**Pull request by DavidWeid**
## What does this PR do?
- Adds pixel tracking for ads targeting
  - Facebook, Google, Twitter

## Motivation
https://datadoghq.atlassian.net/browse/WEB-2406

## Notes:
- Google tag manager script loads in `head` and also includes a `noscript` after the opening `body` tag
- Good to go live on all pages. I have confirmed all 3 tags are firing on the preview

### CODE REVIEW

**Comment by binarylogic** [comment]
FWIW, our audience skews very heavily towards those that block these trackers. In the past it was over 90% of our audience. Given that, do we find these useful? Backend data is much more accurate.

**Comment by DavidWeid** [comment]
> 

Thanks @binarylogic , we can go ahead with the merge and I'll pass this on to the stakeholder so that they're aware

**Comment by spencergilbert** [comment]
I can merge and cherry-pick into the existing version of the site if that's good @binarylogic

**Comment by DavidWeid** [comment]
@spencergilbert This is all ready for going live if you can, thanks!
Not sure about the two pending checks in this PR though

**Comment by binarylogic** [comment]
@DavidWeid just curious if our stance on this has changed? Over 90% of our users block ads, and I cannot load the site because `https://static.ads-twitter.com/uwt.js` takes over 30 seconds to load. If we aren't getting value out of this I would prefer to remove it.

**Comment by DavidWeid** [comment]
hi @binarylogic , the [stakeholder still found value in the pixel](https://datadoghq.atlassian.net/browse/WEB-2406?focusedCommentId=682236) when I mentioned your previous feedback. Having the pixel blocked though should not affect load time because it is an async script and the blocking happens immediately via adblock - tried with "AdBlock" on chrome. Could there be a different issue causing this long load time?

**Pull request merged**
