### PR TITLE
enhancement(dev): Add dedicated helper tool

### PR DESCRIPTION
**Pull request by bruceg**
This is a follow-up to #14990 as @ofek does not have sufficient time to actively pursue this track now that he is no longer embedded. Most of the code is his, I have just closed some of the outstanding issues with it.

I will be following up on this in a separate PR to flesh out the integration testing. Consider that part of this code base a work in progress.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
LGTM, however I would note that this hardcodes the use of `docker` rather than allowing for `docker` or `podman`.

**Comment by bruceg** [comment]
I know. That will be a target of follow-up work.

**Review by lukesteensen — APPROVED** [review]

**Comment by tshepang** [comment]
> This is a follow-up to #14990 as @ofek does not have sufficient time to actively pursue this track now that he is no longer embedded. Most of the code is his, I have just closed some of the outstanding issues with it.

what does _embedded_ mean

**Comment by jszwedko** [comment]
> > This is a follow-up to #14990 as @ofek does not have sufficient time to actively pursue this track now that he is no longer embedded. Most of the code is his, I have just closed some of the outstanding issues with it.
> 
> what does _embedded_ mean

Ah, yeah, that comment would be pretty inscrutable to people outside of Datadog :) It just means that Ofek was working on our team within Datadog for a bit but now is back on a different team.

**Pull request merged**
