### PR TITLE
Add trailing slash to aws endpoint examples

### PR DESCRIPTION
**Pull request by scohajo**
* fix https://github.com/vectordotdev/vector/issues/20773
* PR adds trailing slashes to the AWS Endpoint examples and notes that the slash is required. This addresses the above issue and provides clarity for users

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Good catch, thanks @scohajo

**Comment by jszwedko** [comment]
I think we just need you to accept the [CLA](https://github.com/vectordotdev/vector/pull/20774#issuecomment-2204288628) above when you get a moment.

**Comment by scohajo** [comment]
@jszwedko accepted! Sorry on the delay there

**Comment by jszwedko** [comment]
No worries! Appreciate the contribution!

**Review by hestonhoffman — APPROVED** [review]

**Comment by scohajo** [comment]
@hestonhoffman sorry I think it failed because I forgot to cue fmt

**Comment by jszwedko** [comment]
I realized this actually updated the wrong place: the cue files directly rather than the doc comments. I open https://github.com/vectordotdev/vector/pull/20791 to revert and https://github.com/vectordotdev/vector/pull/20792 to reintroduce.

**Pull request merged**
